### ISSUE TITLE
App dosn't work [Ubuntu / ZorinOS]

### ISSUE THREAD

**Issue by SlateDave** [safing/portmaster#10]
The firewall works flawlessly  but whenever I try to open the app with 

> ./pmctl run app --db=/opt/pm_db

I just get a black window. In the browser console it says:

> <body>Could not connect: Connection refused</body>

**Comment by dhaavi** [comment]
Thank you for reporting this. We are currently working on releasing as `.deb` and Windows Installer (2-3 weeks until we're there). This has led to breaking changes in naming.

Please download the newest updated release here (from current master): https://github.com/safing/portmaster/releases/tag/v0.3.1

This should resolve this issue - please report back with any further problems.

**Comment by SlateDave** [comment]
Now it works. Thank you!
Btw there is no icon for the program is the taskbar.

**Comment by dhaavi** [comment]
Great!

We know. This requires knowledge about the desktop environment, which is tricky to do automatically, better leave it to the installer. The `.deb` installer is coming soon, stay tuned!
