### ISSUE TITLE
Netlimiter Like Speed Limiting

### ISSUE THREAD

**Issue by pcdeem** [safing/portmaster#1003]
**What would you like to add or change?**:
The fact that this app has a Linux version is sensational.
Something that I have missed under Linux is the Netlimiter app that I have used and paid for over the years.
Netlimiter has a basic firewall/blocker built in but nothing like Portmaster.
Portmaster has an excellent firewall but no speed limiting like Netlimiter.
If the same limiting could be incorporated into Portmaster even as a paid feature it would be awesome.

**Why do you and others need this?**:
To limit network transfer speeds on a per app/network source basis both under Windows and Linux without needing to use a separate application to do firewalling and limiting.

**Comment by kr4z33** [comment]
Duplicate: https://github.com/safing/portmaster/issues/382
