### ISSUE TITLE
Upgrade process

### ISSUE THREAD

**Issue by boistordu** [safing/portmaster#1005]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
The upgrade process on Linux is not right. You should choose a more conventional way through the reinstallation of the package. The package on all of my testing benches were stil 0.7 and not 1.0 so I had to reinstall everything everywhere and do a purge obviously in between. 

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by boistordu** [comment]
You still managed to screw up and not test thoroughly. Update to 1.0.3 from 1.0.2, what happened ? No more account details in SPN

**Comment by dhaavi** [comment]
Please attach the debug information, so we can look into this.

A full re-install on every update is unfeasible.
