### ISSUE TITLE
starting resolver failed

### ISSUE THREAD

**Issue by SSA-BlueKnight** [safing/portmaster#1017]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

Starting module resolver failed

**What did you expect to happen?**:

start-up w/o failures

**How did you reproduce it?**:

reboot PC

**Debug Information**:

NJ{"Created":1669669453,"Modified":1669669453,"Expires":1672261453,"Deleted":0}S
executing core/portmaster-core.exe version 1.0.2 on windows amd64
===== Error Report =====
Message: timed out (2m0s)
Timestamp: 2022-11-28 13:06:13.2046273 -0800 PST m=+120.161993901
ModuleName: resolver
TaskName: start module
TaskType: 
Severity: error
PanicValue: %!s(<nil>)
StackTrace:

goroutine 197 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0002a8f00, {0x197db27, 0xc}, {0x1afdec0?, 0xc000625d80?})
	/home/user/git/safing/portbase/modules/error.go:48 +0x49
github.com/safing/portbase/modules.startModules()
	/home/user/git/safing/portbase/modules/start.go:200 +0x1de
github.com/safing/portbase/modules.ManageModules()
	/home/user/git/safing/portbase/modules/mgmt.go:112 +0xda
github.com/safing/portbase/modules/subsystems.(*Manager).handleConfigChanges(0x0?, {0x0?, 0x0?})
	/home/user/git/safing/portbase/modules/subsystems/registry.go:253 +0x205
github.com/safing/portbase/modules/subsystems.(*Manager).CheckConfig(0x0?, {0x1b03af8?, 0xc000712a40?})
	/home/user/git/safing/portbase/modules/subsystems/registry.go:196 +0x25
github.com/safing/portbase/modules.(*Module).runWorker(0x0?, {0x19a3d74?, 0x0?}, 0x0?)
	/home/user/git/safing/portbase/modules/worker.go:128 +0x93
github.com/safing/portbase/modules.(*Module).RunWorker(0x0?, {0x19a3d74?, 0x0?}, 0x0?)
	/home/user/git/safing/portbase/modules/worker.go:52 +0x77
github.com/safing/portbase/modules.(*Module).StartWorker.func1()
	/home/user/git/safing/portbase/modules/worker.go:27 +0x4a
created by github.com/safing/portbase/modules.(*Module).StartWorker
	/home/user/git/safing/portbase/modules/worker.go:26 +0xac

===== End of Report =====

**Comment by br0gio** [comment]
I also have this issue, works fine If I restart portmaster in the application but it's kinda annoying
