### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by EntityinArray** [safing/portmaster#1018]
**What would you like to add or change?**:
It would be really great if Portmaster also had a CLI interface, where you could allow connections from apps without starting a graphical session

**Why do you and others need this?**:
Portmaster is a very nice app-based firewall, giving ability to monitor and control connections from apps, making it really useful in servers for additional security and privacy. People usually use remote shells, such as SSH, to administer remote servers, because starting a remote graphical session just to control the firewall is very cubersome and slow.

**Comment by davegson** [comment]
thanks for using PM and for your suggestion! We do think this would be useful and have plans for this in [our backlog](https://safing.io/backlog/). Just note priority currently lies elsewhere.

on a related note, you might be interested in https://github.com/safing/portmaster/issues/707
