### ISSUE TITLE
Cloudflare WARP (VPN?) Compatibility

### ISSUE THREAD

**Issue by 6ixfalls** [safing/portmaster#1021]
Using Cloudflare 1.1.1.1 WARP "VPN" on Windows sometimes works. From experience, it seems to work at startup; although either after a while or my laptop went to sleep, it couldn't reconnect.

**Comment by 6ixfalls** [comment]
A workaround for this seems to be enabling proxy mode and using the proxy server in the OS configuration. However, I'm not sure if all applications honor the setting.

**Comment by rudolphos** [comment]
Having the same problem. I am using Cloudflare WARP+. I have allowed almost all cloudflare related requests in portmaster. When I enable WARP+, internet doesn't work at all. 

![image](https://user-images.githubusercontent.com/4366810/209905936-af7461c2-3693-4411-8ec8-ccd61a250079.png)
Enabled WARP: Can't connect to geolocation center and can't establish DNS connectivity.
