### ISSUE TITLE
How to build this code to Windows app?

### ISSUE THREAD

**Issue by duongthaison21** [safing/portmaster#1022]
Hi everyone. Have a good day<3

Have anyone can tell me how to build this code to Windows app (Win10 64bit)?
I want to use only backend, not use UI. Interface with another app by API

Thanks for all

**Comment by vlabo** [comment]
If you want to build just the core. 
1. Install the [go compiler](https://go.dev/dl/).
1. Clone `portmaster` repo.
1. Open `bash` compatible terminal (git bash also works).
1. Navigate to `./portmaster/cmds/portmaster-core`
1. Run `BUILD_HOST=myhostname GOOS=windows GOARCH=amd64 ./build`

This will create `portmaster-core.exe`
When running it you have to supply data folder (it can be empty) `portmaster-code.exe -data=C:\someDataFolder` and if you want to access the api you should run with the option `-devmode`.

For Windows there is also the kernel extensions but it is more complicated to build and you need to enable unofficial drivers to run on your machine, which I recommend doing on a machine only meant for testing. But postmaster will automatically download the proper version if is not present.
