### ISSUE TITLE
❓️ How to block all incoming and enable only few ports for incoming for app?

### ISSUE THREAD

**Issue by Flashwalker** [safing/portmaster#1024]
❓️ Now with new behaviour of "Force block" incoming by default
How how can i block all incoming and enable only few ports for incoming for app?

It looks like that if i want to block all incomming, the only way is "Force block" incoming. But if i want to allow incoming for some app, i need to disable "Force block" incoming for this app. 

But how can i achieve the allow only few ports, but not all incoming foe app?

**Comment by Flashwalker** [comment]
Would it be right to 
- Leave "Force block" incoming by default for this app
- Make the rule for block all incoming for app: `* */*`
- Make the rules for allow some port: `Internet TCP/18409`, `Internet UDP/18409`

Is this the right way?

**Comment by LoganDark** [comment]
> But how can i achieve the allow only few ports, but not all incoming foe app?

Incoming rules:

1. Allow `* UDP/18409`
2. Allow `* TCP/18409`
3. Block `*`

Portmaster reads rules from top to bottom, and applies the first one that matches. So just allow the ports you want first, then block `*`.

This also means it is very slightly faster to specify the UDP rules first as UDP is a stateless protocol and doesn't have the connection optimization like what Portmaster has for TCP. But in practice this should be entirely negligible.

**Comment by Raphty** [comment]
all Portmaster settings are top to bottom, this is why force block is above rules and why the filter lists are bellow the rules.

So you can override the rules with the force block (blocking all connections even if they are allowed in a rule)
and override the filter lists with the rules (allowing a connection that is blocked in a filter list)
