### ISSUE TITLE
Firefox is not correctly detected and connections are put into "Other Connections"

### ISSUE THREAD

**Issue by vegedb** [safing/portmaster#1031]
Since a few days ago Firefox has not been detected. It goes under "Other Connections".

As seen in the screenshots here.
![image](https://user-images.githubusercontent.com/72070424/206092386-45bdb6ad-b0ff-4667-9948-45163fbb0c98.png)

![image](https://user-images.githubusercontent.com/72070424/206092223-1ebce561-5616-4da6-8496-582085cb6b8b.png)

![image](https://user-images.githubusercontent.com/72070424/206092324-fd51a54b-7457-4891-b7b9-cd3b08984d06.png)

**Comment by dhaavi** [comment]
Hey @vegedb, thanks for reporting this.

In order to properly investigate, please submit the debug info as described in the template.

**Comment by vegedb** [comment]
@dhaavi 
Which logs are you looking for? 
In these folders,
app
start
core
notifier

I couldn't find any "Other Connections" or Firefox mentioned in any of the logs.

**Comment by Flavelius** [comment]
under ubuntu 22.04 there's something linked to the firefox snap that always ends up in 'Other Connections'. It very frequently (but not always) pops up when opening new websites/tabs. it looks like it connects to some https endpoint (port 443).
