### ISSUE TITLE
ver 1.3 crashing windows

### ISSUE THREAD

**Issue by mkstokes** [safing/portmaster#1033]
Still investigating to pull logs however after the application ugrade from version 1.2->>.1.3  blue screen continued.  Resolve the problem by uninstall. Will watch this thread to see if the issues identified and a new release

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
Hey @mkstokes, thanks for reporting this.

We are tracking this bug in https://github.com/safing/portmaster/issues/1019, so I am closing this as a duplicate.

**Comment by mkstokes** [comment]
Ok Thanks



        MICHAEL STOKES
CSO
direct: 650.597.1190
          [no text]
Michael's Profile<http://mstokes.stokestech.com>        [Click logo for support] <http://support.stokestech.com>


Northern Virginia | Boston | Manhattan | Philadelphia


This email and any attachments thereto are confidential and intended solely for the use of the individual or entity to which they are addressed. If you are not the named addressee you should not distribute, copy or use this intellectual property. Please delete this e-mail from your system.

Taking any action based on the contents of this communication is prohibited without the express permission of stokesTechnologies, inc.


From: Daniel Hovie ***@***.***>
Sent: Friday, December 9, 2022 6:35 AM
To: safing/portmaster ***@***.***>
Cc: Michael Stokes ***@***.***>; Mention ***@***.***>
Subject: [Suspected Spam]Re: [safing/portmaster] ver 1.3 crashing windows (Issue #1033)


Hey @mkstokes<https://github.com/mkstokes>, thanks for reporting this.

We are tracking this bug in #1019<https://github.com/safing/portmaster/issues/1019>, so I am closing this as a duplicate.
