### ISSUE TITLE
SPN exclude improvement feature

### ISSUE THREAD

**Issue by timsderstrm** [safing/portmaster#1036]
**What would you like to add or change?**:

I was thinking if it's possible to have feature on Portmaster that scans the subdomains and also excludes them from the SPN, as it's very annoying to add like 10 subdomains for SPN exclusion manually.

For example when I add Netflix to the SPN exclusion list I also have to manually add all their other subdomains that Netflix.com communicates with for anonymity otherwise my privacy is compromised and it's possible to detect that I'm using VPN/DPN software.

**Why do you and others need this?**:

For enhanced privacy protection and convenience.

**Comment by OfficialEsco** [comment]
Late reply, but have you tried *.netflix.com? Did a quick test and it also excluded netflix.com
