### ISSUE TITLE
ESNI/ECH support 

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1040]
**What would you like to add or change?**:
ESNI (replaced with ECH)- https://blog.cloudflare.com/esni/
ECH newer - https://blog.cloudflare.com/encrypted-client-hello/
Test - https://www.cloudflare.com/ssl/encrypted-sni/

Firefox supports [ECH ](https://www.ghacks.net/2019/04/29/check-if-your-browser-uses-secure-dns-dnssec-tls-1-3-and-encrypted-sni/#:~:text=ECH%3A%20Search%20for%20network.dns.echconfig.enabled%C2%A0and%20toggle%20the%20value%20to%20True)

**Why do you and others need this?**:

Privacy Security

**Comment by dhaavi** [comment]
What exactly do you want support here for?

ECH needs to be support by applications that initiate the connection. There is nothing we can do here.

Other apps that break TLS and initiate it again after the firewall (like Adguard does) will need to add support for this, but we don't, as we don't break TLS.
