### ISSUE TITLE
Norton VPN APP is not working while using Portmaster

### ISSUE THREAD

**Issue by nonogo2035** [safing/portmaster#1046]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**Norton VPN APP is not working while using Portmaster**:

System: Windows 10
Norton VPN is not working while using Portmaster, i have to deactivate it

**What did you expect to happen?**:

System: Windows 10
How can i configure Portmaster so both applications run properly. Norton does not list any DNS VPN Servers to public it seems.

**How did you reproduce it?**:

turn on / Turn off Norton VPN

**Debug Information**:

**Comment by Raphty** [comment]
you can try this: https://docs.safing.io/portmaster/faq#how-do-i-make-my-vpn-or-other-software-compatible-with-portmaster
