### ISSUE TITLE
Portmaster not working with official expressvpn client in Linux Manjaro

### ISSUE THREAD

**Issue by astrophil04** [safing/portmaster#1049]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**
Expressvpn through OpenVPN in combination with Portmaster SNP on Linux (Manjaro = Arch).

**What did not work?**

Using the official expressvpn client and portmaster simultaneously. The problem is that some ports dnsmasq (required by expressvpn client) requires to function properly get blocked by portmaster. 

**Debug Information**:

Subject: A start job for unit dnsmasq.service has begun execution
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support
░░ 
░░ A start job for unit dnsmasq.service has begun execution.
░░ 
░░ The job identifier is 2111.
Jan 01 11:07:24 hp dnsmasq[93787]: dnsmasq: Syntaxprüfung OK.
Jan 01 11:07:24 hp dnsmasq[93788]: dnsmasq: Konnte Empfangs-Socket für port 53 nicht erzeugen: Die Adresse wird bereits verwendet
Jan 01 11:07:24 hp dnsmasq[93788]: Konnte Empfangs-Socket für port 53 nicht erzeugen: Die Adresse wird bereits verwendet
Jan 01 11:07:24 hp dnsmasq[93788]: Start FEHLGESCHLAGEN
Jan 01 11:07:24 hp systemd[1]: dnsmasq.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://forum.manjaro.org/c/support

**Comment by davegson** [comment]
hey there, thanks for the report! Just to let you know - we just extended our VPN compatibility section with a paragraph [Where Incompatibility Comes From](https://docs.safing.io/portmaster/install/status/vpn-compatibility#where-incompatibility-comes-from)

I hope this gives you some pointers of what is going on and potentially provide workarounds or solutions for you
