### ISSUE TITLE
Let the user specify system DNS server

### ISSUE THREAD

**Issue by realSaltyFish** [safing/portmaster#1055]
**What would you like to add or change?**:
Add a configuration item that lets the user specify what DNS server to use when the DNS server list is empty.

**Why do you and others need this?**:
I want to let dnsmasq handle my DNS while still using Portmaster. I need to use different DNS servers for different LAN domains. 

To my understanding Portmaster relies on its DNS module to work in the first place, but if I set the DNS server list to empty Portmaster will automatically pick a "system" DNS server and just act as a proxy. The problem is that Portmaster does not pick the right server and I don't know how to change that. I can't find any documentation on how the process works or any configuration item that changes the behavior.

**Slightly off-topic**
Also, Portmaster seems pretty unhappy about me using dnsmasq+cloudflared to handle DoH. It constantly reports "compatibility issues" and my cloudflared process dies frequently when Portmaster is running. In the logs I see a ton of this:
```
pat/module:108 ▶ ERRO 403 compat: self-check #2: dns integration check failed: did not receive test query after 20s
``` 

I tried configuring Portmaster to use my dnsmasq on 127.0.0.1, but it (almost certainly) did not work, likely because of infinite recursion.

I don't want to give up using Portmaster as it is powerful and easy to use, but IMHO it really lacks flexibility for advanced users. I turned on developer mode but still wasn't able to find a way to make my desired setup work.

**Comment by ppacher** [comment]
Hi @RealSaltyFish,

Portmaster needs to run as your system DNS client as it otherwise is not able to know which apps try to contact which domains. It would only see IP addresses without any DNS information. That's why portmaster reports compatibility issues.

I just checked and we obviously miss the documentation on search-scope based DNS server selection.
Maybe the following example can help you:

```bash
# Use plain DNS via 10.8.1.254 for all domains that end in .home. Do not use this server for anything else 
dns://10.8.1.254:53?name=Local-LAN-Resolver&search=.home&search-only

# Use plain DNS via 10.254.254.1 for all domains that end in .intern.corp. Do not use this for anything else
dns://10.254.254.1?name=WAN-Resolver&search=.intern.corp&search-only

# Use Quad0 via DoT for everything else and make sure to verify it's server certificate
dot://9.9.9.9:853?verify=dns.quad9.net&name=Quad9&blockedif=empty
```

I hope this helps, if not just ask again and we'll try to figure out what's wrong

**Comment by RealSaltyFish** [comment]
Thanks for your reply! It works.

I still wonder if there is a way to override the RerouteToNs verdict for dnsmasq?

**Comment by walwan** [comment]
> Hi @RealSaltyFish,
> 
> Portmaster needs to run as your system DNS client as it otherwise is not able to know which apps try to contact which domains. It would only see IP addresses without any DNS information. That's why portmaster reports compatibility issues.
> 
> I just checked and we obviously miss the documentation on search-scope based DNS server selection. Maybe the following example can help you:
> 
> ```shell
> # Use plain DNS via 10.8.1.254 for all domains that end in .home. Do not use this server for anything else 
> dns://10.8.1.254:53?name=Local-LAN-Resolver&search=.home&search-only
> 
> # Use plain DNS via 10.254.254.1 for all domains that end in .intern.corp. Do not use this for anything else
> dns://10.254.254.1?name=WAN-Resolver&search=.intern.corp&search-only
> 
> # Use Quad0 via DoT for everything else and make sure to verify it's server certificate
> dot://9.9.9.9:853?verify=dns.quad9.net&name=Quad9&blockedif=empty
> ```
> 
> I hope this helps, if not just ask again and we'll try to figure out what's wrong

Thank you very much for implementing the `search` parameter in DNS config. It would be great if this update could be added the the doc!

**Comment by reijerh** [comment]
Glad I found this, seems it _is_ actually in the built-in docs in Portmaster when you click the (i) icon near the DNS settings.

Bonus hint for anyone with a VPN (e.g. Mullvad) struggling getting custom LAN domains working that are not '.local': make sure you also add the DNS server to your VPN's custom dns list. (For Mullvad I now have '127.0.0.1' _and_ my LAN router's IP (192.168. etc).

This allows you to get e.g. .home, .home.arpa etc. working properly.
