### ISSUE TITLE
Portmaster does not work. In worst terms of these words: it blocks DNS while shouldn't do.

### ISSUE THREAD

**Issue by sallevan** [safing/portmaster#1057]
### What happened?
Let's entirely skip a long speech about how modern IT has built and let's agree with that in enterprise environment Cisco AnyConnect and Juniper Secure Connect are standards de-facto: if any other software don't work with them the software in question is useless, period.

### What should to happen?
Portmaster has to be able to quite reliably determine if Cisco AnyConnect or Juniper Secure Connect has been switched up by user (not just **started**! but **switched up the tunnel**!) and update it's DNS settings and filtering rules (moreover - Split-Horizon determination rules too!) to not to block:

1. requests to DNS service if route to it is pointing to the secure tunnel _regardless_ of the IP address it has (`RFC1918` is nice too!);
2. responses from remote DNS if it's reverse forwarding path points to secure tunnel regardless of what it had exactly returned (`RFC1918` is nice too and in this place!);
3. prioritize (i.e, place in DNS servers configuration on the topmost place) DNS servers received while VPDN configuration took place.

### Steps to reproduce:

1. boot Microsoft Windows with Cisco AnyConnect installed;
2. configure VPDN connection to your office;
3. start Portmaster, either automatically or manually, **deleting it's own DNS configuration _entirely_**, as it points in the documentation;
4. get the secure tunnel up and forwarding;
5. open Windows Terminal with command prompt;
6. ping the DNS server obtained via VPDN configuration process - it **should** response to you;
7. run `nslookup` utility **pointing it to the DNS server from 6.** using usual `server IP.ADD.RE.SS` clause;
8. try to resolve anything (**anything** - not just your **work domain names!**)

Resolver will not respond to you while has to.

### Additional information
... shut down Portmaster after steps done above **while not touching anything else** and repeat resolving test in the `nslookup` instance yet running. All will work just fine.
Sad. :(

**Debug-Info**: https://support.safing.io/privatebin/?9981ba507e3d3a0e#9kWh3dULypauG2uLYaCxeUBhGvs7yVeiLEBQb5Qi97eQ

**Comment by Raphty** [comment]
Hey @sallevan, I understand that you are frustrated. Portmaster is focused on Consumers and making Privacy easier for them.

Your enterprise environment is not in scope for Portmaster at the moment
