### ISSUE TITLE
Global Rules do not apply until Portmster is restarted

### ISSUE THREAD

**Issue by Marc05** [safing/portmaster#1059]
**What happened**:
A connection continued to be allowed when a rule allowing it no longer existed.

**What did you expect to happen?**:
Rules should either be applied automatically, or a notification/description should inform the user of the details.

**How did you reproduce it?**:
Specifically, `Other Connections` allowed a ping to a host on a separate VLAN due to `Reason:  allowed by rule: scope matches LAN`, `Applied Setting: Outgoing Rules  from Global Settings`. The `Global Settings / Privacy Filter / Rules` section contained no rules at this time. Restarting Portmaster allowed it to work correctly. The same issue exists vice versa (i.e. adding an allow rule required a restart of Portmaster as well).

Side note:
This is all on Windows 11 22H2 using Portmaster 1.0.4. I've had some odd behavior with all connections being dropped after starting Windows. To solve it, I shutdown Portmaster, disabled/re-enabled the network adapter, and started Portmaster again).

**Comment by vlabo** [comment]
Thank you for the report.
This is a known issue, we already have a fix for it's in the beta channel. You can ether wait for us to put it in stable or if you want here is a guide to try it out.
https://github.com/safing/portmaster/issues/717 

Restarting portmaster after making a config change is also a fix for now.
Note that this kernel extension release is a bit bigger then usual it include few more bug fixes and performance improvements so we are a bit more cautious and taking the time to test it thoroughly.
