### ISSUE TITLE
(GUI) Enchance Active Application Section

### ISSUE THREAD

**Issue by twoex** [safing/portmaster#1066]
Hey everyone!

I would like to submit an idea to improve the active application view section that is on the left hand side of the screen. 

The idea would be to allow categorizing/grouping/tagging apps. 

![Portmaster - Connection Groupings](https://user-images.githubusercontent.com/66793225/212836643-444f6b8c-02a1-4bd5-b339-4be418fc72e3.png)

![Portmaster - All Apps](https://user-images.githubusercontent.com/66793225/212820219-9b05955a-a56e-466c-894b-8dcb019198f2.png)

![Portmaster - Colour Coding 2](https://user-images.githubusercontent.com/66793225/212820235-41e97a07-e1fc-42fd-b318-3a5315620118.png)

![Portmaster - Add Groups](https://user-images.githubusercontent.com/66793225/212820248-ce5bd136-ca6f-4700-8ff8-789aec3c4973.png)

![Portmaster - Colour Coding](https://user-images.githubusercontent.com/66793225/212829291-83a871c9-9508-4920-8d93-f246d35ef893.png)

**Comment by Raphty** [comment]
Thank you, this is such a cool idea! we have been thinking about grouping apps for a while now, in one of the latest releases we implemented custom App Profiles which already could have been used to group apps, but this is a very nice visual indicator!

Portmaster is also built to accept a stack of settings, with the setting closest to the app being the strongest. 

If I understand you correctly you would want to have a structure where you would have:
- Global
- Group
- App

**Comment by Raphty** [comment]
additional idea in #1067

**Comment by dhaavi** [comment]
Hey @twoex, thanks for your amazing work on explaining your ideas!

We will look closer into this in the coming weeks and will evaluate what works for the direction we are going in and which of your suggestions we can implement soon and which of them later!
