### ISSUE TITLE
Portmaster compatibility with iVPN on Linux

### ISSUE THREAD

**Issue by avoidthehack** [safing/portmaster#1070]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

Just want to pass some info along about compatibility with iVPN (on Linux Mint 20.3) + Portmaster:

OpenVPN (via iVPN client! ver 3.10) works as long as you:

* Turn iVPN Firewall to On-demand
* Uncheck "Activate Firewall" on connect to iVPN
* Set Custom DNS to localhost (127.0.0.1)
* Disable the AntiTracker feature (this relies on using iVPN DNS servers to block ads/trackers/malware, but using Portmaster that isn't really a concern.) Also, enabling AntiTracker overrides custom DNS.

In my case, works just fine with iVPN's Firewall enabled or disabled.

I am working on tweaking settings in the iVPN client to get it working with Wireguard, if possible - though I know on https://github.com/safing/portmaster/issues/544 Wireguard without IPV6 seems to work there, just isn't working for me.

Figured I would post to hopefully get iVPN on the VPN compatibility page (https://docs.safing.io/portmaster/install/status/vpn-compatibility#workaround-openvpn) due to iVPN being a well recommended privacy-respecting no-logs VPN provider.

**What did not work?**
Wireguard struggles to stay connected to iVPN (or DNS lookups are so slow the internet is effectively disabled). I can update if I find something that works, but so far nothing even with IPv6 disabled. Unlike Mullvad on Linux, I can sometimes connect to a server, but it usually drops after a few minutes of being painfully slow.

**Comment by Raphty** [comment]
I am currently in the process of setting up a proper wiki for Portmaster, which will also allow community edits.

This will absolutely get added in there! Thank you.

**Comment by avoidthehack** [comment]
> I am currently in the process of setting up a proper wiki for Portmaster, which will also allow community edits.
> 
> This will absolutely get added in there! Thank you.

This is excellent news. I will be on the lookout for it and hope to contribute! :)

**Comment by Raphty** [comment]
This tickets information has been ported into the wiki
https://wiki.safing.io/en/Portmaster/App/Compatibility/iVPN

**Comment by Szu-Szu** [comment]
With integration between ivpn and portmaster soon on the horizon I'm looking forward to a seamless experience.  Are there any current problems with compatibility at the moment?  I'm using proton right now but switching to ivpn.

**Comment by avoidthehack** [comment]
> With integration between ivpn and portmaster soon on the horizon I'm looking forward to a seamless experience. Are there any current problems with compatibility at the moment? I'm using proton right now but switching to ivpn.

Kind of.

My original post still holds true on Linux (specifically Linux Mint) for me, except the firewall issue appears to be fixed. I still have to use OpenVPN versus Wireguard else it will never connect to an iVPN server.

I recently encountered this: the regular split tunnel also seems to break Portmaster (or get it to throw the system integration issue error periodically) on Linux Mint. From what I can tell from netstat and ss is that the split tunnel blocks Portmaster's self-test packet. When I disable split tunnel, everything is fine.

On Windows, from what I can tell, it's a little less buggy. You can use Wireguard and the split tunnel appears to work just fine. Though I will say using the firewall toggle on Windows can be annoying because of how chatty the background processes are.

**Comment by Chiassonastraypatrick** [comment]
Seem to be working you welcome have a goodnight
