### ISSUE TITLE
Soft-Bricks Windows installation on cloud computers (Shadow PC)

### ISSUE THREAD

**Issue by foxscore** [safing/portmaster#1074]
**What happened**:
After installing Portmaster on my Shadow PC, it started blocking connections necessary to use the cloud computer, forcing a reset of the device.

**What did you expect to happen?**:
Nothing

**How did you reproduce it?**:
Installed Portmaster

**Debug Information**:
*Impossible to gather atm*

**Comment by Raphty** [comment]
yes this is known, and documented here:
https://docs.safing.io/portmaster/faq#can-i-run-portmaster-on-a-server
