### ISSUE TITLE
Instructions and compatibility docs for QubesOS

### ISSUE THREAD

**Issue by Opening-Button-8988** [safing/portmaster#1076]
**What would you like to add or change?**:
Instructions on how to install Portmaster+SPN on QubesOS (the best way), and any relevant compatibility issues.

**Why do you and others need this?**:

QubesOS and Portmaster are both useful tools for security and privacy. The target audience for both products merge well. It might be simple to install in an AppVM but it's probably best to install it in a net TemplateVM, which may not be obvious to new users. There may also be certain configs that need to be set in order to provide the best possible protections, which only Safing or Qubes developers would probably know. I'm guessing some iptables configuration is required in dom0, which is risky business unless you know what you're doing. I might be overthinking this and it just works out of the box. Overall, some clarity on this would be great. 

I haven't tested it yet but I will soon, and report the results.

**Comment by Raphty** [comment]
Thanks for testing it! I agree, that Qubes is also focused on privacy, and so are we, but our efforts are targeted on getting people into privacy and making sure that it easy to get started. Although Qubes is great, it is, as you say, not easy.

This is also why we choose the defaults as they are, the idea is, that Portmaster can grow with you as you learn how to be more private online. Qubes might be a destination in the end, but at the moment we are focusing on making it easier for people to get there.

Privacy is important to all, and most of the time the less techie people need it more then the tech savvy ones.

If you can help us get a guide, I would gladly help you integrate it into the upcoming wiki and the current FAQ

**Comment by Opening-Button-8988** [comment]
@Raphty 

Hi,

I tested Portmaster on Qubes very briefly. I didn't test the SPN, I will do that soon. It worked pretty well, but I'd have to do more testing to really see where it breaks. I wonder what would happen if I ran Portmaster and SPN in multiple VMs simultaneously...

If I come across any issues and possible fixes, I will for sure document it.
