### ISSUE TITLE
UDP slower than TCP

### ISSUE THREAD

**Issue by mctvcse839** [safing/portmaster#1077]
**What happened**:

UDP connections are either 3 times slower than TCP or sometime don't even connect. 

Ex: I use a wireguard vpn which uses udp by default. There is also an option to obfuscate the connection with tcp. While connecting to the same server with wireguard, I noticed tcp connects instantly less than 1 second, while using udp it takes about 3 seconds which is 3 times as slower. In theory this should be the opposite, udp are faster than tcp. Now this situation isnt a big issue, but when I try to use the multihop feature (connects to 2 servers) while using udp, it just doesnt connect 95% of the time. I checked portmaster and allowed incoming connections from both servers and pretty much allowed everything related to these connections to make sure it wasn't a rule that was preventing it. but it still didnt connect

I used the TCP obfuscation option with multihop and it works in less than 4 seconds. Just to make sure it wasnt any other program that was interfering, I disabled portmaster and tested multihop with udp and it worked instantly. 

Are UDP connections proccesed differently than TCP? 

**What did you expect to happen?**:
Connection to work while using UDP.

**How did you reproduce it?**:
Tested UDP connections with portmaster on. Than portmaster off. Found that portmaster was making UDP connection slower or completly not connect.

**Debug Information**:
Logs are in critical only. Nothing in them

**Comment by Raphty** [comment]
We know that Portmaster and some Wireguard implementations have issues - this does not necessarily have something to do with upd.
Do you find an issue with other udp streams, on devices without wireguard?
