### ISSUE TITLE
More options for notification when prompt selected

### ISSUE THREAD

**Issue by shumafuk** [safing/portmaster#1078]
**What would you like to add or change?**:
I'd like to have more options in notification window when prompt is selected. I would like to use portmaster as firewall, but adding new connection to allow-list is obsolete. If I click allow, it just allow connection for specific domain. I'd like to choose if:
- Allow all connections per app
- Allow incoming only
- Allow outcoming only
- Allow temporarily
- Block
- Ask later

Also few more information would be nice (ie protocol, connected domain, path of exe that wants to connect, etc.).

**Why do you and others need this?**:
I'd like to switch from simplewall to portmaster, because portmaster gives me more information and options. But not directly in notification window, so adding bunch of new apps to allow-list is time consuming.

**Comment by mariobrostech** [comment]
I'm in the same boat. I'd like to switch from my existing firewall solution, but not having an option to individually whitelist applications or set temporary allow/block lists really prevents Portmaster from being a viable alternative for me.
