### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by alfredonodo** [safing/portmaster#1079]
Hi,
I really appreciate this project. I think it would be really good if you supported arm64 architecture (windows and GNU/linux). Windows 11 arm can [emulate x86_64](https://learn.microsoft.com/en-us/windows/arm/arm64ec) software with some slowdown while for GNU/linux there is [box64](https://github.com/ptitSeb/box64/) which suffers from the same problem.
Thank you

**Comment by dhaavi** [comment]
Hey @srvprivate, if you want to help out here, I think there are only two things missing are the kext/driver and the installer.

You can find them here:
- Kext: https://github.com/safing/portmaster-windows-kext/tree/develop/pm_kext
- Installer: https://github.com/safing/portmaster-packaging/tree/develop/windows

**Comment by srvprivate** [comment]
> Hey @srvprivate, if you want to help out here, I think there are only two things missing are the kext/driver and the installer.
> 
> 
> 
> You can find them here:
> 
> - Kext: https://github.com/safing/portmaster-windows-kext/tree/develop/pm_kext
> 
> - Installer: https://github.com/safing/portmaster-packaging/tree/develop/windows

Okay! Let me try those out!

**Comment by Raphty** [comment]
@srvprivate did you try it? and did it work? 😄

**Comment by shvetsnikita** [comment]
> I think there are only two things missing are the kext/driver and the installer.

What is the missing on Linux side?

**Comment by dhaavi** [comment]
> What is the missing on Linux side?

On Linux, we are just missing the packages. Our script installer should already work with arm: https://wiki.safing.io/en/Portmaster/Install/Linux

**Comment by miroesq** [comment]
Hi. I am having the same issue and just posted about it. I am not very technical, but will be more than happy to provide all the information you need.

**Comment by RasheedAZ** [comment]
Would be great if this can build for aarch64 for Linux phones Librem 5, Pinephone, PostmarketOS, etc.
