### ISSUE TITLE
Get Help / Support Page

### ISSUE THREAD

**Issue by Raphty** [safing/portmaster#1081]
This page is called "Get Support" on mouse hover over the Icon and on the page itself "Get Help"

![Screenshot from 2023-02-03 10-20-08](https://user-images.githubusercontent.com/11504285/216563998-67b04dd9-732e-41a8-90b1-234f383b6688.png)

![image](https://user-images.githubusercontent.com/11504285/216564067-9be24153-8e25-4f03-a83c-63ce22dbe0f9.png)

**Comment by rahulbansal3005** [comment]
I am interested to work on this bug.

**Comment by dhaavi** [comment]
Hey @rahulbansal3005, thanks for wanting to help out!

This is a simple name change, so I don't think there is enough work to make it worth setting up a dev environment just for this.

If you are interested in helping out with other things, I can keep an eye out for things that would be a great match! What fields are you interested in helping out? Which technologies are you familiar with?

**Comment by rahulbansal3005** [comment]
Hi @dhaavi, i mostly works with Java, node js and sometimes with react. I will be very happy to work with you, even if i have to learn something very new, like i saw the repo is in go.
