### ISSUE TITLE
Add option to (temporarily) disable dns logging / Incognito Mode

### ISSUE THREAD

**Issue by SeriousM** [safing/portmaster#1086]
**What would you like to add or change?**:

I would like to see an option where I can disable the dns logging to enhance privacy (which is portmaster's code value).
Browsers do have an incognito mode and so I want to use this mode in portmaster as well.
This feature is not linked to any porn usage yet the servers I connect to must not be traceable (work environment) in any way.

Another possible solution would be to limit the time the dns entries are visible.

**Why do you and others need this?**:

An incognito mode is an important aspect of a privacy focused app.

Pi-Hole has such a feature (which disables pi-hole) but the UI is a good starting point.
![image](https://user-images.githubusercontent.com/462013/217210412-1710745c-4e7e-49d5-a40d-f1e658c766d1.png)

Here in portmaster I have my visited pages exposed.
![image](https://user-images.githubusercontent.com/462013/217210359-45b20c57-7d04-4283-916a-f4749f59f781.png)

**Comment by Raphty** [comment]
Portmaster does not store the dns logs in any way, and you can only see the last 10 min - if you do a reload after 10 min, all these entries are gone

We are thinking about a recording feature, where you can record an apps behavior, but rest assured, this will be something that can be configured. All you do is Private, nothing is stored or shared.

**Comment by SeriousM** [comment]
I can see logs from over an hour ago.

**Comment by SeriousM** [comment]
@Raphty I would like to know, from your perspective, how I can still see transactions days ago:

![image](https://user-images.githubusercontent.com/462013/218400934-b2fb0f0a-ae6c-49fb-be62-2e2ec8910be4.png)

Interestingly, a gap of a few days is visible because I didn't used my computer during the weekend, but still.

**Comment by Raphty** [comment]
they are gone after 10 min when the connection is closed

**Comment by SeriousM** [comment]
Ah I see, thanks for the explanation.
Back to the initial question: is there a way to hide such _open_
connections?
