### ISSUE TITLE
Segfault when using Arch

### ISSUE THREAD

**Issue by nbrugger-tgm** [safing/portmaster#1087]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
When installing the AUR that you referenced in the Linux install guide for Arch-based, the following command produces segmentation fault:
```bash
sudo /opt/safing/portmaster/portmaster-start recover-iptables
```
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8f2238]
```
(Restarting the system after uninstalling portmaster works and restores my ip tables, because when portmaster runs, my ip-tables for docker are broken)
```
docker: Error response from daemon: driver failed programming external connectivity on endpoint ****-container (e386719d24bda752e8341a42ddea7bdcbb7ef93f730f8870737661134cba5b80):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5001 -j DNAT --to-destination 172.17.0.2:5000 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).
```

**What did you expect to happen?**:
The broken IP-Tables are repaired and no segfault occurs.

**How did you reproduce it?**:
1.  `yay -S portmaster-stub-bin`
2. Start using my display manager and also start the "core service"
3. (docker is broken)
4. shutdown portmaster using system tray
5. ```sudo /opt/safing/portmaster/portmaster-start recover-iptables```

**Debug Information**:

Stack trace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8f2238]

goroutine 33 [running]:
github.com/florianl/go-conntrack.(*Nfct).Close(0xe52460?)
        /home/user/go/pkg/mod/github.com/florianl/go-conntrack@v0.3.0/conntrack.go:70 +0x18
github.com/safing/portmaster/firewall/interception/nfq.TeardownNFCT(...)
        /home/user/git/safing/portmaster/firewall/interception/nfq/conntrack.go:30
github.com/safing/portmaster/firewall/interception.DeactivateNfqueueFirewall()
        /home/user/git/safing/portmaster/firewall/interception/nfqueue_linux.go:175 +0x11c
main.glob..func3(0x138b3c0, {0xcf0e6f, 0x0, 0x0})
        /home/user/git/safing/portmaster/cmds/portmaster-start/recover_linux.go:29 +0xd3
github.com/spf13/cobra.(*Command).execute(0x138b3c0, {0x19059d8, 0x0, 0x0})
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x138c040)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/user/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main.func1()
        /home/user/git/safing/portmaster/cmds/portmaster-start/main.go:96 +0x25
created by main.main
        /home/user/git/safing/portmaster/cmds/portmaster-start/main.go:95 +0x291
```
```
➜ ~ cat /opt/safing/portmaster/logs/start/2023-02-07-10-03-01.log 
NJ{"Created":1675764181,"Modified":1675764181,"Expires":1678356181,"Deleted":0}S
executing start/portmaster-start version 0.8.8 on linux amd64
[control] 2023/02/07 10:03:01 starting /opt/safing/portmaster/updates/linux_amd64/core/portmaster-core_v1-0-6 --data /opt/safing/portmaster
[control] 2023/02/07 10:05:19 core/portmaster-core exited without error
```
```
➜  ~ cat /opt/safing/portmaster/logs/app/2023-02-07-10-02-49.log 
NJ{"Created":1675764169,"Modified":1675764169,"Expires":1678356169,"Deleted":0}S
executing app/portmaster-app.zip version 0.2.5 on linux amd64
Portmaster data directory: /opt/safing/portmaster
systemctl start portmaster.service --no-pager
systemctl cat portmaster.service --no-pager
systemctl is-running portmaster.service --no-pager
notifier:exit 0
notifier:close 0
```

**Comment by Raphty** [comment]
If I understand correctly your issue is that Portmaster breaks you Docker IP tables?

Portmaster currently does not work well with all Virtualization Systems, and they are at the moment out of scope for us.
As you can see on the pricing page, we are consider bringing this as a Supporter and Unlimited feature in the future. If you want to see this working consider supporting our work https://safing.io/pricing/ Thanks!

**Comment by nbrugger-tgm** [comment]
> If I understand correctly your issue is that Portmaster breaks you Docker IP tables?
> 
> Portmaster currently does not work well with all Virtualization Systems, and they are at the moment out of scope for us.
> As you can see on the pricing page, we are consider bringing this as a Supporter and Unlimited feature in the future. If you want to see this working consider supporting our work https://safing.io/pricing/ Thanks!

Yes and no - docker breaking with Port aster is unfortunate but not the issue I reported, it was just the reason I discovered that bug, the bug itself is a go panic segfault when running the iptable cleanup command as described.

**Comment by nbrugger-tgm** [comment]
@Raphty could you please re-open the issue since the reasoning given above?

The docker thing was just the way by which i measured if portmaster correctly reverted its changes
