### ISSUE TITLE
Portmaster does not block DNS requests 

### ISSUE THREAD

**Issue by fractalmoth** [safing/portmaster#1088]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

Portmaster reports it is blocking domains on a filter. But it is not blocking those domains. I use OpenVPN (protonvpn) and nextDNS. I have configured Portmaster to connect to the nextDNS DNS in Portmasters settings. I have selected several DNS addresses for it to block. The network activity in Portmaster shows that the connection was blocked with a red dot. However when I check in nextDNS online it shows that a DNS request was made for that blocked address from the PC running Portmaster. 

**What did you expect to happen?**:

I expected Portmaster to block the address I had asked it to block using the outgoing rules.

**How did you reproduce it?**:

I attempted to connect with my browser to addresses that I had blocked in Portmaster. They would connect normally even though I had blocked them in Portmaster. NextDNS reporting system shows my PC running Portmaster, connecting to DNS addresses that I have listed to block in Portmaster. 

**Debug Information**:

It is a windows PC running windows 10. I don't have any other DNS systems installed. NextDNS shows that portmaster is connected to it correctly using the correct DNS over TLS settings. If it was not connected to the NextDNS system the website would show it wasn't. I am using OpenVPN.

**Comment by Raphty** [comment]
this is normal behavior.

Portmaster block all DNS requests and does them itself, it then resolves the request to get all the information.
This is why you see the request in next dns

What you don't see is that Portmaster is **not** giving the app which did the request the information on how to connect. So the connection is blocked!

**Comment by fractalmoth** [comment]
Hi Raphty. 
Thanks for explaining this to me. It makes a lot of sense now.
I think there are some downsides to this though. Windows especially when it is not able to make DNS connections begins to spam DNS requests. Some other services and apps will do this as well causing an influx of requests.
Perhaps a feature in the future to consider would be a cooldown on DNS requests from an App? Let's say Portmaster denies an DNS request from an app, if that app requests that DNS resolution again, Portmaster does not resolve it for another 30 minutes or so. 
Not sure if that's possible but that might an idea.
Thank you very much for your work and your time.

**Comment by Raphty** [comment]
Cool idea thanks!
