### ISSUE TITLE
The computer's internet is disconnected

### ISSUE THREAD

**Issue by RongHouchao** [safing/portmaster#1095]
After opening the portmaster, the computer's Internet is disconnected. How can I restore network access?

**Comment by vlabo** [comment]
Please provide more info.

What OS are you using?
Did you restart your device after you installed Portmaster?
Does Portmaster show any message and do you see active connections in the UI?

**Comment by RongHouchao** [comment]
What OS are you using?
--- Windows10

Did you restart your device after you installed Portmaster?
-- Yes. The device has been restarted after installation.

Does Portmaster show any message and do you see active connections in the UI?
--The interface is shown as follows.

![image](https://user-images.githubusercontent.com/117245915/218044642-2029ecab-69a6-43b3-a6e0-19830418f809.png)


After closing the portmaster, access to the Internet will return to normal. After opening the portmaster, access to the Internet will be blocked.

**Comment by RongHouchao** [comment]
I tried. After opening the portmaster, it is accessible to access the Internet through IP, but it is not accessible to access the Internet through domain name. I suspect that portmaster blocked DNS resolution. Is there any missing configuration?

**Comment by vlabo** [comment]
There is a notification, you can view it when you click the bell icon, this will give you more insight what is happening.

By default Portmaster blocks secure dns request and redirects regular dns request thought a secure channel which is configurable, in the settings.If you have any other dns software on you device this may conflict with Portmaster. Disabling the software may fix the issue.

If the problem is someware else please provide Debug Info, so we can have more insight on what is happening.

**Comment by RongHouchao** [comment]
![image](https://user-images.githubusercontent.com/117245915/219284998-48e835b4-2bff-4844-be1f-c98c1ad34445.png)
Is DNS configured in this way? I have configured it, but still can't access the Internet.

**Comment by RongHouchao** [comment]
How to view the network request message

**Comment by RongHouchao** [comment]
If I want to see a detailed message of network connection, similar to the network packet captured by wireshark, where can I check it.

**Comment by Raphty** [comment]
Sorry @RongHouchao but without debug information https://wiki.safing.io/en/FAQ/DebugInfo this is difficult to troubleshoot.
also you did not answer the question regarding the notification earlier, Portmaster does try to tell you something, this might be the solution already
