### ISSUE TITLE
Portmaster causes slow loading of webpages, latency in apps and other slowdowns on windows 10

### ISSUE THREAD

**Issue by fractalmoth** [safing/portmaster#1100]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Portmaster takes between 20 and 60 seconds to open webpages and allow apps to communicate out. But having Portmaster enabled causes the browser to freeze for half a minute sometimes less and sometimes more before the page loads. When the page has loaded there is no longer any wait time and navigating within the page is fast and fine. 

It seems to only happen when initially connecting to a website. I saw there was an eariler post from last year detailing this exact situation. However it seems to still be an issue.

I am using windows 10.

**What did you expect to happen?**:
I expected my browser to load websites the same as it does without Portmaster. 

**How did you reproduce it?**:
This happens everytime portmaster is enabled and working. I thought disabling filters would help but it did not. 

**Debug Information**:

**Comment by Raphty** [comment]
this has to do with DNS and can depend on the DNS you have configured inside Portmaster. the default is Cloudeflare because it is the fastest for most people, but try a different one and check if that fixes your issue.

**Comment by fractalmoth** [comment]
Thanks Raphty.
After your advice, I've reinstalled and switched to cloudflare finding that things are much more responsive. Previously I was using NextDNS as my DNS resolver. 

After playing around with the DNS server settings in portmaster I've found that resolving NextDNS over TLS seems to cause very slow responses for me. This is made much worse if in Portmaster there are DNS filters enabled.

I switched to dns over HTTPS for NextDNS and disabled portmasters filters which has significantly increased the responsiveness.

Thanks again for your help and your work on this project.

**Comment by Raphty** [comment]
The filters are an add-on but as you mentioned - there are alternatives for that, what Portmaster does what others don't do is allowing to block specific domains in specific apps. with pi hole its all or nothing. In regards to dns over https or tls, there is debate - but we agree TLS is better in most cases, which is why we have it as the default.

**Comment by fractalmoth** [comment]
I agree with Raphty. DNS filters are very good but the main reason for me personally using the program is control and analysis of what my programs are doing, who they are calling and control over their network functions. 

Intitially I needed a replacement for Private Windows 10 firewall which had a memory leak and hadn't been updated for some time and Portmaster is an amazing alternative. 

Since I have DNS filter lists already in NextDNS it would be superfluous to have double filters anyway. Although I've found enabling the safing filter lists which aren't on NextDNS don't slow down the latency of initial website loading very much, if at all.

At the end of the day I'm very happy with Portmaster as a program. Although I understand there is a signficant debate regarding DNS over HTTPS vs DNS over TLS, in reality I don't have much of a choice if I want my webpages to load in a timely manner.
