### ISSUE TITLE
Portmaster system tray notifier stops responding.

### ISSUE THREAD

**Issue by Kostrol** [safing/portmaster#1105]
**What happened**:
The system tay notifier of portmaster seems to get stuck after a while on Windows 11 and is unresponsive when right clicking or interacting.

**What did you expect to happen?**:
Being able to click the tray notifier.

**How did you reproduce it?**:
This seems to happen after a period of time on it's own, with no direct evident cause. Even ending the task and reopening the executable it will remain stuck. I am using a program from Stardock called Start11 as an alternative to the native windows taskbar, maybe there could be some conflict with this, however it seems to have little to no influence over the default native tray.

**Comment by Raphty** [comment]
can you pleas provide debug information so we can have a look into what might be going on.
https://wiki.safing.io/en/FAQ/DebugInfo

**Comment by Raphty** [comment]
Ticket# 1717445

**Comment by Raphty** [comment]
thanks for sharing the debug info, I was not able to find an obvious clue in there.

Can you shed some light why you use the tray icon? I never use it

**Comment by Raphty** [comment]
I agree, we have been a bit inconsistent in removing features when they have been implemented.

I personally want an as clean as possible interface so I hide all the tray icons if I can.

But you know we do not develop just for us. But for others, so improving the features, if the value is clear, is something I want to make sure happens.

so thanks for reporting and letting me know.

**Comment by Terrance** [comment]
This was marked stale but is still a recurring problem -- unfortunately I've not seen it happen reliably, though I do often find it unresponsive after resuming from hibernation.

**Comment by didi8517** [comment]
Hello there. This sounds a lot like https://github.com/safing/portmaster/issues/340 no? To me, anyway. And I have similar problems, the tray icon suddenly not reacting, needs to be shut down in task manager and reopened from start menu. I haven't been able to establish a pattern of when this happens or so... Hope there comes a solution: I find it much more practical to open the UI from a tray icon, than having to open the start menu (and I don't like cluttering my desktop with shortcuts)
I've got Win10 laptop, btw

**Comment by elgatov** [comment]
this problem is still present and does not affect only the tray icon but the `portmaster-start.exe` process. if we kill the process manually through the task manager and try to reopen it by `Start menu > Portmaster` the process will start but will die seconds later.
