### ISSUE TITLE
Silent / unnatended install + import saved profile, would be nice for NTLite integration.

### ISSUE THREAD

**Issue by UNTAGATUN** [safing/portmaster#1111]
**What would you like to add or change?**:
Silent / unnatended install + import saved profile, would be nice for NTLite integration.

**Why do you and others need this?**:
For a painless windows fresh install.

**Comment by Raphty** [comment]
We are thinking about a snapshot feature - where you can transfer one Portmaster to another device - does this sound like what you are looking for?
