### ISSUE TITLE
Not able use DoH with IP

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1114]
**What happened**:

Example - https://8.8.8.8/dns-query

![image](https://user-images.githubusercontent.com/62152714/221513834-8cf85bad-8053-4086-b09f-a91d3ae33056.png)

**What did you expect to happen?**:

When using DoH with IP. It is harder to block and spoof.

**Comment by dhaavi** [comment]
It cannot be secure without knowing which domain name to verify the TLS encryption certificate for.

Use as seen here:
https://docs.safing.io/portmaster/guides/dns-configuration#google-public-dns-

`dot://8.8.8.8:853?verify=dns.google&name=GoogleDNS&blockedif=zeroip`
or with DoH:
`doh://8.8.8.8?verify=dns.google&name=GoogleDNS&blockedif=zeroip`

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/224532327-eaad43a7-7a51-422f-b445-b66648c59124.png)

![image](https://user-images.githubusercontent.com/62152714/224532342-80ec6ba8-9658-45ab-baed-0ea3cbd2ebc3.png)
