### ISSUE TITLE
Request to add DNS in Quick Settings.

### ISSUE THREAD

**Issue by Noir16** [safing/portmaster#1117]
**What would you like to add or change?**:
I would like to request that the following DNS lists be added to the Quick Settings list so that they can be easily added within Portmaster.

Mullvad:
`dot://194.242.2.2:853?verify=doh.mullvad.net&name=Mullvad&blockedif=empty`
`dot://193.19.108.2:853?verify=doh.mullvad.net&name=Mullvad&blockedif=empty`

Control D (with Malware Filter):
`dot://76.76.2.1:853?verify=p1.controld.com&name=ControlD&blockedif=empty`
`dot://76.76.10.1:853?verify=p1.controld.com&name=ControlD&blockedif=empty`

dns0 ZERO:
`dot://193.110.81.9:853?verify=zero.dns0.eu&name=dns0&blockedif=empty`
`dot://185.253.5.9:853?verify=zero.dns0.eu&name=dns0&blockedif=empty`

**Why do you and others need this?**:
This provides easy access to other trusted DNS.
I think having a DNS other than Adguard and Cloudflare as the default would provide a better environment for privacy.

However, I'm not asking you to uninstall Adguard and Cloudflare for compatibility reasons.

Some sources: https://www.privacyguides.org/en/dns/

**Comment by Raphty** [comment]
Thanks for the suggestion, we will take this into consideration.

**Comment by youdontneedtoknow22** [comment]
> dns0 ZERO

Didn't found anything about it on [Privacyguides](https://www.privacyguides.org/en/dns/). IMO Adding Mullvad is enough, the more options you get the more complicated it gets

**Comment by Noir16** [comment]
> Didn't find anything about it on [Privacyguides](https://www.privacyguides.org/en/dns/). IMO Adding Mullvad is enough, the more options you get the more complicated it gets

This does not refer to the Privacyguides. (Only Mullvad and ControlD)
This DNS was recently released by nextdns for European users, and we thought it might be useful for European users, so we added it.
Most users will choose Cloudflare, and those like us will just have to "choose". I think that more choices are better.

**Comment by Noir16** [comment]
Better DoH servers for users in Asia. (Powered by xTom, Available to users in Europe and the Americas as well as Asia.)

DNS.SB:
`dot://185.222.222.222:853?verify=dot.sb&name=DNS-SB&blockedif=empty`
`dot://45.11.45.11:853?verify=dot.sb&name=DNS-SB&blockedif=empty`

**Comment by Raphty** [comment]
hey @Noir16 thanks for the suggestions, I added them to the wiki! https://wiki.safing.io/en/Portmaster/App/DNSConfiguration. As suggested here, we are not going to add too many DNS servers to the drop down list to keep the UI simpler (it is pretty crowded as it is). I already have ideas for the future on how we could make this easier in the future, but for now I think the wiki is the best spot.

I also put a warning label next to DNS.SB and dns0 ZERO since I don't know them. If you or someone else knows them better and can send review links I will consider removing the warning.

**Comment by Noir16** [comment]
@Raphty Thanks! DNS-SB is Recommended Asian Users, But, Asian DNS, as in the wiki, can be misleading.
DNS-SB is a DNS service provided by VPS and hosting company xTom, and is available in many countries, not just Asia.
