### ISSUE TITLE
Portmaster notification re VPN & aniti-virus affecting

### ISSUE THREAD

**Issue by GOMpt** [safing/portmaster#1118]
Hi
Please disclose security related issues privately to support@safing.io.
-->

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

Two occasions in the last 24 hours in which Portmaster notification advised that something incompatible was affecting it such as a running VPN or anti-virus. However, no VPN running and no anti-virus running. On the first occasion, restarting Portmaster resolved the issue. After downloading / copying debug info on the second occasion the issue appeared to be resolved and Portmaster reported Portmaster & SPN operating normally. On the second occasion I was trying to make a payment via Paypal. I have experienced a problem with Paypal previously when using a VPN. It's impossible to login to Paypal when using a VPN in my experience. However, I did succeed in making the payment which suggests that Paypal did eventually accept the SPN exit node.

**What did you expect to happen?**:

a) I did not expect the error notifications.
b) I was aware that there may be a problem with Paypal when using Portmaster / SPN.

**How did you reproduce it?**:
NA

**Debug Information**:

**Comment by dhaavi** [comment]
Closed by accident.
