### ISSUE TITLE
(Linux) Distinguish wine run applications

### ISSUE THREAD

**Issue by Flavelius** [safing/portmaster#1119]
(It's possible that this mainly applies to the portmaster UI, not sure which part handles it though)

**What would you like to add or change?**:
Currently it seems when an application runs within wine (the windows compatibility layer) and wants to connect to the internet, 'wineserver' is what's caught by portmaster. 
It would help if portmaster or the portmaster ui were able to recognize the actual application in this case to improve decision making.

**Why do you and others need this?**:
Currently it's complicated trying to determine what wants to connect where when some applications have (/background) helper processes, for telemetry etc. that some, me included, do want to block without restricting the main application

**Comment by Raphty** [comment]
Thanks for the suggestion, Wine is at least a bit like a VM in that regard and will therefore take some time until we will tackle it

**Comment by Flavelius** [comment]
This auto close messages is irritating, does it mean you need more input to even keep it on your todo-later list?

**Comment by Flavelius** [comment]
By the way, the 'Process Detail' popup/tab correctly displays the process name as the actual executable's with the commandline also matching, only the Path points to /usr/lib/wine(64). This all makes me believe that it should already have all the required information to correlate to the actual executable instead of simply falling back to the wine process
