### ISSUE TITLE
Let the system/user manage DNS configuration.

### ISSUE THREAD

**Issue by Chief36** [safing/portmaster#1122]
**What would you like to add or change?**:
Please just let Portmaster be less nosy by having an option to make Portmaster just obey the DNS configuration set by the system, i.e., just disabling the local dns client(?). 

**Why do you and others need this?**:
Sometimes DNS configuration setup by a typical nerd is so complex that it is beyond the scope of Portmaster to be able to handle DNS properly. It just breaks some things, like DNSSEC, .loki and .snode resolution in my case. Similarly, there might be other uses cases where it is better to let a different DNS client or just the system handle DNS entirely - Portmaster plays no role here than to just sit and watch. 

Please provide suggestions, opinions and corrections 😀.

**Comment by dhaavi** [comment]
> nosy

I believe this is the reason people install Portmaster. In order to see what is going on on their system.

> sit and watch

Literally what Portmaster is supposed to do.

---

Snarkiness aside...

We might implement DNSSEC in the future, but really, your recursive resolver should do that for you.
Portmaster can handle custom zones, eg: `dns://127.3.2.1?search=loki&search-only`

It would be great if we had the option to disable handling DNS, but Portmaster needs the domain info of connections in order to provide its privacy protections.

**Comment by Chief36** [comment]
> I believe this is the reason people install Portmaster. In order to see what is going on on their system.

In that process it should not break the DNS configuration setup by the user. 

> We might implement DNSSEC in the future, but really, your recursive resolver should do that for you.
Portmaster can handle custom zones, eg: dns://127.3.2.1?search=loki&search-only

I tried it and this doesn't work very well. It is unable to resolve PTR records which is a requirement for Lokinet.   

> Literally what Portmaster is supposed to do.

But it is not doing what it is supposed to do. It thinks it knows how to handle DNS configuration better and breaks it.

> It would be great if we had the option to disable handling DNS, but Portmaster needs the domain info of connections in order to provide its privacy protections.

Could you please elaborate? Why exactly does Portmaster need the domain info of connections and what are the significant privacy protections it provides using this?

**Comment by youdontneedtoknow22** [comment]
Just to add another use-case for this. [Privacyguides about encrypted DNS](https://www.privacyguides.org/en/advanced/dns-overview)

> If you're using a VPN, you should use your VPN's DNS servers. When using a VPN, you are already trusting them with all your network activity.

And as I did a standard [DNS leak test ](www.dnsleaktest.com)while connected to my VPN, it shows that I'm using the DNS Provider from Portmaster (Cloudfare)

**Comment by CommanderTurtle** [comment]
Bump on reviving an old thread. Is the project even compatible with this, or does anyone actually use this type of case? For instance. My domain I host on openwrt I use full dnssec and dnscrypt. Windows just needs to be able to use unsecured 192.168.x.1 for everything. As it does. I already handle my filter lists. And, I already handle everything with secure dns getting routed properly by superrouter.

Question is, I can't append random filterlists to any of this? I'm forced to keep portmaster DNS off in my case, and solely rely on the whole feature category being disabled?

Or - if anyone knows, please do if you do, is there a dns route I have to set like mentioned above? i.e. "dns://127.3.2.1" ...

To add to the stupididty, I host quad9 for ipv6 as well as ipv4 in my local dns server. As well as performing overrides for unsecured dns queries, with filtered dnscrypt and dnssec validation. Would be neat if at the application level I can just still let portmaster block certain domains specifically for the system, but I am a noob at the application layer, no matter how deep I get into low-level nftables/iptables/ip6tables. Feel free to reply if you know the answers to any of these things. Cause it's probably simple and the wiki just needs work (very bare bones wiki)
