### ISSUE TITLE
NordVPN and Portmaster won't work together in windows 11-any help

### ISSUE THREAD

**Issue by looking0101** [safing/portmaster#1123]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

**What did not work?**

**Debug Information**:

**Comment by looking0101** [comment]
either program will work on its own but if you try and do both no go nordvpn will not connect while portmaster is running.

**Comment by Raphty** [comment]
we do have a compatibility list, it is not the most up to date - but if you add more details I can add them to the list.

https://wiki.safing.io/en/Portmaster/App/Compatibility

keep in mind, we do not actively try to stay compatible with most VPN software.

**Comment by looking0101** [comment]
no worries  already moved on to a different software than yours. Thanks
