### ISSUE TITLE
Automatic reload / Live feed of Network Activity

### ISSUE THREAD

**Issue by OfficialEsco** [safing/portmaster#1124]
This is a follow up of #679 which got closed for some reason.

**What would you like to add or change?**:
I would like to set a Reload interval or even have a real time feed of Network Activity

Because this is pretty pointless =))
![Screenshot_20230308_171245](https://user-images.githubusercontent.com/15158490/223767602-eaa06a9d-159c-4f1c-8eaf-919014600845.png)

**Why do you and others need this?**:
As the Original Issue said, its a nice QOL for monitoring whats going on without having to click reload.

**Comment by NightHawkATL** [comment]
2nd'd!

Coming from the Apple world, I used Little Snitch for the longest time and it was great. Portmaster is the closest I have found to the same thing. Auto reload/refresh of the network monitor would be a great thing to have as I have it always open on a 3rd monitor to see what is going on. Little Snitch did this by default.

**Comment by Raphty** [comment]
I think we have this already on the roadmap. 

rest assured we want this as well, and it will be implemented.

**Comment by OfficialEsco** [comment]
Uhm, wrongly closed?

**Comment by dhaavi** [comment]
Yup

**Comment by OfficialEsco** [comment]
Does this mean the feature is added? 🤔

**Comment by Raphty** [comment]
as you probably have noticed, I want to clear out issues. there are many things we know we want to do, having open issues does not increase the desire to work on them, but distracts form the other issues that actually do need to be worked on at the moment.

we want to do this. and we do have plans for it 😄 it is not implemented yet. sorry

**Comment by OfficialEsco** [comment]
GitHub 👍 is used for wanted Features from the community and the issue should be used for progress for transperency. These issues are critical if you want outside contributors.

**Comment by Raphty** [comment]
I agree, but when you have 300+ open issues people don't search but just open new issues -  also sadly we have not been good in reporting back on issues on how the development has continued... I know we could do better in that regard... 😅
