### ISSUE TITLE
Incompatible to systemd-homed hsers

### ISSUE THREAD

**Issue by TobiPeterG** [safing/portmaster#1130]
Hey there,

Today I tried portmaster and noticed that users created with -homed can't interact with the GUI.
The app just says connecting to portmaster...

A traditional user can interact with the app.
Am I missing something?
Can this be confirmed?

To reproduce, simply create a systemd-homed user with:
Homectl create username

Then, try to open the application.

I'm on Manjaro Linux and installed it using the official package that downloads the newest version.

Should any additional information be required, I'd be happy to help!

**Comment by Zesko** [comment]
> To reproduce, simply create a systemd-homed user with:
Homectl create username

Do not forget to login this username of systemd-homed.

Yes, I can reproduce this issue on VM:  **Endless waiting for "Connecting to Portmaster".**  
But no error in log except ignoring `gpu_memory_buffer_support_x11` on VM.

```
/opt/safing/portmaster/portmaster-start app --data=/opt/safing/portmaster 
[control] 2023/03/15 11:01:23 starting /opt/safing/portmaster/updates/linux_amd64/app/portmaster-app_v0-2-5/portmaster-app_v0-2-5 --data /opt/safing/portmaster
Portmaster data directory: /opt/safing/portmaster
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[4359:0315/120123.620382:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported


```

Switch to normal user without systemd-homed, no issue.
However, I do not think it is a bug, but it would lack some feature that supports systemd-homed?

**Comment by TobiPeterG** [comment]
> However, I do not think it is a bug, but it would lack a feature that supports systemd-homed?

That might be.
Some apps have issues checking the username/uid with systemd-homed users, as they are not registered the same way normal users are.
