### ISSUE TITLE
DNS Leak: Chromium needed access 192.168.1.1:53, Postmaster is not redirecting it to self and router is resolving Chromium's requests.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1136]
Also Most sites are not loading or not loading fully and speed is slow due to postmaster
Firefox doesn't have access to 192.168.1.1:53 iirc but it also has the same problems - Most sites are not loading or not loading fully and speed is slow due to postmaster

Windows 11 x64 Enterprise
Portmaster 1/.0.7

**Comment by Raphty** [comment]
this seems to be a setup issue and handled in #1137
