### ISSUE TITLE
[Windows] Shadow PC - After installation, it doesn't connect

### ISSUE THREAD

**Issue by unz3r0** [safing/portmaster#1144]
**What worked?**
Installation and restart on https://shadow.tech

**What did not work?**
I cannot connect to the shadow pc anymore. It seems that the outgoing video stream is blocked. Kinda an expected experience?

**Debug Information**:

I cannot include any debug information, since I have no access anymore.

**Comment by dhaavi** [comment]
Hey @unz3r0, thanks for reporting this.

This seems to be a VM running in the cloud or so. Portmaster is probably just blocking the incoming connections. How do you connect to the shadow pc? RDP/VNC? What Ports do you use?

**Comment by unz3r0** [comment]
Hey @dhaavi,

It is difficult to say what ports it uses. First, there is an electron app, which I use as client. It is used for authentication and setting parameters with the GUI.

There is a binary which is called `Shadow` and `ShadowHelper` (Linux) which actually doing the connection handling. Here is the line from `ps -aux | grep -i shadow` (sensible information replaced):
```
./Shadow --ip <domain> --port 2000 --branch prod --agent <browseragent> --session-id <sessionid> -b 49000000 --user-uuid <uuid> --no-usb --streaming-profile reliability --token <token> --cef-locale=de --dynamic
```

On the Cloud VM there are several `Shadow` programs/services running. One of them is `ShadowStreamer.exe.`.

![grafik](https://user-images.githubusercontent.com/33820044/227708974-fb40b6ba-8937-470f-8031-6e9fccedd52c.png)


Maybe this gives you an idea how one would narrow it down?

![grafik](https://user-images.githubusercontent.com/33820044/227708210-621fa127-3222-4d33-8b39-e84e6fc9dbd2.png)

:notebook: ShadowDomain:Port -> MyPublicDomain:Port

Anyway, it is a self-made service from shadow/blade, so it seems no VNC/RDP involved. It is made to detect gpu intensive applications and adjust the frame rates and responsiveness.

If you need more specific information, then I would gladly provide them.

**Comment by Raphty** [comment]
Hey there @unz3r0 I just have read through the old comments, if this issue has not been resolved yet, here my suggestion to resolving it.

Shadow is a remote PC app, and Portmaster is blocking all Incoming connections by default, we do not yet offer an installer that handles this differently. 

You did not answer @dhaavi question regarding the how you are connecting, so helping here is hard, but over all what you would need to do is find another way to connect to the remote pc and disable the blocking of Incoming connections in Portmaster.

As mentioned, this is not a typical use case and support for it is super limited at the moment.
