### ISSUE TITLE
not compatible with dnscrypt-proxy2 

### ISSUE THREAD

**Issue by fR415** [safing/portmaster#1146]
**What worked?**
install + run

**What did not work?**

dns not compatbile with dnscrypt-proxy2

**Debug Information**:

<!--
Operating System: EndeavourOS 
KDE Plasma Version: 5.27.3

Qt Version: 5.15.8
Kernel Version: 6.2.7-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 12 × Intel® Core™ i5-10600K CPU @ 4.10GHz
Memory: 15,5 GiB of RAM
Graphics Processor: AMD Radeon RX 580 Series

System Version: 2.0

**Comment by OfficialEsco** [comment]
@Raphty i think you have to stop using "waiting for input" if you're not waiting for a answer c:

**Comment by dhaavi** [comment]
Yes, this could have been communicated clearer. But it seems there is nothing actionable here anyway. Looks more than a report than a help request.

In case you would like help in getting it to work @fR415, please provide more information about dnscrypt-proxy2 and any error messages.
