### ISSUE TITLE
Not Compatible with Fedora Silverblue Rawhide

### ISSUE THREAD

**Issue by minadwaita** [safing/portmaster#1150]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)
```
NAME="Fedora Linux"
VERSION="Rawhide.20230329.n.0 (Silverblue Prerelease)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux Rawhide.20230329.n.0 (Silverblue Prerelease)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://silverblue.fedoraproject.org"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://github.com/fedora-silverblue/issue-tracker/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
SUPPORT_END=2024-05-14
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='Rawhide.20230329.n.0'
```
**What worked?**

Installing the rpm package via GNOME Software GUI.

**What did not work?**

- Launching the program via GNOME dashboard.

- Running

```
❯ curl -fsSL https://updates.safing.io/latest/linux_all/packages/install.sh | sudo bash
Portmaster Installer

 Application Firewall: Block Mass Surveillance - Love Freedom
The Portmaster enables you to protect your data on your device. You
are back in charge of your outgoing connections: you choose what data
you share and what data stays private. Read more on docs.safing.io.

- Checking dependencies ...
- Detected supported architecture amd64
- Downloading portmaster-start and installer assets
-   Downloading assets from https://updates.safing.io/latest/linux_all/packages/installer-assets.tar.gz
*   Installer assets downloaded to /tmp/portmaster-installer-UCuHVLGcwC/assets.tar.gz
-   Downloading portmaster-start from https://updates.safing.io/latest/linux_amd64/start/portmaster-start
*   portmaster-start downloaded to /tmp/portmaster-installer-UCuHVLGcwC/portmaster-start
- Extracting assets to /opt/safing/portmaster
tar: .: Cannot change mode to rwxr-xr-x: Read-only file system
tar: ./.INSTALL.sh: Cannot open: Read-only file system
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/32x32: Cannot mkdir: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/32x32/portmaster.png: Cannot open: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/48x48: Cannot mkdir: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/48x48/portmaster.png: Cannot open: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/128x128: Cannot mkdir: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/128x128/portmaster.png: Cannot open: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/96x96: Cannot mkdir: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/96x96/portmaster.png: Cannot open: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/16x16: Cannot mkdir: No such file or directory
tar: ./icons: Cannot mkdir: Read-only file system
tar: ./icons/16x16/portmaster.png: Cannot open: No such file or directory
tar: ./portmaster.desktop: Cannot open: File exists
tar: ./.installed-files: Cannot open: Read-only file system
tar: ./portmaster.service: Cannot open: File exists
tar: ./portmaster_notifier.desktop: Cannot open: File exists
tar: Exiting with failure status due to previous errors
```

**Debug Information**:
```
❯ cat /opt/safing/portmaster/log
cat: /opt/safing/portmaster/log: No such file or directory
```

According to <https://silverblue.fedoraproject.org/about>

>However, unlike other operating systems, Silverblue is immutable. This means that every installation is identical to every other installation of the same version. The operating system that is on disk is exactly the same from one machine to the next, and it never changes as it is used.

**Comment by minadwaita** [comment]
What I really want is a Flatpak version on Flathub.

**Comment by Raphty** [comment]
We have been thinking about Flatpak in the past, but due to the nature of Flatpak (sandboxing apps) we think this will not be possible - maybe this changes in the future.

also this is not a priority at the moment.

**Comment by minadwaita** [comment]
I got an idea of making this app a local VPN or local proxy.

**Comment by minadwaita** [comment]
But the problem is that a local VPN or local proxy cannot determine which application process made which network request. Are there GNOME APIs for this?

>A possible way to do this is to use the Linux network namespaces feature, which allows creating isolated network environments for different processes. By using network namespaces, a local VPN or proxy can assign a different network interface and routing table to each application process, and thus monitor and control the network traffic of each process separately. To use network namespaces with GNOME applications, one would need to use the GApplication API, which provides a way to launch and manage application instances. By launching each application instance with a different network namespace, the local VPN or proxy can associate each network request with the corresponding application process.

Bing AI gave me this.

**Comment by Raphty** [comment]
thanks for the input

**Comment by BirdInFire** [comment]
> thanks for the input

One question tough does installation with rpm on Silverblue work as intended (if we follow the selinux fix on your doc) ?

Prefer ask before even trying on this immutable system.

Thanks !

**Comment by fR415** [comment]
Is not working also on Kinoite, the app will install normally but, when manually launched: " The Portmaster has been launched by an unexpected portmaster-start binary at /var/opt/safing/portmaster/portmaster-start. Please configure your system to use the binary at /opt/safing/portmaster/portmaster-start as this version will be kept up to date automatically " .

I tried all startup options with no luck, i am new in those immutable systems, but i didn't found any clear way to completely override the ostree on this case, even with the ostree override didn't helped at all, it just installed some for me apparently useless drivers and so on.

For what i've read on previous posts is what i was thinking too, create a VPN service i think would be easier to set in any circumstances and OS's.

**Comment by Raphty** [comment]
Currently Fedora Silverblue is not working, if this changes in the future you will find the guide here:
https://wiki.safing.io/en/Portmaster/Install/Linux/FedoraSilverblue

If you want to help get Portmaster compatible pleas reach out.

**Comment by 6-AND-9** [comment]
Has anyone tried with `ostree admin unlock --hotfix`?
