### ISSUE TITLE
Route traffic to network interface ; I use tun2socks to TUN-ify proxies ; Consider usage with lokinet

### ISSUE THREAD

**Issue by planetoryd** [safing/portmaster#1153]
- Ability to route application traffic to user-specified interface. 
  - Use case 1, for [tun2socks](https://github.com/xjasonlyu/tun2socks) 
  - Use case 2, traffic may be routed to lokinet TUN (and they plan to support TAP)

Personally I use a [VPN](https://geph.io) specialized in bridging (as in Tor bridging) along with some manually bought proxies (the exit IPs of geph aren't clean), which isn't what SPN offers.

I currently put tun2socks TUNs in individual network namespaces and put my apps in firejail. In the past I tried using iptables to mark traffic and route them to TUN, which seemed to leak traffic when the TUN was down and troublesome to set up. 

Creating an interface for each proxy might not be the best practice, tho

**Comment by Raphty** [comment]
thanks for the suggestion, this is not a focus for us at the moment. Maybe this changes in the future.
