### ISSUE TITLE
Button to toggle Google Blocklist

### ISSUE THREAD

**Issue by Abyssgrowth** [safing/portmaster#1155]
**What would you like to add or change?**:
Would you be so kind to add a toggle on/off option to block all google tracking / all facebook tracking / microsoft / amazon / apple
This wouldn't need to be active by default since many people are still silly sheeps using google but it would be really great if you had an option to block google analytics, etc.

**Why do you and others need this?**:
Privacy. Freedom.

**Comment by Raphty** [comment]
cool idea, maybe a section in the filter list area

**Comment by Raphty** [comment]
This sounds like a great community project. If anyone wants a crack at this you can create a pull request and we will have a look. Also if you are planning this and have questions get in touch.

**Comment by LoganDark** [comment]
> This wouldn't need to be active by default since many people are still silly sheeps using google

lol~

> Would you be so kind to add a toggle on/off option to block all google tracking / all facebook tracking / microsoft / amazon / apple

This sounds like a filter list, which Portmaster already supports. I don't think there is currently a filter list for blocking Google/Facebook/Microsoft/Amazon/Apple but you could probably make one and propose to get it added to the settings menu.

**Comment by Abyssgrowth** [comment]
> cool idea, maybe a section in the filter list area

That's what i had in mind.
What can we do to contribute to the google-blocklist?
I've only got a few custom urls blocked in portmaster, really not much.

www.google.com
accounts.google.com
googletagservices.com
googlesyndication.com

Blocking google.com will break google-captcha verification on all websites.
It's a bit annoying but i don't mind allowing the connections temporarily when registering an account somewhere.

Also it would be great if we can fully block microsoft, there are some connections even when you blocked all the preinstalled bloatware. System DNS Client (svchost.exe) trys connecting to these two domains:
go.microsoft.com and ctldl.windowsupdate.com (i had to manually block them).

Plus, nvidia drivers should also be blocked from phoning home, i've used NVCleanstall to remove bloatware of the driver, however even then the nvidia driver trys to connect to:
services.gfe.nvidia.com
That's ridiculous because i never used geforce-experience, which i asume is what gfe stands for.

**Comment by LoganDark** [comment]
> go.microsoft.com

This is required for a ridiculous amount of functionality. Basically everything uses this. I would not block this globally as users wouldn't know they would have to make an individual exception for some programs.

**Comment by LoganDark** [comment]
> Also, how do you know that? Know that go.microsoft.com is required for ridiculous amount of functionality?

It's required for doing things like using the microsoft store, all of their installers (like the SDK and WDK as well as Visual Studio itself), updates, etc. not something you would want to disable for the average user.

> Like i said, no issues for me.

Not everyone is you.

**Comment by Raphty** [comment]
we added a first version of this functionality

![image](https://user-images.githubusercontent.com/11504285/231114747-03c06ed9-33f3-459b-ae2d-6747f9cb5d1b.png)

**Comment by Raphty** [comment]
I agree that toggles are a cool idea, and we can change this in the future to be easier to access.

**Comment by dhaavi** [comment]
Important: We provided an initial set of entries for these new lists, but expect them to be curated by you - the community.

In order to request a change, please just go here: https://github.com/safing/intel-data/tree/master/lists/big-tech
Open a file and click the edit button, then create a PR.

We will then bullshit check the PR or wait a couple days for other community members to react.

**Comment by Abyssgrowth** [comment]
> > Also, how do you know that? Know that go.microsoft.com is required for ridiculous amount of functionality?
> 
> It's required for doing things like using the microsoft store, all of their installers (like the SDK and WDK as well as Visual Studio itself), updates, etc. not something you would want to disable for the average user.
> 
> > Like i said, no issues for me.
> 
> Not everyone is you.

Yeah i don't use that garbage microsoft store bloatware, deleted that nonsense at day one.
Sure not everyone is me. Anyway whatever you need from the store you can most likely get it elsewhere, and if not it's probably not worth it. But i see no point in arguging here, microsoft is garbage and so is the ms-store that's about it really.
PS: No idea what you mean about visual studio, i installed it offline and it works.

**Comment by Abyssgrowth** [comment]
> we added a first version of this functionality
> 
> ![image](https://user-images.githubusercontent.com/11504285/231114747-03c06ed9-33f3-459b-ae2d-6747f9cb5d1b.png)

Amazing! Thanks to you and the portmaster team!
