### ISSUE TITLE
How to get custom reply from portmaster ?

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1156]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

See https://github.com/kiwix/libkiwix/issues/926

I want portmaster to redirect to a IP when asked for wikipedia.org

**Comment by LoganDark** [comment]
Can't you do this using your hosts file?
