### ISSUE TITLE
Network Noise reports outgoing connections

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster#1157]
Regression of process attribution:

![chrome_D3v7agid3E](https://user-images.githubusercontent.com/4723091/229617647-e8a7c882-bca4-4016-a92a-8d2df79e7b14.png)

![portmaster-app_v0-2-5_9FAIbzyejj](https://user-images.githubusercontent.com/4723091/229617678-eb01378f-1348-4dea-9e66-a43379cf7f96.png)

It's even worse now and I have to turn prompt notifications off completely because of how broken Portmaster just became.

Since Portmaster doesn't support downgrading, I guess I'm stuck like this. (This is why I generally don't update software that works...)

_Originally posted by @LoganDark in https://github.com/safing/portmaster/issues/1141#issuecomment-1494926006_

**Comment by dhaavi** [comment]
Thanks @LoganDark for reporting this.

Does this happen only with Network Noise or other apps too?
What platform are you on?

There might be an issue where Portmaster switched "Unknown Connections" and "Network Noise", please check if that matches your issue.

Also, I would kindly ask you to switch to the Beta release channel, as
- You can help us identify issues earlier and prevent them from reaching the Stable release channel
- And you can switch back to the Stable release channel yourself in case there is a regression.

**Comment by dhaavi** [comment]
Hm. Not sure why this continues to happen. What we were able to reproduce we could not anymore with v1.0.11.

Can you share the debug info from when it is happening?

Is there anything unusual about your setup maybe? (A bit of luck shot here.)

Sorry, I must have missed your comment on HN. Normally, I get a notification for that.
Are you on Discord? This is where most of the active community is at the moment.

**Comment by dhaavi** [comment]
We just released Portmaster v1.0.12 to beta, which includes a fix for this - at least it fixed the unexpected behavior I myself experienced. Please try this update and report back.

**Comment by LoganDark** [comment]
> We just released Portmaster v1.0.12 to beta

How long should I expect it to take for the update check to actually *pick up* this new version?
