### ISSUE TITLE
No update mechanism for the RPM package?

### ISSUE THREAD

**Issue by cig0** [safing/portmaster#1169]
**What would you like to add or change?**:

Hi,

While checking Portmaster as part of my evaluation of the SPN service, I noted that the RPM package lacks a repository configuration file:

```bash
~/Desktop/p % rpm -ql portmaster-installer.rpm         
/etc/xdg/autostart/portmaster_notifier.desktop
/lib/systemd/system/portmaster.service
/opt/safing/portmaster/portmaster-start
/opt/safing/portmaster/portmaster.desktop
/opt/safing/portmaster/portmaster.service
/opt/safing/portmaster/portmaster_notifier.desktop
/usr/share/applications/portmaster.desktop
/usr/share/applications/portmaster_notifier.desktop
/usr/share/icons/hicolor/128x128/apps/portmaster.png
/usr/share/icons/hicolor/16x16/apps/portmaster.png
/usr/share/icons/hicolor/32x32/apps/portmaster.png
/usr/share/icons/hicolor/48x48/apps/portmaster.png
/usr/share/icons/hicolor/96x96/apps/portmaster.png
/usr/share/pixmaps/portmaster.png
```

I also checked the website but couldn't find any reference for updating the tool.

Does Portmaster have a way to auto-update itself?

Thanks

**Comment by dhaavi** [comment]
Yes, Portmaster auto-udpates. There is a setting for this and also there is a big improvement coming in v1.0.12.

Linux packages are built with nfpm and are maintained here: https://github.com/safing/portmaster-packaging/tree/develop/linux
