### ISSUE TITLE
Disable incoming connections blocking by default

### ISSUE THREAD

**Issue by cig0** [safing/portmaster#1171]
**What would you like to add or change?*

The title says it all :)

**Why do you and others need this?**:

I'm uncomfortable with adding extra layers of complexity when unnecessary, and this one is such a case.
Since we already run firewalls on our hosts that precisely block incoming connections to specific applications, why is Portmaster stepping into that territory?
I can't see any good coming from that, but conversely, adding an extra layer of complexity to manage and take care of can lead to a waste of time troubleshooting issues that shouldn't occur otherwise.

Suppose you believe you should provide blocking functionality for incoming connections, even though we are already taking care of that with the tools we already have - {ip,ns}tables / firewalld / ufw / f2ban, etc -. In that case, I believe it should be disabled by default, as a bonus / nice-to-have feature should the user, later on, decides to turn it on.

Thanks!

**Comment by dhaavi** [comment]
Hey @cig0, thanks for the suggestion.

I don't believe that any reasonable number of regular desktop already configured a firewall on their host.

In the security world, another layer is not called "complexity", but "defense in depth" and is seen as a good thing.

If you don't like Portmaster blocking incoming connections, you can just untick "Force Block Incoming Connections" in the global settings and you have what you want.
