### ISSUE TITLE
Option to disable "bypass attempt" notifications

### ISSUE THREAD

**Issue by LoganDark** [safing/portmaster#1172]
**What would you like to add or change?**:

Option to disable "bypass attempt" notifications

**Why do you and others need this?**:

"Bypass attempts" often aren't the result of malicious code in your system actively trying to circumvent the firewall, but rather completely normal DoH attempts from innocent applications (e.g. anything that uses Electron). It would be nice to be able to turn these off, as there are quite a few culprits on my system that constantly generate these useless notifications.

What am I supposed to do, block the DoH server? The notification is telling me that's already been done, so it's not even like I can disable it once it's been seen. Not that I particularly care about seeing it in the first place anyway.

**Comment by LoganDark** [comment]
omg. I DID NOT INTEND TO SUBMIT THIS SO SOON GIVE ME A MINUTE

**Comment by dhaavi** [comment]
Hey @LoganDark,

thanks a lot for your feedback on this. I will think about how we can improve this.

Ah! One idea: Just block their DoH IP in the rules, then the bypass prevention system will not be activated.
You can easily find them in the network activity view.

**Comment by LoganDark** [comment]
> Just block their DoH IP in the rules, then the bypass prevention system will not be activated.

Thank you~

**Comment by dhaavi** [comment]
The notification is important, as the bypass prevention might break the software in question. Not everyone will just fall back to plain DNS.

**Comment by LoganDark** [comment]
> The notification is important, as the bypass prevention might break the software in question.

i said once it's been seen - maybe have a per-profile toggle to not show bypass attempt notifications for that profile. That way I can still be notified if DoH is the reason for an app not working, but I can turn them off for apps that have been verified to work without DoH.

**Comment by LoganDark** [comment]
Closed as portmaster no longer prioritizes free features
