### ISSUE TITLE
Improve documentation about Portmaster creating files into apps directories

### ISSUE THREAD

**Issue by tlartaud** [safing/portmaster#1177]
**What would you like to add or change?**:
I noticed that Portmaster create files into many app directories on my computer. I understand that those files are probably required to let portmaster work, but that would be nice to document that and let the users know :) Also, isn't ffmpeg.dll a library used for video/audio encoding? What should be the main purpose about creating such files in so many directories? I'm getting a bit confused about that.

**Why do you and others need this?**:
Because it is actually really confusing that some softwares report that portmaster create some dll in some others app directories without letting us know about that.

![pm-making-its-own-journeyyy](https://user-images.githubusercontent.com/494234/232298409-cc395c17-cdb8-4f89-88ac-e7d78abe912d.png)

Thank you in advance for any guidance about that :)

**Comment by dhaavi** [comment]
Hey @tlartaud, thanks for reporting this.

This seems to be electron _looking_ for the ffmpeg.dll.
I don't why Process Monitor reports it as "CreateFile", maybe it means creating the file descriptor by opening the file.
It even reports in the details `Disposition: Open`

ffmpeg.dll should be bundled though.

Mid-term we are going to get rid of Electron anyway, so I this will eventually solve itself.

**Comment by tlartaud** [comment]
Hello there,

Thank you for your answer.

I think that the process monitor reports that because I renamed ffmpeg.dll before opening the portmaster app. I was just wondering if the app could open without that dll. (no it can't).
I think that the app wasn't able to find the dll in `C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-5` so (I guess), it took a look into the whole environment variables running on. That's why, I guess, the process monitor is reporting "create file" events on such directories: In fact, no such files are created (I double checked), I think the app just checked if the DLL could be find in those diretories (see events "desired access: read").

I am sorry that i thought such files could be created on those directories: it's actually not necessarilly the case.
However, I renamed that file to know if that file was a required file to run the app. It seems to be, because the portmaster app cannot open if that file doesn't exist.

At a first glance, I told myslef, "it's okay, that file is used to generate the graphs as video-encoded format into the ui".... Which is finally not the case because the graph are actually SVGs...

I am sorry if I just opened this issue by paranoia. I am just trying to investigate why my upload bandwitdh is getting, those days, randomly (REALLY) bad, and I decided to investigate my main desktop apps. I am probably doing it wrong. I am not a desktop app developer/debugger. I am just a frontend webdeveloper and designer, so I sincelrely apologize if I am going against your reporting rules, if I am doing it wrong, or if I am simply mistaking.

The fact is: I don't actually understand why such a library (as video encoding), could be used into your software, and I would really be pleased to understand, by curiosity, the purpose of it. I would really like to see any of those related term to be documented into your online documentation. Do you have any information about this?

Best regards.

**Comment by dhaavi** [comment]
Thanks for elaborating. It is always a good idea to check the processes exactly before drawing conclusions. :smirk: 

The library (ffmpeg.dll) is part of Electron (https://www.electronjs.org/), which we have no control over.
We just bundle it, as other solutions back then weren't feasible.

We are planning to switch to using the new Edge Webview instead in the future. Then we can get rid of electron.

If you want to understand more about the library, you'll need to dig into electron - which is a massive project.

**Comment by tlartaud** [comment]
@dhaavi Thank you for the input :) I'll probably dig by curiousty, but this is outside of the scope of my skills :) I'm however glad to know where these file comes from.

Thanks.
