### ISSUE TITLE
Add a description field for each rule

### ISSUE THREAD

**Issue by tlartaud** [safing/portmaster#1178]
**What would you like to add or change?**:
When adding en exception rule for an IP, it would be really usefull to let us add a description about that rule, in order to add notes about why we add that rule, or what is the actual concern. Just a simple text field for each added rule.

**Why do you and others need this?**:
Because it is useful.... Because even the Windows Firewall allows that feature :-)

**Comment by dhaavi** [comment]
You can use a `#` to add a comment to a rule.
