### ISSUE TITLE
Improve the regex for incoming and outgoing rules

### ISSUE THREAD

**Issue by tlartaud** [safing/portmaster#1179]
**What would you like to add or change?**:
It is actually really frustrating to be only allowed to specify the **remote peer** port.
For some specific reasons, users might often want to block the local port instead of the remote.
Regex rules (both incoming and outgoing), actually only us to enter inputs like: **LAN UDP/50000-55000** where **UDP/50000-55000** are actually the remote ports. There are tons of reasons that should make an user to want to **block the local port** instead of the **remote**.
An awesome improvement would be to let us also define the local port as a second parameter (local as second parameter wouldn't be the best, but it would prevent breaking changes).
So, the regex should accept strings such as: **LAN UDP/50000-55000 UDP/42000:43000**, or even **LAN * 22000**

**Why do you and others need this?**:
Because it is useful, and because most of the firewalls actually allow us to define rules based on both local and remotes configurations at the same time :-)

**Comment by dhaavi** [comment]
Hey @tlartaud, thanks for the suggestion!

Portmaster always matches the destination port.
Can you give me a common example where matching the source port is needed? Especially as with Portmaster you would always match the Application instead - more precise and secure, while being more flexible all at the same time.

We always try to do things because they are actually good, not because other do it.

**Comment by tlartaud** [comment]
Hi,

Thank you for your answer.

> Can you give me a common example where matching the source port is needed? Especially as with Portmaster you would always match the Application instead
Sure. I personally use PM installed on a Windows environment where hvsi containers are turned on (device guard and so on...). I also use Vmware, and most of the connections are going threw the profile "other connections" (looks like PM doesn't always match applications), where the remote peer is often random, and the local port often the same, such as 2222, or even 9922.

I don't like to create too generic rules into the "other connections" profile because we never know which kind of connection we should expect there. This would be way more simpler to create rules based on the local source since the port doesn't randomly change there.

I would agree to give more details there about those connections. What would you need, screenshots? debug reports? logs? Do not hesitate to tell me.

"Other connections" profile wouldn't be the only requirement, but it is actually the one that often make feel such a ffeature would be useful.

Regards.
