### ISSUE TITLE
Add view for per apps overriden options

### ISSUE THREAD

**Issue by tlartaud** [safing/portmaster#1180]
**What would you like to add or change?**:
An awesome feature from Pormaster is that we can  override some global settings, per apps. This is very useful.
We can actually override the option **Network scope > Force block internet access** on a per-app basis.

The problem is: once we overrided such option in several apps, activating that option in the global settings become kind of useless, because we have no way to know exactly which app will actually be blocked, because we can't efficiently know which app is set to bypass that option.

I see two ways to prevent that:
- add a third state to each global setting option that can be per-app overridden (button would become red), and that would activate the option, no matter if an app option from an app is set to bypass the global settings.
- add a global view which display all the settings options from apps that actually bypass/override global settings options (so we can easily disable them).

Those two options aren't incompatible.

**Why do you and others need this?**:
Because it is annoying  to go in global settings, to check "Force block internet access" globally, and still have apps to be able to access the internet without quickly knowing which one can.

**Comment by dhaavi** [comment]
Thanks for the great idea!

This is something that will we solve in the future with setting layers, where each layer can either add or override other settings, to put it simply.

This will take a while though. As this will be included in that improvement, I will close this issue as an individual aspect of this planned system.

**Comment by tlartaud** [comment]
@dhaavi 
Awesome! Thank you. I am impatiently waiting for that improvement :)

Regards.
