### ISSUE TITLE
Portmaster Fails to Download Assets During Installation

### ISSUE THREAD

**Issue by Abyssgrowth** [safing/portmaster#1181]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Seemingly the issue was fixed https://github.com/safing/portmaster/issues/519
However i'm having this exact problem right now, never happened before here.
I'm on a brand new windows 10 installation (in virtualbox in case it matters) download the latest portmaster installer, compared the matching checksums, but now can't perceed to install.
Portmaster did create the directory in programdata/safing/portmaster and there are some files there but portmaster isn't active on the system and keeps displaying the same error each time i try to install it.

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Abyssgrowth** [comment]
![Capture](https://user-images.githubusercontent.com/125774114/233276464-6116303d-d211-4e72-8fe8-fe36b3513454.PNG)

**Comment by dhaavi** [comment]
Hey @Abyssgrowth, thanks for reporting.

Was the download otherwise fast or was it very slow? We have reports of slow and failing downloads from regions far away from Europe.

You can try to download the assets manually:
- Download https://updates.safing.io/latest/windows_amd64/start/portmaster-start.exe
- Place it in `C:\ProgramData\Safing\Portmaster`
- Run `portmaster-start.exe --data C:\ProgramData\Safing\Portmaster update`

If that worked, just run the installer again, it will detect that all resources are already downloaded and complete the installation.

**Comment by Abyssgrowth** [comment]
Thanks for helping @dhaavi,

As per your instructions i've replaced portmaster-start.exe with the one downloaded from the url you provided.
Then attempted to run the command in both powershell and cmd but neither worked, could you please clarify how i'm supposed to use the command?
PS: I deleted the safing directory with all it's content and tried to reinstall from scratch after redownloading portmaster from safing.io but the issue remains. Also note that i'm downloading portmaster from within europe (switzerland) this should not be an issue.

**Comment by Abyssgrowth** [comment]
![pw](https://user-images.githubusercontent.com/125774114/233546204-a94bd4e4-9674-4f8e-924a-9319a687c5a2.PNG)


![cmd](https://user-images.githubusercontent.com/125774114/233546208-61b7aa24-f784-4aa1-92d4-8dfe63f22488.PNG)

![fail](https://user-images.githubusercontent.com/125774114/233546213-b32c88d1-bb88-4e0d-b607-5a144963743a.PNG)

Interesting, i had issues uploading these screenshots, then realized i must disable the bigtech filterlist in portmaster, and already turned it back on now )

**Comment by Abyssgrowth** [comment]
Update: Found the problem.

First i tought simplewall might cause issues with portmaster but i did allow networkaccess for portmaster inside of simplewall, and i can now confirm there is no compatibility issues between simplewall and portmaster.
The actual problem was that in the host OS i've enabled the "block bigtech option" in portmaster.
While installing portmaster in virtualbox i checked portmaster and noticed that many connections where blocked, when i disabled the bock bigtech settings, suddenly portmaster installed without successfuly.

The domain which appears to have caused this issue is: apps.identrust.com
Now i'm a bit confused, why did the portmaster developers decide to include this adress to the block-bigtech-setting but at the same time portmaster depends on this adress to be installed, that seems wired?

**Comment by dhaavi** [comment]
I did not find `apps.identrust.com` in any of the lists. It could be that it shortly was part of another list, which we auto-update.

If you open a blocked connection, it will always tell you why it blocked something.
