### ISSUE TITLE
remote control

### ISSUE THREAD

**Issue by MrKleeblatt** [safing/portmaster#1187]
### **What would you like to add or change?**:

I would like to have a **remote control** feature added.

### **Why do you and others need this?**:

Every server owner could monitor their server way better if they knew exactly what connections go in and out. They could even block potential attacks and prevent their server from being part of a bot network.

**Comment by Raphty** [comment]
thanks for the suggestion, there is an FAQ for that https://wiki.safing.io/en/FAQ/RemotePortmaster

we know it is not ideal, and we might have something in the future that fits better.
