### ISSUE TITLE
SPN tab outdated message

### ISSUE THREAD

**Issue by northys** [safing/portmaster#119]
It's August already. Someone should update the `Arriving here in July` message.

Okay, enough of trolling :trollface:  I'm curious what is the current state of SPN. I'm really looking forward to see it working =)

```
Core Version Info

Name: Portmaster
Version: 0.4.18
Commit: tags/v0.4.18-0-gdefd88d3a0bf4932b9152f8549d5ee39d44c4c51-dirty
Build Options: main.go
Build User: user
Build Host: docker
Build Date: 31.07.2020
Build Source: https://github.com/safing/portmaster
```

**Comment by dhaavi** [comment]
😉 It's just around the corner ;)

You can see some of progress here: https://github.com/safing/spn/pull/1

**Comment by dhaavi** [comment]
The message is fixed with [v0.5.0](https://github.com/safing/portmaster/releases/tag/v0.5.0). First access codes will go out next week.

**Comment by northys** [comment]
@dhaavi it would be my honor to be part of the closed pre-alpha =)

**Comment by davegson** [comment]
Hey there @northys, we are *super* thankful for your tireless contributions on here. Your reporting and testing was and remains a crucial part in developing and maturing the Portmaster.

Just to keep you in the loop, it's nothing definite yet, but we are discussing to let you join the other pre-alpha testers. A lot is going on atm, so expect an email on this matter around next week
