### ISSUE TITLE
'redirecting rogue dns query' doesn't keep to global settings rules

### ISSUE THREAD

**Issue by KDAM71** [safing/portmaster#1190]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

I made rules in global settings (::/0) to block all ipv6 traffic. Some is still coming through.

**What did you expect to happen?**:

I expected all ipv6 traffic to be blocked.

**How did you reproduce it?**:

I made the rule, then checked network activity and saw some ipv6 traffic was allowed. I looked at the reason for allowing and it said redirecting rogue dns query.

**Debug Information**:

**Comment by dhaavi** [comment]
Portmaster will still redirect DNS traffic to itself. If that is blocked, your Internet access will not work.

This is working as expected.

Also, these connections are intentionally hidden. I suspect you are in the Developer UI Mode - please don't use that when you don't know how networks works.

**Comment by KDAM71** [comment]
By block ::/0 I expected to block all ipv6 traffic. Some is still getting out. I checked using wireshark. Portmaster should still be able to function using only ipv4. I'm indeed in the developer mode but I haven't changed any developer settings. I know a bit about the workings of networks, mainly ipv4, which is one of the reasons I tried to block all ipv6 traffic.
