### ISSUE TITLE
Compatibility with ESET Internet Security Premium

### ISSUE THREAD

**Issue by CaptainFrosty** [safing/portmaster#1191]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**
With the proper exceptions in ESET basic functionality works. 

**What did not work?**
As I run the ESET firewall in Interactive Mode which ignores Windows Firewall rules, I imagine that introduces issues. I have thought about disabling the firewall or running it minimally (Automatic mode) and porting my rules over to portmaster but I haven't tried that yet. As it stands, I have to let the ESET service's secure resolver bypass portmaster, and I can't use certain features I'd like to like disabling insecure DNS.

**Comment by CaptainFrosty** [comment]
I have found that while setting a network adapter to DoH keeps alot of Windows services and such away from port 53, it doesn't prevent any application from using insecure DNS. Wouldn't it be nice if there were a way for Windows to actually intercept all the DNS requests on its OS natively without having to resort to a DNS proxy or some such.

**Comment by dhaavi** [comment]
Hey @CaptainFrosty, thanks for your report about ESET. I think we may have some info lying around, but we don't have ESET ourselves. Hopefully other ESET users can chime in here.

**Comment by dhaavi** [comment]
You can also try asking around on our Discord for more reach: https://discord.gg/safing

**Comment by dhaavi** [comment]
You can also try asking around on our Discord for more reach: https://discord.gg/safing
