### ISSUE TITLE
Custom filter list not loading

### ISSUE THREAD

**Issue by fractalmoth** [safing/portmaster#1192]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

After inputting the 1hostpro list from their github (I'm fairly certain it's in the right format for Portmaster) into the custom filter list section the system gives the error "Failed to open custom filter list" and "The filename, directory name, or volume label syntax is incorrect"

https://o0.pages.dev/Pro/hosts.txt is the link I am inputting into the custom list entry

**What did you expect to happen?**:

I expected the list to be loaded.

**How did you reproduce it?**:

By inputting the 1hosts(pro) list into the custom filter list entry.

**Debug Information**:

![xB4QvSuKTF](https://user-images.githubusercontent.com/111817309/234834600-61aa2998-f2b2-437d-a1be-6bbcdfc535fe.png)
[2023-04-27-10-17-32.log](https://github.com/safing/portmaster/files/11342353/2023-04-27-10-17-32.log)

**Comment by dhaavi** [comment]
It needs to be a local file.

Docs: [Custom Filter List](https://docs.safing.io/portmaster/settings#filter/customListFile)
