### ISSUE TITLE
Incompatable with Surfshark's new version 4.11.12

### ISSUE THREAD

**Issue by Xcczs** [safing/portmaster#1198]
**What worked?**

By shutting down portmaster the VPN works normally.

**What did not work?**

Trying to use portmaster with Surfshark makes the VPN impossible to connect. It just goes to an infinite loop of errors. (Protocol: OpenVPN of course.)

Paste debug information below if reporting a problem:
https://pastebin.com/r4wr5qJ7

**Comment by Sttavv** [comment]
FIX: Disable all the Privacy Filters from Surfshark, OpenVPN daemon and make sure you set the kill switch to soft not strict. I got it working for some hours. Will update again if I have another problem. Strict worked on the previous version so I don't know if this is Portmaster's fault or Surfshark's.

**Comment by Sttavv** [comment]
The fix doesn't work anymore. I couldn't make it work today. I sent a private ticket through the app.

**Comment by akano12** [comment]
Try
Shutting down portmaster=>connecting to VPN =>enabling portnaster

**Comment by Sttavv** [comment]
> Try
> Shutting down portmaster=>connecting to VPN =>enabling portnaster

Tried it multiple times, it doesn't work.

**Comment by Raphty** [comment]
thanks for the report with more info I can update the wiki page. 

but surf shark is already listed as having issues https://wiki.safing.io/en/Portmaster/App/Compatibility
