### ISSUE TITLE
[Help]Internet not working on Windows 11

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1199]
I was using it on Windows 10 and another windows 11 installation and it worked. Portmaster was working on my new installation for 2 days from install of windows and portmaster and since it is not working

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
https://wiki.safing.io/en/FAQ/FrequentlyAskedQuestions

there is a FAQ for that
