### ISSUE TITLE
Portmaster tries to ping back even when incoming is blocked

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1200]
I use comodo firewall + portmaster
I tried ping all ports from another computer
and comodo shows that portmaster is trying to connect to remote LAN host

Sometimes notifier pings too

![portmaster pings back to hakcer](https://user-images.githubusercontent.com/62152714/235303266-f0233232-d8bf-4628-a04d-64d6afd7c716.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
Pleas Check the FAQ:
https://wiki.safing.io/en/FAQ/FrequentlyAskedQuestions

**Comment by ppacher** [comment]
Also, as always, please provide the debug information!
