### ISSUE TITLE
dns is blocked for "Operating System"

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1201]
![Screenshot 2023-04-25 155905](https://user-images.githubusercontent.com/62152714/235303125-ae3bbc49-3b3e-4970-a771-0121b80d4472.png)

I use NextDNS in portmaster settings

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by KDAM71** [comment]
On my side DNS is handled by System DNS Client, not by Operating System.

**Comment by Raphty** [comment]
it says in the screenshot that the reason is bypass prevention, this is expected behavior, you can have a look in our FAQ regarding potential ways how to fix this issue.
https://wiki.safing.io/en/FAQ/FrequentlyAskedQuestions

**Comment by Rexadev** [comment]
reopen
