### ISSUE TITLE
Block using AS-organization

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1204]
Example 
US DoD Network Information Center , US Navy Network Information Center (NNIC) , US Air Force Systems Networking
https://ipinfo.io/countries/us

US DoD has 108 ASN

**Comment by ppacher** [comment]
As far as I understand your issue (there's not much information in it), that's already possible. Please refer to the docs and report again: [Outgoing Rules](https://docs.safing.io/portmaster/settings#filter/endpoints)

**Comment by Rexadev** [comment]
> As far as I understand your issue (there's not much information in it), that's already possible. Please refer to the docs and report back: [Outgoing Rules](https://docs.safing.io/portmaster/settings#filter/endpoints)

`By AS number: AS123456` is possible not AS organization

**Comment by ppacher** [comment]
Blocking by organization name is more prone to writing mistakes but I guess this is something we could add quickly. All add it to the backlog.

**Comment by Rexadev** [comment]
@Raphty How to use ASN org

**Comment by Raphty** [comment]
you can look this up in the info box in Portmaster. Just click the i next to the setting

![image](https://github.com/safing/portmaster/assets/11504285/0d009aef-e717-417d-9aa3-ef8f0e4a90a6)

**Comment by Raphty** [comment]
just be careful, we already got reports of people saying it did not work and they had a number swaped... 🤣

**Comment by Rexadev** [comment]
@Raphty AS Org not AS Number

**Comment by Rexadev** [comment]
@Raphty AS Org not AS Number

**Comment by Rexadev** [comment]
@Raphty AS Org not AS Number

**Comment by Rexadev** [comment]
@Raphty AS Org not AS Number

**Comment by Rexadev** [comment]
@Raphty AS Org not AS Number

**Comment by Rexadev** [comment]
@Raphty AS Org not AS Number

**Comment by Rexadev** [comment]
@Raphty AS Org not AS Number

**Comment by Rexadev** [comment]
@Raphty AS Org not AS Number

**Comment by abdullahdevrel** [comment]
> Blocking by organization name is more prone to writing mistakes but I guess this is something we could add quickly. All add it to the backlog.

I believe the project uses IPinfo's API service, I would recommend our free database as well. We have a [free country ASN database](https://ipinfo.io/products/free-ip-database) that provides full accuracy and daily updates and is licensed under CC-BY-SA 4.0 (commercially permissive and distributable through attribution).

In this case, you can use our ASN organization naming structure. For ASN, we use the `as_domain` column as the unique identifier. 

Details here: https://community.ipinfo.io/t/how-the-domain-field-uniquely-identifies-organizations-in-the-asn-and-company-database/401

Essentially, the `as_domain` field uniquely identifies the AS organization regardless of where it operates from. It could have subsidiaries and operate under different names across different countries. But the `as_domain` name is unique it will cover the AS organization and it's multiple ASNs regardless of their name.

Let me know what you think.
