### ISSUE TITLE
Toggle Option for incoming and outgoing rules

### ISSUE THREAD

**Issue by Abyssgrowth** [safing/portmaster#1207]
![0](https://user-images.githubusercontent.com/125774114/236577793-0a1dca7c-f09c-4ead-a14f-0c95e29e36ab.PNG)

An option to temporarily turn off the user defined incoming filter list would be welcome, i've a few domains on my blocklist and from time to time see myself going to portmasters settings to temporarily allow some domains because sometimes that limites web-functionality.

**Comment by KDAM71** [comment]
I'd like an option to instantly delete a rule too.

**Comment by dhaavi** [comment]
Hey @Abyssgrowth, you can simply add a new "Allow *" rule and move it to the top to allow everything temporarily, and then remove it again.

@KDAM71 - You can delete a single rule by selecting the checkbox and then select delete from the actions menu.

**Comment by KDAM71** [comment]
@dhaavi  The rules list for my browser is quite long by now. I have to scrol al the way to the bottom to get to the actions menu. Sometimes the checked rules are not deleted. This is why I'd like the option to delete a rule instantly.

**Comment by Raphty** [comment]
interesting use case. we know that the prompting feature comes with a couple of drawbacks which will need some fixing in the future. 

Thanks for the info.

**Comment by Raphty** [comment]
We have some ideas for the rule section and we will take some more time thinking this through.
Thank you all for the feedback we will take that into consideration when we touch the rules in the future.
