### ISSUE TITLE
Connection refused when accessing my.jdownloader.com with portmaster running

### ISSUE THREAD

**Issue by BlackJoker90** [safing/portmaster#1210]
**What did not work?**
I am experiencing an issue with portmaster where I receive a "connection refused" message when trying to access my.jdownloader.com. Through this site, I have access to the jdownloader application on my NAS. According to the Network Monitor, the connection is green and not being blocked, so I am unsure of the root cause. When I close portmaster, everything works fine without any issues.

**Additional information**
- Network Monitor shows the connection as green and not being blocked.
- No issues accessing my.jdownloader.com when portmaster is closed.
- Firefoex console shows CORS request failed

**Comment by dhaavi** [comment]
Do you have any blocked connections for this app/browser when trying to connect?

I checked my.jdownloader.com and it returns a public IP, so I am not sure how this connects to the local NAS. Portmaster would block DNS queries whose answers cross boundaries. You might want to disable [Enforce Global/Private Split-View](https://docs.safing.io/portmaster/settings#filter/removeOutOfScopeDNS) and try again.

**Comment by BlackJoker90** [comment]
I currently have no blocked connections for this browser address. Could you please guide me to the Enforce Global setting, as I am unable to locate it?
