### ISSUE TITLE
DuckDuckGo periodically unreachable

### ISSUE THREAD

**Issue by hyuri** [safing/portmaster#1211]
**What happened**:
DuckDuckGo is unreachable from time to time.

**What did you expect to happen?**:
Either reachable or unreachable at all times.

**How did you reproduce it?**:
Using DuckDuckGo often.

**System Information**:
Pop!_OS 22.04

**Comment by dhaavi** [comment]
Are you using the SPN?

It probably is DNS anyway. Please check your DNS servers - possibly try different ones.

**Comment by hyuri** [comment]
> Are you using the SPN?

No.

**Comment by Raphty** [comment]
did you check the dns settings?

**Comment by hyuri** [comment]
I have no idea what to check. What should I look for?

**Comment by Raphty** [comment]
![image](https://github.com/safing/portmaster/assets/11504285/c5967d35-4470-4f65-871a-7a117168c21d)
