### ISSUE TITLE
Why are discussions disabled in the GitHub.

### ISSUE THREAD

**Issue by Bennett-Fourr** [safing/portmaster#1212]
**What would you like to add or change?**:
Discussions being enabled in the GitHub repo 

**Why do you and others need this?**:
It can be helpful for asking questions that do not need the Developer's attention.

**Comment by Raphty** [comment]
We have been thinking about enabling discussions multiple times now

I guess the main reason for not going that rout is that we can't be everywhere, and discussions are already happening on our [discord](https://discord.gg/safing) 

pls join us there!

**Comment by Bennett-Fourr** [comment]
ok
