### ISSUE TITLE
stub 

### ISSUE THREAD

**Issue by gtech2019** [safing/portmaster#1213]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

tried to update portmaster and it failed build this is the error it produced  Validating source files with sha256sums...
    portmaster-start ... FAILED
    portmaster.desktop ... Passed
    portmaster_notifier.desktop ... Passed
    portmaster_logo.png ... Passed
    portmaster.service ... Passed
==> ERROR: One or more files did not pass the validity check!
Failed to build portmaster-stub-bin

**Comment by ppacher** [comment]
Thanks for the report. The AUR package is out-of-date. I'll update it next week :)
