### ISSUE TITLE
Add the option to migrate an application only rule to the global settings

### ISSUE THREAD

**Issue by redgryphon** [safing/portmaster#1214]
**What would you like to add or change?**:
Right now a rule can be added by simply clicking "allow" on a popup notification. There is no way to make the rule actually be applied to all the applications at the same time, especially if we're talking about domains. A simple way to do it would be allowing the possibility to drag the rule from the application zone to the global zone shown underneath it.

**Why do you and others need this?**:
It would help in the first phases after having installed Portmaster.

Imagine setting the default rule as block. While using the PC you open an application and Portmaster will start asking if you want to allow some domains contacted by the application. You give the application your consent and it starts working correctly. Sometimes other applications want to contact the same domain and they will start showing the same notification again. This could be avoided with the feature proposed.

**Comment by ppacher** [comment]
Hi @redgryphon, thanks for the suggestion. I really like it! It shouldn't be to hard to implement that as well. We'll add it to the backlog :)
