### ISSUE TITLE
Google One VPN

### ISSUE THREAD

**Issue by aardvark82** [safing/portmaster#1217]
**Pre-Submit Checklist**:
- Cannot toggle Google One VPN with portmaster enabled

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

**What did not work?**

**Debug Information**:

**Comment by dhaavi** [comment]
I am very confused.

Why on earth would you want to use both Google VPN and Portmaster?

Other than that, you haven't provided any detailed information, so there is nothing we can do, else than refer you to the troubleshooting guides.

**Comment by aardvark82** [comment]
Hi Daniel - 

I predominantly use VPN to route my traffic through a 3rd party and prevent my ISP - or any public Wi-fi etc... from being able to analyze and interpret my traffic habits etc....

I use Portmaster as an advanced Firewall and traffic shaping/monitoring tool.

I initially created this post as google one VPN is fairly common, and I didn't see it listed on the VPN compatibility / incompatibility list.

I have since tried on 3 different configurations - PC, Mac and networks - without success.

- Config 1. Starlink internet (US). Windows 10. iMac 2020 (bootcamp). 64gb ram, clean Windows install (no other firewall software)
- Install Google One  VPN One - sign in - I can enable/ disable it at will.
- Install Portmaster. Restart. Portmaster is running. Google One VPN is disabled.
      - Try to enable Google One VPN. Does not connect (stays on VPN is connecting...) status
- Uninstall portmaster
- Try to connect with google One VPN. Success.

Config 2. Same as iMac 2020. Connection via 5G hotspot. Same results. 

Config 3. PC, Intel i5 8400, 32Gb ram, Windows 10 latest. Clean install.
- Install port master. Reboot. Portmaster active
- Install Google One VPN. Enable. Stuck on "VPN is Connecting..."

The purpose of this post is to gather signals on whether or not any config is known to work, before we try to diagnose my systems (I can pull logs etc....) but first - - if no one can use both combined - I recommend to add it to the incompatibility/VPN list.

**Comment by aardvark82** [comment]
Ok now this gets interesting. -
- uninstall is not necessary 
- if I shutdown portmaster, Google One VPN connects instantly. 
- - When I re-enable portmaster ("Start Core Service") , Google One VPN STAYS CONNNECTED. I can verify as my location is resolving to a google IP. 
- If I toggle Google One VPN off, then it still gets stuck in "Connecting..." (Portmaster is running at that time) BUT I AM ACTUALLY CONNECTED.

So this seems to be an issue with the Google One VPN client UI, reporting the status as "Connecting..." Even though the service is connected and alive.  I will file a bug with google one VPN client.

![image](https://github.com/safing/portmaster/assets/32086262/3654df68-5468-4166-8337-1e403d63a423)
