### ISSUE TITLE
Add ability to Block Specific Top Level Domains TLDs

### ISSUE THREAD

**Issue by DraconicNEO** [safing/portmaster#1219]
**What would you like to add or change?**:

I think users should have the ability to block specific Top Level Domains (TLDs) in addition to the feature Portmaster has to block unofficial TLDs. Obviously since blocking official TLDs can remove access to legitimate sites this should be an Advanced Feature in the Advanced Interface since this is more for advanced users.

**Why do you and others need this?**:

There are a lot of TLDs commonly used for phishing and scams and the ability to block entire TLDs since it may be able to block ones not yet filtered by portmaster might be useful to some advanced users. Also since Google recently made availible .zip TLDs as an official TLD scammers may be able to use these in ways that make detection harder (See [this video](https://www.youtube.com/watch?v=GCVJsz7EODA) for more information on that) which is all the more reason to allowing advanced users to block specific TLDs.

**Comment by Raphty** [comment]
you can block whatever you want, just add it to the global Outgoing Rules.

`block: *.com`

can work

**Comment by DraconicNEO** [comment]
Ah I see, I wasn't fully aware you could do that but it makes sense.
