### ISSUE TITLE
Portmaster persists in launching on startup despite being disabled.

### ISSUE THREAD

**Issue by Sttavv** [safing/portmaster#1225]
**What happened**:

I am experiencing an ongoing issue with Portmaster launching on startup despite being disabled. Even after disabling the Portmaster core service and checking for any related scheduled tasks on the Task Scheduler, the problem persists. Furthermore, this unwanted launch behavior is interfering with the auto-connect feature of my VPN.

**What did you expect to happen?**:

When I disable a program from starting on boot, my expectation is that it should not launch on startup.

**How did you reproduce it?**:

If you have disabled Portmaster on startup, restart your PC, and the Portmaster service is still running despite being disabled.

**Debug Information**:
https://pastebin.com/pxQDv19v

**Comment by NSurtsev** [comment]
Lol.
Did they still haven't added this option?
It was one of issues I had back after launch in 2022 which cause me to uninstall the app.
As I see, devs do not care much of their product.

**Comment by Raphty** [comment]
it is not a supported feature and would not fit with the intended use of Portmaster. If you don't want it its not something we are thinking of supporting any time soon.

**Comment by Sttavv** [comment]
It seems like users really want this specific feature, and it's a widely expected feature that is present in almost all apps these days. Are you just too lazy to add it or do you simply not care about the user experience?

**Comment by Sttavv** [comment]
> it is not a supported feature and would not fit with the intended use of Portmaster. If you don't want it its not something we are thinking of supporting any time soon.

t seems like users really want this specific feature, and it's a widely expected feature that is present in most apps these days. Are you just too lazy to add it or do you simply not care about the user experience?
