### ISSUE TITLE
Tray notification not coming back

### ISSUE THREAD

**Issue by AxeldeWater** [safing/portmaster#1226]
**What would you like to add or change?**: Whenever I shut down Portmaster, the tray notification disappears (fully reasonable). But when I turn Portmaster on again, the tray notification won't come back. I would have to restart my whole pc just to get the tray notification back. My suggestion is making it such that when Portmaster is turned back on, the tray notification comes back too.

**Why do you and others need this?**: The tray notification is a useful quick way to access Portmaster and see if it's up and running.

**Comment by AxeldeWater** [comment]
I'm on Windows 11 I should probably add

**Comment by Raphty** [comment]
this should be the case already. 

If I may ask why (for what) are you shutting down Portmaster?

**Comment by AxeldeWater** [comment]
Well, it is not the case clearly...

I close it because of an issue that I've reported here already, but got dismissed because of not enough input or something. It's when I play Valorant: keeping Portmaster turned on somehow fucks with the voice communication in-game. So before playing Valorant I turn Portmaster off, and after im done playing I turn it back on.

**Comment by Raphty** [comment]
@dhaavi should not the Portmaster check and start the notifier during startup? I know we fixed this for the Portmaster reboot some time in the past.

**Comment by AxeldeWater** [comment]
It works for reboot/restart as I said in the text, that's not the problem. But within a single session when you turn Portmaster off and back on the tray notification won't come back.

**Comment by Raphty** [comment]
Jut had a talk with daniel, there is another issue open where they already figured out that this might be the notifier not properly shutting down, and Portmaster thinking on start that it is still running.

**Comment by AxeldeWater** [comment]
Aha...

**Comment by Raphty** [comment]
thanks for reporting, we might be looking into this, in the future
