### ISSUE TITLE
Grey-out all network toggled when Block Connection at Top is enabled

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1228]
Also greyout incoming internet connections options when internet access is already blocked

**What would you like to add or change?**:
Title

**Why do you and others need this?**:
Easier for noobs to understand.
For Pros easy to configure and clean to look at

**Comment by Rexadev** [comment]
@ppacher done

**Comment by Raphty** [comment]
thanks for the suggestion we will take this in consideration when we go into updating the network monitor in the future.

**Comment by Rexadev** [comment]
reopen
