### ISSUE TITLE
linux immutable, root read only

### ISSUE THREAD

**Issue by keybasegit** [safing/portmaster#1233]
I am running Fedora Silverblue. Default root is read only. Is I install safing to distrobox it get installed into opt, whoever after reboot. I can' t access it.

Immutable linux and read only root is protection. DNS can work as an app on top of root without admin permission at least in android

**Comment by vlabo** [comment]
Unfortunately we don't have official way of installing portmaster on immutable distros.
It's something, we have to investigate and see what will be the best way.

Portmaster is not only a DNS client, it provides a lot more it's not that simple.
On android the only way to run non system dns client is with the VPN service, which is not a solution in our case.

Thank you for sharing your findings.
