### ISSUE TITLE
Filterlist Question

### ISSUE THREAD

**Issue by Abyssgrowth** [safing/portmaster#1235]
**What would you like to add or change?**:
On windows systems, if i want to block bigtech via the filterlist settings should i do this:
A; by blocking bigtech in the portmasters main settings
B: by blocking bigtech in the system-dns-server app
C by blocking bigtech in my webbrowser app

Asking this because when blocking bigtech in portmasters main settings i still able to establish a connection to google in my browsers which gave me the impression i should block it in the browser settings instead, or maybe both. 

**Why do you and others need this?**:

**Comment by Abyssgrowth** [comment]
When i attempt to visit https://linux.org the connection fails with the enabled bigtech filterlist, had to unblock google then the site loaded.
https://pagexray.fouanalytics.com/q/linux.org?f=

**Comment by Raphty** [comment]
if it is enabled on the system level and your browser does not have an exception then it should block everything, but you can see the reason why a connection is treated the way it is in the network monitor.

![image](https://github.com/safing/portmaster/assets/11504285/99fda80f-e23b-4069-b6c6-38ee2669f46d)
