### ISSUE TITLE
Failed to download assets

### ISSUE THREAD

**Issue by Morasithil** [safing/portmaster#1237]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
There are already multiple issues regarding the same problem i encountered.
The developers of portmaster said the issue was resolved, if this was true how come i am in this situation right now?
![pormaster-install-fail](https://github.com/safing/portmaster/assets/136394696/1dc2a6d6-f8f9-49eb-9566-b5f5c856ff82)
![winver](https://github.com/safing/portmaster/assets/136394696/a927c10e-79da-4361-9c29-76a2b1cd96a1)

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Morasithil** [comment]
Why is there no offline installer for the portmaster?

**Comment by Raphty** [comment]
thanks for reporting, but as you mentioned this is a duplicate
