### ISSUE TITLE
[Bug][Website]Google Captch not working on instagram.com/challenge/ when portmaster is enabled but nothing is blocked

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1238]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
pleas provide additional information
