### ISSUE TITLE
Unable to use MikroTik's Winbox (Layer2) even when everything is allowed

### ISSUE THREAD

**Issue by 0blu** [safing/portmaster#1240]
**What happened**:
I am using WinBox in MAC-Address mode to connect to my local router.
When using Portmaster this connection is not allowed.

I turned of all checkboxes in the app specific configuration and it is still blocked.

![image](https://github.com/safing/portmaster/assets/7039020/1e636209-4685-4651-9e21-95aa7354ba24)
![image](https://github.com/safing/portmaster/assets/7039020/7fc9265e-b50c-4e8f-8c28-70f99feb271a)

![image](https://github.com/safing/portmaster/assets/7039020/a3ee4102-8552-4748-ad57-294535641df7)

Even if I am allowing the "invalid" IP `0.0.0.0` and `255.255.255.255` the app cannot connect.
Could it be that it is actually just allowing the IP:Port combination (which is changed every connection attempt)?
Where can I even find the allowed IPs?

Is this happening to all lan(layer2)-broadcast-traffic?

**Debug Information**:
I am not sure where to find the debug information.
Winbox is using a broadcast IP and layer 2 access.

**Comment by 0blu** [comment]
This might be a compatibility issue and I used the wrong template.

**Comment by Raphty** [comment]
so can I close the issue?

**Comment by 0blu** [comment]
Just change the tag from "bug" to "compatiably".
Where can I see allowed IPs?
How can I allow all invalid IPs?

**Comment by Saduff** [comment]
Having the same issue. It's not possible to allow it in Portmaster, even an `Allow *` incoming rule will not allow it. There is some hardcoded rule that drops it due to "Invalid IP".

For iptables, the following rules are required for neighbor discovery and MAC-Winbox:
```
-A INPUT -d 255.255.255.255/32 -p udp --dport 5678
-A INPUT -s 0.0.0.0/32 -d 255.255.255.255/32 -p udp --sport 20561
```

I was able to add the first rule into Portmaster as `LAN UDP/5678`, which makes neighbor discovery work in Winbox, but the MAC-Winbox connection needs the second rule.

**Comment by dhaavi** [comment]
> There is some hardcoded rule that drops it due to "Invalid IP".

Correct.
I've never seen an application using just L2 to communicate and fill L3 with "dummy" data.
Yes, DHCP does that, but this is specifically to bootstrap L3.

I'll have to think about how to handle that.
Maybe I can include 0.0.0.0 and 255.255.255.255 in the "LAN" scope.

**Comment by dhaavi** [comment]
This should now work as of Portmaster v1.3.3 (currently in Beta).

**Comment by Saduff** [comment]
It's working in v1.3.3 when adding an `Allow 0.0.0.0` rule. Thanks for the quick fix!
