### ISSUE TITLE
Add hover description for all menu buttons on the left

### ISSUE THREAD

**Issue by 0blu** [safing/portmaster#1241]
**What would you like to add or change?**:
To make the UI more understandable all menu button the left should have a hover description.
Currently only a few items in the center have a description like (`Apps and profiles`, `SPN`, `Global Settings`, `Get Support`)

Especially the power button is extremely vague.
Does it restart my PC or just the app?
![image](https://github.com/safing/portmaster/assets/7039020/3d038e68-ef3a-40ae-917d-4103665a331f)

**Comment by Raphty** [comment]
just the app - so you would add Restart Portmsater?

**Comment by 0blu** [comment]
Yes. Adding a more verbose button text would help.
But adding a hover over description over the shutdown icon would also be nice.

**Comment by dhaavi** [comment]
There are hover descriptions:

![image](https://github.com/safing/portmaster/assets/18184155/037840c3-adc2-4752-9d88-05b491f047e9)

**Comment by 0blu** [comment]
I currently don't have the application installed, but can you show me the hover description of the shutdown or settings button?

**Comment by dhaavi** [comment]
![image](https://github.com/safing/portmaster/assets/18184155/3c6615ce-a3d4-4943-87d4-e315c5612aee)

I just saw that the tooltip of the tools and power menu are broken. They should be fixed in the next version.
