### ISSUE TITLE
Verify digital signatures and block modified executables or those without signature

### ISSUE THREAD

**Issue by 0blu** [safing/portmaster#1242]
**What would you like to add or change?**:
It would be nice to be able to default block application that dont have a valid signature.
The same case for applications that are not signed at all.

It can be easily tested by taking `putty.exe` for example and change one byte in the binary code.
![image](https://github.com/safing/portmaster/assets/7039020/523b966e-6e05-4953-9f7f-3732722255c2)

**Comment by dhaavi** [comment]
We have thought about signature verification a couple times already and it is an option we have for the future, but it is not yet on the roadmap.
