### ISSUE TITLE
Add option to hide processes from Network Activity tab

### ISSUE THREAD

**Issue by 0blu** [safing/portmaster#1243]
**What would you like to add or change?**:
It would be nice to hide certain processes by default in the Network Activity tab.
I might not be interested in what a certain application connects to.

**Why do you and others need this?**:
Clears up the tab
and when using the "group by" feature it might take less time to generate all those graphs.

**Comment by Raphty** [comment]
nice idea! thanks

**Comment by Jason-K** [comment]
PLEASE!!! Logitech Options+ is KILLING me with its spamming out activity.
