### ISSUE TITLE
Portmaster just freezes on Debian 12 "Bookworm"

### ISSUE THREAD

**Issue by hopelessdecoy** [safing/portmaster#1249]
First needed to install "iptables" via apt, afterword portmaster just freezes on opening, cannot click the quick setup button just needs shut down then. No warnings, no errors..... help?

**Comment by Raphty** [comment]
thanks for the report, we see that more people are complaining about issues on debian.

If you want to help that would be great, we can't and will not divert resources into this at the moment.

**Comment by hopelessdecoy** [comment]
> thanks for the report, we see that more people are complaining about issues on debian.
> 
> If you want to help that would be great, we can't and will not divert resources into this at the moment.

Ouch ok.

**Comment by dhaavi** [comment]
Debian 12 does not ship with the "iptables to nftables" translation as they used to. Portmaster still uses iptables for one part of the integration with the network stack.

If you install the "xtables-nft" package, this should do the trick. If anyone comes across this issue and this works, please report back!

We are working on native support for nftables, but as this is a very critical part of the software, it will take some time to build and thoroughly test.

**Comment by thealphadev01** [comment]
> If you install the "iptables" package, this should do the trick. If anyone comes across this issue and this works, please report back!

I am on Debian Trixie and can confirm that portmaster is working after installing iptables.
