### ISSUE TITLE
✅ IVPN compatibility

### ISSUE THREAD

**Issue by didntchooseaname** [safing/portmaster#1250]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

Microsoft Windows 11 Pro 10.0.22621 N/A Build 22621 (latest release at the date).

ALL worked flawlessly, auto start with the ivpn's firewall turned on and a custom local dns set.

**What did not work?**

Nothing.

**Debug Information**:

**Comment by Raphty** [comment]
thanks for the report! on what system have are you on? windows 10 or 11 or Linux?

**Comment by didntchooseaname** [comment]
> thanks for the report! on what system have are you on? windows 10 or 11 or Linux?

Hello, my bad, i updated my comment.

**Comment by Raphty** [comment]
Updated: https://wiki.safing.io/en/Portmaster/App/Compatibility
