### ISSUE TITLE
wireless monitor connection fails (roku)

### ISSUE THREAD

**Issue by 86ed** [safing/portmaster#1252]
### What happened?
windows&#43;P, shows hisense roku tv, cannot connect.  connections allowed ?by default to 5353 and related ports

### What did you expect to happen?
watch tv from laptop

### How did you reproduce it?
Win&#43;P
wait scan
click hisense
fail

### Additional information
Windows 10, thinkpad

**Debug-Info**: https://support.safing.io/privatebin/?3f254eb743a94f09#6m1cyTz1uKsf2LyjtHSopuQL1uUBXmL2koXPKKSkF4QL

**Comment by Raphty** [comment]
when you say you allowed the connection, did you make sure you allow them for incoming connections?

https://wiki.safing.io/en/FAQ/AllowIncomingConnections

**Comment by Raphty** [comment]
Can you send a Screenshot of settings how you allowed the Incoming connections
