### ISSUE TITLE
per app setting being ignored

### ISSUE THREAD

**Issue by Chaython** [safing/portmaster#1257]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Rules were ignored

**What did you expect to happen?**:
Rules were complied with

**How did you reproduce it?**:
All the battlefield games [ I tested 1 and 4], require incoming connections to join a multiplayer server.
Blocking Incoming connections therefore you will not be able to join a server...
Setting per app to allow incoming connections, is ignored.
![image](https://github.com/safing/portmaster/assets/6486343/be861956-faf0-428a-96ee-95e4e7f40728)
I've tried in stable and in beta
Debug was too long for github

**Debug Information**:
https://pastebin.com/raw/vjd1huzf

**Comment by Raphty** [comment]
some games handle such connections via a different process. did you check associated processes?

**Comment by Chaython** [comment]
> some games handle such connections via a different process. did you check associated processes?

Not all applications are appearing in the list. But it actually seems to be working now. Many issues seemed to have been fixed by disabling "block domain aliases" "block subdomains"
