### ISSUE TITLE
README.md file fix - Getting Started link

### ISSUE THREAD

**Issue by hl2guide** [safing/portmaster#1258]
**What would you like to add or change?**:

Please fix the "Getting Started" link in **README.md**. It currently directs to Page Not Found.

From:
https://wiki.safing.io/en/Portmaster/App/GettingStarted
To:
https://wiki.safing.io/en/Portmaster/App

**Why do you and others need this?**:

The getting started guide is useful.

**Comment by dhaavi** [comment]
Thanks! Fix will be out soon.
