### ISSUE TITLE
Improvement to Secure DNS feature

### ISSUE THREAD

**Issue by hl2guide** [safing/portmaster#1259]
**What would you like to add or change?**:

Please change it so that relevant IPs are whitelisted for each secure DNS provider.

e.g. Choosing Cloudflare currently incorrectly blocks `1.1.1.1` and `1.0.0.1`. 

**Why do you and others need this?**:
So that the base page loads for each provider.

**Comment by dhaavi** [comment]
This would allow bypassing Portmaster's protections.

If you really want this, disable [Block Bypassing](https://docs.safing.io/portmaster/settings#filter/preventBypassing).
