### ISSUE TITLE
1.3 network: failed to check for enabled features: database entry not found

### ISSUE THREAD

**Issue by mattkeenan** [safing/portmaster#1262]
**What happened**:
When running 1.3 on Linux (Ubuntu 22.04) the following message is spammed in /var/log/syslog:
Jul 24 15:33:09 xxxxx portmaster-start[788]: #033[33m230724 15:33:09.711 connection:452 ▶ WARN 491 [2x]#033[0m network: failed to check for enabled features: database entry not found

**What did you expect to happen?**:
No error message

**How did you reproduce it?**:
Install, then run but don't enable SPN.

**Debug Information**:
As above syslog message

**Comment by dhaavi** [comment]
Thanks! Will be fixed in the next release (v1.3.1+).

**Comment by dhaavi** [comment]
Fixed in https://github.com/safing/portmaster/releases/tag/v1.3.1.
