### ISSUE TITLE
you're hanging on to cache too long

### ISSUE THREAD

**Issue by working-name** [safing/portmaster#1263]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

PM is hanging on to cache too long or is resolving some nonsense.

**What did you expect to happen?**:
Resolve the domain the same way curl does in wsl2 which is pointed at 1.1.1.1 directly.

**How did you reproduce it?**:
Ignore PM in the system tray because it's a bug ridden useless ugly monster on windows. Problem is... it still responds to DNS queries even though everything is set to allow.

So I don't know what to tell you here. Try it out yourself.

**Debug Information**:

**Comment by Raphty** [comment]
I guess you understand that this bug report has little substance and therefore doesn't help in regards to fixing a potential issue?

I will forward your concern that the cache is held too long, but humor me, did you enable the setting that Portmaster is resolving from cache? because there is a popup asking you to enable it if your queries take too long.

**Comment by working-name** [comment]
Yes, I'm aware it's low effort, but since most reports are met with silence and censorship, why bother?

I'll humor you: the setting is off because it's a cheap fix to the problem that PM misattributes connections to the wrong exe. I'm waiting for the real fix. Because if I turn on PM it'll block me out of my own remote control tools.

Maybe if you guys also go back on the poor UI decisions where you make it insanely hard to manage connection prompts, then the software might be worth keeping around. What was wrong with having an always-open sidebar with connection prompts? This one you scroll down through the list and it auto-closes on you. Ridiculously frustrating.

**Comment by Raphty** [comment]
@dhaavi if you find something here, pleas re-open
