### ISSUE TITLE
MongoDB connection refused

### ISSUE THREAD

**Issue by elendil7** [safing/portmaster#1278]
## What worked?
Failed successfully 😅 

## What did not work?
Connecting to MongoDB (via Mongoose library) **fails** when Portmaster is **enabled**.
Connecting to MongoDB (via Mongoose library) **works** when Portmaster is **disabled**.

## Debug Information:
`Error: querySrv ECONNREFUSED _mongodb._tcp.cluster0.qiwebok.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:218:17) {   
  errno: undefined,
  code: 'ECONNREFUSED',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.cluster0.qiwebok.mongodb.net'
}`

## Extra special info
- Connection from node.js shows up as "allowed" on portmaster UI, despite the mongodb connection (part of this process) being blocked.
- When disabling the "Privacy Filter Module" in settings, the connection no longer fails - but instead times out (timeout).

## Gallery
![image](https://github.com/safing/portmaster/assets/80429382/91a56380-538d-4e28-b3b0-16dd835ba7f5)

**Comment by dhaavi** [comment]
Hey @elendil7, thanks for reporting this.

I am not sure what is going on here.
The screenshot shows a DNS requests, not an actual connection.

Can you find the blocked connection in Portmaster?

I tried connecting manually with netcat, which worked.

**Comment by elendil7** [comment]
There is no blocked connection listed for mongodb / nodejs. But its being still being blocked.
