### ISSUE TITLE
Simplify change of Default Network Action for specific Apps

### ISSUE THREAD

**Issue by c-s-n** [safing/portmaster#1281]
**What would you like to add or change?**:

The "Default Network Action" for a specific App should be easier changeable, to quickly configure allowance or blocking.

Notification flyout "..."-menu:
![Notification](https://github.com/safing/portmaster/assets/615657/967e3ffe-ef6b-495f-bf76-98a1e8a43f5c)
"Change Default" has a current behavior of linking to the corresponding App's main page (same as the "App Settings" entry, whyever). I suggest to **replace that button with "Change Default to Allow" and "Change Default to Block" buttons** with a direct effect.
For clarity, I furthermore suggest to rename "Allow All" and "Block All" to "Allow All Listed" and "Block All Listed" respectively, to not give the false impression this button applies to all - including future - connections.

App main page header:
![Block Connections](https://github.com/safing/portmaster/assets/615657/0415723c-99f1-4f7f-8c56-680e0e786b6b)
The "Prompting" link next to "Block Connections" currently takes you to the App Specific Settings. I suggest to instead **directly show a dropdown that offers "Allow" or "Block" choices** and directly performs that change.

**Why do you and others need this?**:

When the "Default Network Action" in the "Global Settings" is set to "Prompt", there are a lot of notifications shown, but often I just want to allow or block that application as a whole, i.e. not specific recently connected-to IPs or domains.
Above suggestions would significantly reduce the number of necessary clicks in the UI. Also would it make the notification flyout "..."-menu actions clearer and slightly more firewall popup-like (where I think people are used to).

**Comment by Raphty** [comment]
thanks for the ideas, we are not working on the prompting right now, but we might be tackling it in later this year. with 1.4 we introduce a dashboard which will give us more options to get buttons in and so on.

**Comment by c-s-n** [comment]
Then I would even see the simplistic Notification flyout to vanish completely in favor of a dashboard widget or the like. But I hope my points regarding the menu are clear, so that you could ideally consider them when building a corresponding widget.

**Comment by Raphty** [comment]
yes, they are and thank you! we do have some ideas as well. 😃
