### ISSUE TITLE
ASN rules not effective

### ISSUE THREAD

**Issue by Terrance** [safing/portmaster#1284]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

The _Outgoing Rules_ help includes, among other examples:

> * By AS number: `AS123456`

I've added an allow by ASN rule, but requests to most(?) IPs in that ASN remain blocked/prompting.

**What did you expect to happen?**:

Requests to match the ASN rule and be allowed.

**How did you reproduce it?**:

Testing with Telegram Desktop and the allow rule `AS62041 TCP/443`:

![image](https://github.com/safing/portmaster/assets/4025899/8454d77b-1284-492b-9c8d-b5026c8455a8)

![image](https://github.com/safing/portmaster/assets/4025899/a5471c50-c6ee-4d20-a64d-284383613c96)

I've also tried omitting the port portion of the rule and specifying ASN alone, with no change.

Both Portmaster and external sources confirm the IP pictured above (149.154.167.91) is in the ASN -- the request shows it to be 62041, as defined in the rule.

Note that a different IP in the same ASN (91.108.56.186) was correctly allowed by the rule.

**Debug Information**:

Too long to paste...  [portmaster-debug.txt](https://github.com/safing/portmaster/files/12330471/portmaster-debug.txt)

**Comment by dhaavi** [comment]
Hey @Terrance, thanks for the report.

I have noticed that the rules are for AS620**14**, and the connection is going to AS620**41**.

Please update the rules and check again.

**Comment by Terrance** [comment]
Well that's irritating... yes, it's a typo in the rule.  😅  Not sure how the other IP was getting through then, perhaps it was a long-lasting connection that got through on a wildcard rule whilst I was testing other options.
