### ISSUE TITLE
Torrenting with Ktorrent results in eventual crash of Portmaster

### ISSUE THREAD

**Issue by S7venLights** [safing/portmaster#1292]
**What happened**:
I switched to the torrent client KTorrent
Over time Torrenting builds up too many connection logs faster than Portmaster clears logs. 
Eventually after some hours Portmaster seemingly grinds to a halt and cuts all internet access.
Trying to open Portmaster UI is slow to impossible.
Remedy: disconnect internet, Kill Portmaster processes, Re-launch in CLI
How to avoid: Disconnect from internet, close Ktorrent, Restart Portmaster before it crashes
or exit Ktorrent for long enough, that logs clear.

As an example of how many requests Ktorrent is making, I would use up my 300 000 monthly free adblocked NextDNS lookups in a few days.

**What did you expect to happen?**:
Maybe best solution is to have a cap/limit on how many network logs can be kept per app or in total.
I am also aware that it's strange that KTorrent would make this many requests, but I've invested a lot of time into KTorrents library features so I don't want to switch torrent clients. Perhaps I could open an issue with KTorrent.

**Debug Information**: Don't have debug info for this issue right now
I'm on Fedora Kinoite, Portmaster version 1.3.6 see my debug info in #1291

**Comment by Raphty** [comment]
When network history is not enables the last 10minutes of traffic are held in memory. so one of the limitation is your RAM and the speed there. how much Ram does the machine have?

**Comment by S7venLights** [comment]
I have 16GB but it's possible my VM was reserving a bunch of the RAM.
Still, Ktorrent is making an exceptional number of requests, so I think at least an option to limit logs per app would be a needed/useful feature

**Comment by Terkyz** [comment]
This is strange, right now I am using KTorrent to download several files and it doesn't really make that many requests, how many files are you downloading? Because the more downloads you have pending the more requests KTorrent will make. Also, have you tried another torrent client like QBittorrent? Has the same thing happened?

And one last question, is it really necessary to have NextDNS when you already have Portmaster? I mean, Portmaster filters already do the task of NextDNS, you shouldn't worry about the number of requests for that.

**Comment by S7venLights** [comment]
> This is strange, right now I am using KTorrent to download several files and it doesn't really make that many requests, how many files are you downloading? Because the more downloads you have pending the more requests KTorrent will make. Also, have you tried another torrent client like QBittorrent? Has the same thing happened?
> 
> And one last question, is it really necessary to have NextDNS when you already have Portmaster? I mean, Portmaster filters already do the task of NextDNS, you shouldn't worry about the number of requests for that.

NextDNS has more filters, different options,  it's filters update automatically, can be used on different devices simultaneously and of course I want to have encrypted DNS that it offers.

I'm also seeding my collection so maybe that increases the requests. But I haven't experienced crashes for a while. Right now, I've had Ktorrent open for 10min and in portmaster ui it has 6K+ requests on 'Kioslav5' and 3k+ on 'Ktorrent' and 2k+ on 'Other connections'
