### ISSUE TITLE
SPN FEATURE REQUEST

### ISSUE THREAD

**Issue by 32bitx64bit** [safing/portmaster#1293]
It would be nice if their was a option to control the transit node, example im trying to set up where my home node is in the United states, it goes to the UK as a transit node and then exits via switzerland, but thats really hard to do as I cant specify if it can only be used as a transit node.

So please add a way where I can exclude and allow certain nodes as a transit node only. Thanks! 

It would also be nice if their was a feature where instead of only a certain amount of predetermined hops you could set a custom amount, like 4 or 5. Now this is not going to be used in most situations but its always nice to have that fine control

**Comment by Raphty** [comment]
this is now a feature
![image](https://github.com/safing/portmaster/assets/11504285/454fe3f7-7966-4282-9755-454ec4881016)


I hope this satisfies your request :D if not let me know
