### ISSUE TITLE
Extreme (over 1000%, literally) CPU Usage

### ISSUE THREAD

**Issue by ethical-haquer** [safing/portmaster#1294]
**What happened**:
I was using my computer, in fact I was experiencing [This VS Code bug](https://github.com/microsoft/vscode-python/issues/15586), so I was following the steps to solve that issue. Then, my laptop's fans kicked on. I though it was VS Code again, but nope, htop said it was Portmaster. At the worst part, Portmaster had over a dozen processes running, with one using **1048% of the CPU**. My laptop has 12 Intel® Core™ i7-10710U CPU @ 1.10GHz, and 30 Gbs of memory. All of the CPUs were in the red zone.

**What did you expect to happen?**:
Well, I guess I expected Portmaster to use less than 1000% of the CPU. :)

**How did you reproduce it?**:
By starting Portmaster again.

**Debug Information**:
Waiting for it to do it again so I can get the logs...

What I saw when I first opened htop:
![Screenshot from 2023-08-22 20-00-21](https://github.com/safing/portmaster/assets/141518185/31726bfd-29bb-4963-b081-d3feb70e3718)

What I saw 40 seconds later, after trying to restart Portmaster (from the GUI):
![Screenshot from 2023-08-22 20-01-43](https://github.com/safing/portmaster/assets/141518185/2952a2b9-ad84-4fc9-a87c-2bb38e6fd4ae)

What I saw after quitting the top Portmaster process from htop:
![Screenshot from 2023-08-22 20-02-30](https://github.com/safing/portmaster/assets/141518185/875aa640-3198-4531-b59d-f29c4e15860b)

**Comment by ethical-haquer** [comment]
After looking at the screenshots more, it appears that the original Portmaster process didn't even make onto the first screenshot, but then jumped up to first place 40 seconds later (look at the TIME each process had been running). Also it was spawning more processes suddenly?

**Comment by ethical-haquer** [comment]
Update:
I restarted Portmaster, and it did the same thing again. At least getting logs, etc. will be easy. :)

**Comment by Raphty** [comment]
> At least getting logs, etc. will be easy. :)

that would be a great start, can you pleas provide the debug info taken during such an incident.
https://wiki.safing.io/en/FAQ/DebugInfo

**Comment by ethical-haquer** [comment]
Also, is there any way to get the previous logs from Portmaster? Like are they saved after Portmaster has been restarted, and the computer has been logged-out of? I know I really should have just got the logs when the issues were happening :blush: , but I wasn't able to load the Portmaster UI due to how sluggish my system was, or something.

**Comment by Raphty** [comment]
thanks, but the debug info during the event is what I am looking for :D thanks

**Comment by dhaavi** [comment]
If you experience this again, please get the debug info, but also collect a CPU profile.

Docs: [Get CPU Profile](https://docs.safing.io/portmaster/api#v1/debug/cpu)
You might need to enable Developer Mode to access the API directly.

**Comment by ethical-haquer** [comment]
Thanks! I'll be sure to do that if it ever happens again. :smile:

**Comment by Daniil-Demyanenko** [comment]
Confirm. Loads ryzen 7 6800H at 100%. This doesn't happen very often, usually after updating several tabs in the browser. More often it takes about 18-20%.
RAM -- 16GB.
OS -- Manjaro KDE.
I attach a link to the archive with debug-info and log:

[LOGS.zip](https://github.com/safing/portmaster/files/12591142/LOGS.zip)

**Comment by ethical-haquer** [comment]
Maybe I experienced this: #1312. I had just updated Portmaster that day. :man_shrugging:

**Comment by Raphty** [comment]
@ethical-haquer are you also on manjaro? and are you using the manjaro packaged version?

Manjaro is packaging PM themselves.

**Comment by ethical-haquer** [comment]
> @ethical-haquer are you also on manjaro? and are you using the manjaro packaged version?
> 
> Manjaro is packaging PM themselves.

Nope. I'm using Debian 11, PureOS to be exact. I believe I used the portmaster-installer.deb to install Portmaster, as I have that file.
