### ISSUE TITLE
AIRVPN

### ISSUE THREAD

**Issue by G-i-o** [safing/portmaster#1298]
**What worked?**
Portmaster on LInux (Fedora) set with own DNS servers with AirVPN client (Eddie) set to use the Wireguard protocol.

Initially I had DNS leaks issue. DNS was really leaking (not protected by Portmaster contrary to what is stated in the Portmaster docs (VPN help pages).

However, I managed to tap the leak and have Portmaster work as it should, with full DNS protection, by following the below steps (also reported [here](https://airvpn.org/forums/topic/49747-airvpn-eddie-portmaster-and-dns-how-to-configure/?do=findComment&comment=225233)):

- Starting with Portmaster service running, initiate Eddie without connecting to any server.
- **Eddie Internet Lock** set to disabled. Also uncheck the "**SETTINGS > Activate Network Lock at Startup**"
- **Eddie DNS Switch Mode** set to disabled.
- **Eddie Check Air VPN DNS** unchecked.
- Portmaster option "**GLOBAL SETTINGS > SECURE DNS > Ignore System/Network Servers**" must be on.
- Initiate a connection to a VPN server with Eddie.
- Portmaster may need restarting once the connection to a VPN server with Eddie is initiated. In Linux with Systemd, you can type:
`sudo systemctl restart portmaster
`

Hope it helps.

P.S. The docs ([here](https://docs.safing.io/portmaster/install/status/vpn-compatibility)) may need updated, in particular where it says that Portmaster does protect the DNS request in any case. For me that was not the case as the AirVPN client, without the above modifications, would try to modify the resolv.conf (and other config files?) causing a DNS request leak. Please mind that the leak was real, not just a check if the request was through the VPN server.

-->

**Comment by Raphty** [comment]
Thanks I updated the [compatibility list](https://wiki.safing.io/en/Portmaster/App/Compatibility)

what DNS leak test did you use? 

Did it give you your home ip address or what did you mean by "DNS was really leaking"?

P.S. the docs you linked to have a big yellow banner on top saying that "This site is migrating..."

**Comment by G-i-o** [comment]
I used these:

ipleak.net
dnsleaktest.com

So, I previously tested them on a device that does not have any
protection and they showed a dns ip address of my Internet provider.
The very same address was then reappearing when I had the leak on the
protected pc.

For my linked docs, apologies. I did see the warning banner initially
prior to installing Portmaster  but when I later searched specifically
for VPN issues help through the browser search engine I ended up to the
old ones and missed it.

**Comment by Raphty** [comment]
In the mean time because of another issue where someone did mention the Ignore System/Network Servers, I marked that setting extra in the wiki, so people see it better. It usually is not an issue, because when the DNS on top of the list is a fast and reliable one (like cf which is the default) then Portmaster will not have to go down the list until hitting the system/network configured server.
For all who are confused, why this setting is enabled by default, because when you have a name space for your LAN then this is only on your network server... and so Portmaster needs to use that. but all public domains will be found in the upstream dns anyway, so your local server does not see it.

If you find your Portmaster falling back to the system DNS to often, consider putting in multiple DNS option in Portmaster.
I understand that Cloudflare has its issues, but using them as a backup is a good idea.

**Comment by G-i-o** [comment]
At the moment seems to be fine. I keep checking for DNS leaks at each
reboot and wake from suspend and haven't noticed any.

Also, a couple of weeks ago I was using IVPN with Wireguard protocol
and it was also OK without any particular intervention.
Eddie/AirVPN was the most troublesome for me but not any longer, as far
as Portmaster is concerned anyhow.

Thanks!

**Comment by G-i-o** [comment]
Not sure what has changed but after upgrading to v1.5.1 in particular (might be after the previous upgrade too but I'm not sure) e when running it with AirVPN some some webpages do not load.

There seems to be a conflict. I haven't changed any settings compared to the above guide and yet I can only load some pages if I either use only Portmaster or only AirVPN but not together.

Also, it seems that if I restart Portmaster, I need to disconnect the vpn and reconnect to have _any_ page showing up.

**Comment by Raphty** [comment]
As with most VPNs my assumption is that the VPN changed something... We did updates but none of them changed how we Integration into the system. So there should not be a change in behavior

**Comment by G-i-o** [comment]
I guess it could be. I have to say, though, that it's also not working with IVPN any longer (it was last Summer).

I wished the SPN was working for all sites and all this would become redundant.
