### ISSUE TITLE
Clarify DNS Server Config

### ISSUE THREAD

**Issue by TechD123** [safing/portmaster#1300]
**What would you like to add or change?**:
I would like to have Portmaster use the DNS resolver specified by the network as a fallback, as some networks I use censor DNS over TLS requests (I will test whether this is also the case with DNS over HTTPS). Therefore, my DNS server config may look like this:

> dot://dns.quad9.net?ip=9.9.9.9&name=Quad9&blockedif=empty
dot://dns.quad9.net?ip=149.112.112.112&name=Quad9&blockedif=empty
doh://dns.quad9.net/dns-query?ip=9.9.9.9&name=Quad9&blockedif=empty
doh://dns.quad9.net/dns-query?ip=149.112.112.112&name=Quad9&blockedif=empty
**empty slot**

From the [wiki](https://wiki.safing.io/en/Portmaster/App/DNSConfiguration) and the program itself it is not clear whether adding an empty slot as the last dns server will actually reach the desired effect. It would be great if this could be clarified.

**Why do you and others need this?**:

DoH was added to help users in restrictive network environments. For the same reason of helping these users, there should be clarification in how the mechanism works exactly.

**Comment by Raphty** [comment]
there is a setting Ignore System/Network servers right bellow the DNS Server list
![image](https://github.com/safing/portmaster/assets/11504285/ceac4cef-2f56-4f16-83b6-6f8079f066d9)


if you have that off (default) then it will fall back to the system dns

as with all Portmaster rules it goes fro top to bottom, so it will start in your case with the two dot, then the doh and if nothing works fall back to the system configured

**Comment by Raphty** [comment]
thanks for raising the issue that this is not communicated well enough I also updated the wiki to be a bit clearer on this.

It also sparked the idea that we might move  the additional setting inline into the other servers... but we will see if we can do that in a clean way

**Comment by Raphty** [comment]
@TechD123 I get that, I usually am not in advanced either (less scrolling) but your request is a bit advanced 😄

**Comment by Raphty** [comment]
without the debug info to look into it this is hard to say.

if it happens again pleas send in the debug info.
