### ISSUE TITLE
Portmaster creating bogon to 192.0.2.1 @ port 90

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#1302]
```
IN=br-lan OUT=wan SRC=192.168.1.x DST=192.0.2.1 LEN=52 TOS=0x10 PREC=0x20 TTL=127 ID=48481 DF PROTO=TCP SPT=38656 DPT=80 WINDOW=64240 RES=0x00 SYN URGP=0 MARK=0x10000
IN=br-lan OUT=wan SRC=192.168.1.x DST=192.0.2.1 LEN=52 TOS=0x10 PREC=0x20 TTL=127 ID=48482 DF PROTO=TCP SPT=38656 DPT=80 WINDOW=64240 RES=0x00 SYN URGP=0 MARK=0x10000
```

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
This is our captive portal check. We use 192.0.2.1 to stop it from leaking to the Internet.

**Comment by Rexadev** [comment]
@Raphty Use gateway

**Comment by dhaavi** [comment]
Doesn't work.
