### ISSUE TITLE
Add Functionality (and Alert) for Detecting Proxies on Machine

### ISSUE THREAD

**Issue by avoidthehack** [safing/portmaster#1306]
**What would you like to add or change?**:
 I noticed that Proton VPN's App (Windows, specifically) was able to detect when a proxy was running on the system. 

When I ran the proxy, Portmaster could see the traffic being forwarded to the proxy (127.0.0.1:8080) so would it be possible to have Portmaster do something similar? If this is possible, could an alert also be added if a proxy is suspected and possible ramifications of this? An Alert could warn "Portmaster detected a running proxy. Not all connections may be secured by Portmaster."

By extension, could this also be done when the machine is connected to a VPN? Perhaps minus the Alert.

**Comment by dhaavi** [comment]
Okay, if I understand there are two parts to this:

1. Detect if a proxy or VPN is in use.
2. Display that fact in the UI and warn the user if this has an impact on the protection of Portmaster.

Which leads me to:

3. Inspect proxy traffic and correctly apply rules to it. (If the connection is not encrypted, which very likely on localhost.)

And obviously the last step here is:

4. make the SPN use the proxy to establish a connection and start redirecting traffic through the SPN instead and ignore the proxy.

Very nice ideas. Thank you very much. I will think about this over the weekend and talk with the team about this next week.

**Comment by avoidthehack** [comment]
That's precisely it! :)

**Comment by Raphty** [comment]
@dhaavi I know this has been a while, but can you pleas give @avoidthehack an update and I believe we have in cooperated that into our internal tools so we can close the issue, but with a comment :D
