### ISSUE TITLE
Portmaster core service won't start after system freeze

### ISSUE THREAD

**Issue by SatoshiHP** [safing/portmaster#1307]
**What happened**:

Computer froze, after restart portmaster won't start. Tried uninstalling and reinstall without clearing data. Don't want to lose my settings.

**What did you expect to happen?**:

Portmaster core service to start.

**How did you reproduce it?**:

Restart and try again. Close all portmaster processes and try again.

**Debug Information**:

Log:
executing core/portmaster-core.exe version 1.4.5 on windows amd64
230903 00:47:12.363 > BOF
230903 00:47:12.367 ules/start:101 > CRIT 001 modules: could not start module config: invalid character '¾' looking for beginning of value
230903 00:47:12.469 dules/stop:059 > WARN 003 modules: aborting, shutting down...
230903 00:47:12.496 dules/stop:064 > ERRO 005 modules: shutdown completed with error: modules: dependency loop detected, cannot continue
230903 00:47:12.506 < EOF

Error log:
===== Error Report =====
Message: invalid character '¾' looking for beginning of value
Timestamp: 2023-09-03 08:44:35.2385971 +0200 CEST m=+0.111876801
ModuleName: config
TaskName: start module
TaskType: 
Severity: error
PanicValue: %!s(<nil>)
StackTrace:

goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc000176160, {0x16b67a0, 0xc}, {0x1829d20?, 0xc000008288?})
	/home/user/git/safing/portbase/modules/error.go:48 +0x49
github.com/safing/portbase/modules.startModules()
	/home/user/git/safing/portbase/modules/start.go:200 +0x1de
github.com/safing/portbase/modules.Start()
	/home/user/git/safing/portbase/modules/start.go:99 +0x285
github.com/safing/portbase/run.Run()
	/home/user/git/safing/portbase/run/main.go:34 +0x2b
main.main()
	/home/user/git/safing/portmaster/cmds/portmaster-core/main.go:42 +0x171

===== End of Report =====

**Comment by SatoshiHP** [comment]
Nothing?

**Comment by SatoshiHP** [comment]
Nothing?

**Comment by Raphty** [comment]
- Is this still reproducible?
- What PM version are you on?
- Do you have other interfering applications on your system?

thanks for providing the logs so far.

thanks for providing the logs you have,

**Comment by SatoshiHP** [comment]
Same issue everytime. I can't reproduce it, but the problem remains after a full restart and after reinstall without removing user data. I am currently on 1.4.4 I have not installed anything that would interfere. I will try to install the latest version and see it the problem persists. I still cant into the app tho

Maybe PM corrupted my config after a computer freeze because it was busy writing my settings into some file somewhere and corrupted it because it got interupted. If PM has no protection against that that is.
On 21 Sep 2023, at 08:01, Raphty ***@***.******@***.***>> wrote:


  *   Is this still reproducible?
  *   What PM version are you on?
  *   Do you have other interfering applications on your system?

thanks for providing the logs so far.

thanks for providing the logs you have,

**Comment by Raphty** [comment]
so your setup is, you:

- Portmaster is not installed?
- You are still experiencing windows freezes?
- Is the issue that Portmaster does not start?
- What was the cause of the freeze?

**Comment by SatoshiHP** [comment]
PM was and is still installed on 1.4.4. But i will try to reinstall using 1.4.6 when i get the chance at the end of the day.

After my pc start portmaster tray starts but remains red and the ui application tells me to start PM core, which also does nothing.  After force quit I restart the application through the console and it prints the message from my first post it is also logged in the logs. Once for the normal start and once for the one done by hand.

Windows sometimes freezes, i noticed once before that an app wrote something during that time and got corrupted or perhaps caused it (because faulty hardware on my part perhaps)  I don't known the cause since it is never logged anywhere not as a bsod nor as an event in the event viewer. (Although I have a suspect) I ran a ram check and disk check but found nothing. I bought a new disk but no help. Whenever it freezes however It just becomes unresponsive allowing me to only hear sound and move the cursor for a minute after which a complete freeze happens and the only recourse is force powering off and on again.

Thats my problem though. Thats why I think maybe PM wrote my settings and it got corrupted because it got interrupted.

The only thing that I noticed is that PM stopped freezes from being regular. My suspect is Bitdefender or its updates. But PM has worked regardless of those freezes before, and I don't doubt that a full reinstall, with removing my settings, will fix it. I just really don't want to lose my settings.

Regular reinstalls haven't worked before, but I will try the latest version later today.


On 21 Sep 2023, at 08:16, Raphty ***@***.******@***.***>> wrote:


so your setup is, you:

  *   Portmaster is not installed?
  *   You are still experiencing windows freezes?
  *   Is the issue that Portmaster does not start?
  *   What was the cause of the freeze?

**Comment by Raphty** [comment]
i know you could not have known... but when I asked for interfering apps, i was looking for something like bitdefender. we have had reports in the past... this of course is no guarantee. and it seems you PM install has issues besides that.

**Comment by SatoshiHP** [comment]
Installed 1.4.6 and restarted. Still the same error.

**Comment by Raphty** [comment]
so does Portmaster open at all? if so, pleas share the debug info.

**Comment by SatoshiHP** [comment]
It does not open. Only the tray icon. The gui tells me to launch PM core which does nothing. I can't get debug info, only logs.

On 22 Sep 2023, at 08:16, Raphty ***@***.******@***.***>> wrote:


so does Portmaster open at all? if so, pleas share the debug info.

**Comment by Raphty** [comment]
Did you open the config.json? you can try to fix the error in there, if not, you can delete it and Portmaster will create a new one. But the settings would be gone.

**Comment by SatoshiHP** [comment]
I guess there is no other option than deleting it, since my config.json looks like this:

`ｾu%0E%2CNpCﾜｮ・Okﾖ┌%07dｫﾐﾘ>D釮・%19ﾔb1攪%03ｨ・撲璉u%01・Q>8A%1D錥嶸1g*塾膝ﾞ%0E蠅+ﾍRﾕ%11W3%07ﾌ珊4%01f*・茅親+→Z銧ｨﾕcｨ%1CHｺE%0F鞴齬・ｧｰTO炬1ｵLﾝ勳3・｡%2BﾎP%2Bﾍc.茁ﾘNhJ%15ﾆｨ%1BIﾟcT9ｭW8・hbｗJQNｻYﾞ湿王Qk諺%16Z魍峙ﾑｫ%11P%12ｶ｣~t･%23x撒德・+lｫ・_)%7C+・ﾝ頴・ｻﾆE+ﾏ・3ﾍl､簣鋧Iｱ國l~1ﾇ%24ﾎﾘ7%2B%17・吩l%24､ﾄﾓ%14ﾁ%5Cﾝ%14・1ｫ%19ﾒR・-ﾍ髀xHｹxｰ吾nｦﾉ>ﾇﾏ購兌・%5E%1Cﾕ%08社鸞ｨ8GA%01ﾎﾛｲ+_ﾌ%25籘ｭｭ%1DｾSｫhp+%05晰・､璽%08・%14ｽ%7B)33fIﾖV淳Jｵﾟgｳ+襭E讃・%1F・・5_ｽ*・Aｼ%19ｿHｭ%12~ﾃF・q%11萎rDﾍ前%60%2FoV瀅D・・l娠bﾋﾜﾆ蹤e%07!ﾕ%03ﾆ%0FZOｽZF柤・ﾕｮ%2C・ﾎ%05Vｬ+腕ﾞｿE%0E+ﾕ蒻・K%7F0+Q裵5%11+V褝ﾗｪ%10%7DｦｵEdンZｼ辟%5B%1A3・S%2F墨P愚・ﾃ接ﾑ%1C%7Fｪ%1FT倣｢ｻ~ｳj避5qﾗ・+_.・O.Ｖ%06ｸA*_ﾅﾒ+%2F%1F6%5BCO･%25%2Czi5%7F悛R%11%05nｮcﾖ%24jYｦ%2C・・齪ﾆ｢・+饒・%5Edr%25w・9+ﾑ%06%5Eｸh%3D%1Eq)X%7Fﾉ・%13惷)+_鄕｣1ﾊ%122・・%04・・・ﾀ6ﾄ%7C薛Ze迫%7F首熙%17Ｂ`

I was afraid I would have to reconfigure 100 different apps, but it seems those are saved elsewhere.

I guess that's it. Thanks anyway.
