### ISSUE TITLE
Setable password required to change rules.

### ISSUE THREAD

**Issue by ZMensRain** [safing/portmaster#1308]
**What would you like to add or change?**:
I would like to have a password that can be set that is then required to change any rules or a specific rule.
The number of passwords should not be limited.

**Why do you and others need this?**:
To help parents keep their children from accessing websites and content that they deem inappropriate.

**Comment by Raphty** [comment]
Welcome @ZMensRain 

Thanks for the suggestion. We have heard a similar request in the past, but this is a use case we have not considered in the past. This use case is easier. 

@dhaavi what do you think?
