### ISSUE TITLE
Spotube does not work with Portmaster, shows 'offline' status

### ISSUE THREAD

**Issue by advait404** [safing/portmaster#1319]
**What happened**:
when trying to use the app Spotube (version 3.1.2) it shows 'you are currently offline' and as soon as portmaster is shut down, it starts working normally. 

**What did you expect to happen?**:
ideally if portmaster settings allow all inbound and outbound connections, and the DNS servers are not blocking the connection, portmaster should not be blocking and forcing an 'offline' status.

**How did you reproduce it?**:
install Spotube (https://github.com/KRTirtho/spotube), allow all traffic, and configure a DNS without any blocking.

Debug Info for Spotube shared as file: [log.md](https://github.com/safing/portmaster/files/12647626/log.md)

**Comment by advait404** [comment]
I am not sure, but this may be relevant: https://github.com/KRTirtho/spotube/issues/728
however, as far as I am aware, I am not using any VPN or Proxy.

**Comment by Raphty** [comment]
There is a FAQ for allowing blocked connections. If you think that the connection required for your app is erroneously on one of the included filter lists pleas let me know so we can configure the filter lists accordingly 

https://wiki.safing.io/en/FAQ/AllowBlockedConnections

**Comment by e-t-l** [comment]
@advait404 do you have any global block rules in Portmaster? Try disabling *all* blocking rules to see if just having Portmaster running is enough to interfere. I have Spotube so I'll try to check if I can replicate your issue later

**Comment by advait404** [comment]
I had disabled all possible rules, and used portmaster just as a DNS app.

Though I am not currently using the app so I can't confirm if the problem persists in the latest app versions.

**Comment by advait404** [comment]
I tested spotube and portmaster on the their latest versions, and there are no problems.
Closing this issue.
