### ISSUE TITLE
Consider switching from Discord to Matrix

### ISSUE THREAD

**Issue by throwaway-d** [safing/portmaster#1323]
1. Discord is proprietary and privacy-invasive
2. Matrix is open source, libre and decentralized

**Comment by Raphty** [comment]
we thought about it, and from out twitter v mastodon channels we saw that most people still choose the easier option. 

our twitter following to this day grows faster then the mastodon one, and I believe  with Discord v Matrix it would be the same. 

**If you don't want to install discord we understand, just use the pwa with a trash mail account.** 

I am sorry but we won't switch in the near future

**Comment by throwaway-d** [comment]
I think we have both Discord and Matrix. And both Twitter and Mastodon. That would attract both users. Codeberg also used to have both Twitter and Mastodon (now they entirely moved to Mastodon)

**Comment by Raphty** [comment]
we get those recommendations a lot, and personally I sympathies a lot, I had a presence on masotdon for years now... and I do use matrix... but for Safing and Portmaster where the goal is to get more people into privacy, we see that those platforms are not a good place to be.

**Comment by Raphty** [comment]
regarding stale bots, I see it as a focus tool, and yes people don't look at closed issues, which is a good thing, because it increases the focus on the issues people are actually working on. 😀

**Comment by throwaway-d** [comment]
> we get those recommendations a lot, and personally I sympathies a lot, I had a presence on masotdon for years now... and I do use matrix... but for Safing and Portmaster where the goal is to get more people into privacy, we see that those platforms are not a good place to be.

As I have said, we should just use both. Those platforms are also great to even introduce people into privacy and FLOSS. First, they found out not only Safing and privacy importance via YouTube, Twitter, Discord. But they will also find even more privacy-friendly and FLOSS platforms to escape the bubble.

> yes people don't look at closed issues, which is a good thing, because it increases the focus on the issues people are actually working on. 😀

For example, there existed an issue that would make Safing much better could be unluckily created at the time there wasn't any people working on and it was tagged "stale". Then, a week later, someone came to this project and they were ready to solve that issue but they would never find that issue. And that person wasn't interested in other issues causing other issues to also be stale. And that issue would be forever unsolved.

> I see it as a focus tool

I personally find it much harder to focus. To me, closed issues mean that I have solved them. I only focus on checking open issues. Now, with stale bots, I've to check both to ensure I didn't forget any issues. And the "stale" label does two things:
1. When I search through labels, I have to scroll down and look even more.
2. When I check issues, "stale" label just is visual clutter.

And the bot causes two things:
1. When I find a notification caused by the bot, as an issue discusser, I'm disappointed to find out that there is no new information about the issue. As a repo owner, I also will be disappointed that there isn't new information. My time is wasted.
2. Some people may post useless comments just to prevent bots from closing their issues, and they would cause just visual clutter.

**Comment by Raphty** [comment]
If you want join us on discord and start a thread there, I would love to write there. https://discord.gg/safing
