### ISSUE TITLE
VPN's SOCKS5 Compatibility issue for 1.4.9 Beta

### ISSUE THREAD

**Issue by Noir16** [safing/portmaster#1334]
### What worked?
The behavior of pass-through SOCKS5, a feature of VPNs. (ex. Mullvad VPN, IVPN)

### What did not work?
Some VPNs come with SOCKS5 functionality, but if you update to 1.4.9, you&#39;ll get a DNS horizon violation error.

### Additional information
How to fix it:
1. In the search bar at the top of the settings, type in `Enforce Global/Private Split-View`.
2. The issue was resolved by disabling the Enforce Global/Private Split-View [Developer].

**Comment by Raphty** [comment]
Thanks for letting us know!
