### ISSUE TITLE
cannot access adobe express

### ISSUE THREAD

**Issue by wp-coin** [safing/portmaster#1338]
I am using the latest version of portmaster, but after the update in 10/2023 I cannot access adobe express website

**Comment by Raphty** [comment]
The debug info is required to figure out what is happening.
But also interesting in such cases is always what Portmaster tells you. Do you see blocked connections?

**Comment by Raphty** [comment]
The debug info is required to figure out what is happening.
But also interesting in such cases is always what Portmaster tells you. Do you see blocked connections?
