### ISSUE TITLE
Internet not working with Portmaster open when using cell phone as a portable hotspot, but works when using standard home wifi

### ISSUE THREAD

**Issue by JessG1981** [safing/portmaster#1339]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
The internet does not work on my computer when Postmaster is active and I am using my mobile telephone as a portable wi-fi hotspot. The browser does not connect and I get an error message about the "DNS server not responding"

When I use the same mobile/cellular connection with other computers (that do not have Portmaster installed), they work fine. When I shut Portmaster down, the internet works again.

My standard wifi connection works with Portmaster active, it is only when I try to tether to my cell phone.

I have tried flushing DNS, resetting IP config, setting a static IP address to the Google server, etc., and nothing has worked.

**What did you expect to happen?**:
The internet to work when tethered to my cell phone

**How did you reproduce it?**:
I turned Portmaster off temporarily, and the portable hotspot tethering wifi connection worked. I turned Portmaster back on again, and I got the same DNS error.

**Debug Information**:

**Comment by JessG1981** [comment]
Thank you - I have sent the debug info by private message.

**Comment by Raphty** [comment]
In the debug info the error message says that you have SPN enabled but are not logged in.

If you have not bought Portmaster Pro you don't have access to SPN. You should disable it - it will not work.
Also I see you have avast installed, so this might cause issues as well.

But no obvious issues other then that.

**Comment by JessG1981** [comment]
Hi,

Thanks for the helpful information, I have turned off SPN. That plus disabling Avast seems to have helped, thank you!

**Comment by JessG1981** [comment]
Hi,

Thanks for the helpful information, I have turned off SPN. That plus disabling Avast seems to have helped, thank you!
