### ISSUE TITLE
Clean up old profiles that have no rules.

### ISSUE THREAD

**Issue by LoganDark** [safing/portmaster#1345]
**What would you like to add or change?**:
Portmaster currently creates a new profile for every executable that ever runs on the entire system. They never go away, even if you never configure any settings or rules for them.

Portmaster could avoid persisting profiles to disk that have not had any settings changed. That way, short-lived processes can still be tracked down and tweaked, but ones that you have not touched at all will disappear magically after Portmaster's next restart.

**Why do you and others need this?**:
it's so hard to find anything in the profiles list now that it contains every executable that has ever existed on my computer, even the ones in temp directories and even the ones that have since been deleted, 90% of which executables have never had any settings changed whatsoever.

**Comment by Raphty** [comment]
Hey @LoganDark thanks for the suggestion, some additional info, Portmaster only shows executable that have network activity, so not every executable shows up, only those which have/had network activity. I see value in that information.

Du you have a suggestion for a time frame for auto delete? is 3 months too long or short?
