### ISSUE TITLE
[Feature Request] - OSTree Support

### ISSUE THREAD

**Issue by mystic-githuber** [safing/portmaster#1348]
Dear Devs,

Fedora's Immutable spins are becoming popular. It would be great if you could provide OSTree support similar to iVPN.

[https://www.ivpn.net/knowledgebase/linux/fedora-silverblue/](url)

**Comment by Raphty** [comment]
Hey @mystic-githuber, we have not looked much into immutable distros.

If the community want's to develop a Portmaster version/installer that would work on immutable distros, pleas reach out and we can help coordinating the effort.

Our team is focused on the current set of Operating Systems with Android being the next one.
