### ISSUE TITLE
Rules to block countries

### ISSUE THREAD

**Issue by HumanG33k** [safing/portmaster#1351]
Hello, 

Maybe i just do not find it but is there is a way to block all trafic from specific countries.

What i need is 2 things : 
- block 1 specific country 
- block every countries except one 

If i miss that option where can i found it ? Else I think it can be a great idea as more and more law exclude stuff from non compliants countries.
 
thx

**Comment by Raphty** [comment]
![image](https://github.com/safing/portmaster/assets/11504285/cc984b9f-5abc-48d1-88c8-69d6c977d8d1)

and you can only allow specific countries by going allow country A, B, C and then bellow create a rule block *

**Comment by HumanG33k** [comment]
thx it should be in the new documentation because it's quite precious.

**Comment by Raphty** [comment]
it is in Portmaster 

click on the i next to the setting and then show more.

![image](https://github.com/safing/portmaster/assets/11504285/7e42b8cb-aadb-45f5-81a1-bb42aae0fa1d)
