### ISSUE TITLE
Filterlist doesn't work with mullvad-browser

### ISSUE THREAD

**Issue by Morasithil** [safing/portmaster#1355]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Before i add any logs i kindly ask the developer to simply try and reproduce the issue, install the latet mullvad browser and visit youtube.com while the bigtechfilterlist, including google is active.
As youtube is a part of BG-Google it should have been blocked but the connection went through right now, i cannot reproduce this issue with other browsers like librewolf.

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
When the browser does the DNS resolving itself, Portmaster only gives you the IP addresses (like a network firewall). If you want the DNS filtering to work, you need to let Portmaster handle the DNS

**Comment by Morasithil** [comment]
How do i let portmaster handle the dns filtering over the mullvadbrowser?
I opened the mullvadbrowser app profile in portmaster, went to settings, filterlist, and enabled all bigtech options.
But youtube.com just like any other site that should be blocked is still accessible.
What am i missing here?

**Comment by Raphty** [comment]
you will need to change this in mullvad browser
![image](https://github.com/safing/portmaster/assets/11504285/05a7a7b7-5c7b-47ad-bcda-bd3a6e1315e9)

**Comment by Morasithil** [comment]
Thanks but this did not work, i used the option you highlighted in blue but the connection to youtube.com and all others still goes through. Not a major problem anyways, the filtering works with librewolf.

**Comment by Raphty** [comment]
maybe this was cashing. did you leave the setting like this?

is the issue still there after some time?

**Comment by Morasithil** [comment]
Ofcourse i left the settings as intended..
The issue hasn't changed.

This is easy to reproduce, on any windows computer install portmaster and mullvadbrowser, set mullvad to use system dns and access blocked domains.
