### ISSUE TITLE
Failed loading debug data

### ISSUE THREAD

**Issue by NolonQ** [safing/portmaster#1356]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
- Insecure
- starting module interception failed
- When i attempt copying debug info, portmaster shows an error: "failed loading debug data"
- http failure response for https://127.0.0.1.817/api/v1/debug/core?style=github: 503 Service Unavailable

![Capture](https://github.com/safing/portmaster/assets/149939392/920c9c78-9848-4883-a64c-7a6e1d0377fa)

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
What OS are you on?
Was this right after install?
Do you have Antivirus installed?
Did you make significant changes to the OS? or are you running it on default?
