### ISSUE TITLE
Can portmaster block connections by country?

### ISSUE THREAD

**Issue by Morasithil** [safing/portmaster#1358]
**What would you like to add or change?**:
Can i block a whole country, is there any filterlist to block an entire country?
I don't trust china, it's all known china has their so called "great firewall", sometimes i see connections to china on my computer, for example the new countertrike2 has some connections to various chinese companies, i would like to block all of this with a single klick.

**Why do you and others need this?**:

**Comment by Raphty** [comment]
You can do this in each app or globally via the outgoing rules (Incoming is blocked anyway)

here the Screenshots to how to get that info. you see the i next to almost all settings. They help a lot in understanding the setting.
![image](https://github.com/safing/portmaster/assets/11504285/8eb1d917-ac70-4830-b429-ff29bfa7cf1e)

![image](https://github.com/safing/portmaster/assets/11504285/14ac9d60-313f-4acc-8991-cfde98c6839d)

**Comment by Raphty** [comment]
The country code list:
https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2


China is CN
![image](https://github.com/safing/portmaster/assets/11504285/ca84ed0e-b9c0-4a3b-b57e-001d10fc49a3)

**Comment by Morasithil** [comment]
Thank you very much Raphty!
Another thanks for the TLD list!
I only found this one https://www.worldstandards.eu/other/tlds/ but preffer the wikipedia.
