### ISSUE TITLE
Portmaster+Proxifier compatibility

### ISSUE THREAD

**Issue by squromiv** [safing/portmaster#1365]
Portmaster last version
[Proxifier](http://www.proxifier.com/)
Windows Server 2016 x64

Fails to intercept connections before Proxifier.

**Comment by Raphty** [comment]
This message lacks in detail, can you specify what has failed? thanks!

**Comment by squromiv** [comment]
In detail: Portmaster fails to intercept connections before Proxifier. So it does not works correctly and does not filter traffic with applied rules.

The developer of Proxifier noticed, that

> We have not tested Proxifier with Portmaster app but from the description I see that it uses WFP technology on Widows.
Proxifier uses the same API, so conflicts are possible.

Need to use both apps by this way:
1) filter apps and processes by Portmaster
2) route "allowed" apps to different proxies or ethernet interfaces by Proxifier

That`s all. So is there any way to force these apps to work simultaneously?

**Comment by dhaavi** [comment]
If I understand correctly, Proxifier will have to change their Filter Weight Assignment if they want to be run after other software: https://learn.microsoft.com/en-us/windows/win32/fwp/filter-weight-assignment

Nothing we can do here to influence that.

Here is where Portmaster's weight is set: https://github.com/safing/portmaster-windows-kext/blob/28593163f29c2976efa16f3458d809bf3577aafc/pm_kext/src/pm_register.c#L154

I don't know of other ways how to influence WFP callout order.

**Comment by squromiv** [comment]
Author of Proxifier reported:

> I have checked your link, the source code of Postmaster and Proxifier.
Postmaster sublayer weight is 0xFFFF. Proxifier is 0x800A. So Postmaster should be called before Proxifier.

**Comment by squromiv** [comment]
But in fact, it is not working as it should.

As for example, in log of Proxifier I see

![screen_2023 12 13 002](https://github.com/safing/portmaster/assets/15985877/dbe60b86-c112-4df9-8d5e-31b2741eb8cd)

**Comment by Raphty** [comment]
not sure what your screenshot shows, but Portmaster always resolves the dns requests, so you get the info where the connection would be going... otherwise you would not see the destination ip or country.... 

resolving a domain is  a different connection. it also does not connect to the provider, it only goes to the DNS server.

**Comment by squromiv** [comment]
> but Portmaster always resolves the dns requests

**It is not DNS query**. ClipClip.exe attempts to connect to address q.blueswan.io in Proxifier besides of it is "blocked" in Portmaster.

**Comment by Raphty** [comment]
it does try yes, and to do so it needs to resolve the DNS first. Which Portmaster does, and then Portmaster blocks the actual connection.

I am not familiar with proxifier so I cant say how you think you know that there is direct connection established. But pleas shed some more light on this.
