### ISSUE TITLE
GUI messes when changing app from maximize to restore state. 

### ISSUE THREAD

**Issue by livan3li** [safing/portmaster#1368]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Application GUI messes in the moment when I resize application back by dragging title bar while application in maximized mode. As a result of this  application is no longer be able to use. Neither application close button nor GUI buttons are clickable. Application is totally out of control and it has to be closed through task manager.  It could be seen in the below video.

**What did you expect to happen?**:

would except to use usual way. Click buttons, respond normal way, hence be able to use the app through GUI.

**How did you reproduce it?**:
It could be reproduced by maximizing and restore. Also same issue happens when moving application from one monitor(screen) to another. In my case resolutions are different. One is 1600x900 and scale is %100 on the other hand other one is 1920x1080 and scale is 125%.

As it could be seen in the below video, the resize cursor icon is changing on wrong position and hand cursor is same also.  
![2023-11-20 19-51-39](https://github.com/safing/portmaster/assets/46044710/e8bef7f3-1d55-4f41-9542-9ca21f97d2ed)

**Debug Information**:

Debug info has been sent through e-mail by adding this issue link to end of the content. 
Also, as a note: I'm using gnome 43 desktop envinronment.

**Comment by Raphty** [comment]
got the mail, this looks like an electron error. 

I will talk with @dhaavi about this. thanks for reporting
