### ISSUE TITLE
Getting error when opening Portmaster

### ISSUE THREAD

**Issue by Jcastors500** [safing/portmaster#1371]
### What happened?
When I open portmaster, it shows an error. When I click on ok the error closes and the app works, but it&#39;s kinda annoying.

### What did you expect to happen?
The app should have opened without error.

### How did you reproduce it?
I can reproduce the bug just by opening the app via the start menu of windows.

### Additional information
Here is the error :

![image](https://github.com/safing/portmaster/assets/135508867/28cb8615-5696-4c5c-97cc-fb0f332fb6ce)

A JavaScript error occured in the main process

Uncaught Exception:
Error: EPIPE: broken pipe, write
at Socket._write (node:internal/net:55:25)
at writeOrBuffer 12)
at _ write
at Writable.write (node:internal/streams/writable:334:10)
at console.value
at console.log (node:internal/console/constructor:360:26)
at
(C: \ Program Data\Safi ng \ P ortmaster\ -
at ChildProcess.emit (node:events:527:28)
at ChildProcess._handle.onexit

**Debug-Info**: https://support.safing.io/privatebin/?d9f4bbb47e306819#FNzzYe4DKM73AqfTPu7ear1921aQRM19o8bJ8tPxn6xn

**Comment by Ultratc99** [comment]
Same error, any resolution?

**Comment by Raphty** [comment]
@Ultratc99 we have a presumed fix in the current beta 
https://wiki.safing.io/en/FAQ/SwitchReleaseChannel

we were not able to reproduce the issue though. Feedback would be welcome

**Comment by Miniontoby** [comment]
Same problem here. Installed portmaster not long ago. Running on Windows 10.
Also there is no tray icon of the portmaster notifier...


I also installed portmaster on windows 11 at work and that one doesn't have the issue.
And windows 11 does have the tray icon
