### ISSUE TITLE
Windows server support?

### ISSUE THREAD

**Issue by RUNETHERABB1T** [safing/portmaster#1372]
Does this project support being run on windows server? Like can if i make the computers on the network redirect traffic through the server does the software auto block the tracking stuff on the network machines. Sorry if this is a dumb question. I am still learning how windows server works and I am trying to figure out if this would work well for my dumb experiments with windows server

Thanks! :)

**Comment by Raphty** [comment]
This is a great question.

At the moment the answer is no. Portmaster currently ignores forwarded traffic.
