### ISSUE TITLE
HP Wireless Printing & Scanning

### ISSUE THREAD

**Issue by LukySwiss** [safing/portmaster#1376]
I've installed Portmaster and find it a very useful tool.

I just found that I can't use HP OfficeJet Pro 8620 **Scanner** anymore which is connected via WiFi.
Update: Also the Windows test page isn't received by the Printer.
The tray icon already reported that the Scanner is no longer connected... and as soon as I shut down Portmaster it reconnects again.
When manually starting the Scanning App it brings an error message "**Scanner communication cannot be established**".

In the Apps List I only see the app _HPNetworkCommunicatorCom_ which is the *.exe file with the same name from HP bin folder.

**Here is what I found**
1.) the HP app frequently sends _LAN Multicast Outgoing_ to 239.255.255.0:<port> (I have tried to copy it from Portmaster, but it didn't allow or I made a failure and not it's gone).
2.) that _LAN peer-to-peer Incoming_ got blocked from Portmaster

**So, I manually edited Portmaster settings for that app**
Unchecked _Force Block Incoming Connections_.  --> But this didn't resolve the problem.

Now it doesn't show me any blocked traffic for that App, so I don't know what elese I can do.

The App that starts the scanner is **HP Scanner.exe** in same HP bin folder. But I do not see this App in Portmaster.

**My suspicion is**
- there is a Windows Service that is blocking the peer-to-peer communication with the printer / scanner.
These seems actually the case because
- **Windows Service: SSDPSRV** is showing blocked connections:
- _LAN Peer-to-Peer Incoming:_
   192.168.112.1:58520,
   192.168.56.1:58518,
   192.168.8.117:58517, (seems the be from the correct subnet)
   192.168.211.1:58519
and earlier
   192.168.211.1:63751,
   192.168.8.117:63749, (seems the be from the correct subnet)
   192.168.112.1:63752,
   192.168.56.1:63750

The printer/scanner IP address is 192.168.**8.102**
The Win7 test machine IP address is 192.168.**8.117**

**Question**:
What would be the correct settings?
Do I really need to completely unlock that Windows service?

Thank you.

**Comment by LukySwiss** [comment]
After the above message, I thought I provide at least a short message about the status of the problem.

Even after support on Discord's Saving community support, the actual specific problem is not resolved.
(Thank you for your extensive help, also on other questions I had!)
But as I now can print and scan while using PM... I didn't take the effort to further check on the real problem and potentially solving the root cause.

The **workaround** for me with the printer itself was and still is to have PM **allow traffic marked as Network Noise** for that specific LAN IP-Address of the HP8620 and giving the device a permanent IP address (in my case on the device itself).
For the scanner (on the same device) additionally I need to sometimes run "HP print and scan doctor" (which in the latest version (I think it was 7.4) did allow to specifically check for scanner related problems). The only bummer here is, that for fixing the connection issue, this app is asking for the device's web-gui login details :/ (but ok, at least with PM I can deny any HP related traffic to be sent online and their app also accepted that;)

I've been thinking what would be great to actually better understand the underlying problem:
- It would be great if PM could analyze / report, in more detail, what kind of traffic is received when marking it as "Network Noise".

As I it looks like I have found these workarrounds...
I have no problem if you like to close the issue.
Still of course I'd be happy to find the real cause of the problem why that traffic is marked as "Noise".

**Comment by firxworx** [comment]
I am on a wifi network with an HP ENVY wifi printer, thankfully on a trusted network. The printer was not visible and I will share what settings I _temporarily_ disabled to find and add the printer in Windows just so I could print something.

Allow incoming connections by disabling:

- force block incoming connections

Plus I disabled the filter lists _just in case_ they were playing a role:

- ads & trackers
- malware
- deception

(I figure its unlikely these were a factor however I just needed to print something quick and wanted to make sure it would work)

Plus under the EXPERIMENTS section I disabled:

- wsp (windows spy blocker)

(I figure this could be a culprit based on the name, but that's a guess, I have no other knowledge of what this is actually blocking) 

---

I don't have time at this moment to troubleshoot / guess-and-test setting-by-setting to find out which exact settings let the printer be visible.

I was hoping a quick search would provide the answer. 

Instead I found this issue, so in case it helps anyone, I am sharing what I did to print stuff.

I am on a trusted network (thankfully) and after printing I will re-enable all the above settings. 

@LukySwiss hopefully this helps you, maybe if you have more time you can narrow down which setting is responsible for blocking the printer service and selectively disable only that one. Note that in some desktop applications you may need to close any printer dialog (if you have open) and/or even fully restart the app after successfully adding a network printer in Windows for you to be able to see it in-app when you print.
