### ISSUE TITLE
Improve detection some network programs when using systemd-resolved

### ISSUE THREAD

**Issue by Zesko** [safing/portmaster#1379]
**What would you like to add or change?**:

* ~~I notice that Opensnitch can detect  a network-binary such as `/usr/bin/ping` when `ping` is executed and its detail is stored in Opensnitch,  but Portmaster does not.~~

* I notice that Portmaster does not detect a network-binary such as `/usr/bin/ping` when using `systemd-resolved` instead of `openresolv` on any Arch based distros.

* I would like to see cmdline in detail of any app, for example:
When I ran `curl --silent --fail --connect-timeout 8 www.google.com`, Opensnitch shows the detail:
```
Process:
/usr/bin/curl

Cmdline:
/usr/bin/curl --silent --fail --connect-timeout 8 www.google.com

CWD:
/home/test

UID: test (1000) PID: 24988

Node: unix:/local
```
Screenshot of Opensnitch:
![Screenshot_20231203_175731](https://github.com/safing/portmaster/assets/17826352/2846d0b8-5244-4725-ae6c-b50df665996f)

The detail of cmdline lacks in Portmaster except the process-name.

**Comment by dhaavi** [comment]
What you are looking at here are DNS requests, not the actual ICMP message.

You do not see DNS requests when using systemd-resolved, because the requests do not go over the "wire", but go through the DBUS interface, so there is no network packet from the ping process for DNS resolution.
