### ISSUE TITLE
Disable Enforce Global/Private Split-View to access my NAS

### ISSUE THREAD

**Issue by netExtra** [safing/portmaster#1380]
**What happened**:
On my LAN I can access my media player device but not my Synology NAS. Initially Windows Explorer just hanged. But now it says it can't access my NAS. After some searching I found out the solution was to disable Enforce Global/Privat Split-View to access my NAS. Is there another way?

**What did you expect to happen?**:
Access to my LAN asking for credentials.

**How did you reproduce it?**:
Type LAN IP address into Windows Explorer address bar.

**Comment by netExtra** [comment]
Using the DNS name for my NAS works without me having to disable split-view. But that still doesn't explain why I can access my media player by \\\\<ip address> but not the Synology NAS.

**Comment by netExtra** [comment]
> thanks for the update, I guess this is resolved now.

Yes thanks but what is that. I was looking for an IP address and got that weird DNS alias which is why it took me so long to find. That and Scope Internet being the default which is seriously annoying.

**Comment by Raphty** [comment]
if you are looking for a LAN issue I get that, but most of the time you are looking where your programs are sending data to that is not in your Local Area

**Comment by netExtra** [comment]
> if you are looking for a LAN issue I get that, but most of the time you are looking where your programs are sending data to that is not in your Local Area

Thanks and sorry but what is that entry? It's not an IP address, but it looks like a DNS alias of some kind.
