### ISSUE TITLE
Windows 7 UI  now broken

### ISSUE THREAD

**Issue by lenient-f** [safing/portmaster#1384]
**What happened**:
Nothing happens when clicking Open App from Notifier in tray, nor from start-menu.

**What did you expect to happen?**:
Launching of app.

**How did you reproduce it?**:
Restart doesn't matter. Reproduced on two separate Win 7 64bit machines, today.

**Debug Information**:

Portmaster-start log:
{"Created":1702326417,"Modified":1702326417,"Expires":1704918417,"Deleted":0}S
executing start/portmaster-start version 1.0.13 on windows amd64
[pmstart] 2023/12/11 20:26:58 starting C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-6\portmaster-app_v0-2-6.exe --data C:\ProgramData\Safing\Portmaster
[pmstart] 2023/12/11 20:26:58 app/portmaster-app.zip failed with: unknown exit code exit status 0xc0000139

**Comment by Raphty** [comment]
you can try this guide: https://wiki.safing.io/en/Portmaster/Troubleshoot/ResetAppModule

**Comment by csadam** [comment]
Looks like it is an Electron app. Which means it won't work anymore on less than Windows 10.
Look around in `C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app` folder. 
If you still have v0-2-5 then remove all other versions and it will work, then disable auto update in the settings.

**Comment by Raphty** [comment]
you can also use your browser

if you cant enable devmode in the UI you can edit the config.json
![image](https://github.com/safing/portmaster/assets/11504285/ac4dc5d7-fa66-4e02-82f8-73919936687b)

add 

```
{
  "core": {
    "devMode": true,
  },
}
```

and then open 

http://127.0.0.1:817/ 

in your browser

**Comment by Ncrypt3dit** [comment]
> you can also use your browser
> 
> if you cant enable devmode in the UI you can edit the config.json ![image](https://private-user-images.githubusercontent.com/11504285/289870341-ac4dc5d7-fa66-4e02-82f8-73919936687b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzIyODUsIm5iZiI6MTcwNDQ3MTk4NSwicGF0aCI6Ii8xMTUwNDI4NS8yODk4NzAzNDEtYWM0ZGM1ZDctZmE2Ni00ZTAyLTgyZjgtNzM5MTk5MzY2ODdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE2MjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzZjExYTVmNDdhZTE2OGU3OGVlZjY3M2M3NjM5MTMwZTQ2MmViNDM3MWE0ODg1ZDJjMGEyODk1OTk5MDZkMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LXODH-JGyPAkaD4WBXRJnkS56AOBCv5ncxf-KQmluHs)
> 
> add
> 
> ```
> {
>   "core": {
>     "devMode": true,
>   },
> }
> ```
> 
> and then open
> 
> http://127.0.0.1:817/
> 
> in your browser

Apologies noob here.
Can you show your entire config.json file, cause anytime I change/add your above code to my json, my core.exe exits/crashes upon start.

**Comment by Raphty** [comment]
@Ncrypt3dit thanks for the comment. I edited my post now as well.
