### ISSUE TITLE
Is it possible to add multi-language support?

### ISSUE THREAD

**Issue by bluehysteric** [safing/portmaster#1388]
Is it possible to add multi-language support?

**Comment by Raphty** [comment]
We want to do that, but this will be a community translation and we will need to implement the system for this first, which has not been a priority at the moment, translations are a lot of work, and it can create the situation that people have issues with a translation that we cant help with...

So we hear the request, but sadly there is no current plan.

**Comment by realgooseman** [comment]
Setting up a [Crowdin](https://crowdin.com/) panel for community translation contributions might be a good idea, if Portmaster gets localization implementation. It will be community maintained (so continuously corrected/improved) which is one less workload to deal with from the Safing team and will popularize the app even more.

Even tho it's not a high priority feature, I think it would be great to consider it.
