### ISSUE TITLE
WSL Updating cannot resolve deb.debian.org

### ISSUE THREAD

**Issue by RUNETHERABB1T** [safing/portmaster#1391]
**What happened**:

So I was trying to figure out how to use the make command because I am new to building software outside of making games. But I found that I could barely have a WSL terminal run "sudo apt-get update && sudo apt-get upgrade -y" 

**What did you expect to happen?**:
I expected software to just update without having errors saying stuff along the lines of 
" Temporary failure resolving 'deb.debian.org"

**How did you reproduce it?**:
i have barely touched the settings for portmaster so it should be as simple as making a new windows VM. Setup WSL and try to update stuff. I was using the debian Linux terminal at the time if that is relevant

**Random info that might be useful**:
Somehow closing PortMaster down and rerunning the command made it work right away so I am honestly not entirely sure what is up with that. Also please note I am very new to trying to submit issues like this on github so please tell me if I can make future issues more clear and easier to understand as I can't exactly figure out if this is even understandable but I need some help so. Thanks in advance I guess

I also just want to say that I cannot find the Debug info thing that I am asked to also submit so if someone can please help me with figuring that one out I would appreciate it.

Sorry if all of this is basic this barely makes sense to me and I am trying to learn. Thanks and have a good day!

**Comment by Raphty** [comment]
I am sorry but WSL as well as other VM(type) software is currently not sported see #166 

I have seen some people make it work, but we at this point don't consider incompatibility a bug.

**Comment by hexadivine** [comment]
@RUNETHERABB1T  - Portmaster do not support WSL2. However, you can bypass portmaster by changing the nameserver from resolv.conf file (in WSL2 instance). Try this - 

`sudo nano /etc/resolv.conf`

add below nameserver
`nameserver 8.8.8.8`

Keep in mind that with this you are bypassing all traffic from Portmaster. This could be a potential privacy concern for some individuals.

**Comment by hexadivine** [comment]
Understood @Raphty, you are right, after digging deeper - I noticed that all traffic do in fact go through Portmaster (if turned on). To make this work I added `1.1.1.1` in the resolv.conf as mentioned above.

<img width="701" alt="image" src="https://github.com/safing/portmaster/assets/92310365/bc1cc4e4-cc63-447c-beeb-ca19f9c6ade2">

Note - If "Windows Subsystem for Linux" is not visible in portmaster then try creating a server in WSL2 using below command.
`python3 -m http.server ` (I am using WSL2-Ubuntu)

and visit `localhost:8000` from host machine this will generate network traffic to localhost and WSL will be visible in Portmaster.

**Comment by hexadivine** [comment]
I tested same on the Parrot VBox. By default there is no internet connection, for that you have to add 1.1.1.1 in the resolf.conf and traffic will be transferred through portmaster. You can block/unblock or filter traffic from VirtualBox Virtual Machine.

<img width="709" alt="image" src="https://github.com/safing/portmaster/assets/92310365/1f9b0c19-6caa-4d33-b738-0e83268856ae">
 
In the conclusion - I can confirm that Portmaster supports VMs for me.

**Comment by Raphty** [comment]
thank you for letting us know, I will add this into the wiki!

**Comment by Raphty** [comment]
Updated https://wiki.safing.io/en/FAQ/VMsAndPortmaster

**Comment by hexadivine** [comment]
Looks good 😊 thanks @Raphty
