### ISSUE TITLE
Notification "Dangerous Setting: Incoming Connections" is shown with the respective setting enabled

### ISSUE THREAD

**Issue by Marc05** [safing/portmaster#1392]
I sometimes see the following notification from Portmaster:
"Dangerous Setting: Incoming Connections You have disabled "Force Block Incoming Connections" globally."
I have not disabled this setting globally, and clicking the "Change Setting" button on the notification leads directly to the setting which is already enabled. I've tried to disable/enable it, but the notifications still appear. I usually notice this after booting (and logging in). I do disable the setting on some individual apps, but not globally.
[logs.zip](https://github.com/safing/portmaster/files/13697454/logs.zip)

**Comment by Raphty** [comment]
@dhaavi I have seen this as well.

@Marc05 you can click on the revert to default, then the notification should not come again, but you are correct, turning it on again should make it go away as well.

**Comment by dhaavi** [comment]
Thanks for the report. The value type of the setting changed, so we need to update the broadcast notification accordingly.

I just pushed the change to the notification, so you should have it soon.

**Comment by Marc05** [comment]
Haven't seen this in a while - presumably it's been fixed so I'll close this. It can be reopened if needed.

**Comment by Raphty** [comment]
we did change the times for this 😀
