### ISSUE TITLE
Notifications stop working in Windows 10/11

### ISSUE THREAD

**Issue by Kiefy** [safing/portmaster#1403]
I've had Notification troubles in every version of Windows, for years.

It's always the same. I install Portmaster. Notifications work great for some unknown amount of days, and then nothing. Never another Notification.  They are enabled in Portmaster, but Portmaster isn't in Windows' list of allowed apps at all.

I've come here many times expecting to find countless Windows users complaining about the lack of Notifications, but there are none. So I have to assume it's something special to me. Some Program I install that kills the Notifications maybe.

Looking at the source, I see that there is supposed to be a regkey:

`WriteRegStr HKLM "SOFTWARE\Classes\CLSID\{7F00FB48-65D5-4BA8-A35B-F194DA7E1A51}\LocalServer32" "" '"$INSTDIR\${ExeName}" notifier-snoretoast'`

I don't have `{7F00FB48-65D5-4BA8-A35B-F194DA7E1A51}` in my registry, so I was going to add it manually but if I have that syntax right, the name of the reg entry is empty "" and the value is `"$INSTDIR\${ExeName}" notifier-snoretoast` but you can't create an unnamed key in RegEdit.  So what is the name supposed to be?  Does a blank name = `(Default)` ?  I'll try that anyway, but can't say I'm too hopeful.

Am I barking up the wrong tree?

**Comment by Raphty** [comment]
@Kiefy I am sorry for your inconvenience, but sadly i also haven't seen any emails regarding this issue.

It might be a weird system thing, maybe some remanent from the past?
Does the same happen on a new install for you as well?

**Comment by dhaavi** [comment]
Hey @Kiefy,

`notifier-snoretoast` refers to a solution we have stopped using - you can delete any of these.

We are also in progress of switching the app framework from chromium to Tauri, so how notifications are handled will change once again. This will take a little more time though.

**Comment by Kiefy** [comment]
> Does the same happen on a new install for you as well?

Yes. After a format, it works for a while, then stops in both Win10 and Win11. It has to be a niche app or driver that I always install after Portmaster that is breaking it. I'll be formatting a system in a few days, so I'll do some experimenting.

> `notifier-snoretoast` refers to a solution we have stopped using - you can delete any of these.

Fair enough.

> We are also in progress of switching the app framework from chromium to Tauri, so how notifications are handled will change once again.

I look forward to the switch.

Maybe you would consider adding a sound alert feature? Then I would know to check the UI even if the notifications aren't working. Instead of spending an embarrassing amount of time wondering why my apps aren't working.
