### ISSUE TITLE
High latency / slow loading on web pages

### ISSUE THREAD

**Issue by DisturbedShadow** [safing/portmaster#1404]
**What happened**:
When postmaster is on **sometimes** web pages take a lot of time to load. I tried using difference DNS, tried auto update/use dns cache but after a while they stop working.

I assigned DNS manually and removed them from portmaster so that i can test if its a dns problem, and it is not. I think it should be the blocked connections that are getting blocked by the app and then the ms edge or firefox keep trying for no reason and thus the wait. 
I do not know what a possible fix would be also tried reinstalling.
Using Win 11 prof
**What did you expect to happen?**:

**How did you reproduce it?**:
Loading webpages / different websites.

**Debug Information**:

**Comment by io43** [comment]
i had that month ago, for me it was because i was blocking outgoing traffic by default using windows firewall and so it was blocking kernel traffic made by portmaster , i added a rules to allow outgoing traffic for "nt kernel & system" in windows firewall and it fixed the latency
