### ISSUE TITLE
Very high CPU & RAM usage on custom DNS server

### ISSUE THREAD

**Issue by realgooseman** [safing/portmaster#1405]
### **What happened**:

The Portmaster Core process gets very high RAM usage (over 13GB) when using the dns0 DNS resolver.
It makes the app unusable then interrupts my computer's network and responsiveness for a moment.

Built-in "Quick Settings" DNS Servers (Cloudflare, Quad9, Adguard, ...) all work normally.
The dns0 resolver works fine on my Android phone too. So probably not linked to resolver.

![9s8Uwv2NkZ](https://github.com/safing/portmaster/assets/64812183/d4cb5c7c-6fa8-4c26-9796-c87fbd5e27ec)

### **What did you expect to happen?**:

Portmaster should handle the dns0 resolver like the "Quick Settings" resolvers (Cloudflare, Quad9, Adguard, ...).

### **How did you reproduce it?**:
1. Went to Safing Wiki > DNS Configuration > dns0 resolver - [see here](https://wiki.safing.io/en/Portmaster/App/DNSConfiguration#dns0)
2. Copied the Regular > TLS links - see below

> TLS
> dot://193.110.81.0:853?verify=dns0.eu&name=dns0&blockedif=empty
> dot://185.253.5.0:853?verify=dns0.eu&name=dns0&blockedif=empty

3. Pasted them both in Portmaster > Global Settings > DNS Servers
4. RAM & CPU usage of the "Portmaster Core" process skyrockets
5. Alternatively, when using the HTTPS link of dns0 in my browser's Secure DNS section, I get the same problem

### **What I tried and didn't fix it**

I tried to allow the resolver's domain and IP's in the global rules
I tried to check my Ethernet / WI-FI cards. Both are updated and working.
I tried with the DOH links on the Safing Wiki, same problem
I tried to reboot my router and computer

### **Build information**
OS : Windows 11 Pro - Build 22621.2861
Portmaster : v1.6.2 - Stable
DNS Resolver : [DNS0](https://www.dns0.eu/) - EU Based, new (2022)
Browser : Brave - v1.61.109 / Chromium: 120.0.6099.144

### **Debug Information**:
I got multiple core log files similar to what's shown below
```
NJ{"Created":1703834096,"Modified":1703834096,"Expires":1706426096,"Deleted":0}S
executing core/portmaster-core.exe version 1.6.2 on windows amd64
231229 08:14:57.100 > BOF
231229 08:14:57.309 xt/service:035 > WARN 001 kext: old driver service was found
231229 08:15:01.552 tel/entity:209 > WARN 003 intel: failed to resolve IP 192.168.128.3: failed to resolve 3.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:01.552 tel/entity:209 > WARN 005 intel: failed to resolve IP 192.168.128.4: failed to resolve 4.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:01.552 tel/entity:209 > WARN 007 intel: failed to resolve IP 192.168.128.129: failed to resolve 129.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:01.553 olver-mdns:114 > WARN 009 intel(mdns): failed to create udp6 listen multicast socket: listen udp6 [ff02::fb]:5353: setsockopt: not supported by windows
231229 08:15:08.126 tel/entity:209 > WARN 011 intel: failed to resolve IP 192.168.128.182: failed to resolve 182.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:11.099 tel/entity:209 > WARN 013 intel: failed to resolve IP 192.168.128.133: failed to resolve 133.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:15.440 tel/entity:209 > WARN 015 intel: failed to resolve IP 192.168.128.1: failed to resolve 1.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:15.858 tel/entity:209 > WARN 017 intel: failed to resolve IP 192.168.128.135: failed to resolve 135.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:15.858 tel/entity:209 > WARN 019 [2x] intel: failed to resolve IP 192.168.128.135: failed to resolve 135.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:39.330 tel/entity:209 > WARN 021 intel: failed to resolve IP 192.168.128.133: failed to resolve 133.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:44.314 tel/entity:209 > WARN 023 intel: failed to resolve IP 192.168.128.133: failed to resolve 133.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:15:49.327 tel/entity:209 > WARN 025 intel: failed to resolve IP 192.168.128.133: failed to resolve 133.128.168.192.in-addr.arpa.PTR: query was blocked: no compliant resolvers for this query
231229 08:16:16.202 es/restart:105 > WARN 027 updates: initiating (automatic) restart
231229 08:16:16.305 dules/stop:057 > WARN 029 modules: starting shutdown...
```

**Comment by dhaavi** [comment]
Can you try stopping Portmaster and removing the cache database from Portmaster's directory?

Others were able resolve performance issues that way.

**Comment by realgooseman** [comment]
Hi @dhaavi,

I posted this issue 2 months ago. I since then switched to Mullvad DNS resolver which works fine.

If I happen to have this problem again in the future, deleting the "**db.bbolt**" file in : `C:\ProgramData\Safing\Portmaster\databases\cache\bbolt` would fix this problem ?
