### ISSUE TITLE
Unable to copy paste connection adresses

### ISSUE THREAD

**Issue by NolonQ** [safing/portmaster#1411]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
In portmaster we obviously see connections of our devices, when i want to do research on a specific connection i must look at the connection, remember it, and then manually enter it in my browser to look it up, why is it that copy paste does not work is beyond me.
I can highlight the connections in blue if i move the mouse cursor over them while holding the shift key, so it es being marked but pressing CNTRL & C does not copy the entry, also klicking the right mouse button which normaly provides a copy option does not work. Why can you highlight entrys if copying them doesn't work?

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
pro tip, push `ctrl` and then click on the domain or ip or...

**Comment by NolonQ** [comment]
> pro tip, push `ctrl` and then click on the domain or ip or...

hello and sorry if i was harsh or rude, my apologies for that behaviour... its just i got so upset with the portmaster because cntrl c and cntrl v dont work for me but i did recommend portmaster to a colleague of mine and it works for him so i asume the issue must be on my end but i really dont know what it could be..
