### ISSUE TITLE
Looking for saveing/backup individual rules each app

### ISSUE THREAD

**Issue by Neurothiker** [safing/portmaster#1414]
**What would you like to add or change?**:
I would like to save all my individual setting e.g.rules each app to import into an other instance on an other device - currently neither I can find the feature nor I can decide in the standard import/export Filterlist my individual rules.

**Why do you and others need this?**:

**Comment by e-t-l** [comment]
To edit per-app rules: Go to "Apps and Profiles" on the left-hand sidebar (see photo).
![image](https://github.com/safing/portmaster/assets/40775958/b52dc107-2fae-4964-8f16-acb3fc79986a)

If you click on an app, there's a button to export its profile, although I don't know how to export multiple/all apps' profiles. On the "Apps and Profiles" page, click "Manage" to import profiles. 

On the left-hand sidebar, going to "Global Settings" (two buttons below "Apps and Profiles") provides a blue "Export" button, but I do not know if this will export per-app settings or only global settings.

**Comment by Neurothiker** [comment]
Thanks for reply.
Does it make sense to combine all individual settings instead to export each app setting??
It is possible to collect all individual rules instead to "walk through the apps"?

Thx
