### ISSUE TITLE
Allowing inbound connections from IP/Host doesn't seem to work 

### ISSUE THREAD

**Issue by JS-E** [safing/portmaster#1417]
**What happened**:
I'm trying to locally send data to and from my Steam Deck (Hostname: BigBlackDeck) and although i have allowed the connection and created a rule for it, it seems global settings overrides this when it should be the other way round.

**What did you expect to happen?**:
I expect the app setting to allow the inbound connection based on the TCP rule i set within the app settings

**How did you reproduce it?**:
I connect my steam deck to the local network, and set up a rule to allow connections from the host, yet they are still blocked.

EDIT: SIDE NOTE- If i disable global 'force block incoming connections' the steam deck connects all fine and sends data 👍 

**Debug Information**:

I have included screenshots below specifying the rules and the connection being blocked. I have also allowed incoming connections from my steam deck globally also

![image](https://github.com/safing/portmaster/assets/33073990/886443e8-d7e9-436b-a0ba-4e891284fa9c)

![image](https://github.com/safing/portmaster/assets/33073990/7f34350b-d492-4251-afeb-2bb4bea83d20)

**Comment by Raphty** [comment]
as it says in the second screenshot you are still force blocking incoming connections.

there is a video and a wiki page on how to do this
https://www.youtube.com/watch?v=NObJFzBaeW4
https://wiki.safing.io/en/FAQ/AllowIncomingConnections

**Comment by JS-E** [comment]
Thanks for your reply, i've messed with it a bit and i was able to get it to connect without setting global incoming on, appreciate the help. Is there be another way of doing this process though? Similar to the way i can block an allowed outgoing connection as easily? So for example when i see the connection going out and being blocked by global, i can select a button that would add that as an incoming for the selected host?

**Comment by Raphty** [comment]
what I would suggest is copy the url/ip with `ctrl` + mouse click and then you can open the app settings right in the connection. Expand and bottom right
![image](https://github.com/safing/portmaster/assets/11504285/fd2399d5-62c4-4e5c-82e0-e5765833ebd8)

and add the rule manually. keep in mind you need to be in advanced view or must have made changes in that app before to see the incoming rules.
