### ISSUE TITLE
Change SecurityLevels to string enum

### ISSUE THREAD

**Issue by ppacher** [safing/portmaster#142]
**What would you like to be changed**:

Instead of using an integer bitmask for security levels consider using a simple string enumeration:
```go
type SecurityLevel string

const (
    SecurityLevelOff     SecurityLevel = "" // default value
    SecurityLevelNormal  SecurityLevel = "normal"
    SecurityLevelHigh    SecurityLevel = "high"
    SecurityLevelExtreme SecurityLevel = "extreme"
)
```

**Why is this needed**:

Currently a bitmask is used for security levels because in the old (and obsolete) config system a setting could have been enabled/disabled in each level separately. In the current configuration system the security levels are ordered and higher levels are automatically included in lower levels. That is, `SecurityLevelExtreme` is always part of `SecurityLevelNormal` and `SecurityLevelHigh`. Due to this stacking of levels (they are actually usage-thresholds) there's no need for a bitmask anymore. Instead of this bitmask we could just go with either number (`Normal < High < Extreme < Off`) or use string constants instead. I'd prefer string constants over integers as it's more easy to reason about them (in the API for example) and to place them into the configuration file (config.json) by hand.

**Comment by ppacher** [comment]
Closed by accident

**Comment by dhaavi** [comment]
Since we are deprecating the security / threat levels as they are now (will be replaced with something better), we can close this.
