### ISSUE TITLE
DNS request don't prompt me for Wine / Proton on Linux

### ISSUE THREAD

**Issue by Zesko** [safing/portmaster#1420]
PortMaster -> _Global Settings_ ->  _Privacy Filter_ -> _General_ -> _Default Network Action_ -> Change `Allow` to `Prompt` 

That works fine on Linux and the notification asks me whether I accept new connection or not.  For example :

![image](https://github.com/safing/portmaster/assets/17826352/72436ff5-84c6-4b1f-aa01-3a00360c24cd)

That is good.

But that has one issue with Wine/Proton.

**What happened**:

I installed GE-Proton 8 or any Proton 8 version for Steam.
one part of Proton is a binary executable `wine-preloader`:

**Any Windows game** uses this binary `wine-preloader` to perform DNS queries.  But PortMaster does not prompt me or can not block them.  

PortMaster allows all of DNS queries of Windows game without asking me. 😯

![Screenshot_20240118_074547](https://github.com/safing/portmaster/assets/17826352/f6d67d55-bce4-487f-99e2-459a446f827a)

**What did you expect to happen?**:

My expectation is that PortMaster should prompt me to decide "block" or "allow"  when playing any Windows game on Linux.

**How did you reproduce it?**:

1. I am using `NetworkManager` that generates `/etc/resolv.conf` instead of `systemd-resolve`
1. Install any Proton 8 or GE-Proton 8 in Steam
2. Create a new profile "Protin Wine Preloader" to edit Process Matching: `(wine64-preloader|wine-preloader)$` 

![Screenshot_20240118_081521](https://github.com/safing/portmaster/assets/17826352/97cae573-e72a-42cd-9471-6a829557dfc0)

3. Edit this profile settings -> Privacy -> Filter -> General -> Default Network Action -> Change **Allow** to **Prompt** or **Block**
 
4. Test Windows game using this Proton. 
5. But many DNS queries of game are allowed by PortMaster without asking me. That is problematic.

**Comment by Raphty** [comment]
what reason does the connection give when you expand it for being allowed?

**Comment by Raphty** [comment]
![image](https://github.com/safing/portmaster/assets/11504285/3b175141-898f-4e56-8fde-21d50ce4c139)

**Comment by Raphty** [comment]
domain requests are handled by Portmaster itself. 

what this tells you is what app is requesting the domain.

A dns request is not a connection.

Portmaster resolves those requests so it can tell you where the actual connection wanted to go afterwards.
No data has been sent by the application requesting the DNS

**Comment by Raphty** [comment]
It is before a connection is established.

This is expected behavior. If you tell me what your use case is, and why you want to change this behavior. I might be able to help on mitigation ideas that fit your chosen threat model.

**Comment by Raphty** [comment]
Interesting, it seems that wine emulates the windows dns service, which is why the structure is like this.

**Comment by Raphty** [comment]
@Zesko we have the auto close bot enabled to keep a focus on open **issues**.
rest assured that we don't forget about feature requests and suggestions. We are going through closed and active ones when considering new ones. We do have a pretty packed road map though.

regarding this, we probably will look deeper into it when we start tackling virtualization in general.
