### ISSUE TITLE
How to restrict or allow any selected protocols at the application level of the OSI model on Linux

### ISSUE THREAD

**Issue by Zesko** [safing/portmaster#1425]
### What would you like to add or change?:

We would like to edit any profile to restrict or allow any selected **protocol**  for example **HTTP, SMTP and SSH** ... at the **application** level of the TCP/IP model on Linux.

![image](https://github.com/safing/portmaster/assets/17826352/2dede385-9396-4a13-b41b-560d9a8a6b93)

### Why do you and others need this?:

Reason:

![Screenshot_20240121_120225](https://github.com/safing/portmaster/assets/17826352/39e71bc7-5f72-40ff-9a11-36b999ba7c7a)

I set "Prompt" in the profile "Thunderbird" that will notify me when any receiving email sites want to connect to any server. That is good. I like it.

**Issue**: When I write my email and send it, but sending fails because there is a matching domain name in my block list. I have to change "Prompt" to "Allow", then I change "Allow" back to "Prompt" after sending my email.  That is annoying.

My goal:

* I want to only allow **SMTP** in the profile  "Thunderbird", which shouldn't prompt / notify me when sending my email. It should not block sending my emails

* I want to block **HTTP** or **another random protocols** when receiving emails that want to connect to a random server.

**Comment by Raphty** [comment]
you can, already

![image](https://github.com/safing/portmaster/assets/11504285/39774895-b9f1-4bd5-ad94-b33782537458)
Note: the # is used to add a comment, the actual rule is just: `* TCP/587 `

also the idea is if you finished a cool profile pleas consider sharing it with the community here: https://github.com/portmaster-community/apps

**Comment by Raphty** [comment]
in Portmaster when you click on the i
![image](https://github.com/safing/portmaster/assets/11504285/b3ee1f9a-2d9d-4c04-8109-83068717d051)
and then show more
![image](https://github.com/safing/portmaster/assets/11504285/d5803551-a752-4aa9-b415-a961a57ad263)
