### ISSUE TITLE
IDS/IPS

### ISSUE THREAD

**Issue by celevra** [safing/portmaster#1434]
**What would you like to add or change?**:
Hi,

Would be awesome if something like suricata is integrated.

**Why do you and others need this?**:

Then not just the outgoing connection is peotected, also the incoming

Regards

**Comment by Raphty** [comment]
Hey @celevra thanks for the suggestion, there are plans in both directions but Portmaster as a b2c solution is not exactly suited to go deep into this. 

we have an Open collective "project" where you can vote with € to tell us to implement things like Port Scan Detection
https://opencollective.com/safing-portmaster/projects/port-scan-detection

But a b2b flavor of a software firewall is also planned, you can reach out via mail if you want more information.
ps.: the mail can also be in German, I saw in your profile you are in Germany so feel free to write in German
