### ISSUE TITLE
Custom filter list does not block mullvad browser from entering blocked websites.

### ISSUE THREAD

**Issue by Giger22** [safing/portmaster#1437]
- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Portmaster does not block Mullvad browser from entering blocked sites from custom filter list. This is probably because Mullvad on default uses it own DNS resolver.

**What did you expect to happen?**:
Portmaster blocks websites as usual. Could you change app so that block even if browser uses ts own DNS?

**How did you reproduce it?**:
Just add some websites to a custom filter list and try visit them in Mullvad browser, Firefox and Chrome.

**Comment by Raphty** [comment]
Portmaster does alert you of bypass attempts and you can always block any app from connecting to the internet

**Comment by Giger22** [comment]
No, I see no alerts. I am afraid if a browser uses it own DNS setup, custom filter list does not work. 
I noticed one more thing - some hosts are filtered and others are not. This happens only on Mullvad... For example pornhub.com is blocked but xvideos.com is not. I think you could fix it by translating domain names in custom filter list file to IP because when blocked I see normal domain name and when not I see only IP address.

**Comment by Raphty** [comment]
then they probably don't do their actual DNS but probably cache the answers for longer - the indication is that you see some domains but not all.

also Portmaster should let you know of a bypass attempt, but in the case of cashing for longer the later connection looks like a p2p connection (because it sort of is)

blocking based on IP won't happen automatic, it is not feasible in how the Internet works

**Comment by Giger22** [comment]
Yes, indeed I see p2p connection. So you can't fix it?

**Comment by Raphty** [comment]
there is nothing to fix. you can block p2p connections for the browser and it will force it to do the dns request again and then you see it.

**Comment by Raphty** [comment]
I did not look into the mullvad derivative of the tor/firefox browser, but you can maybe change the time it keeps the dns records

**Comment by Raphty** [comment]
![image](https://github.com/safing/portmaster/assets/11504285/21007e46-f260-4f59-88ea-098a9c26fbc2)
