### ISSUE TITLE
.exe exception for apps like Windows Sandbox

### ISSUE THREAD

**Issue by 70V07** [safing/portmaster#1440]
I noticed that it is possible to enable the internet connection within **Windows Sandbox** by inserting exceptions in Incoming Rules, however the problem is that the IPs change after a while, so it is not possible, I ask if you can add a function in the settings to allow requests access specific to an .exe file (or any other type of executable app)

*or any other solution for allow Windows Sandbox without compromise Portmaster and security*

**Comment by Raphty** [comment]
as mentioned in #1324 

> We are planning a VM mode where we handle the network traffic from VM software differently, but again that is planned, and as of now there are only some VM Software that work.
