### ISSUE TITLE
Feature request: Payload inspection and regex based blocking

### ISSUE THREAD

**Issue by Rokuem** [safing/portmaster#1441]
**What would you like to add or change?**:

Was wondering if it would be possible to inspect the payload of some network requests to have an idea of what is being sent, and then performing blocks if there is some sensitive information in the payload, like credit card number, etc.

**Why do you and others need this?**:

a lot of things are happening on the network all the time and sometimes it isn't clear if a process is "bad" or not, althought it might be very suspicious. It would be good to be able to inspect the payload to understand it better. As for the blocking part, you might still need something to have access to the internet, but maybe you don't trust it too much or you just don't want it to track you so you could set-up some regex rules to block requests with specific payloads for example.

I think we can do something like that with wireshark, but I'm not super familiar with it.

**Comment by Raphty** [comment]
hey @Rokuem thanks for the suggestion,

DPI has been requested several times already, the tldr answer is: we might do this in the future... but it is not a silver bullet, also how others do it has big security risks... so we would have to think how to do it properly

regarding regex, take a look into the information pop ups in Portmaster on how to write rules, I guess what you are looking for (in regards to regex) is already covered.
