### ISSUE TITLE
Lost IPV6 after resume from sleep

### ISSUE THREAD

**Issue by marcal** [safing/portmaster#1443]
### What happened?
Hello,
When I put my Windows (11 Pro)  in S3 state (suspent to ram), and after that I wake it up from sleep , I lose my IPV6 after about one minute.
I have the message 
Le système a détecté un conflit d’adresses pour l’adresse IP 2a02:2788:XXX:XX:XXXX:XXXX:XXXX:715f avec le système  d’adresse physique réseau 00-00-00-00-00-00. En conséquence les opérations réseau sur se système peuvent être interrompues.
On firefox (only) the plugin My.JDownloader has problems with the connexion (not on other browsers). If I can restart the portmastercore service imediately after the resume there is no problerm (with ipv6 and firefox).
Also access is faster when restarting service than without.

### What did you expect to happen?
All is fine without restarting the service

### How did you reproduce it?
Put the computer to S3 and resumle a few minutes later

### Additional information
I have a hyper-v bridge (and virtual machine running)
I create a task System &#43; Kernel power / 566
net stop powermaster core
Then on the ID 1 
start portmastercore 
and also 
C:\ProgramData\Safing\Portmaster\portmaster-start.exe notifier --data=C:\ProgramData\Safing\Portmaster
to solve the problem

**Debug-Info**: https://support.safing.io/privatebin/?78a94511df1ab53d#81F4MfUZpmmkseKE9aGZTTUF9pReGopjpQvpQqKmmAfm

**Comment by dhaavi** [comment]
Hey @marcal, thanks for the report.

I am starting to look into this.

I see there is some other network firewall active.
Do you maybe run "Dell NetWorker Data-Protection-Software"?
(I am looking for the software that registers in the firewall as "NSR".)

Also investigating this in https://github.com/safing/portmaster/issues/1448

**Comment by marcal** [comment]
Hello,
Thank you for your answer.

The only firewall I have is Simplewall but it is disabled (I can uninstall it to make a test if you want ).

Marc

**Comment by dhaavi** [comment]
No, Simplewall should be okay, and it has removed its driver from the network stack anyway, but this NSR thing is weird.

This NSR thing is running and active on your system. Maybe it came with the laptop and you are not aware of it. Do you have a DELL laptop?

**Comment by marcal** [comment]
Hello,
It is a desktop computer I made myself (motherboard Gigabyte).
At a moment I installed the realtek Dragon that I removed.
I have no other idea for a firewall. 
It says Microsoft Defender in the firewall.
(private and public)
![image](https://github.com/safing/portmaster/assets/3047877/542a435c-87f8-4f98-979f-44e100d15028)
