### ISSUE TITLE
Does Portmaster create IPv6 localhost?

### ISSUE THREAD

**Issue by Giger22** [safing/portmaster#1444]
**What happened**:
I have disabled IPv6 on my system and there is no IPv6 entry in /etc/hosts but there is still an IPv6 entry if I run a command host localhost. Does portmaster have anything to do with this issue?

**How did you reproduce it?**:
Disable IPv6, try to run coolercontrol from AUR. I can't run it until I enable IPv6 again.

**Comment by dhaavi** [comment]
Portmaster does not "create" IPv6.
If asked for the `AAAA` record of `localhost`, it will always respond with `::1`.

Make sure to restart Portmaster after disabling IPv6.
