### ISSUE TITLE
Is this intended?

### ISSUE THREAD

**Issue by NolonQ** [safing/portmaster#1451]
the number and the status text dont fit together, whats going on?

![Capture](https://github.com/safing/portmaster/assets/149939392/2dac729a-05d3-4c63-8845-e08ea5a4cfc2)

**Comment by Raphty** [comment]
what do you think does not fit?

the test states a goal and the progress shows the percentage towards that goal 😁 

Feedback on how to improve this is super welcome, we knew that it is not displayed the best, but we thought the message is as clear as it can be. We just talked about it yesterday because we wanted to push the information asap.

**Comment by NolonQ** [comment]
> what do you think does not fit?
> 
> the test states a goal and the progress shows the percentage towards that goal 😁
> 
> Feedback on how to improve this is super welcome, we knew that it is not displayed the best, but we thought the message is as clear as it can be. We just talked about it yesterday because we wanted to push the information asap.

In this case it looks like my brain is what needs improvement.
The last thing i remember is after the "the pc security channel" made a video about portmaster, safing hit 100% sustainability through community donations which is amazing!
But now the percentage is back to 39% that confused me, i thought that as you said the 100% peak might have dropped down to 39%.
Do i get you right, the 39% is the new updated progressbar where the goal is again 100%, this time to goal being anroid?
It would be incredibly if the portmaster came to android!! I have a degoogled custom rom but no firewall, yet.

I'm happy that i also purchased the portmaster for a month, i wanted do that since a long time since i'm using the portmaster for free this was the least i could do, i don't have much money and usualy never donate but you guys are the best!

**Comment by Raphty** [comment]
The Goal is: Hiring an Android Developer

You are correct we did have the bar for the current company size and how much % we need until we can sustain the company as it is. In the Blog Post that bar linked to I mentioned that when we surpass the 100% that we want to continue getting new people (as much as I would like a 3d printer 🤣 getting new people into Portmaster is important!) 

As soon as we hit the 100% we can afford to long term hire a full time android developer
There is a beta of Portmaster on android already, but there are a couple caveats to that: 

- it has not been worked on for a while
- we don't have anyone looking at it
- it only is spn at the moment

**Comment by Savamonova16** [comment]
![IMG_9120](https://github.com/user-attachments/assets/f934dec0-b93a-4336-b081-c119613b9c66)
![IMG_9119](https://github.com/user-attachments/assets/11215157-db1d-40d3-86b7-b7ea71a18fc0)
![IMG_9224](https://github.com/user-attachments/assets/1c83c032-c4ee-4467-86ed-e550330248c8)
![IMG_7999](https://github.com/user-attachments/assets/12ddfd6f-273b-4163-b058-05d9860b67b5)
![e16ba763-7717-45f0-9ec1-f8de94a2ffdd](https://github.com/user-attachments/assets/7184295d-3e8d-4ce5-9451-b9527bd53f15)
![86aa09db-37fa-433b-a2cb-9ec7047fd277](https://github.com/user-attachments/assets/6ec1a97d-3f74-4483-a768-b9812739a1c7)
![8f0c104c-91fb-4f2e-89fb-2e72cbf11788](https://github.com/user-attachments/assets/831d2753-f041-4e1a-a314-ad43eaab1280)

**Comment by Savamonova16** [comment]
Please tell your developer on SimpleX Chat called StanIslav Dmitrenko to stop being pedophile in Asia and stop manipulating and made fun of someone mental health I almost k!lled myself cause the trauma he caused me! Hes abuser and covert narcissist!!! IF HE DOESNT WANT TO MAKE A VIDEO OF GENUINE APOLOGIES TO ME I WILL POST HIM ON TIKTOK AND SOCIETY WILL CANCEL THIS APPLICATION AND THEY WILL REPORT SIMPLEX ON APPSTORE OR PLAYSTORE AND THEY WILL DOWN THE RATE! STANISLAV DMITRENKO NEED TO BE CANCELED!

**Comment by jcfyre** [comment]
That would be SUPER COOL to have Portmaster on Android. Even if it had to filter using an offline local VPN like how TrackerControl and DuckDuckGo's app tracking protection work. Going beyond, maybe even an option in the settings for rooted phones to work directly instead of a VPN when available.
