### ISSUE TITLE
Add a pause option.

### ISSUE THREAD

**Issue by DZogratis** [safing/portmaster#1455]
**What would you like to add or change?**:

Option to pause Portmaster.

**Why do you and others need this?**:

Sometimes we might need to access certain websites that we blacklisted. Now the only way to do that is to ShutDown Portmaster. So a pause feature will really come in handy!

**Comment by Blackfire-dev** [comment]
+1
This would also come in handy for diagnosing a possible connection problem.

**Comment by ewebgh33** [comment]
I came here to submit this exact things. It's incredible PM doesn't have this option.
Example: I block all Adobe communications, but every now and then I need to authenticate. Currently the only way to do this is to shut down the app, authenticate, then reboot the app once my Adobe app is working again. All I really want to do is open the UI, hit pause, sign in to Adobe, and unpause.

Multiply this out by all the apps that need cloud authentication? Yeah it's a PITA.
Selectively block/unblock? I'm not taking the chance that the apps change what IPs or ports they're gathering data on and leaving myself open. I don't wany ANY telemetry - just a quick pause, sign in etc

**WOULD BE EVEN BETTER IF
I could pause by App. Want to sign in to Potatoshop? Quickly pause portmaster blocking Creative Cloud, but all other apps are still blocked from telemetry.**

**Comment by Raphty** [comment]
@ewebgh33 what you can do is add a rule `allow *`  in the specific app, then do the update and then delete the rule again.

**Comment by ewebgh33** [comment]
> @ewebgh33 what you can do is add a rule `allow *` in the specific app, then do the update and then delete the rule again.

With respect, I _can_ do that, but that's many more clicks and work that has to be repeated, repeated, repeated, for different apps at different times. Better would be PAUSE APP BLOCKING button when you click on the specific app in PM. Keep all other rules for all other apps running, but hit ONE button, pause/unpause to allow us to authenticate, without having to create a rule, delete a rule, 12 times a year x 2 apps, or 3 apps, or 5 apps, or maybe 10 apps (the way everything is going with cloud sign-ins).

**Comment by Orevin** [comment]
I would like to see a Pause option as well, for the same reasons already mentioned

**Comment by ewebgh33** [comment]
Inactive? The hell?
Come on team many people are asking for this

**Comment by CCS86** [comment]
We need a pause button!

Having a quick way to diagnose whether the firewall is causing a connectivity issue is crucial.

**Comment by tukykarmakar** [comment]
Just came here to say that I'd like to have this feature too. It's easier to pause so that I can test/troubleshoot my connections, instead of turning off completely and then restarting Portmaster.

It'd have saved me so much time when I had to troubleshoot my Wiz lights, the apps that I'm building, my printer's wireless connections, and my Mobile Hotspot on Windows. Seriously, why is Portmaster blocking the connections from my phone by default when I'm trying to connect to internet using my PC's hotspot??

**Comment by DZogratis** [comment]
bump

**Comment by griesi007** [comment]
+1

**Comment by ewebgh33** [comment]
Reopen please

**Comment by DZogratis** [comment]
> Reopen please

I cannot, they marked it as Not Planned
