### ISSUE TITLE
Allow whitelist approach per app on Windows 11 Pro

### ISSUE THREAD

**Issue by griesi007** [safing/portmaster#1459]
So far as I am aware of it is not possible to effectively realize a whitelist approach per app/process. This is what I am used from GlassWire and which is extremly useful. What I need to do is:
- Block all applications processes from Internet Access by default and promt to allow access. Prompt should show process name. Promt should allow th whitelist all connections from a app/process not only a per connection allowance
- of course this should also work when user is logged on with a regular windows user withoud admih privileges
-

**Comment by Raphty** [comment]
There is not a prompt option, but via the UI this is super easy.


Set global default to block an then allow each app individually.
![image](https://github.com/safing/portmaster/assets/11504285/8bac7e2e-5b6b-4eac-b3f3-5cd74ed73f18)
![image](https://github.com/safing/portmaster/assets/11504285/ac5449d3-187b-4417-a22b-89e84be70255)

**Comment by griesi007** [comment]
@Raphty I do not agree. It is to complicated to have to go to the UI anytime. Portmaster should notify the user if a unknown  connection is requested and the user has not yet decided whether it should be allowed or not. This is what I expect when "Prompt" is configured . Ideally the notification should allow to directly allow the specific connection or all connections for the app

**Comment by Raphty** [comment]
I don't know how often you install new software, but for most people this is an easy setup, they do once.

If you want to participate and contribute the required code so Portmatser has the feature the way you would like pleas get in touch, we are open source 👍🏻

**Comment by griesi007** [comment]
@Raphty it´s not only about installing new software but software is constantly updated. it depends on the internals how portmaster identifies an app. if an update is regarded as a new app this will happen often.

**Comment by griesi007** [comment]
@Raphty it´s also about indirect dependencies that want to connect. Just imagine all the exe files of windows. If privacy is set to prompt, each windows exe requires allowance. It´s impossible to do this upfront, it´s cumbersome if you do not get notified

**Comment by griesi007** [comment]
@Raphty could this please be considered as a valid requirement? Please reopen in case
