### ISSUE TITLE
Feature Request: Terminate an Application

### ISSUE THREAD

**Issue by Blackfire-dev** [safing/portmaster#1466]
**What would you like to add or change?**:
The Ability to terminate an application/process

My previous firewall, was setup to block all incoming and outgoing connections from Edge/IE. It would also then terminate the process each time it tried to restart.

**Why do you and others need this?**:
Some applications maybe needed to be installed for niche cases such NVR, CCTVs etc, However, while they can be configured to access the lan only I do not wish for these applications to be constantly restarting themselves with each windows update. Most firewalls provide the feature to terminate applications on a process level and I think this would be nice to see that added to Portmaster.

This would also work really well with #1455 (Add pause button)

**Comment by Raphty** [comment]
This is a feature we have been thinking about as well, it wont happen soon, but it will probably come in the future.

**Comment by Blackfire-dev** [comment]
Bump to prevent closing.

**Comment by Blackfire-dev** [comment]
Bump to reopen.
Still requested
