### ISSUE TITLE
Portmaster won't let our TV see the DLNA Server (Windows Media Player)

### ISSUE THREAD

**Issue by mpek** [safing/portmaster#1467]
Portmaster won't let our TV see the DLNA Server (Windows Media Player)

As you may know, Windows has its streaming media capabilities and we use it to stream videos to our TV. 

The service of that background streaming server seems to be not appearing in Portmaster. 

It works when Portmaster is not active. 

Portmaster Standard Installation with these changes: 

Force Block Incoming Connections: ON
Incoming Rules: Allow LAN

Not visible.

Then added the ip address of that tv to Outgoing Rules and Incoming Rules be Allowed. 

But still not visible.

Every time something was changed, tv was rebooted.

The DLNA server starts with booting Windows 11, but it seems as it is not being recognized by Portmaster, because it's not being shown in Apps list. 
What Portmaster is not recognizing cannot be allowed in it, right? Is this a bug or can I change some setting to get this working?

**Comment by mpek** [comment]
I don't use discord and wiki does not help regarding this issue.

**Comment by Raphty** [comment]
https://wiki.safing.io/en/FAQ/AllowIncomingConnections

**Comment by mpek** [comment]
Okay, have read it and changed to this: 

Force Block Internet Access OFF
Force Block LAN OFF
Force Block Device-Local Connections OFF
Force Block P2P/Direct Connections OFF
Force Block Incoming Connections OFF
Outgoing Rules NONE
Incoming Rules: 
1. Allow LAN
2. Block *
Deleted Rule with the specific IP from that TV

The TV is connected to the same Router and the same LAN. 

The DLNA source is still not visible on that TV. 

I guess the service for this is called WMPNetworkSvc but it is not visible inside Portmaster. 

Still no luck. Any idea?

**Comment by Raphty** [comment]
Portmaster only shows services that are doing actual connections in the network

did you look into the linked yt video in the wiki page? I went through a process where you allow everything, find the connection and then only allow that.

**Comment by mpek** [comment]
Yes, looked all four yt videos yesterday, before opening this issue. How do you allow everything to see the dlna connection to be allowed (always)?

With all setings set above and 
Default Network Action is Allow
This seems to not allow everything, what's the allow everything setting while Portmaster is running?

**Comment by Raphty** [comment]
not the intro, in the wiki page on the top there is a linked video, that works thorugh the setup of remote desktop for windows.
It is not the same app, but the method still works

**Comment by mpek** [comment]
Thank you, that video was helpful and I could tell Portmaster to allow TV's ip address. 
 
Basically that video shows how to filter by ip address and apps accessed by that ip address and shows you how to override global settings by switching _twice_ "Force Block Incoming Connections" in that App settings. 

This video should be Intro video #5: "How to allow incoming connections by unvisible apps"
or "How to filter ip addresses and grouped by app"

Working settings are: 
Force Block Incoming Connections OFF
Outgoing Rules NONE
Incoming Rules:
Allow LAN
Block *

This topic is solved and I will continue trying Portmaster, today is second day.
