### ISSUE TITLE
Add 'Back' button

### ISSUE THREAD

**Issue by NormPlum** [safing/portmaster#1484]
**What would you like to add or change?**:
It'd be nice to have a 'Back' button in the UI to go back to the page you were on previously.

**Why do you and others need this?**:
On the Network Activity page, I group connections by app. As an example, if I'm looking at a particular app (it's expanded) and I click on a connection to view it, then click App Setting, I go to that app's settings page. I'd then like to go back to the list I was looking at before with everything expanded as it was. But all I can do is click on the Network Activity button again, and everything gets reset.

A back button (that restores the state things were in when I left) would be useful here.

**Comment by Raphty** [comment]
We are restructuring our co debase into a mono-repo where all Portmaster components will live happily together.
This issue has been moved due to this restructure.
