### ISSUE TITLE
Left click on the tray icon should open the app directly

### ISSUE THREAD

**Issue by arshcaria** [safing/portmaster#1489]
**What would you like to add or change?**:

Left click on the tray icon should open the app directly. 

**Why do you and others need this?**:

Currently left and right click perform the same action which is opening the menu. Open the app directly with left click (or left double click) could improve UX by shorting the path and removing redundant duplicate behaviors.

**Comment by Raphty** [comment]
thank you for the suggestion, we have seen this particular one in the past. 

The future of the notifier app is currently beeing evaluated, and it might get some bigger changes this year.
