### ISSUE TITLE
Ability to export all global and app-specific settings

### ISSUE THREAD

**Issue by NormPlum** [safing/portmaster#1492]
**What would you like to add or change?**:

An option in the UI to export *all* settings to a plain text file. Ideally this'd be all settings together (global and app-specific), but alternatively it could separate global and app-specific settings into separate files.

Currently, settings can be exported via the UI, but this requires you to:
1. Specifically choose which settings to export (manually ticking all necessary boxes)
2. Export global settings separately from app-specific settings
3. Export app-specific settings for each app *individually*

Global settings are stored in `.../safing/portmaster/config.json` (https://wiki.safing.io/en/FAQ/ResetPortmasterSettings). This is nice and readable, but app-specific settings are stored in `.../safing/portmaster/databases/core/bbolt/db.bbolt`. This is not readable (at least not easily).

**Why do you and others need this?**:

There is currently no way to see all custom settings in one place. And not even a way to see all app-specific settings.

Personally, I'm concerned that I've allowed/denied an app or domain temporarily when trying to get something working, and then forgotten to remove/revert that setting again. Seeing all custom settings in a single list would allow me to scan through and make sure everything is as expected, or know easily what to change. This avoids needing to go through each app in the UI manually to check for issues.

**Comment by aequis** [comment]
I have the same need. I'd like to be able to migrate all my settings between systems and keep a default template so I don't have to reconfigure every single application on my system by hand.

**Comment by rosenand** [comment]
> Personally, I'm concerned that I've allowed/denied an app or domain temporarily when trying to get something working, and then forgotten to remove/revert that setting again. Seeing all custom settings in a single list would allow me to scan through and make sure everything is as expected, or know easily what to change. This avoids needing to go through each app in the UI manually to check for issues.

This! Plus, I'd like to at least take a screenshot of my settings, so that I can save it for reference, and save time (and sanity) next time I'm setting up my system. Currently I would need to do it right away after adding the custom rule, otherwise, as has been mentioned, it's difficult to find all the custom rules I've made.

**Comment by ToUsernameMy** [comment]
Also don't think this is a specific use case. Especially as portmaster gets older, many people will switch PCs at some point and like to avoid painstakingly ex- and importing every app's settings.

**Comment by Aquind** [comment]
This is a basic very important feature to export settings for use on a different computer or new install if ever a computer needs to be reset or software reinstalled.  Very important.

For those needing to backup or export/import settings as a whole, see an old post:
https://github.com/safing/portmaster/issues/388

Apparently the developers back then thought it would be a good idea to be able to export settings individually but not all. ::dizzy confused face::  Thankfully there is a workaround manually.
