### ISSUE TITLE
Allow to configure which desktop-notifications should be shown

### ISSUE THREAD

**Issue by DarthAffe** [safing/portmaster#1499]
**What would you like to add or change?**:
It would be great to be able to configure which type of desktop-notifications should be shown.   
For example I want to see the access-request notifications, but I don't care about the "Configured DNS Servers Failing"-notification

**Why do you and others need this?**:
For whatever reason Portmaster believes regularly that my DNS is not available (which is not the case, everything works perfectly fine even when this message is shown and the tray-icon dot is red) which causes the "Configured DNS Servers Failing"-notification to be shown. Since there aren't any issues in that case it's quite annoying to get that all the time and it would be great, if I could just disable that one notification.

**Comment by Raphty** [comment]
Hey @DarthAffe, welcome in our community.

How did you verify, that the DNS is working besides your connection still working. because Portmaster can fallback to other resolvers automatically if the dns if failing, and the issue you are describing is not something we get a lot of complaints about.

In normal operations without issues Portmaster does basically never send notifications. So this setting would not be a priority.

**Comment by DarthAffe** [comment]
Hey, thanks for the quick reply.
First of all my understanding of the fallback mechanism was, that it falls back to the system-dns if the one configured in portmaster fails - these are the same in my case (it's the one from my opensense).

But I looked at the Core-Logs and it contains a bunch of entries like this:
```
240408 20:16:43.420 er/resolve:460 > WARN 346 resolver: query to dns://192.168.10.1:53#config failed: dial udp :50211->192.168.10.1:53: bind: Der Zugriff auf einen Socket war aufgrund der Zugriffsrechte des Sockets unzulässig.
```
or this
``` 
240408 22:12:24.452 work/ports:049 > WARN 741 network: took 11 attempts to find a suitable unused port for pre-auth
```

Searching this error leads to a lot of issues similar to this in different programs that seem to be related to the use of Hyper-V which would make sense since I'm using WSL.
For example this issue:
https://github.com/docker/for-win/issues/3171

To me this could explain this behavior (at least without knowledge about the portmaster internals) and it would also explain why it is not consistant (like it was really bad the last few days, especially yesterday when I decided to open the issue, but it didn't show up once since the last boot 4 hours ago - but I had no VM running so far)

For now I'll continue observing this and collect the debug info as soon as the problem occurs again.

**Comment by Raphty** [comment]
we are aware that WSL creates issues, we weren't aware of those though, thanks for letting us know. Keep in mind that any kind of VM is currently OOS for us. #166 

help is always appreciated.

**Comment by e-t-l** [comment]
FYI, I also get "configured DNS server failing" notifications because I use DNScrypt-proxy, and presumably a DNS request takes a *little* too long sometimes and it times out (I mentioned an enhancement to help with this in #1373 but no one replied and the issue was closed by a bot). 

This is all to say that I too would appreciate more granular desktop notification controls.

**Comment by Raphty** [comment]
I am curios @mherrmann3 when you see the notification that DNS crypt proxy is blocked... why do you keep it? or why don't you take action? AFAIK the only purpose of that app is encrypted dns which Portmaster tells you it blocked.

The DNS Cash you can disable the notification by enabling and disabling the cash setting (if I am not mistaken we only check if the setting has been modified not which state it is in, so any modification should remove the notification)

**Comment by mherrmann3** [comment]
Well, it seems that it is actually not blocked (or at least not that I know of), as can be confirmed with a DNS leak test: it reports the DNS servers I specified in dnscrypt-proxy. I now disabled _"Block Secure DNS Bypassing"_ for dnscrypt-proxy. Is this what you meant?

Thanks, I switched the setting _"Always Use DNS Cache"_ on and off. I will observe if the related notification comes up again.
