### ISSUE TITLE
Add short build instructions

### ISSUE THREAD

**Issue by MathijsNL** [safing/portmaster#150]
**What would you like to be added**:
I would like some simple build instructions added. Go is not a familiar language for lots of people.

**Why is this needed**:
Because for a tool like this I think people would like to be able to build it from source. Make that easy for us as well!

**Comment by dhaavi** [comment]
We will look into improving documentation about building Portmaster from scratch. This will then most probably then depend on a docker image, as there are many assets that need to be built using different technologies.

Depending on your platform this may not be that easy. On Windows, for example, you'll need an EV Code Signing Cert to sign the kernel extension.

**Comment by MathijsNL** [comment]
Thanks for your reply. That sounds like a fair approach. You probably have more important things to do right now, but once the docker image is available I will definitely go and take a look!

**Comment by kemelzaidan** [comment]
I second the request for building instructions, specially on Linux. Portmaster will not make into any Linux official distro repositories if there is no way to build it from source.
