### ISSUE TITLE
Add detail for obscure services/processes, and maintain log of prompts which have defaulted to block

### ISSUE THREAD

**Issue by sunnyd24** [safing/portmaster#1508]
**What would you like to add or change?**:

As a new user I have found the following limitations of usability on Windows:

_**1. Add detail for obscure services such as "CDP User Svc", "Wlidsvc", "Do Svc", etc......**_
_**2. Maintain history log of prompts which have defaulted to block due to timeout.**_

**Why do you and others need this?**:

1. **Add detail for obscure services such as "CDP User Svc", "Wlidsvc", "Do Svc", etc......**

         - There are many running processes and services on Windows 11, most are not easy to identify through names and require google searches. It would be good to give friendly names or show additional info by adding a info icon next to service/process title.
         - It would be nice if there was a database of common windows services and processes, as well as a database from other processes.

2. **Maintain history log of prompts which have defaulted to block due to timeout:**

         - It is hard to know if a process or service has tried to prompt and timeout has occurred due to being away from the computer.
         - The only way around this is to see visit each process/service in turn, filter on Allowed to "no" and check blocked connections list.

Edited to remove first one from list, thanks @Raphty, Ctrl + Click works great. If only I knew, so may just need documenting better or add shortcut to quick start tour for new users.

**Comment by Raphty** [comment]
Hey there @sunnyd24 thanks for the suggestion.

regarding point 1, you can hit 'ctrl' and everything that is underlined you can copy with a click.
so ctrl + click

regarding 2 and 3, thank you for sharing your thoughts we will take them into consideration as we progress the development of Portmaster, if you or someone else here want to add to these ideas pleas do.

**Comment by sunnyd24** [comment]
Any of the 2 points taken forward into the development or planned to be?
