### ISSUE TITLE
Verify before connecting to DNS servers on private IP ranges

### ISSUE THREAD

**Issue by soleofthesea** [safing/portmaster#1515]
This might be esoteric, but I was wondering if it would be possible to add a feature to the DNS resolver that, if  the server IP is a private one (the ones beginning with 172.16.X.X, 10.X.X.X, and 192.168.X.X), it checks whether the machine has an IP assigned in the same range before trying to connect to it?

I'd like my laptop to not be leaking what subnet I'm using in my home when I take it outside. (Yes, I'm aware the danger this posts to network security is next to nil. But it just... feels wrong to not take every precaution. :P)

**Comment by Raphty** [comment]
I understand your request, we would be tackling this different though, and sadly not in the near future. We have plans for Portmaster "Environments" where you can create multiple "setups" that change based the setting.
So you could have a "home" environment and a remote one.

Also, do you actually need your router as DNS? why don't you activate: "Ignore System/Network Servers"

**Comment by soleofthesea** [comment]
Well, it would defeat the point of having set up Pi-Hole and Unbound, so yes...

Still though, that environment idea seems a pretty good solution.
