### ISSUE TITLE
Windows version handeling with WINGET

### ISSUE THREAD

**Issue by Jank8** [safing/portmaster#1522]
**What happened**:
When using WINGET to install and upgrade, winget checks windows installed program list, there is 1.0.13.0, winget finds latest version on github BUT after installing version on windows installed programs list ramains the same.

**What did you expect to happen?**:
Upgrade and update version on windows installed program list.

**How did you reproduce it?**:
Install via "winget install safing.portmaster"
then use "winget upgrade --all"

**Comment by Raphty** [comment]
The thing you download via winget is just the installer and it then continues downloading the current version.
the version displayed is correct.

we are in the process of making each version available as a full install, this will probably also fix your issue with winget, but the way it is displayed there is correct and the version only changes when we update the installer.
if you looked into Portmaster code a bit you will find a lot of things in there have different versions...
