### ISSUE TITLE
nameserver: failed to resolve then freezes

### ISSUE THREAD

**Issue by PetrusVermaak** [safing/portmaster#1523]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Wondows 11, with all updates installed, running Portmaster version: 1.6.5

Portmaster starts reporting nameserver: failed to resolve errors, then app freezes. Starts blocking all sites and have to restart app. Happens frequently

**What did you expect to happen?**:
Portmaster app should not freeze and block all websites such as google.com etc.

**How did you reproduce it?**:
After start/restart it occurs randomly, sometimes as soon as 5 min after restart.

**Debug Information**:

Paste debug information below:
- General issue: Click on "Copy Debug Information" on the Settings page.
714370100,"Modified":1714370100,"Expires":1716962100,"Deleted":0}S
executing core/portmaster-core.exe version 1.6.5 on windows amd64
240429 07:55:01.283 > BOF
240429 07:55:01.474 xt/service:035 > WARN 001 kext: old driver service was found
240429 07:55:04.287 olver-mdns:114 > WARN 003 intel(mdns): failed to create udp6 listen multicast socket: listen udp6 [ff02::fb]:5353: setsockopt: not supported by windows
240429 07:57:04.293 er/metrics:075 > WARN 005 resolver: suggesting user to use stale dns cache with avg query time of 182ms for config and system resolvers
240429 08:00:09.081 er/resolve:460 > WARN 007 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:56426->192.168.10.1:53: i/o timeout
240429 08:00:09.081 nameserver:293 > WARN 009 nameserver: failed to resolve 228.246.40.124.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:56426->192.168.10.1:53: i/o timeout
240429 08:03:42.032 er/resolve:460 > WARN 011 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:58377->192.168.10.1:53: i/o timeout
240429 08:03:42.032 nameserver:293 > WARN 013 nameserver: failed to resolve 130.60.62.202.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:58377->192.168.10.1:53: i/o timeout
240429 08:03:44.038 er/resolve:460 > WARN 015 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:27622->192.168.10.1:53: i/o timeout
240429 08:03:44.038 nameserver:293 > WARN 017 nameserver: failed to resolve 130.60.62.202.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:27622->192.168.10.1:53: i/o timeout
240429 08:05:55.299 er/resolve:460 > WARN 019 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:23867->192.168.10.1:53: i/o timeout
240429 08:05:55.299 nameserver:293 > WARN 021 nameserver: failed to resolve 23.23.69.219.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:23867->192.168.10.1:53: i/o timeout
240429 08:05:57.308 er/resolve:460 > WARN 023 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:17071->192.168.10.1:53: i/o timeout
240429 08:05:57.308 er/resolve:460 > WARN 025 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:55978->192.168.10.1:53: i/o timeout
240429 08:05:57.308 nameserver:293 > WARN 027 nameserver: failed to resolve 23.23.69.219.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:17071->192.168.10.1:53: i/o timeout
240429 08:05:57.308 nameserver:293 > WARN 029 nameserver: failed to resolve 23.23.69.219.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:55978->192.168.10.1:53: i/o timeout
240429 08:09:46.223 er/resolve:460 > WARN 031 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:23669->192.168.10.1:53: i/o timeout
240429 08:09:46.223 nameserver:293 > WARN 033 nameserver: failed to resolve 131.217.207.49.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:23669->192.168.10.1:53: i/o timeout
240429 08:11:04.354 er/metrics:075 > WARN 035 resolver: suggesting user to use stale dns cache with avg query time of 159ms for config and system resolvers
240429 08:11:33.500 er/resolve:460 > WARN 037 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:25670->192.168.10.1:53: i/o timeout
240429 08:12:18.411 er/resolve:460 > WARN 039 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:59682->192.168.10.1:53: i/o timeout
240429 08:12:18.411 nameserver:293 > WARN 041 nameserver: failed to resolve 224.61.177.93.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:59682->192.168.10.1:53: i/o timeout
240429 08:13:30.718 er/resolve:460 > WARN 043 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:35789->192.168.10.1:53: i/o timeout
240429 08:13:30.718 nameserver:293 > WARN 045 nameserver: failed to resolve 214.192.242.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:35789->192.168.10.1:53: i/o timeout
240429 08:13:32.729 er/resolve:460 > WARN 047 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:50130->192.168.10.1:53: i/o timeout
240429 08:13:32.729 er/resolve:460 > WARN 049 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:52178->192.168.10.1:53: i/o timeout
240429 08:13:32.729 nameserver:293 > WARN 051 nameserver: failed to resolve 214.192.242.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:50130->192.168.10.1:53: i/o timeout
240429 08:13:32.729 nameserver:293 > WARN 053 nameserver: failed to resolve 214.192.242.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:52178->192.168.10.1:53: i/o timeout
240429 08:14:14.738 er/resolve:460 > WARN 055 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:39543->192.168.10.1:53: i/o timeout
240429 08:14:14.738 nameserver:293 > WARN 057 nameserver: failed to resolve 10.47.79.182.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:39543->192.168.10.1:53: i/o timeout
240429 08:16:10.798 er/resolve:460 > WARN 059 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:19777->192.168.10.1:53: i/o timeout
240429 08:16:10.798 nameserver:293 > WARN 061 nameserver: failed to resolve 59.117.180.106.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:19777->192.168.10.1:53: i/o timeout
240429 08:16:32.658 er/resolve:460 > WARN 063 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:60293->192.168.10.1:53: i/o timeout
240429 08:16:32.658 nameserver:293 > WARN 065 nameserver: failed to resolve 239.172.138.45.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:60293->192.168.10.1:53: i/o timeout
240429 08:18:34.883 er/resolve:460 > WARN 067 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:43381->192.168.10.1:53: i/o timeout
240429 08:18:34.883 nameserver:293 > WARN 069 nameserver: failed to resolve 8.251.54.110.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:43381->192.168.10.1:53: i/o timeout
240429 08:18:36.890 er/resolve:460 > WARN 071 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:41503->192.168.10.1:53: i/o timeout
240429 08:18:36.890 er/resolve:460 > WARN 073 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:55018->192.168.10.1:53: i/o timeout
240429 08:18:36.890 nameserver:293 > WARN 075 nameserver: failed to resolve 8.251.54.110.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:55018->192.168.10.1:53: i/o timeout
240429 08:18:36.890 nameserver:293 > WARN 077 nameserver: failed to resolve 8.251.54.110.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:41503->192.168.10.1:53: i/o timeout
240429 08:19:16.415 er/resolve:460 > WARN 079 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:58339->192.168.10.1:53: i/o timeout
240429 08:19:16.415 er/resolve:316 > WARN 081 resolver: async query for 92.162.179.221.in-addr.arpa.PTR failed: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:58339->192.168.10.1:53: i/o timeout
240429 08:22:08.205 er/resolve:460 > WARN 083 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:55519->192.168.10.1:53: i/o timeout
240429 08:22:08.205 nameserver:293 > WARN 085 nameserver: failed to resolve 240.116.7.222.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:55519->192.168.10.1:53: i/o timeout
240429 08:22:48.817 er/resolve:460 > WARN 087 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:31224->192.168.10.1:53: i/o timeout
240429 08:22:48.817 nameserver:293 > WARN 089 nameserver: failed to resolve 62.37.249.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:31224->192.168.10.1:53: i/o timeout
240429 08:22:50.821 er/resolve:460 > WARN 091 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:32672->192.168.10.1:53: i/o timeout
240429 08:22:50.821 er/resolve:460 > WARN 093 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:45044->192.168.10.1:53: i/o timeout
240429 08:22:50.821 nameserver:293 > WARN 095 nameserver: failed to resolve 62.37.249.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:32672->192.168.10.1:53: i/o timeout
240429 08:22:50.821 nameserver:293 > WARN 097 nameserver: failed to resolve 62.37.249.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:45044->192.168.10.1:53: i/o timeout
240429 08:27:04.406 er/metrics:075 > WARN 099 resolver: suggesting user to use stale dns cache with avg query time of 116ms for config and system resolvers
240429 08:28:41.072 er/resolve:460 > WARN 101 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:46912->192.168.10.1:53: i/o timeout
240429 08:28:41.072 nameserver:293 > WARN 103 nameserver: failed to resolve 89.149.37.115.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:46912->192.168.10.1:53: i/o timeout
240429 08:32:34.364 er/resolve:460 > WARN 105 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:46878->192.168.10.1:53: i/o timeout
240429 08:32:34.364 nameserver:293 > WARN 107 nameserver: failed to resolve 14.99.59.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:46878->192.168.10.1:53: i/o timeout
240429 08:33:27.538 er/resolve:460 > WARN 109 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:35372->192.168.10.1:53: i/o timeout
240429 08:33:27.538 nameserver:293 > WARN 111 nameserver: failed to resolve 26.226.159.98.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:35372->192.168.10.1:53: i/o timeout
240429 08:33:29.548 er/resolve:460 > WARN 113 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:28901->192.168.10.1:53: i/o timeout
240429 08:33:29.548 er/resolve:460 > WARN 115 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:19951->192.168.10.1:53: i/o timeout
240429 08:33:29.548 nameserver:293 > WARN 117 nameserver: failed to resolve 26.226.159.98.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:28901->192.168.10.1:53: i/o timeout
240429 08:33:29.548 nameserver:293 > WARN 119 nameserver: failed to resolve 26.226.159.98.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:19951->192.168.10.1:53: i/o timeout
240429 08:36:37.176 er/resolve:460 > WARN 121 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:64948->192.168.10.1:53: i/o timeout
240429 08:36:46.735 er/resolve:460 > WARN 123 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:15269->192.168.10.1:53: i/o timeout
240429 08:36:46.735 nameserver:293 > WARN 125 nameserver: failed to resolve 237.210.195.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:15269->192.168.10.1:53: i/o timeout
240429 08:36:48.748 er/resolve:460 > WARN 127 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:63043->192.168.10.1:53: i/o timeout
240429 08:36:48.748 nameserver:293 > WARN 129 nameserver: failed to resolve 237.210.195.180.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:63043->192.168.10.1:53: i/o timeout
240429 08:37:18.410 er/resolve:460 > WARN 131 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:34753->192.168.10.1:53: i/o timeout
240429 08:37:18.410 nameserver:293 > WARN 133 nameserver: failed to resolve 23.23.69.219.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:34753->192.168.10.1:53: i/o timeout
240429 08:37:20.423 er/resolve:460 > WARN 135 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:42724->192.168.10.1:53: i/o timeout
240429 08:37:20.423 er/resolve:460 > WARN 137 resolver: query to dns://192.168.10.1:53#system failed: read udp 192.168.10.113:43712->192.168.10.1:53: i/o timeout
240429 08:37:20.423 nameserver:293 > WARN 139 nameserver: failed to resolve 23.23.69.219.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:42724->192.168.10.1:53: i/o timeout
240429 08:37:20.423 nameserver:293 > WARN 141 nameserver: failed to resolve 23.23.69.219.in-addr.arpa.PTR: all 1 query-compliant resolvers failed, last error: read udp 192.168.10.113:43712->192.168.10.1:53: i/o timeout

- App related issue: Click on "Copy Debug Information" in the dropdown menu of an app in the Monitor view.

⚠ Please remove sensitive/private information from the "Unexpected Logs" and "Network Connections" sections.
This is easiest to do in the preview mode.

Additional logs can be found here:
- Linux: `/opt/safing/portmaster/logs`
- Windows: `%PROGRAMDATA%\Safing\Portmaster\logs`

[portmaster logs.zip](https://github.com/safing/portmaster/files/15145923/portmaster.logs.zip)

**Comment by Raphty** [comment]
hey @PetrusVermaak please provide the debug info not in a zip. I won't open that.
either post it directly or as .txt

for what I saw with the limited information in the post itself I guess it is a compatibility issue with some other software you got installed

**Comment by PetrusVermaak** [comment]
> hey @PetrusVermaak please provide the debug info not in a zip. I won't open that. either post it directly or as .txt
> 
> for what I saw with the limited information in the post itself I guess it is a compatibility issue with some other software you got installed
App
[2024-03-30-10-29-53.error.log](https://github.com/safing/portmaster/files/15146940/2024-03-30-10-29-53.error.log)

Core:
[2024-04-29-08-51-36.error.log](https://github.com/safing/portmaster/files/15146942/2024-04-29-08-51-36.error.log)
[2024-04-29-08-51-36.log](https://github.com/safing/portmaster/files/15146946/2024-04-29-08-51-36.log)

Notifier:
[2024-04-29-08-51-30.error.log](https://github.com/safing/portmaster/files/15146951/2024-04-29-08-51-30.error.log)
[2024-04-29-08-51-30.log](https://github.com/safing/portmaster/files/15146959/2024-04-29-08-51-30.log)

Start:
[2024-04-29-08-51-36.log](https://github.com/safing/portmaster/files/15146966/2024-04-29-08-51-36.log)


Not sure how it can be incompatability as I did not originally have these issues.

**Comment by Raphty** [comment]
can you provide the debug info please 
it is the first thing in the wiki page https://wiki.safing.io/en/FAQ/DebugInfo
![image](https://github.com/safing/portmaster/assets/11504285/881617cb-a127-4d58-be03-2f9627d7c763)

**Comment by PetrusVermaak** [comment]
I appreciate you taking a look, here's the debug info in txt as too big to paste:
[debug info.txt](https://github.com/safing/portmaster/files/15147728/debug.info.txt)

**Comment by Raphty** [comment]
@PetrusVermaak you have tons of Bitdefender lines in there, I guess BD is the issue, also you don't have a DNS server configured in PM

You should look into making BD work with Portamster, there have been people who are running them next to each other, but you have to disable some things in BD.

I have not done this, so I con only tell you that this is the cause but not how to fix it.

Also we recommend sticking with MS Defender, 3rd party AV is only of questionable usefulness especially for the price, and increased attack surface they come with.

**Comment by PetrusVermaak** [comment]
@Raphty Thank you so much! You helped me solve a very hairy problem! All I did was add the Portmaster installed location folder on BitDefender's exclude list, and excluded all its services. No more freezes and everything is running smoothly.
