### ISSUE TITLE
Allowed/Blocked IP List conditional on Network

### ISSUE THREAD

**Issue by dazu89** [safing/portmaster#1535]
**What would you like to add or change?**:

Currently, at least to my knowledge, the allow/block lists per app apply to all networks. The list should be configurable per network, e.g. one for a home network another one for a work environment etc. The current one-list-for-all approach is undesired, as the user may want to treat an IP range differently depending on the network they are on.

**Comment by Raphty** [comment]
hey @dazu89 thanks for the suggestion, we do have a more broader idea for what you are thinking about, where you can actually change multiple settings in Portmaster based on context, this will not happen soon, we are currently working on restructuring the underlying structure of Portmaster to make such changes in the future easier.
