### ISSUE TITLE
De-selecting a child list within the Filter Lists indicates the entire branch is not enabled (Or is it?)

### ISSUE THREAD

**Issue by ChicagoGregg** [safing/portmaster#1541]
**What happened**:

I was not able to fine-tune the selected Filter Lists.

Using v1.6.5 (Stable).

I went into the Portmaster UI -> Privacy Filter -> Filter Lists.

I de-selected "Mixed Ads/Trackers/Malware" -> "Dan Pollock's List of Bad Stuff". It de-selected the entire branch. I tested this using CMD -> nslookup on a domain to try and figure out which FQDN was in a particular list and just by chance found this bug.

IMO, the top-level checkbox should have something to let users know it's partially selected...

Also of note, while trying to find the FQDN in the lists, I'm not even sure if the others are actually enabled under the parent item. For example, while de-selecting Dan Pollock's list, with the others below it checked, and the top-level "Mixed Ads/Trackers/Malware" de-selected, I'm not sure if it's recognizing the others are selected ("MVPS Hosts File", etc.). Could someone verify this?

**What did you expect to happen?**:

I expected the top-level checkbox to let the user know the child checkboxes under it are partially selected. e.g. put some sort of indication of this like a box within the box, partially grayed out, etc.

**How did you reproduce it?**:

Tried it again and again. :)

![image](https://github.com/safing/portmaster/assets/2259414/41afc9ff-48cf-4d0c-835a-030e2c0a7452)

**Comment by Raphty** [comment]
the blue dot next to the white box is the indication that there are changed settings bellow - this is the same everywhere in Portmaster also in the left bar you see the blue dots next to the setting categories you have changes in.
