### ISSUE TITLE
Reports wrong version on winget

### ISSUE THREAD

**Issue by renzard** [safing/portmaster#1544]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
winget upgrade crosschecks the version and gets it always different so it proceeds to update

**What did you expect to happen?**:
Have the same version reported 

**How did you reproduce it?**:

winget upgrade on terminal

**Debug Information**:

**Comment by Raphty** [comment]
repeat: https://github.com/safing/portmaster/issues/1522
