### ISSUE TITLE
Set a Pre-created Settings (profiles) to an App

### ISSUE THREAD

**Issue by rbdevr** [safing/portmaster#1547]
Hello all,

It would be helpful if the users could create profiles, pre-created settings, and every time a new app comes up, a popup could ask the user to select the profile for that app. This feature enhances the current "Global Settings" and it could work the same way in case a user decides to do so.

Some profile examples:
Default App (all external access is blocked)
Internet App (All internet access)
Games (full Access)
Background service (Prompt the user to access internet)

And so on. once you change a profile all the apps attached to it will be updated.

I'm available to chat.
Cheers

**Comment by Raphty** [comment]
Also an interesting idea! 

out team does not use the prompt feature a lot, we are more of the philosophy of creating solid allow lists for the apps we use.

We also encourage the sharing of such profiles here: https://github.com/portmaster-community/apps

I like the idea! we might look into something like this in the future.

**Comment by rbdevr** [comment]
I understand the no hands approach but this could be something the user could enable. if not the app will auto select the default profile the same as the current "Global Settings". 
In the future you could do a step forward and using a central server, auto identify apps. So a game.exe the server could tell Postmaster it is a Game and auto select the Game profile.

**Comment by Raphty** [comment]
we have been thinking about how to integrate the library of profiles on the GH in a privacy respecting way.
and automate this as well, so if you want Portmaster automatically pulls the community profile and applies it.

But this is in the further future at the moment.
