### ISSUE TITLE
Include Apps with specific settings section in "Apps and Profiles" Screen

### ISSUE THREAD

**Issue by rbdevr** [safing/portmaster#1548]
Hello all,

The "Apps and Profiles" screen right now has got 3 sections. 1 - active, 2 - recently edited, 3 - all. Plus a blue dot if the app has got a specific setting.

I suggest to include another sections to display all apps only if they have a specific setting.

Now you might be thinking this screen is getting too big with so many apps and so many sections so I suggest to have a filter toolbar instead of displaying all the 4 sections at once. so you always display all apps and the user can select a filter from a dropdown just like we have in the network activity screen. maybe also include a search textbox.

Filter 1
- All
- Active
- Recently Edited

Filter 2
- All
- Contains Specific Settings
- Doesn't Contain Specific Settings 

Filter 3 
[Search by name]

I'm available in case any questions come up.
Cheers

**Comment by Raphty** [comment]
super interesting idea, I have not thought about.

sadly this is probably not something we will tackle soon, but it is heard and we will consider it in the future!

**Comment by rbdevr** [comment]
Yes of course. All in its on time. Are you guys using agile?
