### ISSUE TITLE
Remote custom filter lists

### ISSUE THREAD

**Issue by realgooseman** [safing/portmaster#1551]
**What would you like to add or change?**:
Adding an option to add URL's to multiple online blocklists.

**Why do you and others need this?**:
Currently, it's annoying to have to download the filter and put the path of the single file in Portmaster. Just to see that same list get updated a day later.

Having the ability to put the URL of a list would be better and allow auto-updates.
So there would be the pre-installed Safing lists and the custom added ones. Something like what uBlock Origin allows.

If it's not considered, for whatever reason, please add these three filters in Portmaster (they are effective and balanced) : 

**[Hagezi - Multi Pro](https://github.com/hagezi/dns-blocklists?tab=readme-ov-file#ledger-multi-pro---extended-protection-recommended-)**
**[Badmojr - 1Hosts Lite](https://github.com/badmojr/1Hosts?tab=readme-ov-file#1hosts-lite)**
**[Firebog - EasyPrivacy](https://v.firebog.net/hosts/Easyprivacy.txt)**

**Comment by Raphty** [comment]
@realgooseman we have heard this multiple times, we belive that good allow listing is better then wack amoling with tons of block lists.

adding remote lists is also a privacy risk in that you connect to that service and are therefor a known user.

we might look into this in the future, it is not a high priority at the moment.

filter lists are handled here: https://github.com/safing/intel-data

If you want to help with great allow listing per app, here is the place: https://github.com/portmaster-community/apps
