### ISSUE TITLE
Beta 1.6.11 doesn't work correctly, keeps on the red dot, "The portmaster service is not running"

### ISSUE THREAD

**Issue by RonnyTNL** [safing/portmaster#1565]
**What happened**:
Upgraded from "Beta 1.6.10" to 1.6.11, portmaster core and notification cannot communicate, keeps showing service not running.

**What did you expect to happen?**:
Portmaster to function as expected

**How did you reproduce it?**:
Not, but on the discord channel multiple users on both Win10 and Win11 are reporting similar issues.

**Debug Information**:
Can't even get to the UI to Copy Debug info.
Below is a partial log

```
executing core/portmaster-core.exe version 1.6.11 on windows amd64
240603 19:40:36.321 > BOF
240603 19:40:36.377 entication:291 > WARN 001 api: denying api access from 127.0.0.1:55830
240603 19:40:37.584 t2/handler:152 > WARN 003 [5x] kext: src/packet_callouts.rs:144 failed to get key from nbl: failed to get net_buffer data
240603 19:40:38.239 v/location:303 > WARN 005 netenv: failed to get IPv4 device location from traceroute: did not receive any actionable ICMP reply
240603 19:40:38.573 t2/handler:152 > WARN 007 [3x] kext: src/packet_callouts.rs:144 failed to get key from nbl: failed to get net_buffer data
240603 19:40:40.127 olver-mdns:114 > WARN 009 intel(mdns): failed to create udp6 listen multicast socket: listen udp6 [ff02::fb]:5353: setsockopt: not supported by windows
240603 19:40:48.580 t2/handler:154 > ERRO 011 kext: src/device.rs:161 failed to inject packet: filter-engine: failed to begin transaction: STATUS_FWP_TXN_IN_PROGRESS
240603 19:40:51.623 pat/module:112 > ERRO 013 compat: self-check #3: dns integration check failed: failed to receive test response: lookup a8023b63ea69c1cfedb1a2ae4205440ceb.self-check.portmaster.home.arpa.: no such host
[8:09 PM]

executing core/portmaster-core.exe version 1.6.11 on windows amd64
240603 19:59:36.827 > BOF
kext: old driver service was found
kext: old driver service was deleted successfully
240603 19:59:39.491 olver-mdns:114 > WARN 001 intel(mdns): failed to create udp6 listen multicast socket: listen udp6 [ff02::fb]:5353: setsockopt: not supported by windows
```

**Comment by Raphty** [comment]
I am sorry for the inconvenience in our testing it worked well, I am not sure what is happening and not even it it effects all people
here is the link to the relevant folders to backup in case you want to reinstall:  https://wiki.safing.io/en/Portmaster/Install/Windows

also if you reinstall make sure that you remove the line

 "releaseChannel": "beta" 

from the config.json

**Comment by ElliotS2007** [comment]
Happening here too:
![image](https://github.com/safing/portmaster/assets/67877214/00dee6e8-a53d-409f-8e47-e3f4ad3f1971)
Windows 10 22H2 (OS build 19045.4474)

**Comment by JS-E** [comment]
Yup got this too :/ gonna try reinstalling to repair

**Comment by dhaavi** [comment]
Easiest was to get back to stable is to remove the beta.json file from the updates directory.
Then, after Portmaster started, change the release channel setting.

**Comment by dhaavi** [comment]
Update:

It seems only the communication between the App (Electron) and the Core service is affected. This means that everything else operates as usual.

If you have Development Mode enabled, you can access the UI in the browser at http://127.0.0.1:817/

To activate Development Mode, follow this guide: https://wiki.safing.io/en/Portmaster/Install/Windows#windows-7-and-8

We also already found a fix, but want to first fully understand the issue before we continue.

**Comment by RonnyTNL** [comment]
I have an other machine that upgraded just fine to 1.6.11, so if you have a clue where to look for details pls let me know

**Comment by Marc05** [comment]
I don't know the scope of that communication issue between the core service and the GUI, but things were not operating normally in my case. Specifically, IPv4 DNS (using DoH) did not work. Fortunately I also have IPv6 DoH set up which meant I was still able to work on things in the meantime, but the time waiting for IPv4 requests to time out was what led to realize there was a problem.

I'm glad to hear an offline installer is being worked on - it just makes sense for the purpose of the app.
