### ISSUE TITLE
option to disable the notification with (Blocked Bypass Attempt by XY)

### ISSUE THREAD

**Issue by youdontneedtoknow22** [safing/portmaster#1571]
**What would you like to add or change?**:
On Prompt mode (I don't know how it is in other modes), I get daily at least 5-7 bypass attempts from Discord, Msedge, Brave, Microsoft Edge Webview2. There should be an option to disable this kind of notifications.
Disabling notifications from windows itself will make prompt mode into deny mode, so that's not an option
![grafik](https://github.com/safing/portmaster/assets/85135068/4ec1f6e0-260e-4a48-819d-7a7d71a6af17)

**Why do you and others need this?**:
This is very annoying and doesn't let one concentrate on his job when the pop up comes every hour or two (next to other notifications like emails, etc..).

**Comment by Flavelius** [comment]
Even other notifications like the ~couldn't find a valid dns server~ (i.e. in airplane mode) one should be disable-able, most of the time the 'issue' that these report doesn't require any user intervention at all, so they are mainly informative, and informative notifications should be configurable.

**Comment by seiferflo** [comment]
I agree this is an annoyance (see below on my end)

<img width="471" height="291" alt="Image" src="https://github.com/user-attachments/assets/afbda9d2-5117-4499-ba38-69654da684ea" />
