### ISSUE TITLE
Add allow app、block app options in **Desktop Notifications** 

### ISSUE THREAD

**Issue by XCJYO** [safing/portmaster#1576]
When I set the Default Network Action to prompt, a new application will pop up **Desktop Notifications** with only allow and block options. I hope to add allow apps and block apps directly to the pop-up notification, so there is no need to open the portmaster application for modification，which is much more convenient. Thank you

![image](https://github.com/safing/portmaster/assets/111405468/81f8d237-8271-496c-b866-3297fc336eb9)

**Comment by Raphty** [comment]
Thanks for the suggestions, this is similar to requests from the past, when we tackle the prompt mode again we will probably in-cooperate this or something similar

**Comment by 3941** [comment]
Don't take my word for it, but I think I've once learned that the Windows notifications don't allow more than two buttons.
So either we'd need configurable buttons, so we can set them to our personal, most common use cases, or Portmaster needs to have its very own notification window.

**Comment by Raphty** [comment]
@3941 we are looking into the own window option for the future, the switch to tauri as the UI backend can help us with that.
