### ISSUE TITLE
New screen "Monitor" for realtime report

### ISSUE THREAD

**Issue by rbdevr** [safing/portmaster#1578]
Hello all,

I would like to suggest creating a brand new screen called Monitor.

It would work similar to the "Network Activity" screen but the idea is this screen is a realtime representation of network traffic.

The screen should display a list of active connections and recently transfers inbound and outbound with an auto update.

1- active connections:
 - arrow pointing in and out flashing when there are data trafficking.
 
2- inbound and outbound transfers:
 - displays per app and group " destinations and connection type " in the same list item.
 - duplicated are displayed in the same item with a counter on the right side number of times that was requested.
 - the item is removed once the app is "idle" after a period of time.

I suggest a refresh time of 3 seconds and remote idle time 10 seconds.

example:

Windows - update.windows.com          - outgoing  - started - Filter Lists @ Global   &nbsp; &nbsp; &nbsp;  &nbsp;      - 1
&nbsp;  &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; - store.windows.com    &nbsp;   &nbsp;        - outgoing - ended   - Outgoing Rules @ Global  - 3

Steam     - store.steampowered.com   - outgoing - started  - Filter Lists @ Global     &nbsp;  &nbsp; &nbsp;      - 10
&nbsp;  &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; - 192.168.1.5      &nbsp; &nbsp;  &nbsp;   &nbsp; &nbsp;  &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp;                - outgoing - ended   - Local Cons @ Global         &nbsp;  &nbsp; &nbsp; - 3
&nbsp;  &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; - 127.0.0.1          &nbsp; &nbsp; &nbsp;  &nbsp; &nbsp;  &nbsp;  &nbsp; &nbsp;  &nbsp; &nbsp; &nbsp;  &nbsp;                  - outgoing - active   - Outgoing Rules @ Global   - 1

I 'm available to chat.
Cheers

**Comment by Raphty** [comment]
thanks for the ideas!

did you look into the grouping options in Portmaster?
![image](https://github.com/safing/portmaster/assets/11504285/c8fc4c4e-2ea9-4172-a427-d71396f5db36)
