### ISSUE TITLE
Update Chocolatey Package

### ISSUE THREAD

**Issue by Yolakalemowa** [safing/portmaster#1579]
**What would you like to add or change?**:
Update Choco package. It's currently at version 1.0.0. 
But latest stable version is 1.6.10

**Why do you and others need this?**:
chocolatey is a great package manager for windows and has been growing a lot. It's a great way to manage all my windows packages rather than have to take care of each app individually.

Would be much appreciated.

**Comment by Raphty** [comment]
@Yolakalemowa we are not maintaining the Chocolatey packages.

But as a note, the v1 is the current version of the installer which is correct - I guess Chocolatey just Installer the installer and then it auto updates to the current version

this behavior can only change after we moved into making each reales a new (offline) install

**Comment by Yolakalemowa** [comment]
> making each reales a new (offline) install

Hi thanks for reply.

If I may ask, I'm a noob: do you recommend then I stick to downloading from your official site instead of chocolatey or doesn't matter? 
And are there plans on maintaining choco packages in future?

**Comment by Raphty** [comment]
again we are not maintaining choco, and there are no plans for it.

since choco is not an official way to install Portmaster I would not use it unless you trust the person maintaining the Portmaster install there.
