### ISSUE TITLE
Can provide full package?

### ISSUE THREAD

**Issue by lost22git** [safing/portmaster#1580]
Unable to install due to extremely slow download

![Screenshot 2024-06-11 195934](https://github.com/safing/portmaster/assets/65008815/451cd659-9a52-4c55-9a34-f993642d99db)

**Comment by lost22git** [comment]
Sorry I don't use discord so I can only ask here

**Comment by Raphty** [comment]
we are thinking about moving to full release and offline installers, but this will be a while.
