### ISSUE TITLE
WIndow content sometimes takes long to become visible when opening UI

### ISSUE THREAD

**Issue by Flavelius** [safing/portmaster#1585]
This is basically the still active issue from: 

https://github.com/safing/portmaster-ui/issues/475

Sometimes i accidentally click on the windows notification instead of its allow/block buttons, which opens the portmaster UI.
The opened window then stays black for a good amount of time, maybe 20 seconds, during which i lose the ability to allow or deny the connection attempt.
I'm not sure if it's related to opening the ui from the notification. Often times it just opens/loads without this issue.

**Comment by vlabo** [comment]
Thank you for the report and for using postmaster.
We are currently working on a UI framework change which should fix most of the UI bugs that we have in the moment, we will start testing it in the near future.
