### ISSUE TITLE
Default blocklist configuration blocks common websites from functioning

### ISSUE THREAD

**Issue by candroid-man** [safing/portmaster#1586]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**Issue**:

Various sites and services such as Steam, Facebook, Instagram, and more are 100% blocked with the default blocklist configuration. I recommend and sometimes install Portmaster on customer devices at my repair shop, however customers often come back to me with issues accessing the sites they normally visit, because I don't know which of the 21 blocklists that are enabled by default is blocking that particular site, and some people wouldn't be able to figure out how to create an exception. I really like installing Portmaster because it protects people (especially the elderly) from malicious or scam sites, but I also can't keep making people come back so I can create exceptions for them.

**Potential Solution**:

Get rid of some of these blocklists, and add more relevant and up to date lists such as Hagezi lists. Or perhaps make preset blocklist configurations for users, and they can decide how aggressive the blocking is from 1-5 or whatever. Make a configuration that has little to no breakage, to give folks some protection while keeping things easy.

**Comment by Raphty** [comment]
I can assure you that Steam, FB and Instagram are not blocked by default.

I guess you (or they) enabled Big Tech, which is not enabled by default.

also as a reminder, you can see the reason why something is blocked in each blocked connection, which is also where you can allow the connection with one click
![image](https://github.com/safing/portmaster/assets/11504285/6d77e7c6-f08d-4594-958b-9f046af2fd2e)

**Comment by andylh** [comment]
I am using the default settings and it blocked Facebook.
