### ISSUE TITLE
Portmaster Core Service Crashing on Startup - Windows 7 64

### ISSUE THREAD

**Issue by Ncrypt3dit** [safing/portmaster#1588]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**: Portmaster Core Service Crashing on Startup. 

**What did you expect to happen?**: Portmaster Core Service not crashing

**How did you reproduce it?**: Reboot. Clean Uninstall and Re-Install. Same issue.

**Debug Information**:

Core Error log:
NJ{"Created":1718516338,"Modified":1718516338,"Expires":1721108338,"Deleted":0}S
executing core/portmaster-core.exe version 1.6.10 on windows amd64
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall(0x22fcf8)
	/usr/local/go/src/runtime/sys_windows_amd64.s:75 +0x7a fp=0x22fc80 sp=0x22fc60 pc=0x476d3a
rax     0x0
rbx     0x1a98538
rcx     0x20608a8
rdx     0x20
rdi     0x7fffffde000
rsi     0x22fe78
rbp     0x22fdc0
rsp     0x22fc58
r8      0x0
r9      0x22fee8
r10     0x37a2e8
r11     0xc000004000
r12     0x22fec8
r13     0x0
r14     0x1a96d80
r15     0x3
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

Notifier Error Log:
NJ{"Created":1718516173,"Modified":1718516173,"Expires":1721108173,"Deleted":0}S
executing notifier/portmaster-notifier.exe version 0.3.6 on windows amd64

**Comment by vlabo** [comment]
We have not supported windows 7 for more then 2 years and Microsoft has stopped supporting it for 4 years.
