### ISSUE TITLE
Sunshine incoming connections reported as Network Noise

### ISSUE THREAD

**Issue by SerialVelocity** [safing/portmaster#1589]
**What worked?**

I can connect to [Sunshine](https://github.com/LizardByte/Sunshine/) using Moonlight.

**What did not work?**

Moonlight disconnects after a few seconds. This is because the UDP traffic on port 48000 is being treated as "Network Noise". I have to allow that to get it to work.

**Debug Information**:

Windows 11 Pro 10.0.22631 Build 22631
Portmaster 1.6.10
The debug information shows the connection is "_unsolicited" in "Network Noise". I can attach the debug info if required (just don't have the time to sanitise the logs atm and copy it across to a computer with Github access)

**Comment by SerialVelocity** [comment]
Still an issue

**Comment by SerialVelocity** [comment]
@Raphty How do I reopen this?

**Comment by Raphty** [comment]
i recall that there has been an issue where I helped with this in the past... it is a configuration issue not a compatibility one

**Comment by Raphty** [comment]
found it, on the discord, just search for sunshine on the discord.... there you see how you need to configure this

**Comment by SerialVelocity** [comment]
@Raphty Sorry for the delay, I looked up sunshine in the discord and all I can find is what I mentioned in my first post, that you can get it to work by allowing "Network Noise". Is there something I missed? How can I get the "Network Noise" to be picked up as "Sunshine" traffic?

**Comment by SerialVelocity** [comment]
@Raphty Is there something I missed in the discord? (Hoping you see this as it is a closed issue and I can't re-open. Should I open another?)

**Comment by Raphty** [comment]
When you have changing IPs and such it always needs to connect first, and then it can be associated.... this is how networking works. there is nothing that can be done about that.

Portmaster should label the connection correctly as soon as the connection has been established between the apps.

**Comment by Raphty** [comment]
there is not compatibility issue - this is an issue regarding the knowledge about networking and what information is available when. So no need to open another ticket

**Comment by SerialVelocity** [comment]
Oh, is this because Moonlight originally connects through TCP and that connection is recognised properly, but after that UDP is used for other connection streams?

That seems odd because either Moonlight is listening on those UDP ports already which means Portmaster should know about them, or Moonlight has initiated a connection (or at least sent out packets since I know UDP doesn't really do connections) on that UDP port, which I'm assuming would mean the port would be associated with the app as well?
