### ISSUE TITLE
Portmaster Network Activity gets stuck on "Loading Chart" and doesn't show any network activity

### ISSUE THREAD

**Issue by netExtra** [safing/portmaster#1595]
Windows 10

**What happened**:
Install application. Select Network Activity

**What did you expect to happen?**:
Network Activity Chart appears but it doesn't. Instead stuck on "Loading Chart". Screenshot attached

**How did you reproduce it?**:
Works on initial install, but after a short time stops working. Even restarting doesn't work. Only way to fix is to reinstall the application.

Logs attached
<img width="1060" alt="Screenshot 2024-06-24 at 18 28 36" src="https://github.com/safing/portmaster/assets/140253706/ec178fe7-64c9-4f41-9913-ba8c0046f1cd">

-->
[2024-06-24-17-36-47.error.log](https://github.com/user-attachments/files/15959354/2024-06-24-17-36-47.error.log)
[2024-06-24-17-36-47.log](https://github.com/user-attachments/files/15959355/2024-06-24-17-36-47.log)
[2024-06-24-15-27-26.log](https://github.com/user-attachments/files/15959370/2024-06-24-15-27-26.log)

**Comment by mmm-gh** [comment]
The same error scenario on my laptop (running Windows 11)

**Comment by cg089** [comment]
+1 on a Windows 11 Laptop

**Comment by netExtra** [comment]
I reported that issue a few months back. But now I wonder if I really had the issue or if I just didn't scroll down enough lol because nothing has changed but the issue is no longer there.
