### ISSUE TITLE
SPN appears to be objectively inferior to common VPNs

### ISSUE THREAD

**Issue by Kreyren** [safing/portmaster#1598]
![image](https://github.com/safing/portmaster/assets/11302521/d3c904cc-0f8d-4a9d-96c2-fa6c74ce5cff)

SPN claims to be coming with a `state of the art encryption` yet seems to be lacking any kind of management for `Post Quantum Safety` as it's apparently not using a Post Quantum Safe encryption and it's unclear who runs the SPN nodes to probably sanely claim that it's also lacking management for [Harvest Now, Decrypt Later](https://en.wikipedia.org/wiki/Harvest_now,_decrypt_later) to claim that all traffic sent over SPN is at a high risk of being collected and decrypted in the future.
So it seems that you are not really solving any problems with VPN and seemingly adding problems as e.g. [wireguard can be configured to use a post-quantum safe cryptography](https://www.reddit.com/r/mullvadvpn/comments/ypfgv5/postquantum_safe_vpn_tunnels_available_on_all) to manage this problem.

Please fix that, the idea of SPN seems good on paper and i would like to use it for our infra in https://github.com/NiXium-org/Nixium to provide clearweb services that do not expose the location of the server to the SPN service provider or anyone who's trying to locate the IP.

Referencing for details: https://github.com/FiloSottile/age/issues/578

P.S: Cut out the marketing bullshit it makes you seem like glowie instead of someone who's serious about privacy and security to the point that majority of people i talked to about SPN didn't want to use it as it seems too suspicious.

**Comment by dhaavi** [comment]
Hey @Kreyren,

Thank you for raising your concerns.

SPN definitely uses state of the art encryption.

PQC is still experimental. While NIST has selected four algorithms for standardization in 2022 - CRYSTALS-Kyber, CRYSTALS-Dilithium, SPHINCS+, and FALCON - none of them are standardized yet. Three of them have draft standards. None of them are available in the golang stdlib.

Apart from that, practical quantum computers are still at least 10-30 years away. If your network traffic is worth saving 10 years and then paying for computation on a quantum computer "just in case", then whoever is targeting you has enough money to target you in other, faster, more practical, and cheaper ways.
Thus, PQC currently does not fit a realistic threat model for Internet traffic for pretty much anyone.
 
 As soon as PQC is standardized and available, we will put it on the roadmap.

**Comment by Kreyren** [comment]
> PQC is still experimental. While NIST has selected four algorithms for standardization in 2022 - CRYSTALS-Kyber, CRYSTALS-Dilithium, SPHINCS+, and FALCON - none of them are standardized yet. Three of them have draft standards. None of them are available in the golang stdlib. -- @dhaavi (https://github.com/safing/portmaster/issues/1598#issuecomment-2199693355)

[NTRU](https://en.wikipedia.org/wiki/NTRU) was developed in 1996 and European Union recommended it on 7th September 2015 in PQCRYPTO https://pqcrypto.eu/docs/initial-recommendations.pdf and beyond the EU standardization it's standardized in **IEEE Std 1363.1** and **X9.98** and implemented by OpenSSH, WolfSSH, Lokinet, BouncyCastle, etc..

> None of them are available in the golang stdlib. -- @dhaavi (https://github.com/safing/portmaster/issues/1598#issuecomment-2199693355)

![image](https://github.com/safing/portmaster/assets/11302521/d6bcef11-df5e-4a21-ae74-af71a769e594)

> Apart from that, practical quantum computers are still at least 10-30 years away. -- @dhaavi (https://github.com/safing/portmaster/issues/1598#issuecomment-2199693355)

Willful missinformation:

[Atom Computing has 1225-Qubits already](https://www.forbes.com/sites/moorinsights/2023/10/24/atom-computing-announces-record-breaking-1225-qubit-quantum-computer), [Cleveland Clinic uses their quantum computer for healthcare research](https://youtu.be/8ppnBSljG94) and most importantly [IBM's Senior Vice President and Director of Research Dario Gill claims that there are no obstacles to get quantum computers with +100K qubits in 5 years](https://youtu.be/K4ssT6Dzmnw?t=723)

> If your network traffic is worth saving 10 years and then paying for computation on a quantum computer "just in case", then whoever is targeting you has enough money to target you in other, faster, more practical, and cheaper ways.
> Thus, PQC currently does not fit a realistic threat model for Internet traffic for pretty much anyone. -- @dhaavi (https://github.com/safing/portmaster/issues/1598#issuecomment-2199693355)

That's apparently what NSA and their data center in utah is doing to every day people as reported by forbes https://www.forbes.com/sites/netapp/2013/07/26/nsa-utah-datacenter with capacity to hold estimated exabytes of storage harvested through their global surveillance programs such as those explained by [Edward Snowden](https://en.wikipedia.org/wiki/Edward_Snowden) during his interview by John Oliver on Last Week Tonight S2E8: https://youtu.be/SgTQDp1jwBw?t=2082

Because of that we can sanely claim that objectively that fits everyone's threat model.

---

It's frankly alarming that you are the lead developer of SPN and yet are apparently this misinformed on the critical subjects and refuse to take this subject with the seriousness it deserves which is enough for me to disqualify SPN for it's use in [NiXium](https://github.com/NiXium-org/NiXium/issues/77).

**Comment by dhaavi** [comment]
It seems we have different views on this.
You are welcome to choose whatever technology fits your needs.
