### ISSUE TITLE
Stop the notification sound so that the notification is displayed only in the GUI.

### ISSUE THREAD

**Issue by oklokl** [safing/portmaster#1605]
**What would you like to add or change?**:
When I boot Windows, a notification (sound) occurs while Windows is locked.
It happens before I log in to Windows. That's the notification sound.
I wish I didn't hear a notification sound before logging in.
I don't know why, but a notification (sound) occurs if previous notifications remain.

It would be nice to not have a notification sound. Added features. For quiet users.
(Fortunately, I don't hear notification sounds when I play games or watch videos. additional information)

**Why do you and others need this?**:
Users who want to use the device quietly without notification sounds can turn off the notification sounds. It would be a good idea to display it only in the GUI. Then, it would be rare to be bothered by the sound when recording the computer or doing something else.

**Comment by Raphty** [comment]
thanks for the feedback, we are currently reworking the UI backend, and the whole notification system will end up in this newer model, we will look into what sort of settings we can offer after the transition.

but your suggestion will be taken into account thanks for the idea

**Comment by vlabo** [comment]
There is an option to turn off desktop notifications.
https://docs.safing.io/portmaster/settings#core/useSystemNotifications
