### ISSUE TITLE
Can't browse to wiki.safing.io with SPN on

### ISSUE THREAD

**Issue by JustinWebDev** [safing/portmaster#1609]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
enabled SPN

**What did you expect to happen?**:
opening help topics (like the wiki page) should still load in the browser

**How did you reproduce it?**:
In the UI,
enabled SPN
click Help
click "Portmaster Wiki & FAQ" link

**Debug Information**:

**Comment by Raphty** [comment]
we are in the process of updating some servers, the wiki has been effected.
