### ISSUE TITLE
SPN login prompt does not do anything

### ISSUE THREAD

**Issue by JustinWebDev** [safing/portmaster#1610]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
enabled SPN, a Windows toast says I have to login (should say "log in"), but nothing happens

**What did you expect to happen?**:
clicking the "login" button on the toast would show me where to log in

**How did you reproduce it?**:
In the UI,
enabled SPN
wait for the toast
click the login button

**Debug Information**:

**Comment by Raphty** [comment]
Thanks for letting us know, we will start looking into all our notifications when we switched the UI backend

but I guess you know that you can login here:

![image](https://github.com/safing/portmaster/assets/11504285/9290d34c-ff6f-4dfa-a172-abb5d900514b)

**Comment by JustinWebDev** [comment]
Yep, thanks.
