### ISSUE TITLE
Ability to easily update the Pre-release with one button

### ISSUE THREAD

**Issue by oklokl** [safing/portmaster#1612]
**What would you like to add or change?**:

I would like to use the beta version, but it's too complex and difficult. It would be great if there was a single button that, when pressed, upgrades to the beta version.

Additionally, it would be good if pressing the beta version button again could downgrade it back. That's what I mean. It would be appreciated if you could make this.

Also, it would be nice to have a button for providing automatic feedback to the developers, excluding personal information. This button would allow sending information that could help in reporting bugs. It would be a voluntary feedback provision button. Users who do not wish to participate can simply not press it. Please provide an explanation on the button to avoid confusion (default: inactive). Include this only in the beta tester version.

**Why do you and others need this?**:
It would be good to allow users to easily use a Pre-release
![_55172e99-28d6-4109-89c7-66a78c8aacd4](https://github.com/safing/portmaster/assets/1571600/1b1f439c-27a6-4fe0-a794-1a6729de6464)

**Comment by Raphty** [comment]
I dont quite understand what the complication is, sorry

you can search for channel in the global settings and then change between the channels in a dropdown

![image](https://github.com/safing/portmaster/assets/11504285/1bbb0b11-d536-4ee3-a7c6-6b54152ed48a)
