### ISSUE TITLE
Timers for connections

### ISSUE THREAD

**Issue by jonsnow231** [safing/portmaster#1613]
I like how Simple Wall allows you to easily set a timer for something. So if you only want something to connect for a minute to install it or whatever, it will then automatically block it. Sorry if this feature is already on Portmaster, I couldn't find it though. 

Also, bump for the feature of [anonymized](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Anonymized-DNS) dns relays like YogaDNS has, so even my grandma can set it up.

**Comment by Raphty** [comment]
Thank you for the suggestion, we might look into this for the future, but the reason this is required in simple wall is that SW is very limited in what it can do. It can not filter per connection, so if you allow https you allow all https, that is not the case with Portmaster. 

With Portmasters Filter lists trackers are blocked automatically, and we also have a community where we share profiles for apps, so you can only allow the connections required for that app to work https://github.com/portmaster-community/apps

SW has a different focus, it is - simple - it is an easy on off toggle, but Portmaster is more complex, both have different pros and cons - with Portmaster you can control where each app can go, not just if it allowed to leave the house so to speak. 

regarding the YogaDNS thing, I only glanced at it, what servers are the ones doing the de and encryption and who is paying for them? again, did not read into this, but if you want something like this, SPN is what you are looking for.

**Comment by jonsnow231** [comment]
The anonymized relays are the ones here: https://dnscrypt.info/public-servers/ 
To my knowledge, on Windows only two apps with GUI offer this (YogaDNS and SimpleDNSCrypt). There are a bunch others that do, like dnscrypt-proxy, SecureDNS, encrypted dns server, etc. But no actively maintained, open-source app with a gui that I could find.

**Comment by eugenesvk** [comment]
> but Portmaster is more complex, both have different pros and cons - with Portmaster you can control where each app can go, not just if it allowed to leave the house so to speak.

But adding more config knobs is adding complexity, so it should be fully aligned with Portmaster!

One specific example: if you don't want to be force-fed mandatory reboots on Windows OS updates, you might want to simply block all updates for a period of time in a firewall and then update manually by turning a rule off temporarily or simply be reminded again in a week when the rule expires, but even then you'd only allow this rule "for 1 day" to update 

(as a side not: please check the UI of Little Snitch on macOS, it has one of the better UIs of the different firewall apps, where you don't even need to click to select a duration, but can press a few keys instead, not moving your hands off keyboard)
