### ISSUE TITLE
[Compatibility Report] Linux Mint Cinnamon DNS requests are not always routed through the DNS in Portmaster 

### ISSUE THREAD

**Issue by ghost** [safing/portmaster#1616]
**What worked?**

Everything besides the reported issue.

**What did not work?**

Portmaster configures itself as the DNS resolver, but it's often ignored, with DNS requests being made through the System/Network DNS instead. I tested this on a fresh installation of Linux Mint, after disabling the pre-installed firewall. The logs are not from this test.

I conducted the tests via: https://www.dnscheck.tools/.

**Additional Information:**

I have "Ignore System/Network Servers" enabled, which solves the issue of the DNS configured in Portmaster being bypassed. However, DNS requests that would have been routed through the System's DNS are not resolved, causing an error. These are shown as DNS requests in Portmaster with a yellow dot (see attachment for further information).

**Comment by Raphty** [comment]
it does not look like ca compatibility but a configuration error - in the debug info you sent I don't see that you disabled system DNS, also the configured dns servers look to be wrong... which would lead to Portmaster having to fall back to the system dns.

further, browsers sometimes want to use their own dns, if you say sometimes, then I would assume that it happens depending on the browser you use. Portmaster tells you that there was a bypass attempt - but depending on your config you can block a bypass or allow it.

again, I feel like you miss configured Portmaster.
Even though mint is not officially supported by us, I know of several people who have no issues running Portmaster on mint

**Comment by Uneccessary** [comment]
> I don't see that you disabled system DNS

System DNS is uncofigured, the DNS of my ISP is beeing used.

> also the configured dns servers look to be wrong...

They are not. They work fine on Windows 11 and they are just like in your documentations for NextDNS, also using the pre-sets would probably end up with the same issue. I can try it too.

> further, browsers sometimes want to use their own dns, if you say sometimes, then I would assume that it happens depending on the browser you use.

Sorry I wasn't probably not really clear about that one, it basically depends if Portmaster has been restarted recently which somehow solves the issue and if the DNS query is cached or not. DNS queries which are cached are not affected.

I tested it in Brave, LibreWolf and Chromium build by Linux Mint. I disabled Secure DNS in each of them.

> Even though mint is not officially supported by us, I know of several people who have no issues running Portmaster on mint

Suggest them to test if their configured DNS is actually beeing bypassed or not, most people probably not aware that their DNS configured in Portmaster is bypassed.

/https://dnscheck.tools/

**Comment by Uneccessary** [comment]
You can just test it yourself in a Virtual machine (the host OS should not have the DNS configured used in Portmaster nor should have Portmaster running, otherwise it could cause false-positives) and install Linux Mint and configure Portmaster.

Disable Linux Mint's Firewall application, since that could cause issues and run the test in your prefered browser.

**Comment by Raphty** [comment]
> You can test it yourself using a Virtual Machine (ensure the host OS does not have the DNS used which is in Portmaster configured, nor should Portmaster be running, to avoid false-positives). Install Linux Mint, disable Linux Mint's Firewall application (as it could cause issues) and then setup Portmaster. And run the test in your preferred browser.
> 
> https://dnscheck.tools/

again mint is not supported by us, we don't test it 
you are the first and only report of this, and we do have many reports to the contrary. 

If someone else wants to test this please let us know what your results are.

**Comment by Uneccessary** [comment]
> again mint is not supported by us, we don't test it

I apologize, I thought compatibility reports were available to report non-compatible Linux distributions, etc. and that these would receive appropriate treatment.

**Comment by Raphty** [comment]
You got me ❤️ .... we honestly want and try to help... but we need to focus on getting things done... I see you are not an developer (at least not on GH) so maybe you don't understand how entitled free users behave, thinking that everything needs to work on their platforms how they want... 

I did install the vm... and it showed me why I hate mint... which is partially why we are not supporting it 🤣 

I did not fiddle with the built in firewall or anything, just tried with firefox that came preinstalled and it did not show your described behavior... I am sorry but it seems to be your system that has issues... not a compatibility thing... 

I hope you find a solution, maybe someone else can chime in and help, but we will not consider this an issue.

**Comment by Uneccessary** [comment]
I did the test once again, and have recorded it. The DNS requests were sometimes routed through the underlying OS's DNS. It seems you probably forgot to turn off Secure DNS in Firefox, which doesn't appear to have such issues.

**Comment by Uneccessary** [comment]
In addition you can also try: https://dnsleaktest.com/

It's provided by IVPN and shows the same results as the other test.
