### ISSUE TITLE
how to manally update a filter?

### ISSUE THREAD

**Issue by lost22git** [safing/portmaster#1618]
Due to networking problem, my portmaster cannot update filter automaticly

![Screenshot 2024-07-09 125008](https://github.com/safing/portmaster/assets/65008815/e1809ee8-d7f3-4abc-b036-9548666f9589)

so i want to know how to update my filters manally

(I'm sorry that i ask here since i cannot use discord)

or a feature request: provide a http/socks5 proxy configuration

**Comment by Raphty** [comment]
click the button in the bottom left and then "Check for Updates"

![image](https://github.com/safing/portmaster/assets/11504285/b570a858-88a3-470e-b0d8-bfafba44da59)
