### ISSUE TITLE
Please add a build workflow to allow fans of open source to easily build portmaster

### ISSUE THREAD

**Issue by DavidXanatos** [safing/portmaster#1620]
Please add a build workflow to allow fans of open source to easily build portmaster.
Since there is no documentation how to do that it would be great if there would be a workflow that does it, and imho its less work for you then writing a documentation.

**Comment by Raphty** [comment]
https://github.com/safing/portmaster/blob/develop/Earthfile

**Comment by Raphty** [comment]
keep in mind that Portmaster is complex and interacts with multiple parts of your system. It will never bee as easy as some app that only has to work within itself.

**Comment by DavidXanatos** [comment]
does this earth file works to build a windows version as well?

**Comment by Raphty** [comment]
the kext needs an ev code signature, you need to buy one for it to work

**Comment by DavidXanatos** [comment]
> the kext needs an ev code signature, you need to buy one for it to work

I use the Custom Kernel Signers Hack so can self sign my own drivers for my systems. muhahahhahahha.....

**Comment by DavidXanatos** [comment]
cool we should do that some day :)

**Comment by DavidXanatos** [comment]
for the UI i still need safing/portmaster-ui right?
running ./pack gives an error: portmaster-ui/app-electron/dist/latest-linux.yml: No such file or directory
what am I missing?
