### ISSUE TITLE
Flatpak update doesn't work

### ISSUE THREAD

**Issue by RasheedAZ** [safing/portmaster#1622]
### What worked?
Everything else

### What did not work?
Most of the time, updating flatpak apps either from terminals or app store does not work unless i turn off Portmaster. Long term issue for several months if not longer.

dl.flathub.org
Reason: domain does not exist

### Additional information
on Pop!_OS 22.04

**Debug-Info**: https://support.safing.io/privatebin/?5a2c05534993a7fe#63QvcmTpQWDeVs5F1Rp18FK3ca2dNXgHHHAMAcHpExbM

**Comment by Raphty** [comment]
Flatpak works on all tested devices, if more people chime in and tell us that their FP also has issue please let us know, but I think this is a configuration error.

It looks like a dns issue, maybe consider adding a DNS in Portmaster
