### ISSUE TITLE
this is what systemctl status portmaster gives me how do i fix this?

### ISSUE THREAD

**Issue by seanfire99** [safing/portmaster#1624]
I am on EndeavourOS based on arch-Linux just reinstalled so this is a fresh installation 

[USER ~]$ systemctl status portmaster
● portmaster.service - Portmaster by Safing
     Loaded: loaded (/etc/systemd/system/portmaster.service; enabled; preset: disabled)
     Active: active (running) since Wed 2024-07-17 16:29:50 PDT; 25min ago
 Invocation: 88c425a003dd4230a501dd954e21ee05
       Docs: https://safing.io
             https://docs.safing.io
   Main PID: 23307 (portmaster-star)
      Tasks: 28 (limit: 38286)
     Memory: 129.2M (low: 2G peak: 149.1M)
        CPU: 24.961s
     CGroup: /system.slice/portmaster.service
             ├─23307 /opt/safing/portmaster/portmaster-start --data /opt/safing/portmaster core --
             └─23316 /opt/safing/portmaster/updates/linux_amd64/core/portmaster-core_v1-6-10 --data /opt/safing/portmaster

Jul 17 16:46:12 PC portmaster-start[23307]: 240717 16:46:12.090 pat/module:112 ▶ ERRO 993 compat: self-check #1: system integration check failed: di>
Jul 17 16:47:12 PC portmaster-start[23307]: 240717 16:47:12.091 pat/module:112 ▶ ERRO 995 compat: self-check #1: system integration check failed: di>
Jul 17 16:48:12 PC portmaster-start[23307]: 240717 16:48:12.093 pat/module:112 ▶ ERRO 997 compat: self-check #1: system integration check failed: di>
Jul 17 16:49:12 PC portmaster-start[23307]: 240717 16:49:12.093 pat/module:112 ▶ ERRO 999 compat: self-check #1: system integration check failed: di>
Jul 17 16:50:12 PC portmaster-start[23307]: 240717 16:50:12.095 pat/module:112 ▶ ERRO 002 compat: self-check #1: system integration check failed: di>
Jul 17 16:51:12 PC portmaster-start[23307]: 240717 16:51:12.096 pat/module:112 ▶ ERRO 004 compat: self-check #1: system integration check failed: di>
Jul 17 16:52:12 PC portmaster-start[23307]: 240717 16:52:12.097 pat/module:112 ▶ ERRO 006 compat: self-check #1: system integration check failed: di>
Jul 17 16:53:12 PC portmaster-start[23307]: 240717 16:53:12.099 pat/module:112 ▶ ERRO 008 compat: self-check #1: system integration check failed: di>
Jul 17 16:54:12 PC portmaster-start[23307]: 240717 16:54:12.101 pat/module:112 ▶ ERRO 010 compat: self-check #1: system integration check failed: di>
Jul 17 16:55:12 PC portmaster-start[23307]: 240717 16:55:12.102 pat/module:112 ▶ ERRO 012 compat: self-check #1: system integration check failed: di>

**Comment by seanfire99** [comment]
and this is yay output

yay -S portmaster-stub-bin 
AUR Explicit (1): portmaster-stub-bin-1.0.0-1
:: PKGBUILD up to date, skipping download: portmaster-stub-bin
  1 portmaster-stub-bin              (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>  
  1 portmaster-stub-bin              (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
==> Making package: portmaster-stub-bin 1.0.0-1 (Wed 17 Jul 2024 05:15:13 PM PDT)
==> Retrieving sources...
  -> Found portmaster-start
  -> Found portmaster.desktop
  -> Found portmaster_notifier.desktop
  -> Found portmaster_logo.png
  -> Found portmaster.service
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    portmaster-start ... Passed
    portmaster.desktop ... Passed
    portmaster_notifier.desktop ... Passed
    portmaster_logo.png ... Passed
    portmaster.service ... Passed
:: (1/1) Parsing SRCINFO: portmaster-stub-bin
==> Making package: portmaster-stub-bin 1.0.0-1 (Wed 17 Jul 2024 05:15:14 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found portmaster-start
  -> Found portmaster.desktop
  -> Found portmaster_notifier.desktop
  -> Found portmaster_logo.png
  -> Found portmaster.service
==> Validating source files with sha256sums...
    portmaster-start ... Passed
    portmaster.desktop ... Passed
    portmaster_notifier.desktop ... Passed
    portmaster_logo.png ... Passed
    portmaster.service ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting prepare()...
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/home/seanfire99/.cache/yay/portmaster-stub-bin/src/icons/16x16//portmaster.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/home/seanfire99/.cache/yay/portmaster-stub-bin/src/icons/32x32//portmaster.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/home/seanfire99/.cache/yay/portmaster-stub-bin/src/icons/48x48//portmaster.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/home/seanfire99/.cache/yay/portmaster-stub-bin/src/icons/96x96//portmaster.png' @ warning/png.c/MagickPNGWarningHandler/1526.
WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"

convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `/home/seanfire99/.cache/yay/portmaster-stub-bin/src/icons/128x128//portmaster.png' @ warning/png.c/MagickPNGWarningHandler/1526.
==> Sources are ready.
 -> portmaster-stub-bin-1.0.0-1 already made -- skipping build
==> Making package: portmaster-stub-bin 1.0.0-1 (Wed 17 Jul 2024 05:15:17 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
[sudo] password for seanfire99: 
loading packages...
warning: portmaster-stub-bin-1.0.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)          Old Version  New Version  Net Change

portmaster-stub-bin  1.0.0-1      1.0.0-1        0.00 MiB

Total Installed Size:  18.14 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                [-------------------------------------------------------] 100%
(1/1) checking package integrity                                                              [-------------------------------------------------------] 100%
(1/1) loading package files                                                                   [-------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                             [-------------------------------------------------------] 100%
(1/1) checking available disk space                                                           [-------------------------------------------------------] 100%
:: Processing package changes...
(1/1) reinstalling portmaster-stub-bin                                                        [-------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/3) Arming ConditionNeedsUpdate...
(2/3) Updating icon theme caches...
(3/3) Checking which packages need to be rebuilt

**Comment by seanfire99** [comment]
nvr mind after multiple reboots it just started to work.

**Comment by Raphty** [comment]
thanks for the update... still weird. 

hope it stays like this, if not, it would be interesting to know how to reproduce the issue.
