### ISSUE TITLE
incoming rule `allow LAN` is not working for WSL2 incoming traffic

### ISSUE THREAD

**Issue by lost22git** [safing/portmaster#1633]
![Screenshot 2024-07-23 230835](https://github.com/user-attachments/assets/5a6bab0e-f126-4851-b9f8-2fa1114865d6)

or can we add a preset rule `allow interface_alias/interface_index`？

**Comment by lost22git** [comment]
I choose to disable `Force Block Incoming Connections` as a temporary solution

**Comment by lost22git** [comment]
my fault: `Force Block Incoming Connections` is stronger than `rules`

**Comment by Raphty** [comment]
thanks for the clarification.
