### ISSUE TITLE
Non-reversible Outlook connection problems after installing / deinstalling Portmaster

### ISSUE THREAD

**Issue by Vasquez-Berlin** [safing/portmaster#1670]
**What happened**:

After installing Portmaster, we cannot start Outlook 2019 anymore. 
We receive several error messages (see attachment).

With a new Windows user profile, Outlook is running fine.

The warning messages say: 

„Outlook cannot start. Outlook windows cannot be opened. Folder Group cannot be opened. Information Store is not available.“

Second warning message says:
„Error when logging in. Check Network Connections, check Server Name and Name of Mailbox. Microsoft Exchange Information Service does not contain the necessary informations. Check yout profile“
And Error

„System resources are low. Close some windows.“

**What did you expect to happen?**:

After deinstalling Portmaster, the problem is still there. Also after deactivating all three windows Firewalls.

It seems, that Portmaster still blocks important ports/connections even if already uninstalled.

**How did you reproduce it?**:

made a new windows profile, it shows no outlook connection problems

**Comment by Raphty** [comment]
hey @Vasquez-Berlin as i wrote in the email, this is probably not a Portmaster issue.

especially if it works on another account... the kernel (where Portmaster sits) is the same on all accounts 😅
