### ISSUE TITLE
DNS server for the SPN

### ISSUE THREAD

**Issue by NolonQ** [safing/portmaster#1676]
**Pre-Submit Checklist**:

**What happened**:
Does safing host it's own DNS server that should be used with the SPN so we can browse the web privately without DNS leaks?

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by vlabo** [comment]
Safing does not host a DNS server. You should choose one that you trust.

[More info about DNS leaks](https://wiki.safing.io/en/FAQ/DNSLeak)

**Comment by NolonQ** [comment]
> Safing does not host a DNS server. You should choose one that you trust.
> 
> [More info about DNS leaks](https://wiki.safing.io/en/FAQ/DNSLeak)

Then may i ask another question, i'm using mullvad vpn and wish to use their DNS with portmaster.
How do i do that?
I've already contacted mullvad support and this is what they responded:

We don't have any insight in how the syntax for that software should be,
I can only recommend their documentation for that.

All information regarding our DNS over HTTPS/TLS service is available here,
https://mullvad.net/en/help/dns-over-https-and-dns-over-tls

**Comment by NolonQ** [comment]
> Safing does not host a DNS server. You should choose one that you trust.
> 
> [More info about DNS leaks](https://wiki.safing.io/en/FAQ/DNSLeak)

If i chose a DNS that is not brought with the encrypted SPN tunnel, will this not leak my activity to my ISP?

**Comment by vlabo** [comment]
Not sure I understand the question compliantly.

If SPN is enabled the DNS requests will be routed through SPN.
If you are using secure DNS (the default one is) the ISP wont be able to see your activity even if the SPN is disabled.

**Comment by NolonQ** [comment]
I thought the spn works like a vpn but instead of using a single ip adress we can hop through multiple proxys and use many ips for all our different programs, even if the spn tunnel is encrypted cant my isp see my dns queries since the spn has no dns?
i am so confused.
