### ISSUE TITLE
Portmaster Networknoise

### ISSUE THREAD

**Issue by Morasithil** [safing/portmaster#1683]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
What is this?
![what is this](https://github.com/user-attachments/assets/f31f63fd-e618-4c75-8f13-39fbd0a07985)
![what is this2](https://github.com/user-attachments/assets/86ddaf1f-0e85-4e11-acac-d67641a639dd)

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by NolonQ** [comment]
> Hey @Morasithil, thank you for raising this issue with us.
> 
> After a first review we noticed that this does not seem to be a technical issue, but rather a configuration issue or general question about how Portmaster works.
> 
> Thus, we invite the community to help with configuration and/or answering this questions.
> 
> If you are in a hurry or haven't received an answer, a good place to ask is in [our Discord community](https://discord.gg/safing).
> 
> If your problem or question has been resolved or answered, please come back and give an update here for other users encountering the same and then close this issue.
> 
> If you are a paying subscriber and want this issue to be checked out by Safing, please send us a message [on Discord](https://discord.gg/safing) or [via Email](mailto:support@safing.io) with your username and the link to this issue, so we can prioritize accordingly.

I can't use discord since these rats require my phone number to keep using discord which they won't get ever.
SO I CAME HERE TO ASK :)

**Comment by NolonQ** [comment]
a community forum instead of discord would be so much better. safing stands for privacy while discord stands for mass suvrillance, doesnt fit if you ask me. F* discord.

**Comment by dhaavi** [comment]
Those who can read have a clear advantage. :smirk: 

If you want to know "Details", I recommend clicking on "Details".

![image](https://github.com/user-attachments/assets/1e0e4ccf-c782-4826-a70f-7491c2b7b38d)
