### ISSUE TITLE
Syntax for custom DNS?

### ISSUE THREAD

**Issue by NolonQ** [safing/portmaster#1684]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
I'm using mullvad vpn and would like to use their DNS with portmaster.
How do i do that?
I've already contacted mullvad support and this is what they responded:

"We don't have any insight in how the syntax for that software should be,
I can only recommend their documentation for that.
All information regarding our DNS over HTTPS/TLS service is available here,
https://mullvad.net/en/help/dns-over-https-and-dns-over-tls"

So what syntax must i use?

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by vlabo** [comment]
We have a wiki page for it
https://wiki.safing.io/en/Portmaster/App/Compatibility/Software/MullvadVPN

Here you can read more about the syntax of the DNS config and some user contributed settings
https://wiki.safing.io/en/Portmaster/App/DNSConfiguration

**Comment by NolonQ** [comment]
Thanks

**Comment by NolonQ** [comment]
> We have a wiki page for it https://wiki.safing.io/en/Portmaster/App/Compatibility/Software/MullvadVPN
> 
> Here you can read more about the syntax of the DNS config and some user contributed settings https://wiki.safing.io/en/Portmaster/App/DNSConfiguration

Sorry to bother you again... regarding mullvad i see this:
# TLS
dot://194.242.2.2:853?verify=dns.mullvad.net&name=Mullvad&blockedif=empty

But which of mullvad's dns servers is used here?
![Capture](https://github.com/user-attachments/assets/b37cfe65-1a43-4311-bed5-657273041e2b)

**Comment by vlabo** [comment]
It using the first one
`verify=dns.mullvad.net` if you want an adblock the config will be
```
dot://194.242.2.2:853?verify=adblock.dns.mullvad.net&name=Mullvad&blockedif=empty
```
or probably easier to read
```
dot://adblock.dns.mullvad.net:853?ip=194.242.2.2&name=Mullvad&blockedif=empty
```

**Comment by NolonQ** [comment]
> It using the first one `verify=dns.mullvad.net` if you want an adblock the config will be
> 
> ```
> dot://194.242.2.2:853?verify=adblock.dns.mullvad.net&name=Mullvad&blockedif=empty
> ```
> 
> or probably easier to read
> 
> ```
> dot://adblock.dns.mullvad.net:853?ip=194.242.2.2&name=Mullvad&blockedif=empty
> ```

Thank you! I didn't understand fro mthe docs what exactly i had to do.
Can i replace the word adblock with all if i want to use all filters or must i change other parameters?
