### ISSUE TITLE
Windows 11 - cannot run Portmaster from regular user acount using "Run as administrator"

### ISSUE THREAD

**Issue by griesi007** [safing/portmaster#1685]
Hi,

in day to day work I am working under a regular user account without administrative permissions. When I try to open the Portmaster UI from this account using "Run as administrator" the UI does not open. I see a elevation prompt. After authentication with a administrative user the Portmaster UI windows frame is shortly displayed then immediately closed. Portmaster was installed via winget with scope machine. I do not know any other application which I cannot "Run as administrator" from an unpriviliged account

**Comment by griesi007** [comment]
With the latest 1.6.24 Beta the behaviour has changed. It still does not work but now shows the attached error message. Can I somehow change the locations which Portmaster uses to store data?
![Screenshot 2024-09-29 183732](https://github.com/user-attachments/assets/f18543f9-08a9-401a-b2c2-0e9d315c472b)

**Comment by griesi007** [comment]
still not possible with 1.6.28

**Comment by griesi007** [comment]
@vlabo your are completely wrong. winget is the only "official" package manager for windows and should be supported. Portmaster is the only package of many i use which does not support winget. Installing packages without a package manager is a security risk and not  best practice for maintaining and assuring a secure system: long time windows did not have a package manager. As one exists now it should be supported. Especially for "security" applications

**Comment by Raphty** [comment]
It is not Safings official install method - someone else has added Portmaster there - Safing provides the .exe on safing.io
