### ISSUE TITLE
Portmaster takes a long time to open UI on wayland on integrated graphics card

### ISSUE THREAD

**Issue by Nyha454** [safing/portmaster#1686]
**What happened**:
Portmaster takes over 2 minutes to open UI on Wayland only if use the integrated graphics

if i use prime-run to run command to open portmaster UI "/opt/safing/portmaster/portmaster-start app --data=/opt/safing/portmaster" it opens almost instantly, GPU is an nVidia RTX 2060, but when i use the integrated graphics which is intel uhd graphics 630 it takes forever.

**What did you expect to happen?**:
Portmaster to open quickly

**How did you reproduce it?**:
launching UI of portmaster 1.6.10 (installed via aur portmaster-stub-bin) stable branch on archlinux using kde 6.1 on wayland

**technical info**
archlinux  kernel 6.10.8 kde 6.1.4 wayland nvidia rtx 2060 mobile 560.35.03 intel uhd graphics 630 using opensource builtin kernel driver
this problem is not present while using X11

**Comment by Raphty** [comment]
hey @Nyha454 I am sorry, but this probably does not have to do with wayland, as I have been running on an igpu and wayland for years now.

I know that back when kde was making the switch to wayland in 6.0 I had tons of issues, like screen flickering and so on. what makes you think that it is Portmaster not something else?

do you see the same issue with other electron UIs?
Can you try the beta channel, we did switch away from electron in the beta already.

**Comment by Nyha454** [comment]
> hey @Nyha454 I am sorry, but this probably does not have to do with wayland, as I have been running on an igpu and wayland for years now.
> 
> I know that back when kde was making the switch to wayland in 6.0 I had tons of issues, like screen flickering and so on. what makes you think that it is Portmaster not something else?
> 
> do you see the same issue with other electron UIs? Can you try the beta channel, we did switch away from electron in the beta already.

Ok, I am going to try other electron apps and also switch to beta channel and update you on this situation.
