### ISSUE TITLE
Portmaster on Windows 11 Pro is regularly causing BSOD - KERNEL_MODE_HEAP_CORRUPTION

### ISSUE THREAD

**Issue by griesi007** [safing/portmaster#1696]
Portmaster on Windows 11 Pro is regularly causing BSOD - KERNEL_MODE_HEAP_CORRUPTION

Der Computer wurde nach einem schwerwiegenden Fehler neu gestartet. Der Fehlercode war: 0x0000013a (0x0000000000000011, 0xffffb80d88010140, 0xffffb80e1c4e8890, 0x0000000000000000). Ein volles Abbild wurde gespeichert in: C:\windows\Minidump\091624-19296-01.dmp. Berichts-ID: cf8fef11-948e-4b1d-bc9c-8abbbc087154.

Please find the DebugInfo as well as MiniDump Analysis attached. 
[PortmasterDebugInfo.txt](https://github.com/user-attachments/files/17015072/PortmasterDebugInfo.txt)
[MiniDumpAnalysis.txt](https://github.com/user-attachments/files/17015076/MiniDumpAnalysis.txt)

**Comment by Raphty** [comment]
try the current beta. this is usually related to torrent and similar software

https://wiki.safing.io/en/FAQ/SwitchReleaseChannel

**Comment by griesi007** [comment]
@Raphty  I am not very comfortable with running beta´s. When will this be released in a stable version? How "stable" is the beta. Are there any issues likely?

**Comment by Raphty** [comment]
you can switch back and forth super easy, and it runns well.

I can't give you an ETA atm.
