### ISSUE TITLE
More verbose Compatibility Detected error messages, at least in Advanced/Developer view

### ISSUE THREAD

**Issue by e-t-l** [safing/portmaster#1699]
**What would you like to add or change?**:
 In-app error notifications, specifically "Detected Compatibility Issue," could include some preliminary diagnostic info. For example, what Portmaster check is failing that triggers the "compatibility issue," or perhaps the name of the process that is conflicting with Portmaster, if that information is possible to find.

**Why do you and others need this?**:
I've noticed a number of issues on this github where users have gotten the "Detected Compatibility Issue" notification and had to do a lot of digging to figure out why. It would probably save a lot of time for users, devs, and community contributors alike if this information were presented in the error notification, at least when Portmaster is set to Advanced view or Developer view.

**Comment by Raphty** [comment]
@e-t-l thank for the feedback and you are right, more info might help

just so you know, there is tons of info on the wiki.

here would be a good place for you to start https://wiki.safing.io/en/Portmaster/Troubleshoot/DebugInfo
