### ISSUE TITLE
Out of date certs - C:\ProgramData\Safing\Portmaster\updates\windows_amd64\kext\portmaster-kext_v1-1-2.sys

### ISSUE THREAD

**Issue by theusername-sudo** [safing/portmaster#1709]
![image](https://github.com/user-attachments/assets/b6f4b0c4-3c86-4186-be59-6797ecef737b)

There seems to be some out-of-date certificates for this specific .sys file @ C:\ProgramData\Safing\Portmaster\updates\windows_amd64\kext\portmaster-kext_v1-1-2.sys

**Comment by Raphty** [comment]
those are EV certs, this is ok. you can read more here: https://en.wikipedia.org/wiki/Extended_Validation_Certificate
