### ISSUE TITLE
Compatible with TunnelBear but needs additional configuration

### ISSUE THREAD

**Issue by KazumaKun1** [safing/portmaster#1710]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

TunnelBear have 3 VPN protocols:
- WireGuard
- OpenVPN
- IKEv2

There's also an "auto" option there 

![picture](https://github.com/user-attachments/assets/f48a9393-60eb-4870-bfb0-d8fab7aa2c55)

The only protocol that's stable is the WireGuard. If you're going to choose "Auto", make sure that TCP Override is off.

**What did not work?**

- OpenVPN - Might work but it's really slow and can't access any internet speed test/safing's documentation.
- IKEv2 - Same issue as OpenVPN

**Debug Information**:

- VPN Version: 4.9.6
- OS: Windows 10 Home Version 22H2

**Comment by Raphty** [comment]
@KazumaKun1 thank you for contributing this information!
