### ISSUE TITLE
Rule groups

### ISSUE THREAD

**Issue by vastar** [safing/portmaster#1713]
**What would you like to add or change?**:
I would like to be able to create rule groups with specific names, and than use group names to allow/block connections or to allow/exclude SPN in different apps, similar to Localhost and LAN.

**Why do you and others need this?**:
Many services have multiple domains and IP addresses, with groups it would be able to create one set of rules and use it everywhere, without having to copy rules every time.

**Comment by Raphty** [comment]
i think I get what you mean, but please let me know if I miss understood.

what you are describing sounds like you want to group app profiles, so they all follow the same set of rules.
you can do that already.

in the apps section top right you see manage
![image](https://github.com/user-attachments/assets/91ee2364-8886-45ad-9261-f310166da70c)

you can select merge or delete profiles, then multi select the ones you want and hit merge.

you can then rename the app profile to whatever you want.

If you want to get one app out you need to edit the "App Profile" and remove the specific process match.
Portmaster will create a new profile as soon as that app is active in the network.

you can then copy and add the settings from the old combined profile if you want.

**Comment by vastar** [comment]
Yes, this is an option, but I would prefer one profile per app. There are a couple drawbacks too, you cannot prioritize profiles and cannot share connection rules with SPN rules. These are two issues I would like to solve.

**Comment by eugenesvk** [comment]
App groups are indeed a worse substitute to the rule groups, they're also not intuitive - why would I need to mess with apps if I want to have global rules applying to all apps?
