### ISSUE TITLE
APP Merge Feature: Expand

### ISSUE THREAD

**Issue by twoex** [safing/portmaster#1714]
It's absolutely beautiful that the app merge feature was implemented to allow grouping/merging of apps.  Definitely helps simplify and isolate applications that branch off.

If I may request a further expansion on this aspect as I feel it is significant...When we group say  5 sub applications that are relative to 1 application, we are asked to name it Application1... When we go into details and look at the history / live connections. It now bulks said apps under 1 label in that group, labelling all 5 apps to be called Application1, instead of maintaining each individual name/source in that group...

(Apologies if below is redundant as above is self explanatory) 

**[Application 1] grouped with [Sub App1 through 5]**
> Device-Local Outgoing | Device | Application 1 | ipadress:port | started xxx time ago | outgoing rules,  and so on...  

the 3rd column should display each application individually in said group... 

Thank you for reading my novel :)

**Comment by Raphty** [comment]
Thank you for the suggestion! this is a good idea, and we will take it into consideration for the future.
