### ISSUE TITLE
Metrics for per-app (or even per-connection?) data usage

### ISSUE THREAD

**Issue by e-t-l** [safing/portmaster#1717]
**What would you like to add or change?**:

Would it be possible for Portmaster to measure not only the number of connection requests from an app, but also the volume of data uploaded/downloaded by those connections? For example, Windows Settings > Network & Internet > Data Usage shows how much data is being used by Firefox and Brave, but not which websites are using the most of that data.

**Why do you and others need this?**:

This could be particularly useful for users on metered networks, where it is critical to be able to identify data-intensive connections. (Also, Windows Data Usage monitoring will differentiate between various userspace apps, but then a generic "System" for all OS-related connections, and it could be useful to know which OS programs are sending/receiving large amounts of data.)

**Comment by Raphty** [comment]
This is a think in Portmaster Plus and Pro
![image](https://github.com/user-attachments/assets/ffeb7766-cc2f-4c68-ac86-890d8de7515a)

**Comment by e-t-l** [comment]
Oh ok thanks, sorry to waste your time! Most Pro features I can see in the app, such as SPN and connection history, with a handy tag indicating they're Pro-only features so us Free users know we should upgrade, but I hadn't seen anything about data usage so I didn't realize it was already included!
