### ISSUE TITLE
Massive new connections increase packet response times too much

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster#173]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

Portmaster experienced high packet response rates when there were _a lot_ of connections.

**What you expected to happen**:

Packet response times should be stable.

**How to reproduce it (as minimally and precisely as possible)**:

Start an aggressive nmap scan.

**Environment**:

Portmaster Version: v0.5.7

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [ ] Windows 10
- [x] Linux

Others probably affected, but not confirmed.

**Comment by TensorTom** [comment]
Same for me. The security tools look awesome but I can't test on a production machine as is due to increased connection latency.

**Comment by TensorTom** [comment]
Just realized this is a duplicate of https://github.com/safing/portmaster/issues/161

**Comment by dhaavi** [comment]
Thank you for confirming this issue.

We actually confirmed quite confidently that this is _not_ the same issue as #161. Here, the Portmaster is overwhelmed with connections, in #161 however, it is a single connection that is failing at some point, and as far as we can current tell, on Windows only.

**Comment by dhaavi** [comment]
This should now be fully resolved with [v0.6.0](https://github.com/safing/portmaster/releases/tag/v0.6.0). The Portmaster should notify you of the update.

If the problem persists with the new version, please reopen this issue.
