### ISSUE TITLE
Cannot start the cinnamon session when restarting  my computer

### ISSUE THREAD

**Issue by Titanet** [safing/portmaster#1733]
### What happened?

From my Journalctl log : 

ov. 09 16:09:28 msi-x370 portmaster-start[905]: [pmstart] 2024/11/09 15:09:28 got terminated signal (ignoring), waiting for child to exit...
nov. 09 16:09:28 msi-x370 portmaster-start[905]:  <INTERRUPT>
nov. 09 16:09:28 msi-x370 portmaster-start[905]: 241109 16:09:28.388 5/run/main:085 ▶ WARN 049 main: program was interrupted, shutting down.
nov. 09 16:09:28 msi-x370 systemd[1]: Stopping Portmaster by Safing...
nov. 09 16:09:28 msi-x370 systemd[1]: avahi-daemon.service: Deactivated successfully.
nov. 09 16:09:28 msi-x370 NetworkManager[893]: <info>  [1731164968.4045] exiting (success)
nov. 09 16:09:28 msi-x370 systemd[1]: Stopped Avahi mDNS/DNS-SD Stack.
nov. 09 16:09:28 msi-x370 systemd[1]: NetworkManager.service: Deactivated successfully.
nov. 09 16:09:28 msi-x370 network[3847]: Stopping network profile 'bridge'...
nov. 09 16:09:28 msi-x370 systemd[1]: Stopped Network Manager.
nov. 09 16:09:28 msi-x370 kernel: br0: port 1(eno1) entered disabled state
nov. 09 16:09:28 msi-x370 dbus-broker-launch[885]: Activation request for 'org.freedesktop.nm_dispatcher' failed.
nov. 09 16:09:28 msi-x370 kernel: igb 0000:21:00.0 eno1: left allmulticast mode
nov. 09 16:09:28 msi-x370 kernel: igb 0000:21:00.0 eno1: left promiscuous mode
nov. 09 16:09:28 msi-x370 kernel: br0: port 1(eno1) entered disabled state
nov. 09 16:09:28 msi-x370 portmaster-start[905]: 241109 16:09:28.489 dules/stop:057 ▶ WARN 051 modules: starting shutdown...
nov. 09 16:09:28 msi-x370 systemd[1]: Requested transaction contradicts existing jobs: Transaction for systemd-hostnamed.service/start is destructive (systemd-update-utmp.service has &#39;stop&#39; job queued, but &#39;start&#39; is included in transaction).
nov. 09 16:09:28 msi-x370 hostnamectl[3876]: Could not get property: Could not activate remote peer &#39;org.freedesktop.hostname1&#39;: activation request failed: a concurrent deactivation request is already in progress
nov. 09 16:09:28 msi-x370 portmaster-start[905]: 241109 16:09:28.749 ◀ EOF
nov. 09 16:09:28 msi-x370 portmaster-start[905]: [pmstart] 2024/11/09 15:09:28 core/portmaster-core exited without error
nov. 09 16:09:28 msi-x370 network[3847]: Stopped network profile 'bridge'
nov. 09 16:09:28 msi-x370 systemd[1]: netctl@bridge.service: Deactivated successfully.
nov. 09 16:09:28 msi-x370 systemd[1]: Stopped Bridge eno1.
nov. 09 16:09:28 msi-x370 systemd[1]: portmaster.service: Deactivated successfully.
nov. 09 16:09:28 msi-x370 systemd[1]: Stopped Portmaster by Safing.
nov. 09 16:09:28 msi-x370 systemd[1]: portmaster.service: Consumed 1.971s CPU time, 263.3M memory peak.

### Additional information
I didn&#39;t have this problem the days before November 9.
I had to disable the service Portmaster to be able to start my cinnamon session.

**Debug-Info**: https://support.safing.io/privatebin/?1d9724b827422797#4ZAmXMNUbdx2nfitmdmg1sdN8RxWLpgptjMxxChgeoap

**Comment by dhaavi** [comment]
Hey @Titanet and @Nextnx, thanks for reporting and chiming in.

We've experienced this before, but I am currently not able to reproduce this.
Please try out if this works in Beta, here is how you can switch: https://wiki.safing.io/en/FAQ/SwitchReleaseChannel

**Comment by Titanet** [comment]
After following your advice and modifying the configuration in Incoming rules, the Cinnamon session launch works again, thank you.

**Comment by dhaavi** [comment]
Great! Thanks a lot for reporting back.
