### ISSUE TITLE
Systemd Service points to wrong location

### ISSUE THREAD

**Issue by markusressel** [safing/portmaster#1737]
**What happened**:
* Install `portmaster-stub-bin` using `yay`
* Try to launch the service usign `sudo systemctl enable --now portmaster`
* Portmaster Systemd service fails to load completely

```
Nov 11 17:41:35 portmaster.service: Unable to locate executable '/var/lib/portmaster/portmaster-start': No such file or directory
```

**What did you expect to happen?**:

* Service starts as expected

**How did you reproduce it?**:

* Remove and reinstall package multiple times

**Debug Information**:

I can't provide UI logs since the service doesn't even start.
However, these are the files that are created by the package:

![image](https://github.com/user-attachments/assets/81d7a3ff-130a-451c-af6f-c180b84a2b9c)

The path to the required binary is:
```
/opt/safing/portmaster/portmaster-start
```
instead of
```
/var/lib/portmaster/portmaster-start
```

which is specified in the systemd file.

I am not sure why this is, but its a pretty frustrating showstopper for the whole thing.

Oh and btw, the portmaster UI also doesn't appear in my launcher, so even after fixing the path, and running the core service successfully, I still have no idea how to launch the UI. I have looked at the official documentation but it doesn't even mention it other than the "fully manual install", which I definitely don't want to do.

IMHO you should really take a close look at the initial install experience, because each time I take a look at portmaster again, I get stuck on things that should not be the things creating major headaches.

**Comment by dhaavi** [comment]
Hey @markusressel, thanks for reporting this.

Where exactly did you install this from?
The current AUR package has the correct path in the service file: https://aur.archlinux.org/cgit/aur.git/tree/portmaster.service?h=portmaster-stub-bin

**Comment by markusressel** [comment]
I have removed the package again, and also removed the systemd file, reinstalled the package and the path is now correct.
I want to point out that removing the package like mentioned in the readme, specifically for arch, does not work as well:

```shell
> sudo pacman -Rnsu portmaster 
error: target not found: portmaster
```

Probably because there is no such package, but the stub package instead.
Uninstalling the stub package did not remove the service file, but I guess that is because of my manual modifications.

The portmaster-core service seems to be running now and writes logs:

```
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.753 sts/lookup:019 ▶ WARN 127 [4x] intel/filterlists: not searching for cache:intel/filterlists/lists/domain/brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.755 sts/lookup:019 ▶ WARN 129 intel/filterlists: not searching for cache:intel/filterlists/lists/asn/16509 because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.755 sts/lookup:019 ▶ WARN 131 intel/filterlists: not searching for cache:intel/filterlists/lists/ipv4/54.71.172.57 because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.755 sts/lookup:019 ▶ WARN 133 intel/filterlists: not searching for cache:intel/filterlists/lists/country/US because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.792 sts/lookup:019 ▶ WARN 135 intel/filterlists: not searching for cache:intel/filterlists/lists/domain/sync-v2.brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.792 sts/lookup:019 ▶ WARN 137 intel/filterlists: not searching for cache:intel/filterlists/lists/domain/brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.792 sts/lookup:019 ▶ WARN 139 intel/filterlists: not searching for cache:intel/filterlists/lists/domain/sync-v2.brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.792 sts/lookup:019 ▶ WARN 141 intel/filterlists: not searching for cache:intel/filterlists/lists/domain/brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.793 sts/lookup:019 ▶ WARN 143 intel/filterlists: not searching for cache:intel/filterlists/lists/domain/sync-v2.brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.793 sts/lookup:019 ▶ WARN 145 intel/filterlists: not searching for cache:intel/filterlists/lists/domain/brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.793 sts/lookup:019 ▶ WARN 147 intel/filterlists: not searching for cache:intel/filterlists/lists/domain/sync-v2.brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.793 sts/lookup:019 ▶ WARN 149 intel/filterlists: not searching for cache:intel/filterlists/lists/domain/brave.com. because filterlists not loaded
Nov 12 22:13:29 M16 portmaster-start[26279]: 241112 22:13:29.795 sts/lookup:019 ▶ WARN 151 [3x] intel/filterlists: not searching for cache:intel/filterlists/lists/domain/sync-alb-152764135.us-west-2.elb.amazonaws.com. because filterlists not loaded
```

These (abbreviated) logs seem fine to me.

Now: How do I launch the UI?
I am using `rofi` as a launcher, which usually picks up new applications immediately, but portmaster is not showing up.
Is this expected? If so, how do I fix this?

**Comment by dhaavi** [comment]
Well, the AUR package includes a desktop file, this should have been picked up.

If you like, you can switch to beta to get the new non-electron UI.

**Comment by markusressel** [comment]
Seems like 
```
rofi -show run
```
does not show it, but

```
rofi -show drun
```

does. I am not sure what the difference is, but I guess ".desktop" files are not shown when using just `run` instead of `drun`. I will have to figure this out myself. Thx for the support.
