### ISSUE TITLE
Portmaster broken on Fedora after trying to use the security enhanced portmaster.service file from the guide

### ISSUE THREAD

**Issue by blind-confused** [safing/portmaster#1745]
**What happened**:

Earlier today I installed Fedora 41 Workstation. 
Before installing Portmaster, I updated my system and made sure that NetworkManager is preinstalled.
I installed Portmaster according to the guide (the Fedora guide, not the manual install guide) and everything was fine, the app was working fine. Until I decided to replace the `/etc/systemd/system/portmaster.service` file with a more security enhanced version of it (there's an instruction on how to do it in the official manual install guide), because I prefer a more secure version. 
After replacing the file using `sudo rm` and `sudo mv` commands (and making sure it worked correctly), I followed the next step of the guide, which is to run `sudo systemctl daemon-reload` and then `sudo systemctl enable --now portmaster`. When running the second command, it said: `Failed to enable unit: File '/etc/systemd/system/portmaster.service' already exists`. I then restarted my computer, hoping it would fix that. I noticed Portmaster didn't start by default. I opened the app and it said that the core service is not running. I clicked "start core service" and it said: Unable to find Portmaster Core Service. Please re-install Portmaster. Error invoking remote control method 'api.startService': [object Object]

how do I fix this? Do I really need to reinstall Portmaster?
I'm a rather non-tech person, that's mostly why I arrived here for help.

I thought it could be due to Fedora's default enforcing mode of SELinux, since the guide says that it's likely to happen. But the guide also says that Portmaster won't launch in that case, and in my case it launched at first (before trying to replace the portmaster.service file). I tried applying the fix for that issue anyway. The first command, `sudo chcon -t bin_t /opt/safing/portmaster/portmaster-start`, ran without errors. But the second command, `systemctl restart portmaster`, gave this output: `Failed to restart portmaster.service: Unit portmaster.service not found.`

**What did you expect to happen?**:
I expected that the portmaster.service file would be replaced without any bugs, because this issue did not happen on my other Linux systems that I used in the past.

**How did you reproduce it?**:
Explained in the main message

**Debug Information**:

I'm unable to share debug information from the Settings page as the Portmaster app is not accessible, it's behind the "failed to launch core service" screen. I'm sorry, I have no idea how to access the Monitor view and it's dropdown app menu. If you let me know, I'll be happy to share the logs.
But here are my logs from `journalctl -u portmaster`, in case any of it is helpful:
[the logs from the command journalctl -u portmaster.txt](https://github.com/user-attachments/files/17800355/the.logs.from.the.command.journalctl.-u.portmaster.txt)

Here are also two log files from the directory `/opt/safing/portmaster/logs/core`. 
[the 2024-11-18-08-25-37.error.log file.txt](https://github.com/user-attachments/files/17800337/the.2024-11-18-08-25-37.error.log.file.txt)
[the 2024-11-18-08-25-37.log file.txt](https://github.com/user-attachments/files/17800338/the.2024-11-18-08-25-37.log.file.txt)

Let me know if any more logs or info are needed.

**Comment by vlabo** [comment]
There is no security enhanced version of portmaster service. I think what you are referring to is
Security-Enhanced Linux (SELinux), which is linux with additional security features.
You need to take care of extra steps when you are doing manual installation. If you are using the installer you dont need to do the extra steps since the installer is doing it for you.

Since we cant be sure what exactly you did, its better if you just reinstall it.

If Im mistaking and you are using some 3-party guide please provide a link to it.

**Comment by vlabo** [comment]
Thanks for the clarification.

The file referred in the links is the same file used by the installer.
The manual install is for distributions that we dont have official installer fallowing the steps out of context will result in weird result if you dont understand what every step does.
