### ISSUE TITLE
If portmaster is ON means it is taking 60 to 80 seconds of duration to block incoming traffic

### ISSUE THREAD

**Issue by rajagopalan181** [safing/portmaster#1752]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

If portmaster is ON means it is taking 60 to 80 seconds of duration to block incoming traffic

**What did you expect to happen?**:

incoming traffic should be blocked immediately when we ON the portmaster.

**How did you reproduce it?**:

**Debug Information**:

**Comment by Raphty** [comment]
What are you talking about? do you mean that the other device only recognizes that the traffic is not allowed after 60 to 80 seconds? that is due to timeouts and how connection blocking is communicated.

**Comment by rajagopalan181** [comment]
When we start the portmaster service in windows it is taking around 60 to 80 seconds of time period for the income traffic rules to applied but outgoing traffic rules applied immediately when we on the portmaster     ---- On Mon, 25 Nov 2024 15:48:34 +0530  Raphael ***@***.***> wrote ----  
What are you talking about? do you mean that the other device only recognizes that the traffic is not allowed after 60 to 80 seconds? that is due to timeouts and how connection blocking is communicated.

**Comment by vlabo** [comment]
Can you provide example how you are testing this and on which OS.
The way that Portmaster works it does not have a difference between blocking incoming and outgoing connection, so they should be blocked at the same time.

**Comment by rajagopalan181** [comment]
Test what we done is1) In this test windows defender firewall is off2) next all incoming traffic is  blocked in port master3) next we restarted the  portmaster4) and we ping the portmaster pc lan ip and the ICMP request was not block for 60 to 80 second after that ICMP request is blocked    ---- On Tue, 26 Nov 2024 17:26:15 +0530  Vladimir ***@***.***> wrote ----  
Can you provide example how you are testing this and on which OS. 
The way that Portmaster works it does not have a difference between blocking incoming and outgoing connection, so they should be blocked at the same time.

**Comment by vlabo** [comment]
Thanks for letting us know.
It seem like this is already fixed in the beta channel.
If you dont want to wait until is moved to the release channel you can switch to the beta version:
https://wiki.safing.io/en/FAQ/SwitchReleaseChannel
