### ISSUE TITLE
inspectThenVerdict() called twice

### ISSUE THREAD

**Issue by Raskaro** [safing/portmaster#18]
inspectThenVerdict() is called twice, once synchron, once in a gorouting:
https://github.com/safing/portmaster/blob/321a355c302e1de51b6f8832534cd860bb3b6515/firewall/firewall.go#L271
=> https://github.com/safing/portmaster/blob/321a355c302e1de51b6f8832534cd860bb3b6515/network/link.go#L78
=> https://github.com/safing/portmaster/blob/321a355c302e1de51b6f8832534cd860bb3b6515/network/link.go#L182
and
https://github.com/safing/portmaster/blob/321a355c302e1de51b6f8832534cd860bb3b6515/firewall/firewall.go#L272

**Comment by dhaavi** [comment]
Resolved by recent revamp.
