### ISSUE TITLE
errors after installation on windows 10

### ISSUE THREAD

**Issue by baermathias** [safing/portmaster#196]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:
I have downloaded and installed the app from https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe. After starting it, I get the following errors:

subsystems:
```
The subsystem framework failed to start or stop one or more modules.
Error: modules: could not start module interception: interception: could not get kext dll: failed to make request to "https://updates.safing.io/windows_amd64/kext/portmaster-kext_v1-0-3.dll": Get "https://updates.safing.io/windows_amd64/kext/portmaster-kext_v1-0-3.dll": dial tcp: lookup updates.safing.io: no such host
Check logs for more information.
```

interception:
```
failed to start module: interception: could not get kext dll: failed to make request to "https://updates.safing.io/windows_amd64/kext/portmaster-kext_v1-0-3.dll": Get "https://updates.safing.io/windows_amd64/kext/portmaster-kext_v1-0-3.dll": dial tcp: lookup updates.safing.io: no such host
```

**What you expected to happen**:
Running app

**How to reproduce it (as minimally and precisely as possible)**:
Just install the windows installer on win10

**Anything else we need to know?**:

**Environment**: Win 10

Portmaster Version: 0.5.7

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>

Resource | Active Version | Latest/Selected Version | Downloaded |  
-- | -- | -- | -- | --
all/intel/geoip/geoipv4.mmdb.gz |   | 20200514.6.49 | false
all/intel/geoip/geoipv6.mmdb.gz |   | 20200514.6.49 | false
all/intel/lists/base.dsdl | 20201031.23.0 | 20201031.23.0 | true
all/intel/lists/index.dsd |   | 2020.9.22 | false
all/intel/lists/intermediate.dsdl | 20201121.23.0 | 20201121.23.0 | true
all/intel/lists/urgent.dsdl | 20201123.11.0 | 20201123.11.0 | true
all/spn/bootstrap.dsd |   | 0.0.5 | false
all/ui/modules/assets.zip | 0.1.5 | 0.1.5 | false
all/ui/modules/base.zip | 0.2.10 | 0.2.10 | true
all/ui/modules/console.zip | 0.1.10 | 0.1.10 | false
all/ui/modules/monitor.zip | 0.2.3 | 0.2.3 | false
all/ui/modules/profilemgr.zip |   | 0.1.7 | false
all/ui/modules/settings.zip |   | 0.1.8 | false
darwin_amd64/control/portmaster-control |   | 0.3.5 | false
darwin_amd64/core/portmaster-core |   | 0.5.6 | false
darwin_amd64/hub/spn-hub |   | 0.2.3 | false
darwin_amd64/start/portmaster-start |   | 0.4.2 | false
linux_amd64/app/portmaster-app |   | 0.1.10 | false
linux_amd64/control/portmaster-control |   | 0.3.5 | false
linux_amd64/core/portmaster-core |   | 0.5.7 | false
linux_amd64/hub/spn-hub |   | 0.2.3 | false
linux_amd64/notifier/portmaster-notifier |   | 0.1.9 | false
linux_amd64/packages/portmaster-installer.deb |   | 0.4.1 | false
linux_amd64/start/portmaster-start |   | 0.4.2 | false
windows_amd64/app/WebView2Loader.dll |   | 0.10.0 | false
windows_amd64/app/portmaster-app.exe |   | 0.1.10 | true
windows_amd64/app/webview.dll |   | 0.10.0 | false
windows_amd64/control/portmaster-control.exe |   | 0.3.5 | false
windows_amd64/core/portmaster-core.exe | 0.5.7 | 0.5.7 | true
windows_amd64/hub/spn-hub.exe |   | 0.2.3 | false
windows_amd64/kext/portmaster-kext.dll |   | 1.0.3 | false
windows_amd64/kext/portmaster-kext.sys |   | 1.0.3 | false
windows_amd64/notifier/portmaster-notifier.exe |   | 0.1.9 | true
windows_amd64/notifier/portmaster-snoretoast.exe |   | 0.6.0 | true
windows_amd64/packages/portmaster-installer.exe |   | 0.4.2 | false
windows_amd64/start/portmaster-start.exe | 0.4.2 | 0.4.2 | true

</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs`
 - Windows: `%PROGRAMDATA%\Safing\Portmaster\logs`

**Comment by dhaavi** [comment]
Hi @baermathias, thanks for reporting this issue.

This behavior would occur if there is no network connection. Were you connected to the Internet when this occurred?
Also, did the installer mention anything about not being able to download resources?

**Comment by baermathias** [comment]
Just tried to start it again. I am connected to the internet, but the errors are stills there

**Comment by dhaavi** [comment]
I have improved the installation routine with [v0.6.0](https://github.com/safing/portmaster/releases/tag/v0.6.0). Please download the new installer and try again. The installer requires Internet connectivity to fully install all components - it will soft-fail otherwise, because the service can also download resources.

**Comment by dhaavi** [comment]
I am closing this issue for now, due to not hearing back from anyone who is/was affected. We _think_ this issue has been resolved, but we don't have confirmation yet. If it happens to persist, please reopen this issue, so we can take another look.

**Comment by Crumb93** [comment]
Hello, I'm having this issue on the latest version from: 

https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe

I'm using Windows 11

**Comment by dhaavi** [comment]
I've replied in the new issue references above.
