### ISSUE TITLE
DNS requests are sometimes blocked in error

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster#203]
This affects v0.6.0 on ~all platforms~ Linux.

We are still triaging the issue, but it seems that in some cases the Portmaster will block queries that should result in an error or similar.

Clearing the DNS cache or waiting usually resolves the issue for cached queries for the moment.

**Comment by dhaavi** [comment]
This issue should now be resolved on Linux, please report if you are still having DNS problems on Linux.

**Comment by ppacher** [comment]
I guess we can close this now?

**Comment by dhaavi** [comment]
We are still having problems on Windows, which I am working on now. Can't fully say where they come from, so I want to leave this open for now.

**Comment by dhaavi** [comment]
This should be now mostly resolved with [v1.0.7 of the Windows Kext](https://github.com/safing/portmaster-windows-kext/releases/tag/v1.0.7). There still seem to be IPv6 requests that slip through and get blocked, continuing to investigate.

**Comment by dhaavi** [comment]
We will continue to track this internally, but closing this issue here in order to clean up our issues. If you experience something like this please reopen this issue or create a new issue if you are unsure if it is connected to this.
