### ISSUE TITLE
Various outgoing traffic logged under Unidentified Processes

### ISSUE THREAD

**Issue by MPeti1** [safing/portmaster#204]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:
Portmaster logs a few PTR querys, connections to domain names, and global P2P connections under the Unidentified Processes category.

**What you expected to happen**:
Portmaster recognizing the source of the connections

**How to reproduce it (as minimally and precisely as possible)**:
I was seeing these after booting the system (from hibernation, but I don't think this matters) and connecting to the network over wifi (no wired connection).

**Environment**:

Portmaster Version: 0.6.0

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
[core\2020-11-25-12-00-52.log](https://github.com/safing/portmaster/files/5611014/2020-11-25-12-00-52.log)

Screenshot of the UI showing the connections:
![image](https://user-images.githubusercontent.com/9215491/100523103-01d8fb80-31ae-11eb-9d14-c9a24a46b02c.png)

**Comment by dhaavi** [comment]
Thanks for reporting this. I already found hints of this in a previously supplied log file and a fix is also ready in review in #202. After it has been merged and released, please check for this issue again.

**Comment by dhaavi** [comment]
This fix was just released with [v0.6.1](https://github.com/safing/portmaster/releases/tag/v0.6.1).

This means that this should not happen anymore in the extent that it did. Although we are still working on Windows performance issues.

Please report back if the issue persists.
