### ISSUE TITLE
Portmaster fails to set up iptables integration on Arch Linux

### ISSUE THREAD

**Issue by cocoonkid** [safing/portmaster#214]
**Checklist**:

- [x ] I'm using the official portmaster release (i.e no custom builds)
- [x ] I searched for similar/existing issues first.
- [x ] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.558 ules/start:089 ▶ INFO 001 modules: initiating...
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.558 ules/start:193 ▶ INFO 002 modules: started database
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.558 ules/start:193 ▶ INFO 003 modules: started runtime
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.558 ules/start:193 ▶ INFO 004 modules: started config
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.561 ules/start:193 ▶ INFO 005 modules: started rng
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.561 ules/start:193 ▶ INFO 006 modules: started base
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.561 ules/start:193 ▶ INFO 007 modules: started subsystems
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.561 ules/start:098 ▶ INFO 008 modules: initiated subsystems manager
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.661 dules/mgmt:094 ▶ INFO 009 modules: managing changes
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.661 ules/start:193 ▶ INFO 010 modules: started netenv
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.662 ules/start:193 ▶ INFO 011 modules: started notifications
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.662 ules/start:193 ▶ INFO 012 modules: started api
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.662 api/router:062 ▶ INFO 013 api: starting to listen on 127.0.0.1:817
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.662 ules/start:193 ▶ INFO 014 modules: started status
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.686 ules/start:193 ▶ INFO 015 modules: started resolver
Dec 13 12:50:13 sonos portmaster-start[140423]: 201213 12:50:13.943 r/updating:096 ▶ INFO 016 updates: updated index all/intel/intel.json
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.007 ules/start:193 ▶ INFO 017 modules: started updates
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.007 ules/start:193 ▶ INFO 018 modules: started geoip
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.007 ules/start:193 ▶ INFO 019 modules: started filterlists
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.007 ules/start:193 ▶ INFO 020 modules: started intel
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.007 ules/start:193 ▶ INFO 021 modules: started ui
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.069 ater/fetch:074 ▶ INFO 022 updates: fetched https://updates.safing.io/all/intel/lists/index_v2020-9-22.dsd (stored to /var/lib/portmaster/updates/all/intel/lists/index_v2020-9-22.dsd)
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.129 ules/start:193 ▶ INFO 023 modules: started profiles
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.129 ules/start:193 ▶ INFO 024 modules: started processes
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.129 ules/start:193 ▶ INFO 025 modules: started network
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.324 dules/mgmt:108 ▶ WARN 026 modules: could not start module interception: could not initialize nfqueue: running [/usr/bin/iptables -t mangle -N C170 --wait]: exit status 3: iptables v1.8.6 (legacy): can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
Dec 13 12:50:14 sonos portmaster-start[140423]: Perhaps iptables or your kernel needs to be upgraded.
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.324 dules/mgmt:112 ▶ INFO 027 modules: finished managing
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.324 les/worker:029 ▶ WARN 028 subsystems: worker initial subsystem configuration failed: modules: could not start module interception: could not initialize nfqueue: running [/usr/bin/iptables -t mangle -N C170 --wait]: exit status 3: iptables v1.8.6 (legacy): can't initialize iptables table `mangle': Table does not exist (>
Dec 13 12:50:14 sonos portmaster-start[140423]: Perhaps iptables or your kernel needs to be upgraded.
Dec 13 12:50:14 sonos portmaster-start[140423]: 201213 12:50:14.817 ine-status:205 ▶ INFO 029 netenv: setting online status to Online (all checks passed)
Dec 13 12:50:24 sonos portmaster-start[140423]: 201213 12:50:24.019 r/updating:096 ▶ INFO 030 updates: updated index stable.json

**What you expected to happen**:

That it works, IPTables is up-to-date

**How to reproduce it (as minimally and precisely as possible)**:
Just follow the arch linux installation

**Environment**:

Archlinux  5.9.11-arch2-1
Portmaster Version: 
portmaster-core_v0-6-3

**Comment by ppacher** [comment]
Hi @cocoonkid,
Thanks for trying out Portmaster!

I guess you just did an kernel upgrade (like running `pacman -Suy`) but didn't reboot. By default, Arch will compile and install kernel modules for the installed kernels and a kernel upgrade may remove the modules of the now outdated kernel even if you're still using it. Please reboot your machine and try again.

I'm running portmaster fine on Arch with a 5.9.6 kernel. To ensure it's not an issue with the upstream 5.9.11 I'm going to update my system sometime tomorrow.

**Comment by cocoonkid** [comment]
Yes indeed that was it. Had to fix my screen first (and blacklist noveau first). It works like a charm now!

5.9.14 here.

**Comment by cocoonkid** [comment]
Thanks for this great piece of software!
