### ISSUE TITLE
[UI] Filterlists: Unselecting a list als unselects the whole category

### ISSUE THREAD

**Issue by davegson** [safing/portmaster#216]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

After de-selecting a child list, iE from Malware, it de-selects all Malware lists as a result.

**What you expected to happen**:

That it only de-selects the child I wanted to.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to settings/privacy filter/filter lists, deselect a child.
2. go out of settings and then back in
3. see all of the children deselected

Here are some images:

![1_before](https://user-images.githubusercontent.com/3080765/102073428-33cb9e00-3dfb-11eb-9bac-cc3c6d0d78e4.png)
![2_one_unselection](https://user-images.githubusercontent.com/3080765/102073433-35956180-3dfb-11eb-9e69-eb77b1326cb4.png)
![3_after](https://user-images.githubusercontent.com/3080765/102073437-36c68e80-3dfb-11eb-9fc6-4f5f95badab9.png)

**Environment**:

Portmaster Version: 0.6.3

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

If applicable you can provide related sections from the log files and ensure to **remove sensitive or otherwise private information**.
 - Linux: `/var/lib/portmaster/logs`
 - Windows: `%PROGRAMDATA%\Safing\Portmaster\logs`

**Comment by dhaavi** [comment]
Thanks for reporting this issue.

I was able to reproduce this. For context: Between screenshots 2 and 3, you need switch the page away from the settings and back again.

Note: For issue regarding the user interface, please open issues in our UI repository at https://github.com/safing/portmaster-ui

**Comment by davegson** [comment]
moved to https://github.com/safing/portmaster-ui/issues/96
