### ISSUE TITLE
Allow text selection of portmaster version, hostnames and IPs to copy it

### ISSUE THREAD

**Issue by northys** [safing/portmaster#226]
**What would you like to be added**:

I'm not able to select portmaster version so I can't report it for you in issues. Also I would love if all IP's and hostnames and probably some other text could be selected and copied.

**Why is this needed**:

=)

**Comment by dhaavi** [comment]
We had this as an internal task, but it somehow got lost. Thanks for the reminder, it's on track again.

Also, we will soon have a button that copies all the important information for reporting issues to your clipboard with one click!

**Comment by dhaavi** [comment]
This is ready for release - coming soon!

**Comment by northys** [comment]
:eyes:

**Comment by northys** [comment]
@dhaavi do you have any ETA for new release please? I'm looking forward to test it

**Comment by davegson** [comment]
the newest release was prepared last Monday (1st Feb) but sadly had to be aborted on Tuesday since weird behavior broke things on Windows. Daniel will probably be able to give you a new ETA next week.

**Comment by dhaavi** [comment]
Update: We have a fix for the issue that kept us from releasing. Release is now scheduled (but not guaranteed) for tomorrow. Thank you for your patience.

**Comment by dhaavi** [comment]
This was fixed in [ui/portmaster-v0.1.4](https://github.com/safing/portmaster-ui/releases/tag/portmaster-v0.1.4) and further improved in [ui/portmaster-v0.1.5](https://github.com/safing/portmaster-ui/releases/tag/portmaster-v0.1.5), which was released today.

Please report back if this works for you as expected.

**Comment by northys** [comment]
I can confirm that everything in the right content "panel" can be copied.
