### ISSUE TITLE
Add more DNS providers

### ISSUE THREAD

**Issue by CyberPunkInterface** [safing/portmaster#246]
**What would you like to be added**:  More DNS providers added as an option preconfigured

 >**suggestions** BlahDNS, LibreDNS, NextDNS, NixNet, PowerDNS, and Snopyta<

**Why is this needed**:  To add more options for the users of new installs.

**Comment by dhaavi** [comment]
Hey @CyberPunkInterface, I will raise this issue with the team and will report back then. Our next meeting for stuff like this is in four weeks (we just had one, and the one in two weeks got cancelled).

Here are some preliminary thoughts on this:

- We want to empower our users, so giving them more choices is generally always good.
- At the same time we don't want to overwhelm users and make them feel lost, so our designer regularly challenges us to reduce and simplify as far as we can.
- Preconfigured options are not just convenience, but convey recommendation and trust. All current preconfigured services have been [investigated and vetted by us](https://safing.io/blog/2020/07/07/how-safing-selects-its-default-dns-providers/). Obviously, Google's public DNS service will never find its way into there.

If you have any further thoughts on this topic or additional things you want us to talk about internally, that would help us greatly to understand your needs!

**Comment by davegson** [comment]
Thanks for your input @CyberPunkInterface!

I see your suggestions are all recommended by privacytools.io. Naturally, they are good at vetting so I would trust their recommendations overall. The thing is, with the defaults we select, we as a company put our name at stake too. So next to having more maintenance, adding more providers also means that it is more likely that one of the chosen ones turn sour.

However, I do see an alternative approach here where we make user choice easier. We are currently extending our documentation and there will be a section where we talk about every setting in more detail. Something like Firefox' Docs where they explain every `about:config`. 

And then, we will sooner or later link the settings in the Portmaster to these docs. So in there, in the docs, I feel it might be a good place to list _examples_ of how to configure custom DNS providers. And these examples can be extensive, so having all your suggestions in there feels natural to me.

As Daniel mentioned, we like to discuss bigger issues with the whole team first to get a broad set of perspectives. We will keep you in the loop as things happen

**Comment by davegson** [comment]
Oh I forgot to ask - do you think that would simplify things adequately? What do you think of the suggested approach in general?

**Comment by CyberPunkInterface** [comment]
Yes I think everything sounds good with this approach.

>So in there, in the docs, I feel it might be a good place to list examples of how to configure custom DNS providers

Yes that would be good to have documentations/Examples of configurations for all recommended by privacytools.io

**Comment by dhaavi** [comment]
Just to give you a small update: We talked about this as a team and will continue similar to what we discussed.

**Comment by davegson** [comment]
this just got published - hope it provides value
