### ISSUE TITLE
More readable log file formatting

### ISSUE THREAD

**Issue by MPeti1** [safing/portmaster#250]
**What would you like to be added**:
Tab (instead of space) separated log files.

**Why is this needed**:
I think log files are hard to read from a text editor, especially if I want to look for a series of connected events, because often the next line is a different facility, and so the message will always start at different positions.

I started using a spreadsheet utility and they help a lot with marking odd rows, filtering and breaking columns into.. columns, but since the columns are delimited by spaces, the utility will break every word into a new column. Excel even confuses itself on the first line, because on newer versions it seems it can't be turned off to look at the first line as a header.
I think tab delimitation would help, because most such utilities support it, and this is a character that probably isn't used anywhere else in the logs.
This is a minor inconvenience, but since debugging usually goes with a lot of log reading, this might help a lot in the end.
What do you think?

I'm not actually sure if I can have a say in how you manage your logs, but I thought it couldn't hurt to ask :)
Also, can I ask what methods do you currently use to examine logs? Maybe this is not needed at all, and I just didn't think of something simpler

**Comment by davegson** [comment]
I cannot answer on the technical part, but wanna comment regarding:

> I'm not actually sure if I can have a say in how you manage your logs, but I thought it couldn't hurt to ask :)

Do not worry - we appreciate all kinds of input; we can only benefit from receiving other perspectives. And regardless of what is done in the end, a conversation around a topic will make any decision better.  So thanks for all your thoughts and contributions!

@dhaavi or @ppacher will chime in with the technical details tomorrow or next week.

**Comment by dhaavi** [comment]
Hey @MPeti1, sorry for the delay and thank you for your thoughts!

We usually just read logs with a text editor. I haven't found that the different facilities/modules and the different indentation they induce are a problem. For us, debugging normally revolves around the handling of connections or dns requests. In this case there are loads of logs that belong to a single "event", so we created tracing logs, where all logs of an event are printed bundled together.

You can find an example for this in the docs: https://docs.safing.io/portmaster/architecture/core-service/fundamentals/#logging

Using a tab is probably not a bad idea. Currently, we always manually add the facility/module to the log lines, as logs are not integrated into the module system, but are a separate "library". This also means that putting a tab between the module name and the log message would require us to change _all_ log messages. We would like to take a cleaner approach in the future, and that is where we will re-evaluate how we will handle the module name in the log lines.

I would love to hear how the tracing log format works for you!

**Comment by MPeti1** [comment]
No problem! Also, sorry for the late reply, my todo list has "overflown".

What made me suggest this is that most of the times I checked the logs I wanted to look at logs of a specific kind rather than complete events. This would be easier both if I could filter for specific kewords of specific columns, and also if all columns would be aligned and I wouldn't need to search with my eyes where does the next line of interest start. CSV management tools can do both of these, and there are a few of them already (excel for more advanced things, but [CSVFileView](https://www.nirsoft.net/utils/csv_file_view.html) from Nirsoft is plenty for this)

Currently I can't come up with an example of when is it useful, as I don't have access to longer logs now, though.

> We would like to take a cleaner approach in the future, and that is where we will re-evaluate how we will handle the module name in the log lines.

Ok, no problem! :)

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
