### ISSUE TITLE
More intuitive DNS names

### ISSUE THREAD

**Issue by Celuni** [safing/portmaster#253]
**What would you like to be added**:
I'd like to have more intuitive DNS names, at least for your default ones.

For example 1.1.1.2 is for _**Malware Blocking**_ where 1.1.1.3 is for _**Malware and Adult Content**_.
Since you only call it _Cloudflare_ it is confusing since they have three different groups of DNS.

Simply call it **_Cloudflare No Malware_**. 
Or add a small panel to when you hover it, it shall give you a little more info about what you get from them.
It is up to you what you call it in the end, or if you just want minimal info.

**Why is this needed**:
To avoid confusion for not so experienced users.

**Comment by Celuni** [comment]
Should probably be moved to portmaster-ui, sorry my bad.

**Comment by dhaavi** [comment]
Thanks for this input. I too think that this would improve usability. I will bring this up with the team at our next meeting for stuff like this.

Internal note: tracked by CC#1809.

**Comment by dhaavi** [comment]
Update: We will move forward with this and there should be an improvement in the coming weeks.

**Comment by dhaavi** [comment]
This is improved now in [v0.6.6](https://github.com/safing/portmaster/releases/tag/v0.6.6). More improvements to the docs in that regard are in review.

I am closing this now, please continue to comment if needed.
