### ISSUE TITLE
The game League of Legends doesn't start at all

### ISSUE THREAD

**Issue by Celuni** [safing/portmaster#255]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**: When starting the League of Legends client it spawns 3 processes and one of them seems to bug at P2P and "Local Outgoing".

**How to reproduce it (as minimally and precisely as possible)**: Simply start league (the patcher) from desktop and it bugs after few seconds you can see it just like in my screenshot.

**Anything else we need to know?**: I've tested with all settings disabled (even used dns://1.1.1.1) and wildcard on out-/incoming connection but it still bugs. Notice the undefined NaN. 
It clearly isn't intended, I guess by default portmaster blocks it if something fails even tho I have wildcard permitted everything.

**Side info: Torrenting works btw.**

![del](https://user-images.githubusercontent.com/35907275/107850477-13bc5900-6e03-11eb-92a0-2537385bdfd2.png)

![del](https://user-images.githubusercontent.com/35907275/107850502-2f276400-6e03-11eb-8ee4-93dd3ba9fe22.png)

![del](https://user-images.githubusercontent.com/35907275/107850463-f9827b00-6e02-11eb-8711-1a6b05332ddf.png)

Portmaster Version: 0.6.5

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux
  - Please provide the output of `cat /etc/os-release`

**Comment by Celuni** [comment]
`210213 14:30:01.024 all/master:150 > WARN 237 filter: failed to find local peer process PID: could not find connection in system state tables`

I think that causes the undefined NaN problem, the client instantly closes (because the request gets gets blocked by something we can't see).

**Comment by dhaavi** [comment]
Thank you for reporting this.

I will look into this in the coming weeks. If you switch the UI Mode to Developer, you will see a couple more connections, which we deem "internal" in the sense of "not interesting for the normal user", but it might shed some more light on this issue.

**Comment by davegson** [comment]
just a thought I had and wanted to double-check:

@Celuni are your settings for _Privacy Filter > Network Scope > Connection Types_ correctly configured? If a connection is blocked by the `Network Scope`, allowing connections via `Rules`, even wildcards, will _not_ overwrite behavior since the `Network Scope` is stronger.

Be sure your Network Rating (next to the shield) is at a level where P2P or incoming connections are _not_ blocked.

I assume you set things up correctly but just wanted to double-check.

**Comment by dhaavi** [comment]
This could be similar to #258, where extensive checking leads to longer than usual packet handling times and makes the program think that the connection won't work. What might be happening here is that LoL is trying to connect to the Riot Client.

Maybe the fix we have in progress for #258 will also work here.

If you go to the settings and switch the "UI Mode" to "Developer" you might see more information regarding the connections of LoL. Maybe that'll give us another hint.

**Comment by dhaavi** [comment]
This might now be fixed with [v1.0.9 of the Portmaster Kernel Extension](https://github.com/safing/portmaster-windows-kext/releases/tag/v1.0.9). If you are not reinstalling, please make sure you have v1.0.9 of the Kext by looking it up in the version details on the settings page.

**Comment by dhaavi** [comment]
With [v0.6.7](https://github.com/safing/portmaster/releases/tag/v0.6.7), we were able to work around the requirement that the Portmaster needs the Windows DNS-Client service stopped. The Portmaster now re-enables the DNS-Client and the new installer does not even disable it anymore now.

This might also have an effect on this issue. If you find the time to test this, please report back.

**Comment by Celuni** [comment]
**Yes the problem is fixed.**
I'm sorry for not testing it earlier, I'm now using Portmaster again (v0.6.17-beta).

**Comment by davegson** [comment]
no worries, life does not always allow to do everything immediately. Good to hear it is fixed, thanks for reporting in retrospect!
