### ISSUE TITLE
AppImage Installer for Linux

### ISSUE THREAD

**Issue by peepopoggers** [safing/portmaster#269]
**What would you like to be added**:
Appimage executable as an installer option.

**Why is this needed**:
Appimages support a wide range of linux distros out of the box, and can help with expanding to all distributions instead of a select few. If you add a download i would also recommend linking the appimage launcher, so the app can install like a normal deb.

**Comment by dhaavi** [comment]
Hey @peepopoggers,
thanks for giving us feedback on this and suggesting AppImage!

I had a deeper look at this and I fear that AppImage does not support the complexity that we require in our setup routine. For example, we actually install three software components, one system service with a specialized and secured systemd service configuration as well as two .desktop applications. They are run with different users and permissions. From what I have seen, AppImage unfortunately only provides a rather generic setup routine, which is insufficient for us.

We currently have installers for Debian/Ubuntu and Arch Linux. We hope to expand these in the near future.

Are you personally affected by this? Ie. is there no installer available for your distro?

**Comment by Taza53** [comment]
what about flatpak?

**Comment by dhaavi** [comment]
From what I have researched about flatpak - and snap for that matter - in the past, they both also don't seem to be a good match for us. Especially as their main use cases are to "freeze" the application and sandbox it - both of which would break the Portmaster in addition to the problems mentioned above about AppImage.

We actually do sandbox/restrict the portmaster as far as possible using systemd.

**Comment by shivanshsinghx365** [comment]
may i kindly know how do i install it in an arch based distro (Manjaro to be precise) ?
i tried searching in AUR but it wasn't there even and the website only seems to have a .deb package :(

**Comment by shivanshsinghx365** [comment]
if arch users can get the program from aur directly(if that's possible), then most of us won't ask for app images as most prominent linux distros will get covered automatically if we can include an arch linux package and an rpm package for the program aswell.

**Comment by shivanshsinghx365** [comment]
if arch users can get the program from aur directly(if that's possible), then most of us won't ask for app images as most prominent linux distros will get covered automatically if we can include an arch linux package and an rpm package for the program aswell.

**Comment by dhaavi** [comment]
We are in process of getting into the AUR, please follow https://github.com/safing/portmaster-packaging/issues/30 for updates on that.

We have updated the docs a couple days ago to include both a `PKGBUILD` as well as a `.pkg` directly, if you prefer that. You can find everything you need here: https://docs.safing.io/portmaster/install/linux

An `.rpm` package is planned as well.

**Comment by davegson** [comment]
> may i kindly know how do i install it in an arch based distro (Manjaro to be precise) ?

we do link to the install instructions from the download section, but that seems not to be clear enough. Thanks for letting us know!

Funnily, we just had a talk today about adding an Arch Button to the download section and we concluded: "Nah, it works good enough as it is". Well... not so much xD

**Comment by dhaavi** [comment]
I'm concluding this feature request with the analysis that AppImage/Flatpak/Snap do not fit our needs currently. If our needs change or these technologies change to fit our needs better in the future, we will re-evaluate them.

For now, we think the best way to go forward is to provide high quality installers for the major distribution branches directly.
