### ISSUE TITLE
Dependency problem, while installing on Ubuntu 18.4

### ISSUE THREAD

**Issue by DebanjanBarman** [safing/portmaster#270]
Getting error 

$sudo dpkg -i portmaster-installer.deb 

(Reading database ... 236890 files and directories currently installed.)
Preparing to unpack portmaster-installer.deb ...
Unpacking portmaster (0.5.0.0) over (0.5.0.0) ...
dpkg: dependency problems prevent configuration of portmaster:
 portmaster depends on libnetfilter-queue1; however:
  Package libnetfilter-queue1 is not installed.

dpkg: error processing package portmaster (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu3.18.04.2) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Errors were encountered while processing:
 portmaster

**Comment by dhaavi** [comment]
The package `libnetfilter-queue1` does seem to exist in Ubuntu 18.04 / `bionic`: https://packages.ubuntu.com/bionic/libnetfilter-queue1

Do you have the universe repository enabled?

---

You can enable the universe repository like this:
```
sudo add-apt-repository universe
sudo apt-get update
```

**Comment by DebanjanBarman** [comment]
Thanks, That helped.

**Comment by DebanjanBarman** [comment]
Closing the issue
