### ISSUE TITLE
high cpu usage in manjaro kde on using portmaster 0.6.6

### ISSUE THREAD

**Issue by shivanshsinghx365** [safing/portmaster#274]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:
while using latest portmaster build for manjaro kde, i noticed my cpu usage go from 5% to 50%

**What you expected to happen**:
i hoped cpu usage to remain around 2-5%

**How to reproduce it (as minimally and precisely as possible)**:
just opening the application on manjaro kde(atleast on my system) makes the issue visible in system monitors like htop

**Anything else we need to know?**:
my specs are as follows so i am not sure if this is a bug or just my system, but i am sure even chromium and firefox use less than this much amount of cpu in my laptop
i have an i3-7020u, an hdd and a 4gb ddr4 ram

**Environment**: 
KDE Plasma version: 5.21.2
KDE Framework Version: 5.79.0
Qt Version: 5.15.2
Linux Kernel: 5.4.101-1 LTS 

**Portmaster Version**: 

<details>
  <summary>Versions from the `About` page in Portmaster's UI: 0.6.6</summary>
  <0.6.6>
</details>

Operating System:
- [x] Linux
  - output of `cat /etc/os-release`
  - NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

**Comment by dhaavi** [comment]
Thank you for reporting this. This is a known issue that we are investigating.

This only affects the Portmaster UI and not the Core Service - please follow https://github.com/safing/portmaster-ui/issues/124 for updates.

Closing as not applicable, referring to applicable repo and issue instead.
