### ISSUE TITLE
Please make a section that shows all blocked connections 

### ISSUE THREAD

**Issue by idfktbh** [safing/portmaster#276]
Add a blocked connections menu.
Reason: connivence

**Comment by dhaavi** [comment]
We are currently working on this in https://github.com/safing/portmaster-ui/pull/122.

The new view will list connections individually and you can filter to show only blocked connections.
If you have any more specific use cases, now is a good time to bring them up!

**Comment by davegson** [comment]
Thanks @idfktbh for the feature request!

As Daniel mentioned we are working on something like this in https://github.com/safing/portmaster-ui/pull/122. As far as I understand, that feature will then list connections per app/per process ordered by time. Starting with most recent moving back in history. And then you can additionally filter to only show the blocked connections.

Let us know if that is what you are looking for or elaborate a bit more if you are after something else.

**Comment by dhaavi** [comment]
Update: We just merged the feature, it's going into testing today and the release is scheduled for tuesday.
