### ISSUE TITLE
System tray icon not automatically launched after install 

### ISSUE THREAD

**Issue by H1rkul2** [safing/portmaster#280]
**What would you like to be added**:   
A tray icon would be useful because...

- It would show whether Portmaster is running in the background.
- At one glance, one could see if a new notification  Portmaster was last opened.
- Portmaster could be brought back into the foreground with a left click.

**example:**
The way it is implemented in [discord](https://discord.com/):
![image](https://user-images.githubusercontent.com/52507296/112859865-2933cc80-90ab-11eb-8ab0-b0e57cc1339b.png)

Thanks

**Comment by H1rkul2** [comment]
it is already there but it was not launched the first time after the install . thanks
![image](https://user-images.githubusercontent.com/52507296/112894366-affc9f80-90d3-11eb-899a-7f631fb08dca.png)

**Comment by dhaavi** [comment]
Hey @H1rkul2,

the tray icon should actually be launched right after install.

Can you tell us which installer you used to that we can fix that?

**Comment by H1rkul2** [comment]
hey @dhaavi 

I downloaded the Debian package from this  link : https://safing.io/portmaster/#downloads

here is more information about the package and os i m using
```
h1rkul2@a-pc:~/Desktop$ dpkg --info portmaster-installer.deb 
 new Debian package, version 2.0.
 size 5665804 bytes: control archive=2560 bytes.
      47 bytes,     1 lines      conffiles            
     114 bytes,     8 lines   *  config               #!/bin/sh
     561 bytes,    15 lines      control              
     933 bytes,    12 lines      md5sums              
    2521 bytes,    73 lines   *  postinst             #!/bin/sh
    1027 bytes,    40 lines   *  postrm               #!/bin/sh
     356 bytes,    17 lines   *  preinst              #!/bin/sh
     226 bytes,     7 lines   *  prerm                #!/bin/sh
     297 bytes,     6 lines      templates            
      61 bytes,     2 lines      triggers             
 Package: portmaster
 Version: 0.5.2.0
 Architecture: amd64
 Maintainer: Safing <noc@safing.io>
 Installed-Size: 12966
 Pre-Depends: debconf (>= 0.5) | debconf-2.0
 Depends: libnetfilter-queue1, libc6 (>= 2.3.2)
 Recommends: gir1.2-harfbuzz-0.0, libappindicator3-1
 Section: net
 Priority: optional
 Homepage: https://safing.io/
 Description: Application Firewall
  The Portmaster enables you to protect your data on your device. You
  are back in charge of your outgoing connections: you choose what data
  you share and what data stays private. Read more on docs.safing.io.

h1rkul2@a-pc:~/Desktop$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

h1rkul2@a-pc:~/Desktop$ cat /usr/share/gnome/gnome-version.xml
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>36</minor>
 <micro>8</micro>
 <distributor>Ubuntu</distributor>
 <!--<date></date>-->
</gnome-version>

```

**Comment by dhaavi** [comment]
Thanks for the additional information.

After checking with @ppacher, he reminded me that the tray icon should not launch automatically on install after all. This is a limitation from the system, as we cannot easily start a process correctly in user space from the installer process, which runs as root.

We are already looking into streamlining the install process and making this clearer in the future.

I'm closing this for now as this is expected behavior. We have improvements for this tracked internally with CC#1891.
