### ISSUE TITLE
Proposal: toogle filter blocked / allowed / all connections + checkbox to automatically pool connetions history

### ISSUE THREAD

**Issue by northys** [safing/portmaster#288]
**What would you like to add or change?**:

I would love to see a filter next to Previous button on App detail's connection history listing that would allow me to filter between Allowed / Blocked / All connections.

Also it would be brilliant if there could be a checkbox to pool connection history which is basically the original behavior.

**Why do you and others need this?**:

My use-case for both proposed features is when I debug something that is blocked I would filter only blocked connections and also I would love to pool them because I expect that there are not so much of them as the allowed ones ones.

---

Btw I love the new UI with paging and it makes a sense to me. I love that the connections don't run away while I'm trying to inspect them like they used to =)

**Comment by davegson** [comment]
Hey there,

I think the described feature already exists, is this what you are looking for?

![filter](https://user-images.githubusercontent.com/3080765/114508997-8cce0600-9c24-11eb-8bd2-5a4a15c09a4d.png)

Going into advanced UI Mode lets you choose from even more filter options while the Show `by Domain` lets you pool them together as before.

But 100% thanks for the suggestion! It means that the feature is overlooked and that is something we must improve upon.

----

Great to hear you like the new layout :) forwarding to Patrick and Luke who deserve the credit

**Comment by northys** [comment]
> I think the described feature already exists, is this what you are looking for?

I didn't see the icon I swear! :D

I would prefer portmaster looks more like swiss army knife (which looks bad actually) than a piece of art. Everything is so tiny, hidden, collapsed...

**Comment by davegson** [comment]
> I didn't see the icon I swear! :D

really no worries mate! Easy to overlook :D - but closing since it already exists

> I would prefer portmaster looks more like swiss army knife (which looks bad actually) than a piece of art. Everything is so tiny, hidden, collapsed...

I agree 😅 still so much we can, should and will improve.
