### ISSUE TITLE
Proposal: CTRL+F puts caret to search field

### ISSUE THREAD

**Issue by northys** [safing/portmaster#289]
**What would you like to add or change?**:

I would like if portmaster could implement default browser CTRL+F feature. There's already a search field so only CTRL+F shortcut has to be bound.

On default dashboard screen it could also put caret to App search / filter field but this is not what I would expect. I would expect it only on search pages because the search there actually acts as CTRL+F (and is actually smart beucase it search collapsed stuff, I know) in any other browser.

**Why do you and others need this?**:

I would actually prefer to have the default browser CTRL+F you disabled and implemented yourself so I can full text search any page when I decide to not when someone decides when I'll be allowed to full text search and what :D But who I am to be allowed to say anything about modern app design, right...? :D

**Comment by dhaavi** [comment]
I see your point - I will bring this up with the Team the next time we talk about such stuff - should be in 1.5 weeks or so.

Internal note: tracked by CC#1904.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
