### ISSUE TITLE
NextDNS is compatible

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster#291]
**What worked?**

I was able to successfully configure NextDNS within the Portmaster using the [DNS Servers](https://docs.safing.io/portmaster/settings#dns/nameservers) setting, the [DNS Configuration Guide](https://docs.safing.io/portmaster/guides/dns-configuration) and a test account from NextDNS.

🚨🚨🚨 __You will need to adjust the DNS Server configuration according to your account.__ 🚨🚨🚨  

Take the IP address from the right, and your custom domain name (for `verify=`) from the left.

With the test account, I used:
```
dot://45.90.28.144?verify=43ab19.dns.nextdns.io&name=NextDNS&blockedif=zeroip
```

The test account page:

![Screenshot from 2021-04-14 14-11-25](https://user-images.githubusercontent.com/18184155/114709146-86c34c80-9d2c-11eb-9c5a-8f03094691ff.png)

Block detection also works:

![Screenshot from 2021-04-14 14-12-55](https://user-images.githubusercontent.com/18184155/114709157-8925a680-9d2c-11eb-9de8-fcad6547f7a1.png)

**What did not work?**

I _did not_ test using NextDNS with their own client software - I also don't recommend using such a technically similar software alongside the Portmaster as they will get in each others way.

**Comment by davegson** [comment]
added the report to the docs, hence this can be closed

**Comment by DevilInMachine** [comment]
One unpleasant thing is that in the control panel NextDNS all requests from Portmaster are signed "Unidentified devices", that is, the name of the device is not transmitted in any form, as a result it is impossible to watch the DNS logs of the computer with Portmaster separately from other devices.

**Comment by ThomasDalla** [comment]
Another unpleasant side effect of using the IP is that it needs to be linked to the account on NextDNS, which is usually your home IP so it doesn't work when you go out of your home network.
It would be a lot better if Portmaster used bootstrap DNS like Pi-hole and AdGuard-Home do so that we can setup the custom DoT hostname in Portmaster (and not only identify the device but also work everywhere without IP binding needed).

**Comment by PoorPocketsMcNewHold** [comment]
[**@ThomasDalla**](https://github.com/ThomasDalla) commented on [Jan 17, 2022, 11:44 AM UTC](https://github.com/safing/portmaster/issues/291#issuecomment-1014430704 "2022-01-17T11:44:29Z - Replied by Github Reply Comments"):
> Another unpleasant side effect of using the IP is that it needs to be linked to the account on NextDNS, which is usually your home IP so it doesn't work when you go out of your home network.  
> It would be a lot better if Portmaster used bootstrap DNS like Pi-hole and AdGuard-Home do so that we can setup the custom DoT hostname in Portmaster (and not only identify the device but also work everywhere without IP binding needed).

![image](https://user-images.githubusercontent.com/13170204/150385133-9c801c0f-a657-4a56-a71b-d533826d7f70.png)
It can actually be done.
As described on the ¨Identify your devices¨ on NextDNS configuration website.

> DNS-over-TLS
> Prepend the name to the provided domain (the name should only contain a-z, A-Z, 0-9 and -). Use -- for spaces.
> For "John Router", you would use John--Router-f1528d.dns.nextdns.io as your DNS-over-TLS endpoint.

So, in the OP example, it would be : 
```
dot://45.90.28.144?verify=portmasterhome-43ab19.dns.nextdns.io&name=NextDNS&blockedif=zeroip
```

**Comment by ThomasDalla** [comment]
> 
> So, in the OP example, it would be :
> 
> ```
> dot://45.90.28.144?verify=portmasterhome-43ab19.dns.nextdns.io&name=NextDNS&blockedif=zeroip
> ```

That's only the hostname to verify.
It doesn't identify your service on the actual DNS queries and still requires IP binding.

**Comment by ThomasDalla** [comment]
I was under the impression that it was only the hostname to verify the IP but if that works, it's great.

It still requires IP binding though, so when on the move on a laptop for example, it doesn't work anymore if your home network is registering the IP (standard use case).

**Comment by Rexadev** [comment]
Why specify IP and domain. NextDNS doesn't expect to get DoT on that IP and it may cause slow resolve and no resolve

**Comment by Stofa14** [comment]
Any advice for configuration with my nextdns account ?

**Comment by Bastigonzales** [comment]
Thank you so much 🕺🏽

**Comment by ronilaukkarinen** [comment]
It works. Thanks!

**Comment by richou672005** [comment]
ipv6 ??

**Comment by bjorneyz** [comment]
So when it is configured within Portmaster there is no need to use the NextDNS software itself since Portmaster will take care of everything?

**Comment by pixincreate** [comment]
> So when it is configured within Portmaster there is no need to use the NextDNS software itself since Portmaster will take care of everything?

Portmaster NEEDS a DNS to be setup without which it does not work.

**Comment by Raphty** [comment]
@bjorneyz you are correct.

**Comment by H1ghSyst3m** [comment]
Can Someone show me a example how the doh (DNS over HTTPS) should look?

**Comment by Raphty** [comment]
![image](https://github.com/safing/portmaster/assets/11504285/d275e372-6dc4-4853-ab9d-497825ce1049)

You will need a DNS with an ip address in there, so your URL from Next DNS can be resolved.
This is why there is the Cloudflare backup quick setting
![image](https://github.com/safing/portmaster/assets/11504285/ae946b2a-b2b0-462f-b198-e37ba2367fa7)


So add you custom url in the first line and then click the QS and CF fallback.

**Comment by katastrophe92** [comment]
Hello Portmaster Community! 
In the first line should I add my NextDNS DNS-over-TLS/QUIC or DNS-over-HTTPS or both in separate lines and as fallback DNS can be NextDNS IP also be added? IPv6 is not indicated to be used? Sorry for too many questions.
Thanks!

**Comment by Raphty** [comment]
@katastrophe92 I like dot more, so I would start with that and bellow doh

as a fallback we recommend going with something reliable like cloudflare, but you can add multiple, Portmaster will always use the top one and if that fails it goes down the list in order.

**Comment by katastrophe92** [comment]
> @katastrophe92 I like dot more, so I would start with that and bellow doh
> 
> as a fallback we recommend going with something reliable like cloudflare, but you can add multiple, Portmaster will always use the top one and if that fails it goes down the list in order.

Nice. Thanks for the reply
