### ISSUE TITLE
Compatible with Linux Mint 20 Cinnamon & NordVpn

### ISSUE THREAD

**Issue by Shaolin-Twelve** [safing/portmaster#297]
The install, setup, and running appear to be working very well for my system, and NordVpn seems to have no issues with Portmaster at present.

System = Linux Mint 20
Desktop = Cinnamon 4.6.7
Kernel = 5.4.0-72-Generic
Processor = Intel© Core™ i7-8700 CPU @ 3.20GHz × 6
Memory = 31.3 GiB

Nordvpn Client App Version = 3.9.2

Appears to be compatible with both NordLynx and OpenVpn connections (UDP/TCP),
though I have had issues recently with the speed of NordLynx, this is unrelated to Portmaster, and may in fact be down to poor mobile broadband signal.

So far, Portmaster is working without any issues I am aware of. I tried several settings whilst on the internet, and all appear to do what was expected, blocking or allowing as expected, and notifying me from the system notifier as expected.

I have noticed a couple of things, but these I think are down to me not being fully conversant with this program, as I have only been aware of it for 2 days. I will keep an eye on those things, and learn more about the settings 'Danger/Untrusted/Trusted' as in some settings this appears to me to be doing the opposite of what I expect, but this is down to my not quite grasping the concepts, rather than a flaw, and testing to see what effect they have, has resulted in settings which appear to block and allow what I wish anyway.

Portmaster-Notifier too seems to have integrated well, and starts-up with no visible issues, and the links work too.

Thank you all who are making this possible, it is exactly what I have needed and scoured the internet for, for years. I will be much happier when Electron is dropped (I loathe it), but I have to say, this is one very smart-looking and very useful app for my Linux system, and the dark mode is much appreciated too.

At last, this is the GUI'd application aware firewall for Linux that I've been waiting (quite impatiently) for! Excellent work, excellent business model !!

Thank you, thank you, thank you :-)

**Comment by davegson** [comment]
Hey Shaolin-Twelve,

your report made my weekend - _thank you_ for taking the time to write these kind words. I'm sharing this with the whole team so we all get a boost :)

There is definitely a learning curve to our "threat model approach" (Danger/Untrusted/Trusted) but still do mention when you stumble or notice how it could improve. We wanna find and fix all broken issues, both from a technical and from a UX perspective.

> I will be much happier when Electron is dropped (I loathe it)

You might have already seen our "Ditch Electron" card [in the backlog](https://safing.io/backlog) - not happening in the short term, but we want that gone as well ;)

I will update the docs with your VPN and Linux compatibility report shortly. Thanks again!

**Comment by davegson** [comment]
thanks again for the support! The reports are in the docs now for everyone to see hence I'm closing this.

If anything comes up just open a new issue

**Comment by davegson** [comment]
for the record: another user reported perfect compatibility for cinnamon (mint) via matrix

**Comment by Shaolin-Twelve** [comment]
Hi Dave,

That's really good news, and I'd like to add that even after 2
kernel upgrades, Portmaster is still working very well on my Cinnamon
Mint, it has already helped me identify where certain connections
(which I wasn't expecting were going) - no surprise really - Google
(now blocked).

Portmaster is a must-have already, it has made it so much easier to see
and control what is going on and where, and I am still very much a fan
of your efforts and products, because well - unheard of really - an
Alpha product that on my system is more stable than other released
'Stable' products! Remarkable and uplifting.

Kind regards (and much genuflecting in your direction)

Peter Micallef





On Fri, 28 May 2021 02:33:49 -0700
Dave Gson ***@***.***> wrote:

> for the record: another user reported perfect compatibility for cinnamon (mint) via matrix
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/safing/portmaster/issues/297#issuecomment-850287962


-- 
Shaolin Twelve ***@***.***>

“Those who sleep in a democracy wake up in a dictatorship.”

**Comment by rafalohaki** [comment]
If i have portmaster running and when i connect via nordvpn on linux, i have no internet connection. no problem with only portmaster and only nordvpn separated.

**Comment by dhaavi** [comment]
Hey @rafalohaki, thanks for reporting this.

I would ask you to create a new issue for this - in the best case from within the Portmaster App, so it attaches the necessary debug data.
