### ISSUE TITLE
Facebook Business Inbox

### ISSUE THREAD

**Issue by OfficialEsco** [safing/portmaster#302]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
When i go to the Facebook Business inbox i get this
![image](https://user-images.githubusercontent.com/15158490/118372131-43206480-b5b0-11eb-9f4c-5df2570f06e6.png)

Portmaster is not blocking any Facebook domains
![image](https://user-images.githubusercontent.com/15158490/118372295-3f411200-b5b1-11eb-864b-79319459b9de.png)

BUT `nav.smartscreen.microsoft.com` is going craaaazy when you are on that site
![image](https://user-images.githubusercontent.com/15158490/118372163-782cb700-b5b0-11eb-836f-23219a2ce623.png)

**What did you expect to happen?**:
To get to the inbox 🤷‍♂️

**How did you reproduce it?**:
Incase it matters, open Microsoft Edge
1. go to Facebook.com
2a. Click on the Business Chat notification
2b. Go to your business, click inbox

**Debug Information**:

**Comment by davegson** [comment]
Hey @OfficialEsco, thank you for your report! We will come back to you this week and have a proper look

**Comment by dhaavi** [comment]
Hey @OfficialEsco, thanks for the report!

I'm not sure what is happening here, as the Portmaster seems to have allowed all connections.
Further, the error `ERR_TOO_MANY_REDIRECTS` hints to a problem on the server, not the client. Thinking about it, I'm not sure if the Portmaster is even capable of triggering that error. The only possibility I see is that another resource on the site was blocked that somehow triggered that behavior in the browser.

I tried opening `https://business.facebook.com` and it seemed to work here. I do not have a facebook or facebook business account, so I cannot confirm that while being logged in.

I'd ask you to provide some more information so we can continue to look into this:
1) Please confirm that the website works then the Portmaster is shut down. With v0.6.13 you can stop and start the Portmaster easier than ever.
2) Shortly after triggering the error, please go to the Monitor page in the app and open the Browser where the issue occured. Then, press the "Copy Debug Information" and paste the result here.

I hope we can shed more light on this with some additional data.

**Comment by OfficialEsco** [comment]
Apparently i am the dummy, Facebook Business Inbox have gotten a Third rework in a short amount of time, and this time they wanted to set a new cookie for `https://business.facebook.com` and you would get this screen if you've blocked cookies..

Hope you didn't invest too much time into this as it worked for you, eitherway thank you for your time ❤️ 

The Portmaster shut down switch will certainly help for future troubleshooting 👍

**Comment by davegson** [comment]
happy to hear it works 🎉 All good, you did not trigger much workload at all - it just sometimes takes us a while to respond since we have plenty of stuff going on simultaneously. Always feel free to report/suggest anything anytime.

Have a good one!
