### ISSUE TITLE
Portmaster Core keeps restarting

### ISSUE THREAD

**Issue by darkskyfullofstars** [safing/portmaster#308]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

It just keeps crashing on reopening it and it wont open, it says to launch the core when i click start it just crashes, no error, it just says not responding.

its in a loop when it closes it auto restarts and then crashes and i dont see what whats making it happen.

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:
NJ{"Created":1621632475,"Modified":1621632475,"Expires":1624224475,"Deleted":0}S
executing notifier/portmaster-notifier.exe version 0.2.3 on windows amd64
210521 16:27:55.386 > BOF
210521 16:27:55.387 ent/client:072 > INFO 001 client: connecting to Portmaster at 127.0.0.1:817
210521 16:27:57.401 ent/client:064 > ERRO 002 client: error connecting to Portmaster: dial tcp 127.0.0.1:817: connectex: No connection could be made because the target machine actively refused it.
210521 16:27:58.402 ent/client:078 > INFO 004 client: reconnecting...
210521 16:28:01.409 ent/client:078 > INFO 005 client: reconnecting...
210521 16:28:04.413 ent/client:078 > INFO 006 client: reconnecting...
210521 16:28:07.417 ent/client:078 > INFO 007 client: reconnecting...
210521 16:28:10.419 ent/client:078 > INFO 008 client: reconnecting...
210521 16:28:13.422 ent/client:078 > INFO 009 client: reconnecting...
210521 16:28:16.427 ent/client:078 > INFO 010 client: reconnecting...
210521 16:28:19.430 ent/client:078 > INFO 011 client: reconnecting...
210521 16:28:22.435 ent/client:078 > INFO 012 client: reconnecting...
210521 16:28:25.436 ent/client:078 > INFO 013 client: reconnecting...
210521 16:28:28.439 ent/client:078 > INFO 014 client: reconnecting...
210521 16:28:31.443 ent/client:078 > INFO 015 client: reconnecting...
210521 16:28:34.448 ent/client:078 > INFO 016 client: reconnecting...
210521 16:28:37.451 ent/client:078 > INFO 017 client: reconnecting...
210521 16:28:40.455 ent/client:078 > INFO 018 client: reconnecting...
210521 16:28:43.458 ent/client:078 > INFO 019 client: reconnecting...
210521 16:28:46.462 ent/client:078 > INFO 020 client: reconnecting...
210521 16:28:49.466 ent/client:078 > INFO 021 client: reconnecting...
210521 16:28:52.468 ent/client:078 > INFO 022 client: reconnecting...
210521 16:28:55.470 ent/client:078 > INFO 023 client: reconnecting...
210521 16:28:58.471 ent/client:078 > INFO 024 client: reconnecting...
210521 16:29:01.473 ent/client:078 > INFO 025 client: reconnecting...
210521 16:29:04.476 ent/client:078 > INFO 026 client: reconnecting...
210521 16:29:07.479 ent/client:078 > INFO 027 client: reconnecting...
210521 16:29:10.479 ent/client:078 > INFO 028 client: reconnecting...
210521 16:29:13.481 ent/client:078 > INFO 029 client: reconnecting...
210521 16:29:16.482 ent/client:078 > INFO 030 client: reconnecting...
210521 16:29:19.485 ent/client:078 > INFO 031 client: reconnecting...
210521 16:29:22.488 ent/client:078 > INFO 032 client: reconnecting...
210521 16:29:25.492 ent/client:078 > INFO 033 client: reconnecting...
210521 16:29:28.495 ent/client:078 > INFO 034 client: reconnecting...
210521 16:29:31.496 ent/client:078 > INFO 035 client: reconnecting...
210521 16:29:34.499 ent/client:078 > INFO 036 client: reconnecting...
210521 16:29:37.501 ent/client:078 > INFO 037 client: reconnecting...
210521 16:29:40.504 ent/client:078 > INFO 038 client: reconnecting...
210521 16:29:43.506 ent/client:078 > INFO 039 client: reconnecting...
210521 16:29:46.507 ent/client:078 > INFO 040 client: reconnecting...
210521 16:29:49.516 ent/client:078 > INFO 041 client: reconnecting...
210521 16:29:52.519 ent/client:078 > INFO 042 client: reconnecting...
210521 16:29:55.522 ent/client:078 > INFO 043 client: reconnecting...
210521 16:29:58.524 ent/client:078 > INFO 044 client: reconnecting...
210521 16:30:01.533 ent/client:078 > INFO 045 client: reconnecting...
210521 16:30:04.536 ent/client:078 > INFO 046 client: reconnecting...
210521 16:30:07.538 ent/client:078 > INFO 047 client: reconnecting...
210521 16:30:10.540 ent/client:078 > INFO 048 client: reconnecting...
210521 16:30:13.542 ent/client:078 > INFO 049 client: reconnecting...
210521 16:30:16.545 ent/client:078 > INFO 050 client: reconnecting...
210521 16:30:19.549 ent/client:078 > INFO 051 client: reconnecting...
210521 16:30:22.551 ent/client:078 > INFO 052 client: reconnecting...
210521 16:30:25.566 ent/client:078 > INFO 053 client: reconnecting...
210521 16:30:27.063 ifier/main:123 > WARN 054 program is shutting down
210521 16:30:28.074 < EOF

210521 16:27:48.085 dules/stop:050 > ERRO 637 modules: shutdown completed with error: remove C:\ProgramData\Safing\Portmaster\updates\tmp\portmaster-start.exe-1621632245-upgraded: Access is denied.
210521 16:27:48.096 < EOF

**Comment by davegson** [comment]
thank you so much for the report! Looking at your other reports, did this resolve itself in the end? Or how did you get it to work? 

We still want to know what is going on so other's don't experience this frustration. Daniel and Patrick are the main devs of the Portmaster and will have a proper look what happened next week (soonest Tuesday since Monday is a public holiday)

**Comment by dhaavi** [comment]
Hey @darkskyfullofstars, thanks for the report.

Can you provide the log and error log file of the core from when it failed to start?
You can find them in `C:\ProgramData\Safing\Portmaster\logs\core`.

You did provide two log lines from the core at the end of your post, but there should be quite a lot more.
Unfortunately, what you have provided so far does not indicate the error.
