### ISSUE TITLE
Easy way to enable/disable network access for apps

### ISSUE THREAD

**Issue by robjob1938** [safing/portmaster#310]
**What would you like to add or change?**:
A one button way to turn off and turn on all network access.  Right now to block a program, you have to go to "Apps" then choose the app then choose "Block Internet Access" "Trusted."

It would be great under the Network monitor to have a switch so I could give the program instant on and off access.

**Why do you and others need this?**:
Example: My company communicates through slack.  It would be great to just easily turn it off/on at will.

![image](https://user-images.githubusercontent.com/80987657/119224698-38edf100-baef-11eb-9dbc-fd0fac79ad38.png)

**Comment by davegson** [comment]
I do understand the need and like the idea. It might be hard to pull off just because of our threat model approach. But we will talk about it.

In the meantime you could monkey patch your setup with two environments to fit your needs. Think of "Untrusted" as your everyday, private setup, and then "Trusted" as "Work, which gets more benefits".

You could then allow Slack only to have Internet in "Trusted" and flick the switch after work to "Untrusted", immediately blocking Slack from the Internet. I know this is kinda hack-ish. It especially is a mental challenge to associate "Untrusted" with "Home as I like it" while "Trusted" is work...  ugh, I don't know, it might also need a lot of configuration to adapt the other settings to this. So pretty unsure about this but just brainstorming how you could monkey patch the current tools to your needs.

**Comment by dhaavi** [comment]
Hey @robjob1938,

this is an absolute great use case that we need to think about more. Thanks!

I think @davegson is on the right track here.
Promoting single app settings in such a prominent way is a nice idea, but every user will want to have a different setting promoted like this to suit their use case. Alone with your use case there are multiple ways to actually implement that in the settings.
I would definitely want to use the power of the network rating levels to tackle your and similar use cases.

Here are two ideas how this could look like.

1) We could introduce another Level called `Permissive` that would be above `Trusted`. This is essentially what @davegson suggested, but with the additional level we would not be twisting your brain, but have a distinct level for letting programs do things that you would rather not have them do, but have to for some reason.

2) We could instead add custom environmental buttons that work similar to the network ratings, but are not part of their "levels". None of them is portrayed as better or worse, but are special in nature. You can then attach settings to these special environments in addition to the network rating level. Eg. You could have a special environment called "Work". In that, you allow Slack to connect to the Internet, but only if that environment is active. You can then switch these environments on and off through the notifier icon in the system tray.

Please note that these ideas are purely a brainstorm and do not convey that we plan on implementing something like this as of now. Please give us feedback to see what would fit your needs.

Internal note: tracked by CC#1956.

**Comment by dhaavi** [comment]
Adding the "planned" label as we are going to discuss this internally and see how we can solve this. Please continue to provide feedback though!

**Comment by robjob1938** [comment]
> Adding the "planned" label as we are going to discuss this internally and see how we can solve this. Please continue to provide feedback though!

Thanks, the program is pretty comprehensive otherwise.  The first time I used this program, I actually thought that the label with how many network connections with a green or red dot was a slider that would do this very function.  I was trying to read why my sliders were not working when I figured out it was not slider button at all!

**Comment by ppacher** [comment]
Well we should revisit the design of those then or actually make the sliders.
Maybe @LukeSeers has some ideas on that

**Comment by dhaavi** [comment]
This is just around the corner.

**Comment by robjob1938** [comment]
Thank you so much.  Also thank you for the change in the buttons (instead of looking like it is sliders), I greatly appreciate it.  I have been using postmaster everyday and the improvement over the past year have been noticeable.

**Comment by dhaavi** [comment]
This has been implemented in v0.8.4, which is now available in the [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel).
