### ISSUE TITLE
Simplewall is compatible with one minor issue

### ISSUE THREAD

**Issue by R1123345** [safing/portmaster#314]
**Simplewall and portmaster**
Works out of the box. So far only one minor issue emerged.
Please note that this is the result of very basic testing on a windows 10 machine. 

**What worked?**
Connections intended to be blocked were blocked by either portmaster or simplewall. 

**What did not work?**
When simplewall is turned on and blocks a connection, and Portmaster's privacy filter is set to "prompt" for the same connection, Some connections are displayed as "::1" instead of the address in Portmasters notifications. Others do not show up in portmaster, indicating the possibility they are blocked by Simplewall first. 
When blocking or allowing "::1", it is subsequently registered as ip-address "::1". This does not block whatever address it should have been. 

**Workaround**
when establishing blockrules for portmaster, be sure to turn off the firewall rules relevant to the app/connection you want to adjust in portmaster _before_ doing so. 
Recommend to block everything by default in portmaster before doing so, to avoid unwanted connections.

**Debug Information**:
N/A

**Comment by dhaavi** [comment]
Hey @R1123345, thanks for the report!

Great to heart that it works.

About the `::1` connections:
Do you know how Simplewall blocks connections? I couldn't find in the Simplewall docs how it blocks connections, but it may be rewriting the packets, which makes the Portmaster see `::1`.

May I ask why you want to use both Portmaster and Simplewall together in the first place?

**Comment by davegson** [comment]
> May I ask why you want to use both Portmaster and Simplewall together in the first place?

I did [encourage testing both at the same time to check and report compatibility](https://old.reddit.com/r/safing/comments/ni3j39/portmaster_as_firewall_how_does_it_stack_up/) a few days back on reddit. This is super valuable since people may want to transition from Simplewall, where already a lot of settings may be set and then migrate them to Portmaster.

**Comment by TMS-Namespace** [comment]
@dhaavi simplewall is just a control UI over windows default firewall,  it is not a stand alone firewall.

Why we need it?  At least in my case,  I need sometimes to block a bunch of applications from connection,  and enable them easily back when needed.

For example,  once a week,  I update my anti-virus,  windows,  store apps etc..  After that,  I block them from Internet access.

Postmaster currently provides no easy way to do that.

**Comment by davegson** [comment]
thanks for your thoughts @TMS-Namespace - your use case reminds me of the suggestion in https://github.com/safing/portmaster/issues/310, might want to chime in there too
