### ISSUE TITLE
Sound distortion while blocking on Win10

### ISSUE THREAD

**Issue by TMS-Namespace** [safing/portmaster#318]
On win10, with portmaster 0.6.14, if you will run youtube on the background or even in "picture in picture" mode,  sound gets distorted (as in old windows when it hangs up,  or when cpu usage spikes to 100%).

I noticed that this happens particularly when portmaster blocks some domain in any other application. 

I got same behavior across multiple browsers.  Also I have i7-9750H CPU,  so it can't be due to weak device performance:  when portmaster blocks a domain, it uses 2-4% of cpu power at Max.

**Comment by dhaavi** [comment]
Hey @TMS-Namespace, thanks for the report.

This is really odd. It might have something to do with the kernel extension.

Could you please copy the debug information right after this happens and paste it here?
You can find the button on the top right on the settings page. Maybe this will give us some clues.

I'm also re-labeling this as a bug, as this affect Windows directly and not a 3rd party software.

**Comment by TMS-Namespace** [comment]
Hi,  sorry for the late replay,

Just want to let u know,  that this was happening after multiple sleep/wake-up cycles of my laptop. 

Restarting portmaster actually resolved this, did not try the behavior of latest versions yet.

**Comment by ppacher** [comment]
Hi @TMS-Namespace,

no worries.
It would be great if you find some time to test it with the latest version. We should re-open the issue if it still persists. 

As long as you did not disable automatic updates you should be running the new version after a reboot.
