### ISSUE TITLE
Youtube should not showing ads

### ISSUE THREAD

**Issue by devmalick** [safing/portmaster#319]
**What would you like to add or change?**:

Youtube should not showing ads, It should filter ads from youtube videos 

**Why do you and others need this?**:

becuse yoube used by every one

**Comment by davegson** [comment]
Portmaster works on the network level, meaning it sees domains such as ads.facebook.com and can then block them. YouTube ads do not seem to go through a blockable "ad-domain" but come from the same domain as the normal video.

We **highly recommend** to continue using an a Adblocker like uBlock Origin which is capable of knowing which part of youtube.com is wanted or unwanted
