### ISSUE TITLE
OpenRC support

### ISSUE THREAD

**Issue by lilithium-hydride** [safing/portmaster#322]
**What would you like to add or change?**:
Support for init systems other than systemd, such as OpenRC. Simply using something like initify to convert portmaster.service does not work for this purpose.

**Why do you and others need this?**:
Users on Artix and other systemd-less setups would be able to take advantage of Portmaster on their systems.

**Comment by dhaavi** [comment]
Hey @fort-ified, thanks for the suggestion,

I'll talk to the team about it.
In general, we'd like to support as many distros as we can, but due to limited resources we need to do some quite hard selection of things we can do in this phase of the project.

Internally tracked by CC#1959.

**Comment by fort-ified** [comment]
That's quite understandable, especially considering the somewhat fringe nature of this for the majority of people :p

**Comment by danrobi11** [comment]
> Users on Artix and other systemd-less setups would be able to take advantage of Portmaster on their systems.

+1 SysV init here

**Comment by BirdDev** [comment]
+1 openrc here :)

**Comment by dhaavi** [comment]
Thanks for the additional support for this!

We recently went over the linux installers and it currently does not seem likely that we'll add support for this to our installers in the near future.
If anyone is up for it, we'd happily review a guide on how to set up the Portmaster with OpenRC/SysV and include it in the [docs](https://github.com/safing/docs).

**Comment by lilithium-hydride** [comment]
Since filing this initially, I've become a bit more experienced with init scripts, and I might give it a shot later this week. No promises on its correctness being up to the standards of someone who actually knows what they're doing, but I would like to at least get it working.

**Comment by FlabIt** [comment]
@lilithium-hydride no need to :) I already created the required files to run portmaster with openrc init system.
I'll push it to the arch user repositories (AUR) during the following days.

**Comment by dhaavi** [comment]
Hey @FlabIt, that would be great! 👌

**Comment by FlabIt** [comment]
Ok so the package is pushed and available at [portmaster-openrc](https://aur.archlinux.org/packages/portmaster-openrc/)
Please let me know if this works for you :)

**Comment by lilithium-hydride** [comment]
I had to edit the paths provided to point to `/var/lib/portmaster/`, perhaps they recently moved away from using `/opt`. It's also probably worth documenting that this doesn't keep track of the service process, and so the status remains as "stopped," regardless of the state of the process it started. The application is also extremely buggy for me in strange and inconsistent ways, but it's quite likely that this is due to my now-quite-janky network configuration (wireless+iwd+connmand+wireguard). 

I'd appreciate if anyone running a more standard networking setup could also give this a shot, just to be able to rule out any issues that may be specific to my system.

**Comment by dhaavi** [comment]
Regarding the path, we actually moved from `/var/lib` to `/opt`. See the corresponding troubleshooting section in the docs: https://docs.safing.io/portmaster/install/linux#install-path-change

**Comment by lilithium-hydride** [comment]
Interestingly enough, this was a fresh installation of Portmaster on a fresh installation of Artix, using the tar.gz provided by the link on the installation guide.

**Comment by dhaavi** [comment]
Oops, that shouldn't be there anymore. We phased out the pkg.tar.gz installer with the last update, but it seems we have forgotten to remove the link when we updated the docs. Fixing in https://github.com/safing/docs/pull/67.

Please use the provided PKGBUILD - which will also be available from AUR soon.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
