### ISSUE TITLE
Portmaster and PIA VPN on Windows

### ISSUE THREAD

**Issue by gabgabsky** [safing/portmaster#323]
Howdy sorry to bother I watched your episode on Portmaster on Techlore and was very excited to try it I mean uBlock Origin for the computer and I can't do Pi-hole I'm on a public Wi-Fi.   It didn't work.  It immediately turned off PIA VPN and endlessly well for 10 minutes said downloading filter lists with yellow icon in tray on new AMD Acer laptop with Windows 10.  I would like to find out what's wrong I had to uninstall it. Thank you.

**Comment by dhaavi** [comment]
Hey @gabgabsky, thanks for the report.

We don't know yet if PIA works with the Portmaster on Windows 10. Can you try disabling PIA?
The issue seems to be that there is some sort of interference with another software, likely PIA, but maybe something else.

**Comment by dhaavi** [comment]
You can also try [this guide](https://www.privateinternetaccess.com/helpdesk/guides/windows/troubleshooting/windows-changing-dns-servers-in-the-pia-app#windows-changing-dns-servers-in-the-pia-app_step-2-settings) and set the Portmaster as the DNS server by entering the IP address `127.0.0.1` as the custom primary DNS server.

Please note that this is safe, as the Portmaster will take care of securing your DNS requests.

**Comment by dhaavi** [comment]
If you find the time to test the suggested solutions, it would be great if you could report back what worked, so we can put that in our compatibility list to inform the community. 👌

**Comment by ppacher** [comment]
Just for the reference, there's another report for PIA VPN in #317. It seems to work in OpenVPN mode, but not in wireguard mode (as outlined in #292 )

**Comment by dhaavi** [comment]
Issue #317 was reported with Linux, this one with Windows 10. Therefore I would not assume that the other issue applies here.

@gabgabsky Were you able to try out the guide as mentioned in https://github.com/safing/portmaster/issues/323#issuecomment-851374596?

**Comment by ppacher** [comment]
@dhaavi you're absolutely right. I've overseen that this one is for windows.

**Comment by dannyagostinelli** [comment]
I changed the PIA DNS to 127.0.0.1 like suggested in https://github.com/safing/portmaster/issues/323#issuecomment-851374596 and it worked. Is this the recommended solution or is it considered a workaround?
