### ISSUE TITLE
KDE Plasma System Tray Integration

### ISSUE THREAD

**Issue by shaurya-007** [safing/portmaster#324]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**
The application itself worked fine.

**What did not work?**
I did not see the portmaster icon in the KDE Plasma System Tray even after a reboot.

**Debug Information**:

**Comment by dhaavi** [comment]
Hey @shaurya-007, thanks for reporting this.

I'm not very familiar with KDE and how they handle the appindicator interface. Can you check if `libappindicator` is installed? Specifically you are probably looking for `libappindicator-gtk3`. I saw that we don't have it in the manual install docs - maybe because it comes by default with the Gnome DE.

What you can also do is to run the notifier manually and see if there are any errors.
Use this command if you used the same install path:
`/var/lib/portmaster/updates/linux_amd64/notifier/portmaster-notifier_v0-2-3 --data /var/lib/portmaster --log trace`

**Comment by shaurya-007** [comment]
That did not solve the problem.

**Comment by 8BallBomBom** [comment]
Can't confirm this issue.
Running Kubuntu 21.04 with Plasma Desktop 5.21.5, no problems, the notifier icon is visible.
Was also previously running a much lower Plasma Desktop version 5.18.5 which also didn't have any issues.
![taskbar](https://user-images.githubusercontent.com/3690196/120225507-f4452100-c277-11eb-95d9-ea2683dc4bec.png)
4th icon from the left, currently disabled but the notifier is visible.

As for how postmaster was installed, nothing special, deb file + dpkg.

**Comment by dhaavi** [comment]
Hey @8BallBomBom, thanks for chiming in here!
The icon doesn't look as smooth as the others though. Interesting.

@shaurya-007 Can you run the notifier from the terminal as laid out in https://github.com/safing/portmaster/issues/324#issuecomment-851366700? There might be some error messages there that would help us out a lot here.

@davegson I'm adding the docs pending label here to add the "KDE Plasma" DE as of version 5.18 as reported compatible.

**Comment by 8BallBomBom** [comment]
@dhaavi It would seem the task bar icons i use [here](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) are mostly svg files going as low as 16x16.

Unsure what you are using for the notifier icon but shouldn't be hard to touch up 😃

**Comment by dhaavi** [comment]
Unfortunately, the library we currently use does not support supplying `.svg`s. I hope we can change this some day.

We provide our icons in 256x256, so if the DE scales it down with a proper algorithm it should stay nice. 😉 
Normally they are...

**Comment by brandocorp** [comment]
I can confirm that I do not see the icon on startup/login, but when I open the portmaster application, the systray icon shows up as I would expect.

```
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.10.42-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 32 × AMD Ryzen 9 3950X 16-Core Processor
Memory: 62.8 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2070/PCIe/SSE2
```

**Comment by ppacher** [comment]
Hi @brandocorp, thanks for reporting that it works for you!

@shaurya-007, could you try to run the notifier as requested by @dhaavi  in https://github.com/safing/portmaster/issues/324#issuecomment-852040496?
