### ISSUE TITLE
Add custom block list

### ISSUE THREAD

**Issue by toyboatcash** [safing/portmaster#326]
**What would you like to add or change?**:

option to add custom Blacklist

**Why do you and others need this?**:

this would allow users to add their own lists they wish to block one exsmple 
https://api.tosdr.org/pihole

**Comment by dhaavi** [comment]
Hey @toyboatcash, thanks for the suggestion.

Currently, there is no way to manually add lists, but we are happy to consider new ones if we believe they will be a benefit to a large enough part of our userbase.

With https://tosdr.org/ - they seem to have a browser addon to inform you about sites with a bad privacy policy. In general I feel that these sites are not about impacting user privacy in the background, but require an intent to use the product by the user anyway. Eg. by creating an account with them. And this is something that every user has to decide on their own anyway.

We might add an option to the Portmaster in the future that would fetch lists directly, but a lot slower than we can provide them. But nothing is planned at the moment.

Better yet, what would like to do is to warn users that they are using service and applications by companies with a bad privacy reputation. This way we would be able to educate users and help them make good decisions. But this is future talk. 😉

**Comment by davegson** [comment]
I believe the topic touched upon here is a bit wider than https://tosdr.org. It might be interesting to import filter lists to the rules, from whatever source, be it an external source or previous settings from another firewall.

**Comment by AlphaPancake** [comment]
On this topic I agree with @davegson.
The thought about educating people over sites with bad privacy practices is good.
But for more advanced users it could open up the possibilitie of easily configure a block list and load it into Portmaster, for the sake of individual use cases (which probably only affects a small percentage of users in general).

**Comment by MaiAsagi** [comment]
I agree with @davegson and @AlphaPancake as someone with a custom filter list being able to add my own filter list would be nice.

**Comment by davegson** [comment]
another person [asks for this feature on Reddit](https://old.reddit.com/r/safing/comments/qzr1qr/custom_filters/) 👍

**Comment by i27i13** [comment]
Very wired to have such and advance tool and not allow for **easy** custom rules.

**Comment by Rexadev** [comment]
Add option have more than 1 blocklist

**Comment by dhaavi** [comment]
Sorry, we somehow missed to update this issue.
You can use a [Custom Filter List](https://docs.safing.io/portmaster/settings#filter/customListFile) in Portmaster.

(@Rexadev, I will respond in the issue you opened.)
