### ISSUE TITLE
Improve Windows 10 task tray menu design

### ISSUE THREAD

**Issue by luximus-hunter** [safing/portmaster#328]
**What would you like to add or change?**:
As of now, the task tray menu doesn't follow the Windows theme setting. It also doesn't look that great.

![LXMS1622553074](https://user-images.githubusercontent.com/49814847/120332781-5c831980-c2ef-11eb-8415-196cda68f053.png)

I suggest trying to make something similar to what [ModernFlyouts](https://github.com/ModernFlyouts-Community/ModernFlyouts) has done to its menu.

![LXMS1622553219](https://user-images.githubusercontent.com/49814847/120332880-71f84380-c2ef-11eb-84f0-74d584cb8488.png)

**Comment by dhaavi** [comment]
Hey @luximus-hunter, that looks great! Thanks!

This is something we'll definitely get to, but it'll take a while.

Internally tracked by CC#1971.

**Comment by luximus-hunter** [comment]
Take your time! It's still alpha 😉

**Comment by STwersky** [comment]
@dhaavi Hi, Daniel! I wanted to ask, is this a bug or is it supposed to be that Tray Notifier does not load after a reboot and there is no such setting in the interface? I also noticed a small error that sometimes loading the main interface launches an additional instance of Notifier in the tray. And I want to suggest that double-clicking on the icon in the tray opens the main interface of the program, it seems to me that this is the most intuitively expected result for most products that have an icon in the tray.

**Comment by dhaavi** [comment]
Hey @STwersky, the Tray Notifier should load after boot. If it does not, please open a new issue for that.

The two icons symptom is because the installers need an update and will be resolved soon. It should _not_ happen after a full reboot of your system.

The double-clicking is a nice idea - I like it very much! Can you open a new issue for that? (Yes, we looove separate issues! 😜)

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
