### ISSUE TITLE
Windows 10 NICs Now Show Zero Information

### ISSUE THREAD

**Issue by 335iguy** [safing/portmaster#335]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
All NIC interface information in Windows 10 is not available. Control Panel > Network > Change Adapter Settings > Select any adapter. All information (time connected, speed, bytes in/out) except IP, Subnet, DNS info shows zeros.

After uninstallation and reboot, I 100% have internet access even without the statistics. 

NICs include onboard and USB C Expansion (3 USB3 ports + 1 NIC, unknown brand)

**What did you expect to happen?**:
I'm not sure how portmaster uses this information to bring into its interface, but this happened after discovering that I had very little to no internet access when default firewall settings were applied. 

**How did you reproduce it?**:
Unable to reproduce.
![2021-06-07 13_07_32](https://user-images.githubusercontent.com/25601348/121062142-42947b80-c7b4-11eb-92fd-6cd711a43a1d.png)

**Debug Information**:
Latest version, uninstalled portmaster to try and revert NIC information. Deleted and reinstalled drivers, updates drivers. No windows updated were performed while software was installed. 
Windows 10 Pro 20H2, installed on 12/5/2020
OS Build: 19042.985
Experience: 120.2212.2020.0
Ryzen 5, 16GB DDR4, Realtek built-in NIC on a B450 Tomahawk motherboard, USB C Expansion Adpater with NIC. 
PortMaster installed 6/1, uninstalled 6/3

**Comment by dhaavi** [comment]
Hey @335iguy, thanks for the report!

I think this is probably the same issue as reported in #330, for which we released a fix today (v0.6.16).
Can you try with that new version again? You don't need a new installer, just install it again. It will download the newest version during install.

Also, out of curiosity, is there any particular reason you reported this today, when you already uninstalled the Portmaster on 6/3?

**Comment by davegson** [comment]
Sounds nice, yesterday I also tweaked some things on my Windows. ✌️

I could not conclude whether this issue was resolved or not with the newest update? Did it remain?
