### ISSUE TITLE
Installation Did Not Work and Cut Off Internet

### ISSUE THREAD

**Issue by davegson** [safing/portmaster#338]
forwarding from a mail:

 
**Pre-Submit Checklist**:
 
- Check applicable sources for existing issues:
- [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
- [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
- [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)
 
**What happened**:
 
Internet cut off after installing the app. It was showing either (Core Service could not start) or (Core Service starting) with a little button for (Start Core service) which opened a CMD when pressing on it. Nothing really happened tho. I restarted the computer, I still had no internet connection.
I tried changing the DNS to 127.0.0.1 and nothing happened. Tried changing it to "detect automaticly", nothing happened too. After uninstalling the App, the internet connection came back even without restarting.
 
**What did you expect to happen?**:
 
The Application to start or to have my internet connection back
 
**How did you reproduce it?**:
 
Just by installing the software.
 
**Debug Information**:

visible in the mail, assigned @ppacher there too

Might be related to https://github.com/safing/portmaster/issues/336

**Comment by northys** [comment]
A similar error happened to me before I disabled local DNS (dnsmasq or systemd-resolved, dunno). But I suppose this problem is Windows related. Maybe it is conflict with some other Windows DNS? Just my thoughts...

**Comment by Mrigank11** [comment]
I'm facing a similar issue. DNS queries don't work. According to logs, it's running in `SemiOnline mode(dns check query failed)`. Tried disabling VPN, windows firewall, ICS service but no gain. Let me know if I can help with any further information.

Excited to try portmaster!

**Comment by ppacher** [comment]
HI @Mrigank11,
thanks for reporting here!

Would you mind sending me your debug logs? If you don't want to post the here you can also send them to support at safing.io.
Also, would it be possible to retry the installation with your VPN being turned off?

**Comment by dhaavi** [comment]
Closing since this issue is pretty old and there are a couple newer ones that are similar.
If you still experience this, please open a new issue.
