### ISSUE TITLE
When opening the UI it says "PM Core Is Not Running" even if it is

### ISSUE THREAD

**Issue by davegson** [safing/portmaster#339]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

When opening the Portmaster User Interface while the Core Process is running in the background the first 1-2 seconds show the message: "Portmaster Core Service is not running".

![Screen Shot 2021-06-14 at 4 58 35 PM](https://user-images.githubusercontent.com/3080765/121914019-6cecb880-cd21-11eb-9527-f52b47d63e3d.png)

Next to making me question if the PM _really_ is running, which makes me uncomfortable even knowing this is the case - it may be interpreted the way that the PM _only_ is running when the UI is open. Which is definitely misleading.

**What did you expect to happen?**:

Just have a normal loading screen and only if the Core Service _really_ is not running show that message.

**How did you reproduce it?**:

Open up the Portmaster, maybe on a slower device.

_Originally reported/suggested by @STwersky in https://github.com/safing/portmaster/issues/336#issuecomment-859947970_

**Comment by TrashPandaCodingGarbage** [comment]
Can reproduce.

**Comment by ppacher** [comment]
Hi @TrashPandaCodingGarbage , thanks for reporting here. Are you running on windows or linux?

**Comment by davegson** [comment]
for me this happens on Windows

**Comment by TrashPandaCodingGarbage** [comment]
> 
> 
> Hi @TrashPandaCodingGarbage , thanks for reporting here. Are you running on windows or linux?

Hello, sorry that I didn't included this info in original post. It's happening on Windows for me.

**Comment by ppacher** [comment]
> Hello, sorry that I didn't included this info in original post. It's happening on Windows for me.

No worries ;) We already have a fix in place for that in safing/portmaster-ui#154 which we'll likely be released this week (no promises though).
