### ISSUE TITLE
Add button to dismiss a prompt

### ISSUE THREAD

**Issue by MPeti1** [safing/portmaster#342]
**What would you like to add or change?**:
It should be possible to dismiss a connection or program entry from the notifications pane of the Portmaster window.
A simple illustration: the point is the red X letters at the entries of the notification pane

![image](https://user-images.githubusercontent.com/9215491/122127643-03ed6980-ce23-11eb-94ba-3f0a5cb6cd07.png)

**Why do you and others need this?**:
If I use the 3 dots menu to apply a different kind of rule, I usually don't want to see the corresponsing entries anymore, because I've already acted on them. Dismissing the entries should be manual, I think it wouldn't benefit if entries would be automatically dismissed based on the change I just made.
Also, I think it could be beneficial if it would be possible to dismiss a single connection entry, or a single program entry with all it's connection entries too, but when hiding program entries, it might be a good idea to not dismiss entries that appeared in the last x hundred milliseconds.

I don't want to "over-engineer" it instead of you, if it feels like that please let me know.

**Comment by ppacher** [comment]
Hi @MPeti1 , thanks for your suggestion.

When you talk about dissmissing, what action would you expect the Portmaster to take? Should be assume you want the connection to be blocked or not decide on it completely and let the program time-out?

**Comment by MPeti1** [comment]
Sorry for the late response.

I think it should always be blocked then, _but_ I'm not entirely sure about this.
If Portmaster can be set up so that it notifies me of certain (otherwise allowed) requests too, then it should allow the connection if I just dismiss the notification, and otherwise (if the goal of the notification is to ask me whether I give the permission to do requests) block it.

So basically this can be summed up as "do whatever it would do if it didn't make the notification"

**Comment by ppacher** [comment]
> Sorry for the late response.

No problem ;)

> So basically this can be summed up as "do whatever it would do if it didn't make the notification"

I'm not sure we're actually talking about the same thing here. Maybe I misunderstood the above issue text because the Portmaster can be configured to either *deny*, *allow* or *prompt* when it sees new connections. When you say you "don't want to see the entries because you already acted on them" did you mean that you already selected "Allow" or "Block" in the connection prompts? If so, a rule is added so these connection will be allowed in the future and all similar prompts for **that program** should disappear. If that's not the case we might hit a bug here. 
Can you clarify what actually happened?

**Comment by MPeti1** [comment]
I meant opening the 3 dots menu, selecting "app settings" in it, and changing settings like 'Network Scope -> Block LAN', adding new entries to 'Rules -> Outgoing Rules', etc.

**Comment by Kiefy** [comment]
It would be nice if the notification would stay there forever until I act on it, then to immediately vanish afterwards.

**Comment by ppacher** [comment]
HI @Kiefy,
thanks for your suggestion! You can try to increase the [Prompt Timeout](https://docs.safing.io/portmaster/settings#filter/askTimeout) to, for example, 3600. The notifications will then be displayed up to a hour. Could you test if that works for you?

@MPeti1, sorry for not replying to your comment. Seems like it somehow slipped through. You're right, the notifications do not currently vanish if the app settings are changed directly and not via the notification actions. I'll discuss that with @dhaavi.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
