### ISSUE TITLE
Add oisd.nl as tracking/adblocking host source

### ISSUE THREAD

**Issue by TrashPandaCodingGarbage** [safing/portmaster#346]
Dear Safing Team,
I love every piece of Portmaster. I want to make it better by suggesting adding oisd.nl as host source for blocking tracking/telemetry/ads. It's simply wonderful.

Oisd is recommended by many people from Reddit, for whom this is the only blacklist they use. They also run NextDNS purely for oisd list. It have almost no false positives, it's free, and coverage of the blocking is great. 
[Here](https://oisd.nl/includedlists) you can read which lists does it utilize. 

I would recommend setting Oisd Basic as default, since it has almost no false positives.
As far as Oisd full, I will leave it as optional for user to check.

Please let me know what do you think about it. 

Cheers!

**Comment by ppacher** [comment]
Hi @TrashPandaCodingGarbage, thanks for that  suggestion! This seems like a nice list to use. I'll discuss this with the team and let you know!

**Comment by TrashPandaCodingGarbage** [comment]
@ppacher Thank you so much, excited for the possible implementation.

**Comment by TrashPandaCodingGarbage** [comment]
Hi guys, any news about adding oisd, or it still hasn't been decided?

**Comment by ppacher** [comment]
HI @TrashPandaCodingGarbage,

sorry there's no update to this yet as we just didn't have enough time. I'll try to push it internally. No promises though ...

**Comment by dhaavi** [comment]
OISD lists are now live:

- Main list in "Ads & Trackers" / "Mixed Ads/Trackers/Malware"
- Extra list in "Experiments"
- NSFW list in "NSFW" / "Mixed"
