### ISSUE TITLE
Portmaster runs without problem with ESET IS and Trend Micro

### ISSUE THREAD

**Issue by davegson** [safing/portmaster#349]
> Originally reported on Malwaretips:
> https://malwaretips.com/threads/portmaster-firewall-alpha-stage.108383/post-945717
> > Also, I have already tried the Portmaster together with Eset IS, SEP and Trend Micro and did not notice any incompatibilities.

**What worked?**

everything

**What did not work?**

no incompatibilities were noticed

---

@DevilInMachine, I made the assumption of Windows 10 for all software since Trend Micro does not offer their services for Linux.

Also, what exactly does SEP stand for? The best guess I found was [Symantec](https://sep.securitycloud.symantec.com/v2/landing), but I need confirmation before adding this to the docs.

**Comment by DevilInMachine** [comment]
@davegson 

> Also, what exactly does SEP stand for? 

Yes, SEP is Symantec Endpoint Protection. I also continue to use Portmaster and Eset already on real hardware and can still confirm that everything is working well. And yes, it was about Windows 10 21H1
I 'm sorry for the long answer =) =)

**Comment by davegson** [comment]
updated the docs! So cool to hear the PM works well! And no worries - we all answer when we have time :) cheers
