### ISSUE TITLE
Location Of Signing Key Used In Order To Verify Downloaded deb Package

### ISSUE THREAD

**Issue by thegranddesign** [safing/portmaster#355]
It's very important with all packages but especially with a package as tied to the security of the system as this, to be able to verify that the package we're installing has not been tampered with. [debsig-verify](https://manpages.ubuntu.com/manpages/xenial/man1/debsig-verify.1.html) is the general way this is done.  Ideally there would be a PPA you all controlled which would allow us to both verify as well as automatically download the latest version for installation, but for now, using debsig-verify will do as a simple solution.

The only thing that would be required on your part is to link to the PGP key used to sign the file.

**Comment by thegranddesign** [comment]
Obviously anything is better than nothing so even if you give us the signing key and we have to manually run `gpg --verify` that would be preferable to not having any verification at all.

**Comment by ppacher** [comment]
Hi @thegranddesign,

thanks for reaching out to us. We already have signing planned but this will likely not happen before we transition into beta  (we're still in alpha version). The Portmaster consists of multiple binaries, does auto-updates of them and also fetches intel data (like filterlists) from our update server. Signing and checksum verification must be done on all of those components and we must also add support to the auto-update system. All of this is planned and in backlog but we have bigger things that we need to tackle first.

Though, thanks for reporting and for taking security seriously. I'll keep the issue open until we transition to beta and eventually add signing/verification to the whole process.

**Comment by thegranddesign** [comment]
Thanks @ppacher!  And also thank you for building this.  I'm transitioning from Mac to Linux and the need for a Little Snitch replacement was a huge reason for delaying until now.  Knowing that you all have a sustainable business model with which to continue to support this helped me decide on portmaster.  I look forward to watching this project grow.

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.

**Comment by biehl1** [comment]
Hello @Raphty 
I still cannot find on public website references to public keys, signatures or checksums for available downloads.
Could someone share references to those? Would really like to give your software a go.
Thanks

**Comment by biehl1** [comment]
Hello @Raphty 
I still cannot find on public website references to public keys, signatures or checksums for available downloads.
Could someone share references to those? Would really like to give your software a go.
Thanks

**Comment by Raphty** [comment]
checksum are here: https://github.com/safing/checksums/
on windows checking the signature is super easy, during the install you can expand an look at the signature.

the installer is signed and each update is signed as well, Portmaster checks the validity of the signature before applying the update

**Comment by biehl1** [comment]
@Raphty never mind, my bad, I missed this before. It is on the website. https://safing.io/download/
The signed commits still valid improvement though 👍 
Thanks

**Comment by thegranddesign** [comment]
@Raphty I'd prefer to keep this issue open until the DEB package is signed. Checksums are an improvement but are not nearly as secure as signing the package. Checksums can be MITM-ed but signatures would require a lot more effort on an attackers part.  Signing DEBs is extremely easy to add to your build pipeline: https://blog.packagecloud.io/how-to-gpg-sign-and-verify-deb-packages-and-apt-repositories/
