### ISSUE TITLE
`libappindicator`: removed from Debian, switch to `libayatana-appindicator`

### ISSUE THREAD

**Issue by Tachi107** [safing/portmaster#356]
Hi, Portmaster looks reeally cool, but I haven't tried it yet, so I can't fill a complete compatibility report.

What I can say is that `libappindicator` has been deprecated for a few years, and has been completely removed from Debian 11 (releasing in a few weeks); you can see the details [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037), but in short you should switch to `libayatana-appindicator3-1`, at least in Debian-based distributions, otherwise Debian users won't be able to install Portmaster :/

**Comment by ppacher** [comment]
Hi @Tachi107,

thanks for reaching out to us and for hinting about the `libappindicator` deprecation. I'll discuss the next steps in this regard with our team.

**Comment by Tachi107** [comment]
Uhm, I don't think that was the right move :/

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by dhaavi** [comment]
The library we use currently has no patch for this - the issue tracked here: https://github.com/getlantern/systray/issues/191

There is however a simple fork to fix this: https://github.com/nekr0z/systray
Fix commit: https://github.com/nekr0z/systray/commit/891b38719d739d142ba82f55cc133495ca27d5bc

I asked them to merge the patch of the fork.

**Comment by Tachi107** [comment]
Fixed in https://github.com/getlantern/systray/pull/225

**Comment by dhaavi** [comment]
Thanks for the heads up @Tachi107 - I hope they tag a new release, else we'll tag to the commit next week.

**Comment by Crosse** [comment]
Hey @dhaavi, let me do a few housekeeping things and I'll tag a new version of getlantern/systray soon.

**Comment by dhaavi** [comment]
Thanks all!

The newest version of the Portmaster Notifier released last week is already using the new updated version.

**Comment by Tachi107** [comment]
Nice, thanks :)
