### ISSUE TITLE
Network Scope settings don't save?

### ISSUE THREAD

**Issue by styromaniac** [safing/portmaster#357]
I'm unable to make any actual change under Network Scope settings for Chromium, and probably other settings below that with the same weird slider. I hit enter and nothing happens. I click the X and the setting goes back to the default, never actually enforcing the setting I select in the first place. Am I doing something wrong or is this a bug?

I'm on Linux Mint Debian Edition, so I'm running the Ubuntu package. PortMaster seems to run just fine and I am able to block all network access to individual apps.

I really want this to work because I'm on ZeroNet and us users don't want clearnet resources (anything not served to the browser via localhost) to load, so that's how I found this apparent bug.

**Comment by ppacher** [comment]
Hi @styromaniac,
thanks for reaching out. I'm sorry you're having a hard time with those settings. 

The Portmaster should auto-save the settings once you edit them. Clicking the "x" on the right hand side of the settings will "delete the setting from the profile" and thus cause a fallback to the respective global setting.

Please note that the Portmaster cannot yet enforce settings on already permitted connections. For performance reasons the decision to allow a specific connection is permanent as long as the connection exists. New connections will get filtered as you would expected. 

What exactly so you want to achieve?

**Comment by ppacher** [comment]
Then setting the "Block Internet Access" setting to "Trusted" should do the trick to always block Chrome from accessing the internet. If you set the slider to "Trusted" it will always be active. If you set it, for example, to "untrusted" that it will only be active if your network rating (on the top left) is either "Untrusted" or "Danger". 

Please note that Chrome normally keeps the HTTP connections active and also shares them across different tabs! If you want to really test the setting you need to open a new tab with a new domain (preferably something you haven't opened in a couple of minutes). Alternatively, you can just close the browser and restart it.

If that doesn't work it would be great if you could attach the debug information form the settings page.

**Comment by styromaniac** [comment]
I understand now, but the whole thing is probably confusing other people too.

**Comment by davegson** [comment]
@styromaniac just wanted to check in and let you know v0.6.22 got released:
https://safing.io/blog/2021/09/08/portmaster-release-6-22/

we hope on-boarding will be smoother now - would be nice to hear what you think!
