### ISSUE TITLE
Feature: Recording of network activity in log files.

### ISSUE THREAD

**Issue by ZeroDot1** [safing/portmaster#359]
**What would you like to add or change?**:
Add a feature to record all network activity in .CSV files for each application individually.
The record should contain minimum the following:

IP address, domain/subdomain, time, process name, file path to the executing process.

Once the recording function has been enabled, the recording should automatically continue when the application is restarted until the user stops the recording.

**Why do you and others need this?**:

A network activity recording feature is especially helpful for all security researchers.

**Comment by ppacher** [comment]
Hi @ZeroDot1,
thanks for reaching out to us!

I like the idea of a simple "record-to-file" feature. Right now the Portmaster only persists connection for about 5 minutes and only stores them in-memory. We already plan for a "history module" that persists connections for a longer period of time. Once we have that we can also do a "export as CSV" feature. This way you don't need to enable it on a per-process basis but instead just export the history of the process of interest.

Still, you'r request made me think about PCAP recording of process network streams. Right now we hand the connection back over to the kernel for performance reasons but if I want to create a PCAP file of all network connections of a process I guess a degraded performance is something one may be willing to pay.

What do you think?

**Comment by ZeroDot1** [comment]
Hi @ppacher, thank you very much for your answer.

I think a PCAP file should be created only if the user has explicitly set it.
If the user does not need a PCAP file Portmaster should run as it is at the moment. 
This has the advantage that there is no speed loss in normal operation.

**Comment by ppacher** [comment]
Yeah that's what I would suggest as well. Right now we have the ["Default Action"](https://docs.safing.io/portmaster/settings#filter/defaultAction). I would suggest extending that and adding an `Allow and Capture` verdict that will create a PCAP file for each connection of the targeted process.

I'll keep this issue open until we find some time to actually plan this feature request.
Thanks for bringing it up!

**Comment by ZeroDot1** [comment]
You can read my thoughts!

That's exactly how I thought, perfect.

:1st_place_medal:

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.
