### ISSUE TITLE
Feature: Translate Portmaster to different languages

### ISSUE THREAD

**Issue by ZeroDot1** [safing/portmaster#360]
**What would you like to add or change?**:
I asked some people if they would also use Portmaster and let them try it out, the problem is that Portmaster is only available in English and therefore some people cannot use Portmaster due to not knowing the language.

If Portmaster became available in more languages, more people would be able to use it.

I recommend weblate as a translation tool. https://weblate.org/
I could do the translation in German.

**Why do you and others need this?**:
Portmaster should be available in different languages so that more people can use Portmaster.

**Comment by ppacher** [comment]
HI @ZeroDot1,
thanks for your suggestion and pushing the Portmaster!

We definitely have localization and multi-language support on our TODOs but are currently lacking the resources to prepare everything for a localized UI. I like the idea of calling for community support using https://weblate.org but we first need to build the basis for a localized Portmaster installation.

**Comment by ZeroDot1** [comment]
Take your time Rome wasn't built in a day either.

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.
