### ISSUE TITLE
Application Typo

### ISSUE THREAD

**Issue by MaiAsagi** [safing/portmaster#361]
Application Version 0.1.18 (Checked for Updates on Startup)

Tested on Windows (Haven't checked on Linux)

![Encrytped](https://user-images.githubusercontent.com/88003732/127062949-5c875668-4d49-42de-b0a6-935aad362e53.JPG)

Suggested Changes

> Encrytped > Encrypted

**Comment by ppacher** [comment]
Hi @MaiAsagi ,

thanks for pointing that out. I just pushed a fix in  safing/portmaster-ui#157.

**Comment by dhaavi** [comment]
Fix is merged, but not yet released.
