### ISSUE TITLE
Blocking selected endpoints

### ISSUE THREAD

**Issue by Ajoni** [safing/portmaster#367]
**What would you like to add or change?**:
Ability to block selected endpoints.

**Why do you and others need this?**:
I would like to block telemetry endpoints for discord like "discord.com/api/v9/science"
Currently I'm getting an error: "unknown endpoint definition"

**Comment by ppacher** [comment]
Hi @Ajoni,

thanks for reaching out! Blocking selected endpoints should already work.

Did you have a look at our documentation regarding the [endpoint rules](https://docs.safing.io/portmaster/settings#filter/endpoints). 
It would be great if you could post the actual rule you're trying to create. It's a bit hard to tell anything useful without it.

Also, are you running on Windows or Linux? It would be great if you could try to fill out the issue template as it greatly improves debug-ability of issues.

**Comment by ppacher** [comment]
Hi @Ajoni,

I didn't notice that this issue is posted as a `suggestion` and not as a `bug`. The suggestion issue template is indeed just the two section you already provided. Sorry for that!

Can you check if the [Endpoint Rules](https://docs.safing.io/portmaster/settings#filter/endpoints) already does what you suggested?

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
