### ISSUE TITLE
Takes too long to load 

### ISSUE THREAD

**Issue by daniyal-f-s** [safing/portmaster#380]
**What would you like to add or change?**:
Needs optimization improvement

**Why do you and others need this?**:
Portmaster takes an eternity to load on a low-end computer.

**Comment by dhaavi** [comment]
Hey @daniyal-f-s, thanks for the suggestion!

Can you elaborate on when at what exactly takes an eternity to load?
Also, which OS are you on?

In general, the Portmaster Core Service, which runs in the backround as a system service is very fast and should run without problems even on a low-end system. The Portmaster UI on the other hand might be a little slow on low-end systems, as we sadly needed to switch that to electron. We hope to improve on this soon, and there are already some nice alternatives on the horizon which will help us make this blazing fast again.

In the meantime, you can also open the Portmaster UI in the browser. For this you need to:

- Configure [API Keys](https://docs.safing.io/portmaster/settings#core/apiKeys).
- Open http://127.0.0.1:817/api/v1/auth/basic in your browser and enter the API key.
- Then open http://127.0.0.1:817 to view the UI.

You can also check out the [Architecture Overview Docs](https://docs.safing.io/portmaster/architecture/overview) for more information.

**Comment by daniyal-f-s** [comment]
OS I'm using is Windows 10
After the installation Portmaster took almost 30 min to load, but now it's opening fine in less than minute, I think that was probably because of first opening maybe....

Thanks for replying....

**Comment by dhaavi** [comment]
Great! Thanks for letting us know.

We will improve the installers in the coming weeks so that this should not happen anymore.
