### ISSUE TITLE
Support for sysVinit maybe?

### ISSUE THREAD

**Issue by skyemk7777** [safing/portmaster#383]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

System information:

System:    Kernel: 5.8.16-antix.1-amd64-smp x86_64 bits: 64 compiler: gcc v: 8.3.0 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.8.16-antix.1-amd64-smp root=UUID=<filter> ro 
           quiet splash init=/lib/systemd/systemd 
           Desktop: KDE Plasma 5.14.5 tk: Qt 5.11.3 info: latte-dock wm: kwin_x11 vt: 7 dm: SDDM 
           Distro: MX-19.4_x64 patito feo March 31  2021 base: Debian GNU/Linux 10 (buster) 
Machine:   Type: Desktop Mobo: MSI model: H61M-P32/W8 (MS-7788) v: 4.0 serial: <filter> UEFI: American Megatrends v: 10.11 
           date: 10/18/2013 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Micro-Star MSI driver: r8169 v: kernel 
           port: e000 bus-ID: 02:00.0 chip-ID: 10ec:8168 class-ID: 0200 
           IF: eth0 state: up speed: 100 Mbps duplex: full mac: <filter> 
Info:      Processes: 252 Uptime: 33m wakeups: 0 Memory: 7.48 GiB used: 2.4 GiB (32.1%) Init: systemd v: 241 runlevel: 5 
           default: 5 tool: systemctl Compilers: gcc: 8.3.0 alt: 8 Shell: quick-system-in default: Bash v: 5.0.3 
           running-in: quick-system-in inxi: 3.3.06 

**What worked?**

UI and notifier works since its started by kde.

**What did not work?**

Core does not start since it relies on systemd.

I switched to systemd in kernel and for some reason core still doesn't start.

Manually starting core works "sudo /var/lib/portmaster/portmaster-start core" works, but I guess it starts late down the line instead of earlier. I'm not really sure, how to write a sysvinit script for on startup.

Is providing support for sysVinit maybe possible?

**Comment by dhaavi** [comment]
Hey @skyemk7777, thanks for reporting this.

As you noted, we currently do not support SysV-Init. We are doing some installer work in the coming weeks, and we will look into this and evaluate supporting SysV-Init. No promises though.

Maybe the service hasn't been enabled. Easiest way to would be to just install the .deb again after the switch to systemd to ensure everything is configured correctly.

**Comment by skyemk7777** [comment]
hey, I switched to systemd, which has a service file for the startup but since sysvinit doesn't portmaster core doesn't start.

I'm not sure how to create a init service file. You guys might be able to anyways, MX Linux isn't compatible out of the box without switching to systemd or making a startup script that starts portmaster core on login.
