### ISSUE TITLE
Update check Fails on startup

### ISSUE THREAD

**Issue by Shaolin-Twelve** [safing/portmaster#389]
### What happened?
Every time Portmaster starts and checks for updates it fails, and using the (Try again now) button throws up an xml error in the bottom left corner of Portmaster.

If I go to the core settings and use the (Check for updates) selection, Portmaster checks for updates without error.

### What did you expect to happen?
Portmaster should start and update without error (where possible), and the &#39;Check again Now&#39; button should not constantly throw up an error.

### How did you reproduce it?
I can reproduce the issue on every startup of the OS.

### Additional information
I am on Linux Mint 20, Kernel: 5.4.0-84-generic x86_64,  Desktop: Cinnamon 4.6.7

I have previously praised your stunning efforts, and will continue to do so. This bug is a minor issue which has persisted over several updates, I am still seriously stoked at what you have created - keep up the exceptional work, you deserve every success.

I think the error may be avoided by delaying the update check until a network interface is confirmed up.

**Debug-Info**: https://support.safing.io/privatebin/?50fff0a58a71f4a5#CYX33y4chCu1tD1fuvC99rMNs6Aev1ALaVHPYefynyif

**Comment by dhaavi** [comment]
Hey @Shaolin-Twelve, thanks for reporting this issue!

> using the (Try again now) button throws up an xml error in the bottom left corner of Portmaster.

Well, that should work.
Tracking this internally with CC#2031.

> I think the error may be avoided by delaying the update check until a network interface is confirmed up.

That's a great idea - we'll look into it!
Tracking this internally with CC#2032.

> I have previously praised your stunning efforts, and will continue to do so.

Thanks! This is very much appreciated.

---

Also, I've noticed something in the logs you provided:
`cannot use resolver dot://103.86.96.100: DOT must have a verify query parameter set`

A resolver you have configured is invalid. Our [DNS Configuration Guide](https://docs.safing.io/portmaster/guides/dns-configuration) might help you with this.

**Comment by Shaolin-Twelve** [comment]
Hi Daniel,

thank you so much for your quick response,

I have now changed the dns entries to DNS not DOT, thank you so much
for pointing that out.

I must admit to finding some of Portmaster difficult to unders ... wait
a mo! as soon as I think of an issue, seems like you're all
clairvoyant ... what can I say except another huge thank you !!!

Somehow you were ahead of my needs and introduced info sections and a
help section and a report section ... seriously good, logical, well
executed ... I'm literally falling in love with your whole project, is
there ANY possibility that you talented, caring, thoughtful people
would re-design the internet and save the World whilst you're at it?

OK I know that all seems over the top, and I am aware of others who do
a Stirling job, however, and I mean this genuinely, I am bowled over by
your forethought and attitudes, you simply are the best, and I can't
believe I'm writing this as I am a picky person who is ultra-critical
of many things (that just seem badly designed or deliberately badly
designed).

Your efforts literally bring a smile to my face, and lift my spirits
like no others have. It is SO refreshing, and SO faith building, some
might wonder how a piece of software could have that effect on a
person, or may suspect I have a screw loose, but I really believe in
credit where credit is due, and credit is well due for you.

I still am stunned that you made ALPHA software that performs better
than most released Software, and I really think you are an excellent
example for the entire planet, let alone the Internet.

All my Love and respect to you and your team/s, may you all be richly
rewarded!

Peter Micallef
Malvern Wells
England.


On Wed, 08 Sep 2021 01:15:31 -0700
Daniel ***@***.***> wrote:

> Hey @Shaolin-Twelve, thanks for reporting this issue!
> 
> > using the (Try again now) button throws up an xml error in the bottom left corner of Portmaster.
> 
> Well, that should work.
> Tracking this internally with CC#2031.
> 
> > I think the error may be avoided by delaying the update check until a network interface is confirmed up.
> 
> That's a great idea - we'll look into it!
> Tracking this internally with CC#2032.
> 
> > I have previously praised your stunning efforts, and will continue to do so.
> 
> Thanks! This is very much appreciated.
> 
> ---
> 
> Also, I've noticed something in the logs you provided:
> `cannot use resolver dot://103.86.96.100: DOT must have a verify query parameter set`
> 
> A resolver you have configured is invalid. Our [DNS Configuration Guide](https://docs.safing.io/portmaster/guides/dns-configuration) might help you with this.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/safing/portmaster/issues/389#issuecomment-915020923


-- 
Shaolin Twelve ***@***.***>

“Those who sleep in a democracy wake up in a dictatorship.”

**Comment by dhaavi** [comment]
Hey @Shaolin-Twelve, thank you very much for your kind words. We've shared this with the team and it was a great encouragement for everyone!

(Sorry for the late reply, there is _a lot_ going on here atm.)
