### ISSUE TITLE
Integrate Multipath TCP (MPTCP) for SPN

### ISSUE THREAD

**Issue by Victor239** [safing/portmaster#395]
**What would you like to add or change?**:

[Multipath TCP](https://en.wikipedia.org/wiki/Multipath_TCP) (AKA channel bonding) in my understanding works by a client on the user's device aggregating the internet connection from multiple sources (e.g. mobile Wi-Fi hotspot, ethernet connection, secondary Wi-Fi, etc) which is then forwarded to a VPN server which intelligently balances traffic across these multiple connections. 

It is currently in use in [several iOS apps](https://en.wikipedia.org/wiki/MPTCP#Use_cases) as well as [Speedify VPN](https://speedify.com/) is doing it commercially. MPTPC support is also [being added into the Linux kernel](https://github.com/multipath-tcp/mptcp_net-next/wiki), and the [OpenMPTCPRouter](https://github.com/Ysurac/openmptcprouter) project is working on it too. It would be great to see Portmaster support this also as I think it would result in a significant speed boost compared to not having Portmaster turned on.

**Why do you and others need this?**:

Improved speed of connection plus stability.

**Comment by ppacher** [comment]
Hi @Victor239,
thanks for your suggestion and for reaching out to us!

We have support for Multi-Path connections already planned for the SPN (see [here](https://safing.io/backlog/#spn)).
Though, it will take some time to get there as we have to do other stuff in the SPN first.

Alos, you can always check what we are [currently up to](https://safing.io/next) and our [backlog](https://safing.io/backlog).

**Comment by Victor239** [comment]
Ah didn't realise, glad to hear!

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.

**Comment by Victor239** [comment]
This issue is still relevant as it was a feature on your official roadmap.
