### ISSUE TITLE
Change app path to reuse configured rules

### ISSUE THREAD

**Issue by katoquro** [safing/portmaster#398]
**What would you like to add or change?**:
Some tools have version in application path to the binary f.e. snap on linux have such path 
`/snap/<app>/<version>/<path to the binary>`
After update the new version is considered as new app 

**Why do you and others need this?**:
I would like to have possibility to replace (or reuse rules from previous version) path to the app to reuse configured rules

As extended proposal I think it's possible to detect such cases (the same app name, almost identical path) and postmaster could prompt to the user to change the path

**Comment by ppacher** [comment]
Hi @katoquro,
thanks for your suggestion!

We already have a solution for that planned but haven't been able to tackle it yet. We do plan to support wildcards/regexp for application paths so one could simply do something like `/snap/app/.*/bin/binary` or `/snap/app/.*`.

I'll keep the issue open until we find time to finally tackle that and will keep you posted!

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by stusmall** [comment]
@ppacher Is there an issue I can subscribe to for the wild card application path work?

**Comment by dhaavi** [comment]
We now have a system to support this use case.
Now tracking internally at CC#2632.

**Comment by dhaavi** [comment]
This is happening: PR https://github.com/safing/portmaster/pull/999
