### ISSUE TITLE
Firewall port ranges (+general firewall rules guide?)

### ISSUE THREAD

**Issue by Tc-001** [safing/portmaster#412]
**What would you like to add or change?**:
I would like to be able to specify an incoming/ougoing port range in the application rules.

**Why do you and others need this?**:
Software like [KDE connect](https://kdeconnect.kde.org/) requires the firewall to allow requests from a specific port range for the syncing to happen. Specifically the ports `1714-1764` for both tcp and udp ([Source](https://www.incredigeek.com/home/allow-kde-connect-through-firewall/)).
I also cannot whitelist a specific local IP address because it might change once the lease runs out.

While researching on writing these rules, I could not find a guide in the docs on even the basic structure of a rule
https://docs.safing.io/portmaster/architecture/core-service/core/#firewall < Not there
https://docs.safing.io/portmaster/architecture/core-service/privacy-filter/#rules < Or here

And I could not find a valid syntax even with trial and error
```
* tcp/1714-1764
* tcp/1714:1764
* tcp/1714 : 1764
and some more...
```
All of them failing with an error message
![image](https://user-images.githubusercontent.com/55956895/136982615-c54d6d92-6eef-4ebb-9d7e-951af92cadf5.png)

I even went so far as to try and dissect the validation regex with still no luck

So I guess the question is: Is it possible to specify a port range in firewall rules? If so, could it (together with a general syntax guide) be added to the docs?

**Comment by dhaavi** [comment]
Great to hear it works!

Can you elaborate what exactly you meant with a firewall rules guide?
What depth do you expect? More examples? A situational walkthrough?
I'm trying to better understand your needs.
