### ISSUE TITLE
"Allow IP" should write incoming rule for incoming connections

### ISSUE THREAD

**Issue by DavidRotert** [safing/portmaster#426]
**How did you reproduce it?**:
1. From an external device, connect to a service on the host (for example to SSH)
2. On "Unidentified Processes" in "Network Monitor", open the information for the incoming connection
3. Click on "Allow IP"

**What happened**:
"Allow IP" writes to "Outgoing Rules" in the app settings.

**What did you expect to happen?**:
"Allow IP" should write to "Incoming Rules".

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by ppacher** [comment]
This should already be fixed with the new network monitor. Hence, I'm closing this. Feel free to re-open if the issue somehow persists.
