### ISSUE TITLE
Doesnt start on 5.14.10-1

### ISSUE THREAD

**Issue by anthonym01** [safing/portmaster#432]
### What did not work?
App doesnt start

**Debug-Info**: https://support.safing.io/privatebin/?547a641fdbefabde#12Snk6mYMHi3R3o4GmYURJESuieqpyxpvJZJhDuRRPs7

**Comment by dhaavi** [comment]
Thanks for the details, we are going to look into this.

Tracked internally with CC#2104.

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by ppacher** [comment]
We had a lot of changes since then. Can you please confirm that the issue has gone away?

**Comment by anthonym01** [comment]
That computer is in the graveyard now, so I can't check

**Comment by ppacher** [comment]
Nice, that was a quick reply :)

I'm going to close this then since 5.14 is already some releases ago and I think we did not get any similar reports for some time now. 
Anyone, feel free to re-open if the issue persists.
