### ISSUE TITLE
Local pihole-unbound-docker useable as DNS would be nice

### ISSUE THREAD

**Issue by Broeckelmann** [safing/portmaster#434]
**What would you like to add or change?**:
Would be nice if it would be possible to use [pihole-unbound-docker](https://github.com/chriscrowe/docker-pihole-unbound) locally in portmaster. I tried around a bunch and I just can't get it to work. (may be related to [issue #166](https://github.com/safing/portmaster/issues/166))

(Edit: I am using Windows btw, with WSL backend for docker)

**Why do you and others need this?**:
To make it possible to rely on a locally hosted dns server, which is much faster after having built up the cache a bit.
And also no more reliance on some DNS provider.

**Comment by Broeckelmann** [comment]
Sorry, was quite busy the last few weeks. 

Can I somehow look up in portmaster the dns query log? Because I can config pi-hole as a dns option and remove everything else, with either your line ``docker run --rm -ti -p 54:53/udp -p 80:80 --env WEBPASSWORD=password cbcrowe/pihole-unbound:latest`` or with the ``.yaml + .env files`` [as described on](https://github.com/chriscrowe/docker-pihole-unbound/tree/master/one-container) and then browse the Internet normally, but the pi-hole admin interface shows no change in the query log.

I honestly never know with portmaster which dns server is getting used, as in this case it shouldn't work if I can trust the pi-hole query log.

**Comment by dhaavi** [comment]
You can just use `dig` to query from within the WSL. The Portmaster attaches additional information to the response.

Eg.
```
$ dig orf.at

; <<>> DiG 9.16.8-Ubuntu <<>> orf.at
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61560
;; flags: qr rd; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 3
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;orf.at.				IN	A

;; ANSWER SECTION:
orf.at.			17	IN	A	194.232.104.149
orf.at.			17	IN	A	194.232.104.140
orf.at.			17	IN	A	194.232.104.150
orf.at.			17	IN	A	194.232.104.141
orf.at.			17	IN	A	194.232.104.4
orf.at.			17	IN	A	194.232.104.3
orf.at.			17	IN	A	194.232.104.142
orf.at.			17	IN	A	194.232.104.139

;; ADDITIONAL SECTION:
info.portmaster.	0	IN	TXT	"accepted: allowing dns request"
info.portmaster.	0	IN	TXT	"served from cache, resolved by Cloudflare (dot://1.1.1.2:853#config)"
info.portmaster.	0	IN	TXT	"record valid for 6h35m46s"

;; Query time: 52 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Do Nov 18 10:47:43 CET 2021
;; MSG SIZE  rcvd: 407
```

You might need to directly target the Portmaster, as WSL2 is a VM and VMs are still out of scope for the Portmaster, as in we cannot guarantee anything.

---

Also, if you are in the [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel), you can already use the localhost IP in the settings. That should work now.

**Comment by Broeckelmann** [comment]
Sorry, beta release just borked portmaster entirely no queries or anything happens anymore even after reverting back to stable, had to completely reinstall and even after I restarted a couple of times just to see whats up, maybe it's because I am running windows11 but I don't know as I get no errors, it just stops working with default settings even.

I am going to wait for localhost to be in the stable version and then try again.

But it does work in dns:// mode with the docker run command, but that's not secure as you already said.

I have to look more into how to set it up securely and more easily, maybe even as a direct option in portmaster later on.

**Comment by dhaavi** [comment]
> Sorry, the beta release just borked portmaster entirely no queries or anything happens anymore even after reverting back to stable, even after I restarted a couple of times just to see whats up. After that I had to completely reinstall, maybe it's because I am running windows11 but I don't know as I get no errors, it just stops working (as in I can't connect the internet) with default settings even.

This is really interesting. I know of no other such problems with the current Beta channel. And at least switching back to Stable channel should have fixed it. Something is going on here.

> I am going to wait for localhost to be in the stable version and then try again.

Not sure how much will change until then. Releases in the Beta channel just stay there for about two weeks to see if there are any big issues and are then released st Stable channel.

> But it does work in dns:// mode with the docker run command, but that's not secure as you already said.

I'm not sure I can follow. Can you elaborate what you mean by "dns:// mode"?

**Comment by Broeckelmann** [comment]
> This is really interesting. I know of no other such problems with the current Beta channel. And at least switching back to Stable channel should have fixed it. Something is going on here.

Oh, I would love to open an issue but without any error log I don't think I can do help much. Haven't tried since maybe it's just somehow caused by windows11, as everyone knows it's still a bit buggy.

> I'm not sure I can follow. Can you elaborate what you mean by "dns:// mode"? 

Sorry, I just mean dns://<local IP>:port

**Comment by Broeckelmann** [comment]
Can I close this?
