### ISSUE TITLE
portmaster updates make my cpu fan go brrrrrrr

### ISSUE THREAD

**Issue by D0nnieD4rk0** [safing/portmaster#442]
they cut off internet tho thats probably a feature to prevent leaks, but thats beside the point
updates take a heavy cpu load pls fix in the future

**Comment by dhaavi** [comment]
Hey @D0nnieD4rk0, thanks for reporting this!

Can you check if this matches the behavior described in https://github.com/safing/portmaster/issues/422?
Also, are you running a low-end system?

**Comment by dhaavi** [comment]
This might also be related to #422 and #420.

**Comment by Flashwalker** [comment]
I have the same thing. Every time I run a UI application, it starts to heat up my CPU.

Even though I disabled updates in settings, every time I see the process: 
```
/op/safing/portmaster/updates/linux_amd64/core/portmaster-core_v1-0-2 --date /opt/safing/portmaster
```

which I assume is trying to update something
