### ISSUE TITLE
Update Check in core fails when on VPN

### ISSUE THREAD

**Issue by trekjunky** [safing/portmaster#448]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
I turn off VPN then run a manual update, then, after a successful update, I turn on VPN and wait a few hours. While VPN is running  which is all the time, the update check from the core app fails.

**What did you expect to happen?**:
The update check to be successful and initiate an update if needed.

**How did you reproduce it?**:
With VPN on, wait an few hours

**Debug Information**:

<!--
Paste debug information below:
- General issue: Click on "Copy Debug Information" on the Settings page.
- App related issue: Click on "Copy Debug Information" in the dropdown menu of an app in the Monitor view.

⚠ Please remove sensitive/private information from the "Unexpected Logs" and "Network Connections" sections.
This is easiest to do in the preview mode.

Additional logs can be found here:
- Linux: `/var/lib/portmaster/logs`
- Windows: `%PROGRAMDATA%\Safing\Portmaster\logs`
--
[2021-11-12-06-36-59.log](https://github.com/safing/portmaster/files/7531523/2021-11-12-06-36-59.log)
>

**Comment by dhaavi** [comment]
Hey @trekjunky, thanks for reporting this.

What kind of / which VPN are you using in this case?
Does everything else work properly while the VPN is active?
Can you supply us with the debug information _while_ experiencing the issue?

**Comment by trekjunky** [comment]
@dhaavi  I use OpenVPN version of ProtonVPN
Everything else works with the VPN I use
I don't know how to collect the debug information

**Comment by trekjunky** [comment]
I just tested it and it worked as expected, Please close case.
