### ISSUE TITLE
Add Checksums and GPG Signature for Verification for Each Release.

### ISSUE THREAD

**Issue by ghost** [safing/portmaster#454]
### Since Portmaster is about Privacy This makes sense.

# -Add SHA1, MD5, SHA256 Signed Checksums.

# -GPG Verifcation 

-**Provide Portmasters Developers key.**

-**Provide Documentation for Windows/Linux Users on how to verify the signature.**

**Comment by dhaavi** [comment]
Hey @CyberPunkInterface, thanks for the suggestion.

The Windows installer is already signed with our EV cert, and the Linux installers will be signed with PGP in the future.
Updates will also be signed through our internal system in the future.

Progress of that is tracked by the "Cryptographically Sign Updates" Card on the [Product Roadmap Backlog](https://safing.io/backlog/).

You can verify the signature of the Windows installer by viewing the file properties.

We will probably add checksums in the future, but we don't have details on this yet.

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by iulko** [comment]
Is there any news about including checksums of the installer? I hope it will also include offline installer

**Comment by Raphty** [comment]
Installer check sums are available
![image](https://github.com/safing/portmaster/assets/11504285/e2f857f9-defa-4506-a06d-3a28e7a54168)

**Comment by Raphty** [comment]
@dhaavi we are also signing update now, do we intend on doing checksum checks as well or is it already implemented?

**Comment by dhaavi** [comment]
Installer checksums are available at https://github.com/safing/checksums - for installers and other resources.

Currently, we provide checksums and sign binary updates.
We might provide PGP support in the future. The signatures files can hold both.

You can check signatures using portmaster-start utility found in the data directory of portmaster: `./portmaster-start verify`
