### ISSUE TITLE
Network login portal issue (Windows, Virgin Media)

### ISSUE THREAD

**Issue by VilotStar** [safing/portmaster#455]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

I was trying to connect to a network of the place I'm currently staying at, I could not reach the login portal by using the detect portal button in Portmaster and also could not do it normally by finding the gateway IP because they both reported having no connection to the internet, I used a few browsers and they all came up with the same result, those browsers being: Brave, Microsoft Edge and Firefox.

I managed to resolve the issue by turning off Portmaster then viewing the login portal, and after turning it on again I'm having no issues.

**What did you expect to happen?**:

I expected the login portal for the network I was trying to connect to display in my browser without connection errors

**How did you reproduce it?**:

Connecting to a Virgin Media network with a login portal to use the WiFi connection

**Debug Information**:

211128 10:45:06.120 connection:631 > INFO 034 [2x] filter: connection NT AUTHORITY\NETWORK SERVICE:C:\Windows\System32\svchost.exe:3400 -> ff02::1:3 accepted: allowed by default action
211128 10:45:06.120 connection:631 > INFO 035 [2x] filter: connection NT AUTHORITY\NETWORK SERVICE:C:\Windows\System32\svchost.exe:3400 -> 224.0.0.252 accepted: allowed by default action
211128 10:45:06.120 connection:631 > INFO 036 filter: connection NT AUTHORITY\NETWORK SERVICE:C:\Windows\System32\svchost.exe:3400 <- 172.16.0.200 accepted: allowed by rule: scope matches LAN UDP/5355
211128 10:45:06.120 connection:631 > INFO 037 filter: connection NT AUTHORITY\NETWORK SERVICE:C:\Windows\System32\svchost.exe:3400 <- fe80::f851:e3de:d1ee:3c1c accepted: allowed by rule: scope matches LAN UDP/5355
211128 10:45:06.354 all/master:141 > INFO 038 filter: granting own connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 -> 127.0.0.1
211128 10:45:06.354 connection:631 > INFO 039 filter: connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 -> 127.0.0.1 accepted: connection by Portmaster
211128 10:45:06.354 all/master:141 > INFO 040 filter: granting own connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 -> 127.0.0.1
211128 10:45:06.355 connection:631 > INFO 041 filter: connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 -> 127.0.0.1 accepted: connection by Portmaster
211128 10:45:06.355 all/master:141 > INFO 042 [2x] filter: granting own connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 -> 127.0.0.1
211128 10:45:06.356 connection:631 > INFO 043 filter: connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 -> 127.0.0.1 accepted: connection by Portmaster
211128 10:45:06.356 all/master:141 > INFO 044 filter: granting own connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 -> 127.0.0.1
211128 10:45:06.357 connection:631 > INFO 045 [2x] filter: connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 -> 127.0.0.1 accepted: connection by Portmaster
211128 10:45:06.626 connection:631 > INFO 046 filter: connection NT AUTHORITY\SYSTEM:C:\ProgramData\Safing\Portmaster\updates\windows_amd64\core\portmaster-core_v0-7-8.exe:13224 to captiveportal.local.portmaster.home.arpa. (192.0.2.1) accepted: connection by Portmaster
211128 10:45:06.650 connection:631 > INFO 047 [2x] filter: connection NT AUTHORITY\NETWORK SERVICE:C:\Windows\System32\svchost.exe:3400 -> 172.16.15.254 accepted: allowed by default action
211128 10:45:06.659 connection:631 > INFO 048 [2x] filter: connection Kernel::4 -> 172.16.15.255 accepted: allowed by default action
211128 10:45:06.675 all/master:074 > INFO 049 filter: re-evaluating verdict on Unknown::-1 <- 172.16.0.200

**Comment by dhaavi** [comment]
Hey @VilotStar, thanks for the reporting this!

This seems like a rather odd issue.
If you experience it the next time, can you copy and paste the debug data from the settings page here? This would include the detected portal and other important pieces of information.

What you can try as a workaround is to open `neverssl.com` in your browser in order to manually trigger the portal.
