### ISSUE TITLE
Add support for device hotspots

### ISSUE THREAD

**Issue by LivelyCarpet87** [safing/portmaster#462]
**What would you like to add or change?**:

Add support for device hotspots. 

OR

Add ability to allow incoming local LAN connections on trusted networks.

**Why do you and others need this?**:

I personally run a hotspot off my Ubuntu PC. The hotspot process is filed under "Unidentified Processes" and all incoming connections from the hotspot are blocked. It is a hassle to make it work with Portmaster because I have to manually unblock each IP on my hotspot LAN. This recommended feature will make it easier for users with hotspots to use Portmaster.

**Comment by dhaavi** [comment]
Hey @LivelyCarpet87, thanks for reporting this!

You can add an "Allow `LAN`" Rule to the [Incoming Rules](https://docs.safing.io/portmaster/settings#filter/serviceEndpoints) for allow all LAN addresses.
Which hotspot software are you using?

**Comment by LivelyCarpet87** [comment]
My PC uses the Gnome desktop enviroment. The hotspot is created using `nmcli connection up Hotspot` in terminal or by turning it on in the settings app. 

Also thanks for the tip to "Allow LAN," though I've already resorted to manually whitelising all my devices for security sake nonetheless.

**Comment by dhaavi** [comment]
Thanks for the info and great to hear you found a way to resolve it!
