### ISSUE TITLE
Fresh Parrot OS Install Error

### ISSUE THREAD

**Issue by kiraitachi** [safing/portmaster#465]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

Havent seen any incompatibilities so far for Parrot OS reported, Its fresh install, havent installed anything aside from Out of the box.
**What worked?**
Nothing, partiall install but not working.

**What did not work?**
After installing it goes onto error:

```
Setting up portmaster (0.7.0~1) ...
portmaster: Configuring portmaster.service to launch at boot
chcon: can't apply partial context to unlabeled file '/opt/safing/portmaster/portmaster-start'
dpkg: error processing package portmaster (--configure):
 installed portmaster package post-installation script subprocess returned error exit status 1
```

**Debug Information**:

**Comment by kiraitachi** [comment]
Just wanted to mention this happens with Parrot OS security edition

**Comment by dhaavi** [comment]
Hey @kiraitachi, thanks for reporting this.

We'll have a look into this.
I'm not sure if the installation would be actually broken without this.
Do you know how hard SELinux is configured in security edition?

Can you attempt a manual install and see if that works, or where this creates problems?

**Comment by dhaavi** [comment]
We have a similar issue at https://github.com/safing/portmaster-packaging/issues/56.

**Comment by kiraitachi** [comment]
Good night.

I fixed the issue, the following steps where taken:

1. sudo dpkg -i portmaster-installer.deb
2. sudo chcon -h system_u:object_r:bin_t:s0 /opt/safing/portmaster/portmaster-start
3. sudo apt update
4. sudo apt dist-upgrade

After the 4 steps it will automatically detect a package not fully installed or removed. It will proceed to reconfigure portmaster.

```
sudo apt dist-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up portmaster (0.7.0~1) ...
portmaster: Configuring portmaster.service to launch at boot
portmaster: Downloading portmaster modules. This may take a while ...
Scanning application launchers
Removing duplicate launchers or broken launchers
Launchers are updated
```

**Comment by dhaavi** [comment]
Hey @kiraitachi, this is great news!

Thanks for sharing the fix. We will look into fixing the installer.

Side note: Instead of an `sudo apt update` and `sudo apt update` you can also just do `sudo apt install -f` to continue with aborted installations.

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
