### ISSUE TITLE
Compatibility check fails on fresh (debloated/tweaked) Windows 11

### ISSUE THREAD

**Issue by SirRFI** [safing/portmaster#468]
**What happened**:

After few minutes, following notification appears in Portmaster:

> Detected Compatibility Issue
>
> Portmaster detected that something is interfering with its operation. This could be a VPN, an Anti-Virus or another network protection software. Please check if you are running an incompatible VPN client or software. Otherwise, please report the issue via GitHub or send a mail to support@safing.io so we can help you out.

![portmaster-compatibility](https://user-images.githubusercontent.com/32642697/145695279-67b8781b-b710-485c-aca3-7b419376531b.png)

Sometimes this disappears over time. Reason of the issue and what it affects is unknown.

First the message got me off-tracks, but I found nothing. Logs seems to be concerned about DNS. When I turned off DNS over HTTPS in Windows 11 (by setting it to automatic), the issue disappeared. When I tried to reproduce before posting, it started happening again, despite DoH not being enabled.

Logs also mention of `WARNING: config.json has unknown release channel "", falling back to stable channel`, despite already using `stable`.

Logs included in email (debug level).

**What did you expect to happen?**:

Unknown.

**How did you reproduce it?**:

0. Start Portmaster GUI
1. Wait few minutes

**Debug Information**:

<details>
<summary>Version 0.7.10</summary>

```
Portmaster
version 0.7.10

commit tags/v0.7.10-0-gbb3591a7aeb47d6ccc0182936c4a0523ccdd89e4
built with go1.15.8 (gc) windows/amd64
  using options main.go
  by user@docker
  on 06.12.2021

Licensed under the AGPLv3 license.
The source code is available here: https://github.com/safing/portmaster
```

</details>

<details>
<summary>Platform: Microsoft Windows 11 Pro 10.0.22000 Build 22000</summary>

```
System: Microsoft Windows 11 Pro windows (Standalone Workstation) 10.0.22000 Build 22000
Kernel: 10.0.22000 Build 22000 x86_64

```

</details>

<details>
<summary>Status: Trusted</summary>

```
ActiveSecurityLevel:   Trusted
SelectedSecurityLevel: Off
ThreatMitigationLevel: Trusted
CaptivePortal:         
OnlineStatus:          Online
```

</details>

<details>
<summary>Compat Module Error</summary>

```
Message: self-check #2: dns integration check failed: did not receive test query after 3s
Timestamp: 2021-12-12 01:08:28.7770299 +0100 CET m=+220.275514501
ModuleName: compat
TaskName: selfcheck
TaskType: 
Severity: error
PanicValue: %!s(<nil>)
StackTrace:

goroutine 524 [running]:
runtime/debug.Stack(0xc000694070, 0xc0007964b0, 0x50)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa5
github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc000177900, 0x134d51e, 0x9, 0x144dc80, 0xc000694070, 0x58)
	/home/user/git/safing/portbase/modules/error.go:48 +0x58
github.com/safing/portmaster/compat.(*systemIssue).notify(0x18d76e0, 0x144dc80, 0xc000694070)
	/home/user/git/safing/portmaster/compat/notify.go:89 +0x1ac
github.com/safing/portmaster/compat.selfcheckTaskFunc(0x145fe80, 0xc0008aa180, 0xc0001d85a0, 0x0, 0x0)
	/home/user/git/safing/portmaster/compat/module.go:85 +0x16b
github.com/safing/portbase/modules.(*Task).executeWithLocking(0xc0001d85a0)
	/home/user/git/safing/portbase/modules/tasks.go:369 +0x94
created by github.com/safing/portbase/modules.(*Task).runWithLocking
	/home/user/git/safing/portbase/modules/tasks.go:318 +0x285


```

</details>

<details>
<summary>Unexpected Logs</summary>

```
211212 01:04:57.089 olver-mdns:094 > WARN 082 intel(mdns): failed to create udp6 listen multicast socket: listen udp6 [ff02::fb]:5353: setsockopt: not supported by windows
211212 01:05:01.747 pat/module:083 > ERRO 084 compat: self-check #2: dns integration check failed: did not receive test query after 3s
211212 01:06:04.748 pat/module:083 > ERRO 169 compat: self-check #2: dns integration check failed: did not receive test query after 3s
211212 01:07:07.751 pat/module:083 > ERRO 181 compat: self-check #2: dns integration check failed: did not receive test query after 3s
211212 01:08:10.752 pat/module:083 > ERRO 203 compat: self-check #2: dns integration check failed: did not receive test query after 3s
211212 01:08:28.777 CURRENT TIME
```

</details>

**Comment by dhaavi** [comment]
Hey @SirRFI, thanks for reporting this.

What is happening is that the Portmaster checks if DNS queries end up at the Portmaster. If that is not the case - as with you - the Portmaster cannot properly protect you. This is a pretty serious integration error.
Are you sure you completely disabled DoH in Windows?

I will look into this more in the coming weeks.

**Comment by SirRFI** [comment]
> Are you sure you completely disabled DoH in Windows?
Unfortunately I am not, as I would need to know reliable way to tell whether that's actually in place or not. According to GUI, DNS server is automatic to 1.1.1.1 (as set in router and host OS), unencrypted.

During today's tests for the app-rules issue, this notification haven't showed up at all. It did, however, show up multiple times throughout the weekend, before reporting the issue. I am not aware if there was any Portmaster-related update today.

I tested Portmaster with default settings if that plays any role in this context.

**Comment by dhaavi** [comment]
Hey @SirRFI,

I actually installed Windows 11 freshly to see if I'd find something, but apart from absolutely needing a restart after install, everything seemed to work fine.

I also wanted to dig into the logs you sent via email, but somehow all files in the archive were empty (zero size) for some reason. Also, the non-error core log was missing completely. If you could send the logs again, that would be great! (Maybe use .zip for archiving)

Do you have any other software installed that could interfere with the Portmaster? Ie. any kind of firewall, antivirus or other DNS based security software?

**Comment by SirRFI** [comment]
I tested this again. Steps taken:
0. Setup new VM (VMware, bridged connection to physical local network) and installed customized Windows11 (debloated and tweaked, nothing that affects network aside from telemetry though), build 376 (newer than previously).
1. Reboot after first boot-in the system.
2. Install Portmaster and reboot, just like the installer requests.
3. Wait for Portmaster icon to appear in tray and open it with delay.
4. After a while (up to few minutes), compatibility error will appear.

Reopening Portmaster at this point will behave the same. Doing another reboot may already change behavior - since this point I had no consistent results. Sometimes I would get DNS warning, despite I checked the configuration before and after installing Portmaster, and every time it was Automatic DNS via DHCP - 1.1.1.1 (unencrypted). The other times it would just work fine.

![image](https://user-images.githubusercontent.com/32642697/147299316-7aca841c-4380-45d5-87b2-3ffb53d4cc6a.png)

Interestingly enough, reinstalling Portmaster does the compatibility error again.

---

> I also wanted to dig into the logs you sent via email, but somehow all files in the archive were empty (zero size) for some reason. 

Indeed. Weird, that's the first time such thing happened, lol. I even remember browsing them before packing up. I gathered new samples - check the mail again.

---

> Do you have any other software installed that could interfere with the Portmaster? Ie. any kind of firewall, antivirus or other DNS based security software?

Nope. Not even Windows defender. Windows Firewall probably in default settings.

---

<details>
<summary>Version 0.7.12</summary>

```
Portmaster
version 0.7.12

commit tags/v0.7.12-0-g466210b6134216054111af2f2bc0740a07e783b6
built with go1.15.8 (gc) windows/amd64
  using options main.go
  by user@docker
  on 16.12.2021

Licensed under the AGPLv3 license.
The source code is available here: https://github.com/safing/portmaster
```

</details>

<details>
<summary>Platform: Microsoft Windows 11 Pro 10.0.22000 Build 22000</summary>

```
System: Microsoft Windows 11 Pro windows (Standalone Workstation) 10.0.22000 Build 22000
Kernel: 10.0.22000 Build 22000 x86_64

```

</details>

<details>
<summary>Status: Trusted</summary>

```
ActiveSecurityLevel:   Trusted
SelectedSecurityLevel: Off
ThreatMitigationLevel: Trusted
CaptivePortal:         
OnlineStatus:          Online
```

</details>

<details>
<summary>Resolvers: 3/3</summary>

```
Cloudflare
  dot://1.1.1.2:853#config
  Failing: false

1.1.1.1
  dns://1.1.1.1:53#system
  Failing: false

1.1.1.1
  dns://1.1.1.1:53#system
  Failing: false
```

</details>

<details>
<summary>Compat Module Error</summary>

```
Message: self-check #2: dns integration check failed: did not receive test query after 3s
Timestamp: 2021-12-23 23:17:30.2298676 +0100 CET m=+167.219749001
ModuleName: compat
TaskName: selfcheck
TaskType: 
Severity: error
PanicValue: %!s(<nil>)
StackTrace:

goroutine 4185 [running]:
runtime/debug.Stack(0xc0014a2d80, 0xc00002cfa0, 0x50)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa5
github.com/safing/portbase/modules.(*Module).NewErrorMessage(0xc0001b1040, 0x174fd05, 0x9, 0x1850860, 0xc0014a2d80, 0x58)
	/home/user/git/safing/portbase/modules/error.go:48 +0x58
github.com/safing/portmaster/compat.(*systemIssue).notify(0x1cda6c0, 0x1850860, 0xc0014a2d80)
	/home/user/git/safing/portmaster/compat/notify.go:89 +0x1ac
github.com/safing/portmaster/compat.selfcheckTaskFunc(0x1862a60, 0xc000932d40, 0xc00047efc0, 0x0, 0x0)
	/home/user/git/safing/portmaster/compat/module.go:85 +0x16b
github.com/safing/portbase/modules.(*Task).executeWithLocking(0xc00047efc0)
	/home/user/git/safing/portbase/modules/tasks.go:369 +0x94
created by github.com/safing/portbase/modules.(*Task).runWithLocking
	/home/user/git/safing/portbase/modules/tasks.go:318 +0x285


```

</details>

<details>
<summary>Unexpected Logs</summary>

```
211223 23:14:50.992 sts/lookup:019 > WARN 060 intel/filterlists: not searching for cache:intel/filterlists/lists/asn/8075 because filterlists not loaded
211223 23:14:50.992 sts/lookup:019 > WARN 062 intel/filterlists: not searching for cache:intel/filterlists/lists/ipv4/20.67.183.221 because filterlists not loaded
211223 23:14:50.992 sts/lookup:019 > WARN 064 intel/filterlists: not searching for cache:intel/filterlists/lists/country/IE because filterlists not loaded
211223 23:14:52.553 sts/lookup:019 > WARN 072 intel/filterlists: not searching for cache:intel/filterlists/lists/asn/8075 because filterlists not loaded
211223 23:14:52.553 sts/lookup:019 > WARN 074 intel/filterlists: not searching for cache:intel/filterlists/lists/ipv4/20.67.183.221 because filterlists not loaded
211223 23:14:52.553 sts/lookup:019 > WARN 076 intel/filterlists: not searching for cache:intel/filterlists/lists/country/IE because filterlists not loaded
211223 23:14:55.986 olver-mdns:094 > WARN 085 intel(mdns): failed to create udp6 listen multicast socket: listen udp6 [ff02::fb]:5353: setsockopt: not supported by windows
211223 23:14:57.143 pat/module:083 > ERRO 087 compat: self-check #2: dns integration check failed: did not receive test query after 3s
211223 23:16:00.164 pat/module:083 > ERRO 102 compat: self-check #2: dns integration check failed: did not receive test query after 3s
211223 23:17:03.189 pat/module:083 > ERRO 155 compat: self-check #2: dns integration check failed: did not receive test query after 3s
211223 23:17:30.229 CURRENT TIME
```

</details>

**Comment by Broeckelmann** [comment]
Had this too, until a couple of weeks ago. 
In my case it somehow had a problem with docker.

For me it worked after just unistalling docker, portmaster with Bulk Crap Uninstaller.
And then reinstall portmaster, restart, install docker and set them up then.
Worked fine afterwards.

**Comment by Broeckelmann** [comment]
And I have the same thing with DNS being reported as unencrypted by Windows11.

**Comment by dhaavi** [comment]
Hey @Broeckelmann, thanks for your input here.

That is really interesting that reinstalling both Docker and Portmaster resolved the problem. Maybe something is different with the network setup after an upgrade vs. reinstall.

Windows 11 should report that DNS is unencrypted, as it does not know what the Portmaster is and what it does.
So that is expected.

---

@SirRFI, I had a look at the logs, and I couldn't find what is causing this.

There is one log file, `logs-3/core/2021-12-23-22-28-30.log`, which shows that everything works:
```
211223 23:39:44.798 /selfcheck:071 > TRAC 489 compat: self-check #1: system integration check passed
211223 23:39:44.800 /selfcheck:145 > TRAC 490 compat: self-check #2: dns integration query check passed
211223 23:39:44.800 nameserver:313 > INFO 491 nameserver: returning accepted response (NOERROR) for ae683570113e7ade09955e230edbd4d75b.self-check.portmaster.home.arpa.A to NT AUTHORITY\NETWORK SERVICE:C:\Windows\System32\svchost.exe:1624 Σ=0s
                 0s nameserver:085 > TRAC     nameserver: handling new request for ae683570113e7ade09955e230edbd4d75b.self-check.portmaster.home.arpa.A from 192.168.0.210:62141
                 0s ocess/find:026 > TRAC     process: getting pid from system network state
                 0s ss/process:117 > TRAC     process: getting process for PID 1624
                 0s ss/profile:027 > TRAC     process: profile already loaded
                 0s tel/entity:320 > TRAC     intel: loading domain list for ae683570113e7ade09955e230edbd4d75b.self-check.portmaster.home.arpa.
                 0s all/master:445 > TRAC     filter: LMS score of eTLD+1 home.arpa is 100.00
                 0s er/resolve:128 > TRAC     resolver: resolving ae683570113e7ade09955e230edbd4d75b.self-check.portmaster.home.arpa.A
                 0s er/resolve:347 > TRAC     resolver: sending query for ae683570113e7ade09955e230edbd4d75b.self-check.portmaster.home.arpa.A to env
                 0s nameserver:282 > TRAC     nameserver: deciding on resolved dns
211223 23:39:44.800 /selfcheck:165 > TRAC 492 compat: self-check #3: dns integration response check passed
```

But the other logs just report:
```
211223 23:20:29.893 /selfcheck:071 > TRAC 250 compat: self-check #1: system integration check passed
211223 23:20:32.894 pat/module:083 > ERRO 251 compat: self-check #2: dns integration check failed: did not receive test query after 3s
```

Looking at this part with a bit more context, we see that the Portmaster in fact did not receive a query:
```
211223 23:20:29.893 terception:540 > TRAC 249 filter: packets accepted 65, blocked 0, dropped 5, failed 0
211223 23:20:29.893 /selfcheck:071 > TRAC 250 compat: self-check #1: system integration check passed
211223 23:20:32.894 pat/module:083 > ERRO 251 compat: self-check #2: dns integration check failed: did not receive test query after 3s
211223 23:20:38.342 connection:631 > INFO 253 filter: connection Unknown::-1 <- 192.168.0.1 dropped: incoming connection blocked by default Σ=0s
                 0s terception:108 > TRAC     filter: handling packet: IN UDP 192.168.0.255:20002 <-> 192.168.0.1:60803
                 0s ocess/find:026 > TRAC     process: getting pid from system network state
                 0s ocess/find:030 > TRAC     process: failed to find PID of connection: could not find connection in system state tables
                 0s connection:322 > DEBU     network: failed to find process of packet IN UDP 192.168.0.255:20002 <-> 192.168.0.1:60803: could not find connection in system state tables
                 0s terception:157 > TRAC     filter: created new connection 17-192.168.0.255-20002-192.168.0.1-60803
                 0s terception:332 > TRAC     filter: handing over to connection-based handler
                 0s terception:366 > TRAC     filter: starting decision process
211223 23:20:39.893 terception:540 > TRAC 254 filter: packets accepted 0, blocked 0, dropped 1, failed 0
```
Line 254 shows that only 1 packet has been dropped since line 249, which is unrelated to our issue.

Do you have any idea what was different between these two launches?

**Comment by SirRFI** [comment]
> Do you have any idea what was different between these two launches?
No. As stated in steps taken, I didn't do anything else.

**Comment by dhaavi** [comment]
I happened to have a VM with Windows 11 open today.
While I did get a notification about compatibility at first, it went away after a couple more minutes.
This was with v0.8.1 - which is now on the [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel).

If there never was any other software installed on the VM, I don't know what else it could be - other than some customization of Windows that you mentioned.

**Comment by SirRFI** [comment]
These weren't modifications, just removed bunch of bundled optional apps and tweaked some privacy and preference settings. Does Portmaster depend on any optional software, that is preinstalled with Windows? Like some services or System/Windows "apps" (like those seen `Get-AppxPackage | select Name, PackageFullname` in PowerShell)? Also it's been a while since the report, so maybe other things played the role.

I'll retest this when new Windows ISO is released, so it might take a while - keep the `waiting for input` tag for now.

**Comment by dhaavi** [comment]
We don't know exactly which dependencies within the Windows structure the Portmaster has, as we are using standard Windows APIs, which have unknown internal dependencies.
We've had multiple cases where disabling things in Windows lead to unexpected breaking.

> keep the `waiting for input` tag for now.

Will do. This will close the issue after a month, but just reopen it if that happens.

**Comment by SirRFI** [comment]
New test:

Windows 11 Pro - 22000.**556** build
Portmaster v 0.8.4
VM and host OS setup same as before

MSDN stock ISO: ✔️ 
MSDN customized ISO: ❔  (to be tested)
UUP dump stock ISO: ✔️ 
UUP dump customized ISO: ✔️ 

`Detected Compatibility Issue` did not appear a single time.
`Detected System DNS Client Bypass Attempt` appeared every time after some time (15 mins or so), with DNS 1.1.1.1 "unencrypted" as shown previously.

**Comment by dhaavi** [comment]
Thanks for the extensive testing!

My conclusion from this is that Windows will just try to do the encryption and then fall back to unencrypted - which is then displayed in the settings.

The solution would be to shut up about the attempt to do secure DNS and only show a warning if Windows does not stop trying - ie. when secure DNS is forced.
When the Portmaster successfully prevents the attempt and Windows falls back to plain DNS for the Portmaster, then everything is OK anyway.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
