### ISSUE TITLE
Better DNS features

### ISSUE THREAD

**Issue by 32bitx64bit** [safing/portmaster#472]
**What would you like to add or change?**:
A few things should be added
A console (To see DNS quires live)
DNSCrypt protocol support

**Why do you and others need this?**:
A console would be a very handy addition  to see whats going on live
DNSCrypt a encryption protocol that would be nice to have the option to use

**Comment by dhaavi** [comment]
Hey @32bitx64bit, thanks for the suggestions!

> console (To see DNS quires live)

I'm not sure what exactly you mean here. Can you elaborate?
What exactly do you wish to see there?

You can see all the queries and connections in the Network Monitor, with some special cases:
- If there is a follow up connection to a DNS query, it is "merged" into the connection and not displayed separately.
- Currently, queries do not show up in the Monitor if the response was served from cache. This is to reduce noise.
- In case your system resolver is active, DNS queries without connections will end up there.

> DNSCrypt protocol support

Can you explain which benefit you see here in comparison to DoT (or DoH)?
From our research, DNSCrypt has a lot less support and is more difficult handle, and also not as secure or private.

> Another thing that would be nice is randomized DNS (Basically picks a random DNS server every query

Can you elaborate on the benefit you see here in comparison to DoT (or DoH)?

**Comment by 32bitx64bit** [comment]
DNSCrypt would just be a nice addition nothing really special over DOT / DOH 

And about the console part i would be nice to have a built in one just plan in text in a console tab 
(Like yogaDNS a DNS client)

**Comment by 32bitx64bit** [comment]
Oh yea and sorry for the late responds i'm not on github much

**Comment by 32bitx64bit** [comment]
Oh and you seem to have not understanded me when i said
'Another thing that would be nice is randomized DNS (Basically picks a random DNS server every query'
Its not a protocol it would be a opinion that would pick a random DNS server thats on your DNS server list that you would have setup
The benefit of this would be enhanced privacy as not 1 provider would have all your DNS traffic 

Hope this allows you to understand better :D

**Comment by dhaavi** [comment]
> DNSCrypt would just be a nice addition nothing really special over DOT / DOH

Ok. From what I remember from our research, not many providers support DNSCrypt, so I'm not sure it would be that helpful.

> And about the console part i would be nice to have a built in one just plan in text in a console tab (Like yogaDNS a DNS client)

We'd also like to do a CLI client some time in the future. But nothing concrete is planned yet so far.

> Oh yea and sorry for the late responds i'm not on github much

No problem. Take the time you need.

> randomized DNS (Basically picks a random DNS server every query

I see. This is an interesting idea. I will keep it in mind for the future.

Thanks for your ideas!

**Comment by 32bitx64bit** [comment]
Anytime!

Hope these will be added sooner or later.
