### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by boistordu** [safing/portmaster#473]
I wanted to congratulate you guys. This is a really nice update 👍 you did there. It resolved a lot of bugs, icon in taskbar in xfce resolved and the behavior of the app is way better it seems with qemu (even if I know it's not supported yet)

**Comment by dhaavi** [comment]
Hey @boistordu, thanks - great to hear that this update had a positive impact on your issues!

> icon in taskbar in xfce resolved

Can't take credit for that one though. We did not change anything in that regard. 🤷
