### ISSUE TITLE
Resolving DNS does not work after shutting down Portmaster on Windows 10.

### ISSUE THREAD

**Issue by xenon2** [safing/portmaster#488]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

Windows 10 / 2004 (19041.1415)

If I disable portmaster using tray icon "shut down portmaster"  DNS queries does not work.

**What did you expect to happen?**:

I expected that normal DNS queries to my router will be performed

**How did you reproduce it?**:

Try multiple times star/stop of the service it happens randomly.

**Debug Information**:

**Comment by dhaavi** [comment]
Hey @xenon2, thanks for raising this issue.

What could be happening is that the Portmaster has an issue shutting down and takes a bit longer than expected. It abort the shutdown after about 2 minutes and forcibly shuts down.
