### ISSUE TITLE
memory usage spiked up to 99%

### ISSUE THREAD

**Issue by n00d13p00d13** [safing/portmaster#493]
### What happened?
i started downloading a torrent file through BitComet and then portmaster core instantly spiked to 3.3gbs of ram (i use 8gbs of ram)

### Additional information

**Debug-Info**: https://support.safing.io/privatebin/?3fae4a4cb896dfe2#GD56J8NWB2riSZbAebddY7TmcTaPfVZYEjyJZM4nntnv

**Comment by dhaavi** [comment]
Hey @n00d13p00d13, thanks for raising this issue with us!

Does this happen also when downloading a file from a website, or just with torrents?

If this happens again, can you go to BitComet within the Portmaster App and press "Copy Debug Info" there and paste it here. This will give us some information on the connections themselves. Redact (but not silently remove) anything sensitive please.
