### ISSUE TITLE
[Suggestion] Add DL/UL limit

### ISSUE THREAD

**Issue by PaulIRL** [safing/portmaster#494]
**What would you like to add or change?**:
The ability to limit download and upload speed per process
**Why do you and others need this?**:
So people with bad internet could do multiple things at the same time without network speed being so much of a bottleck

**Comment by Beefy32659** [comment]
I really want this feature, it is one thing which is restricting my use of PortMaster and I don't want to pay for 'NetLimiter' considering their EULA (End User License Agreement) is poorly worded and its payment systems provider website link doesn't work so I'm not convinced. Adding this feature soon to PortMaster will make 'NetLimiter' surplus to requirement and be a feature I need to confidently recommend PortMaster to others. Please add this asap! Pls Pls Pls!

**Comment by dhaavi** [comment]
Hey @PaulIRL and @Beefy32659, thanks for the suggestion.

We already have this tracked at https://github.com/safing/portmaster/issues/382 - please chime in there and give your support for it!
