### ISSUE TITLE
wayland support, either pass electron flags or add a `--use-wayland` flag to app args

### ISSUE THREAD

**Issue by skewballfox** [safing/portmaster#495]
normally you can run any v12+ electron app by appending the flags `--enable-features=UseOzonePlatform --ozone-platform=wayland` to whatever command is launching the app. often these aren't really handled by the application itself but passed directly to electron (vscode actually complains at startup that these options aren't recognized)

it seems that `portmaster-start app`  isn't launching directly as an electron app, because adding these flags cause the command to fail. If you would rather avoid just passing random flags to the underlying engine, you could add a `--use-wayland` flag to append these specific arguments to the process that is starting electron

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

launching the app via `/opt/safing/portmaster/portmaster-start app --data=/opt/safing/portmaster`

**What did not work?**

launching the app via `/opt/safing/portmaster/portmaster-start app --data=/opt/safing/portmaster --enable-features=UseOzonePlatform --ozone-platform=wayland`

**Debug Information**:

portmaster version: 0.7

**Comment by ppacher** [comment]
hi @skewballfox, thanks for the report!

You should be able to pass any options/arguments to electron by using a `--` delimiter. After that separator all remaining arguments should be passed to electron. 

Like:

```
portmaster-start app --data=/path/to/data -- arg1ForElectron arg2ForElectron 
```

So maybe try the following:

```
/opt/safing/portmaster/portmaster-start app --data=/opt/safing/portmaster -- --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Comment by skewballfox** [comment]
thank you, tested it out last night, opens in a native wayland window as expected.
