### ISSUE TITLE
Select the exit node according to the application.

### ISSUE THREAD

**Issue by febreze21** [safing/portmaster#497]
**What would you like to add or change?**:

Add the possibility to select the exit node according to the application. 

**Why do you and others need this?**:

To connect to zoom to follow my needs, I need to be in the same country as the participants (in France).

With SPN ON i'm most of the time in United States, so Zoom block me and i can't join the zoom meeting, ( i need to be in France)...

Tanks you for Portmaster, an awesome product !

I don't know when you plan to translate Portmaster but I offer to help with the French translation, if needed.

**Comment by dhaavi** [comment]
Hey @febreze21, thanks for the suggestion!

We are already working on it!
Also, thanks for the encouragement!

Currently we are still getting the most important features out and stabilizing everything. When that is done, we will start looking at things like translation.
Thank you for your kind offer, I will pass it along.

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.
