### ISSUE TITLE
[Win11] Portmaster Core Service Won't Start - Windows privacy scripts were applied

### ISSUE THREAD

**Issue by realdep** [safing/portmaster#498]
**Pre-Submit Checklist**:

Known issues checked, Found something similar but it did not work.
#336

**What happened**:
Portmasted UI launches, prompts me to start the core service, I press the button, a terminal launches for a second but the core service does not start.

I tried to manually launch the Portmaster Core service from Windows Services but I get a **"Error 1053: Service did not respond to the start or control request in a timely fashion."**

![image](https://user-images.githubusercontent.com/9782679/150362262-d1403a66-0426-4119-94f7-6290b2bdd23a.png)

**What did you expect to happen?**:
To function normally.

**How did you reproduce it?**:
I launched it.

**Debug Information**:
[logs.zip](https://github.com/safing/portmaster/files/7906168/logs.zip)

**Comment by dhaavi** [comment]
Hey @realdep, thanks for raising this issue.

I am not sure why the Core Service wasn't running in the first place.

Did you just install the Portmaster?
If so, did you reboot?
Rebooting after install has become an absolute requirement with Windows 11.

The logs you attached don't even contain logs for the Core Service, hinting that it never ran.

What I did find in the logs, is that a Windows RPC service is unavailable (`The RPC server is unavailable.`) - are you running a modified version of Windows, or have you disabled any Windows services?

**Comment by realdep** [comment]
I did reboot portmaster right after install.

Windows RPC server appears to be running when I check the services, however I have debloated my Windows using [privacy.sexy](https://privacy.sexy/).

[privacy-script.zip](https://github.com/safing/portmaster/files/7950626/privacy-script.zip)
This is the latest script I used.

**Comment by dhaavi** [comment]
I remember one issue where the Portmaster took one minute to start because it wasn't able to get random data from windows because something was changed with a privacy script. This might be the same here.

Can wait for 5 minutes and see if the Portmaster Core Service comes online eventually?

I've looked through the script and could not find anything obvious.
Can you easily revert these settings again in order to check if that is what is problem? If so, we can start digging into into that direction.

**Comment by realdep** [comment]
I reverted whatever I could and waited 5+ minutes but the issue still persists.

**Comment by dhaavi** [comment]
Is it possible you install Windows 11 in a VM and try the Portmaster with a fresh install there, and step by step apply the privacy script to see what breaks it?

**Comment by realdep** [comment]
Sorry for not answering, So I noticed that my windows updates and some other windows components were broken as well, so I factory reseted my windows install with keep files and eveything including portmasted works now.

**Comment by dhaavi** [comment]
Great! Thanks for reporting back!

**Comment by aaronsvk** [comment]
In my case the problem was caused by the "Windows Event Log" service not being started. I found a reason by manually running service from command line:
```
C:\ProgramData\Safing\Portmaster>C:\ProgramData\Safing\Portmaster\portmaster-start.exe core-service --data C:\ProgramData\Safing\Portmaster --input-signals

C:\ProgramData\Safing\Portmaster>[control] 2022/07/01 07:37:55 WARNING: portmaster-start is marked as a GUI application in order to get rid of the console window.
[control] 2022/07/01 07:37:55 WARNING: CTRL-C will immediately kill without clean shutdown.
[control] 2022/07/01 07:37:55 WARNING: running interactively, switching to debug execution (no real service).
Error: failed to open eventlog: The RPC server is unavailable.

C:\ProgramData\Safing\Portmaster>
```
Is it necessary for portmaster to use Windows Event Logs?

**Comment by dhaavi** [comment]
Hey @aaronsvk, thanks a lot for digging into this. We are actually currently handling a current issue around this in #673.

I will look into this and check if we can make Windows Event Logs optional.

Is there a particular reason you have turned off Windows Event Logs?

**Comment by aaronsvk** [comment]
To minimize windows telemetry and increase performance, I disabled/removed as many Windows features as possible including Windows Event Log. It would be nice if we could use Portmaster also on such hardened systems, but I understand that there are much more important issues.

Btw, thank you for this great tool !
