### ISSUE TITLE
can not install the portmaster on my windows 10

### ISSUE THREAD

**Issue by dnv-max** [safing/portmaster#506]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
Hey @dnv-max, thanks for raising this issue.

In order to know what is going on, we will need more information.

Can you describe how the installation went?
At point did you notice the installation failed?
Were there any error messages?
