### ISSUE TITLE
Control if specific domains for an application are routed via spn

### ISSUE THREAD

**Issue by jmhbnz** [safing/portmaster#508]
**What would you like to add or change?**:

I'm unsure if this is technically feasible but am hoping to have granularity in Portmaster that would allow me to control if specific domains accessed by an application are routed through SPN or not. I can find configuration options to enable SPN for the entire firefox browser but not to go any further than that?

**Why do you and others need this?**:

There are some services I self host. The domain names for these services I trust and want to be able to exclude from SPN for performance reasons.

Currently the only method I have found is to run two different browser applications, one configured to go through SPN and one not which seems heavy.

**Comment by dhaavi** [comment]
Hey @jmhbnz, thanks for the great suggestion!

We actually started writing a specification for this this very week.
In this process we are currently investigating and evaluating multiple options.
From what we have now, it seems that we will able to provide such a feature in the near future.

I understand that running multiple browsers seems heavy, but especially with Firefox I think it's quite ok.
After all, this is just a temporary workaround anyway.

**Comment by dhaavi** [comment]
Update:
We've looked into it and it seems that we'll need upgrade our rule engine to do this properly.
We'll definitely have this in the future, just not sure how fast we'll get this done.

On the bright side, this means that we'll provide per-app control even sooner.

**Comment by northys** [comment]
I would like to say that this is critical feature for me. It's not only about crypto/stock exchanges but also local TV services also uses IP location to allow users. To watch TV I must turn of SPN and later I forget to turn it on so most of the time my SPN is turned off and you are missing my (hopefully valuable) feedback from testing.

I would love to have SPN turned on all the time so I can appreciate it's privacy features it gives me even in alpha state, but I understand that it requires bigger refactoring or something. I don't know what is your roadmap so I just wanted to "vote" for this feature :)

**Comment by dhaavi** [comment]
:shushing_face: :eyes: 

![image](https://user-images.githubusercontent.com/18184155/154564077-20d432c2-20e5-471c-9490-74d56ebf45b4.png)

(Will take another 1-2 weeks until Beta Channel)

**Comment by dhaavi** [comment]
With Portmaster v0.8.5 - which is now out on the [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel) - you can now use the [SPN Rules](https://docs.safing.io/portmaster/settings#spn/usagePolicy) to decide which websites should go through the SPN and which should not.

At this point I want to point out that websites are often hosted on multiple domains, because they draw resources from multiple places. Please be aware of that when creating rules.

**Comment by northys** [comment]
@dhaavi good job!!! i tried it with czech tv service and it works. webpage is loaded through SPN while CDN is accessed directly and I no longer get "you cannot watch this tv show in this country".
![Screenshot from 2022-03-02 16-09-04](https://user-images.githubusercontent.com/2878126/156389358-f9a31f32-a255-42b5-9cb4-694558319a19.png)

**Comment by jmhbnz** [comment]
@dhaavi I've switched to beta channel and can confirm this is doing exactly what I was wanting!  Thanks heaps for adding this feature, I can now have my trusted self hosted services remaining local for maximum performance while all other sites route via SPN, all within one browser 💯
