### ISSUE TITLE
Restart services / run commands after portmaster startup

### ISSUE THREAD

**Issue by northys** [safing/portmaster#513]
**What would you like to add or change?**:

I used to have perfectly working wg and portmaster together using many lines in portmaster unit before I switched to official fedora package. Now I cannot make this work again by using systemd unit overides.

It would be awesome if user could provide a list of services which should be restarted on startup and also disabled when SPN turns on.

Maybe it could be a list of commands?

For me it woulf be `systemctl restart wg-quick@wg0.service` and others could set `myshinyvpnservice reconnect`.

I think that portmaster runs under root user so it should be able to do stuff like this without any troubles regarding the permissions.

**Why do you and others need this?**:

I think this could fix many issues people have with VPN while using portmaster. Maybe this is only wireguard related I dont know but I suppose that both random vpn clients and portmaster writes something to iptables which collides / have different priority.

Maybe we could just figure out what should I set to systemd unit overides to let systemd take care of it but it wasnt 100% anyway. But I think if portmaster could take care of it after it properly starts it maybe would be 100%.

**Comment by dhaavi** [comment]
You actually can just edit the systemd file. It is only written by the installer, not by the Portmaster itself.

**Comment by northys** [comment]
@dhaavi I don't like to edit the systemd unit ditectly. That's what are overrides for. I'll try to study how to get it working using overrides. Portmaster is not the only service that I would like to change to my needs but I'm posponing it as much as I can :D

I'm leaving the issue opened until I figure out how to do it. Later it could be included in doc to help others.

**Comment by dhaavi** [comment]
Ok, I'll also assign @ppacher here, he might have an idea how to best do this.

**Comment by ppacher** [comment]
Hi @northys ,

sorry for not replying earlier, I've overseen this issue.

I have a similar issue with dnsmasq and docker which I solved by using a `ExecStartPost` overwrite for docker. In my case I needed dnsmasq to be restarted once docker came up so dnsmasq can and will handle the bridge network `docker0`. I created `/etc/systemd/system/docker.service.d/90-restart-dnsmasq.conf` with the following content:

```ini
[Service]
# Try to reload or restart the dnsmasq.service if it's enabled.
# This is required as dnsmasq might otherwise not respond to queries
# on the docker bridge which breaks DNS service discovery using consul.
ExecStartPost=/usr/bin/env sh -c "! systemctl --quiet is-enabled dnsmasq.service || ( echo 'Restarting dnsmasq due to docker start' ; systemctl try-restart dnsmasq.service )"
```
I guess this approach can be tweaked for your use-case as well.

ExecStartPost can be specified multiple times so you can add a file for every service you want to restart after the portmaster came up.

**Comment by northys** [comment]
Hi @ppacher, it works like a charm. Thank you!

Should I write something about it to documentation or should I just close this issue since it is solved for me?

**Comment by dhaavi** [comment]
I guess adding a section for this would be nice to have in the docs.
I'll add the "docs pending" tag for this. Otherwise, we can close this.

**Comment by northys** [comment]
@davegson pls lemme know where would you put it (link to md) and I'll try to drop a few lines. I think there is some page about compatibility but maybe you know a better place.
