### ISSUE TITLE
Portmaster Fails to Download Assets During Installation

### ISSUE THREAD

**Issue by thrillho93** [safing/portmaster#519]
Checklist: 

- [x] I've checked the Windows Known Issues document
- [x] I tried the latest release from [your site](https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe)
- [x] I'm running the latest Windows 11 build
- [x] My machine is currently connected to the Internet
- [x] I'm using Windows Defender 

**What happened**:

Portmaster fails to install on my machine. This seems similar to [this issue that was closed out](https://github.com/safing/portmaster/issues/196)

**What did you expect to happen?**:

I should be able to download the assets without issue

**How did you reproduce it?**:

I can successfully reproduce just by trying to install Portmaster

**Debug Information**:

Nothing's being written to the logs directory, and I'm unable to access the UI (because the installation fails).

**Comment by dhaavi** [comment]
Hey @thrillho93, thanks for reporting this!

Can you check if downloading the assets works manually?
`portmaster-start.exe update --data=C:\ProgramData\Safing\Portmaster`

You can get portmaster-start.exe from here: https://updates.safing.io/latest/windows_amd64/start/portmaster-start.exe

**Comment by thrillho93** [comment]
@dhaavi Yes, that seemed to resolve the issue. I did need to create the `C:\ProgramData\Safing\Portmaster` directory manually.

**Comment by dhaavi** [comment]
Great!

Ok, I will need to look into why that directory was not created - I really think it should have been.

I'll leave the issues open as a reminder for me.

**Comment by NZ510** [comment]
I'm having the same issue. Also Windows 11.
But for me the installer creates the Portmaster folder in the ProgramData Directory with the "postmaster-start.exe". But still the installer fails to download the assests. Even if I try to replace the .exe with yours.

**Comment by Zeik0s** [comment]
Same issue for me. But in my case, @dhaavi suggested solution fails with 

>[control] 2022/03/02 22:25:44 WARNING: portmaster-start is marked as a GUI application in order to get rid of the console window.
[control] 2022/03/02 22:25:44 WARNING: CTRL-C will immediately kill without clean shutdown.
220302 23:25:44.087 > BOF
220302 23:25:44.456 < EOF
Error: failed to unpack resources: 1 error occurred:
        * EOF

But the zip in C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app was successfully downloaded (~82 Mb) and i don't see any other file that was empty or somehow containing EOF. Besides tested it with my main fiber data line and a cellular network to check if the network is the problem during download.

**Comment by VottonDev** [comment]
Same issue here on Windows 11 specific. The portmaster-start not making a difference.

**Comment by dhaavi** [comment]
Thanks all of you for chiming in here.

We have discovered and fixed a bug related to the installer.
I've reverted the current version back to the previous installer until we get the fix out.

Please try to download and run the installer again.

**Comment by dhaavi** [comment]
Also, I think the comments from the last 24 hours are unrelated to the issue handled before, so we are looking at two different things here.

**Comment by Zeik0s** [comment]
still not working for me. Should i create a different issue for the EOF error?

**Comment by dhaavi** [comment]
If it turns out that the previous version does not work either, then, yes, please create a new issue.

As this was a manual rollback, it did not correctly update all references, please try again.

**Comment by VottonDev** [comment]
The latest installer fixed the asset issue for me.

**Comment by NZ510** [comment]
Yeah, for me the issue is fixed. Thanks :)

**Comment by Zeik0s** [comment]
Interesting, same for me. As if i still downloaded the "old" installer a few hours ago. Will close #558.
