### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Roki100** [safing/portmaster#522]
Hello, does portmaster modify windows network interface dns servers? Because i want to try it but i dont really want it to mess up dns server settings on my 30 interfaces on which i use e.g. pihole

**Comment by dhaavi** [comment]
Hey @Roki100,

No, the Portmaster does not make any changes to Windows other than loading a kernel module, which is unloaded when the Portmaster stops.
So there should not be any changes made to Windows at all - except for installing the software to a directory and setting some registry keys for the install.

Regarding DNS, the Portmaster then redirects queries to itself "on the wire".

**Comment by Roki100** [comment]
So when its disabled it leaves completely no trace on the system? sounds good 👍, Thanks!
