### ISSUE TITLE
When SPN subscription is not active the portmaster breaks after enabling SPN until you logout from SPN account

### ISSUE THREAD

**Issue by northys** [safing/portmaster#523]
**What happened**:

I connected to SPN but since I no longer have the first month free alpha subscription active it failed to connect and it showed status message that I'm not subscribed. Since this happened I couldn't open new websites but I could visit websites I've visited recently. I tried to dig the new websites (account.safing.io for first try) and got the A response with IP immediately with no error. I also could ssh to my home server through wireguard VPN (which I access using private IP in public DNS records and I resolved it recently). I couldn't ping anything though.

Tried to restart portmaster in the UI, didn't help. Stopping portmaster using `systemctl stop portmaster.service` fixed the issue. Starting the portmaster using `systemctl start portmaster.service` breaks it again. The SPN is turned off though. I haven't tried to reboot my laptop yet.

---

I've found the solution - logout from SPN safing account fixes the issue immediately. SPN stayed in failed state even after restart so it probably broke the networking on purpose because of the `insecure state`.

![Screenshot from 2022-02-09 15-16-18](https://user-images.githubusercontent.com/2878126/153220357-79e7a1ec-d186-4f5b-881a-00bd1cc62244.png)

**What did you expect to happen?**:

Everything works like before I tried to connect to SPN.

**How did you reproduce it?**:

Connect to SPN with account which is not subscribed to SPN.

**Debug Information**:

I've forgotten to copy it as usually but I suppose it can be replicated without issue and **maybe this is even the expected / desired behavior.**

**Comment by dhaavi** [comment]
This is interesting. To be sure I understood correctly, I'll try to summarize the observed behavior:
- SPN Subcription Inactive + SPN On = No Internet
  - This is expected, as the SPN is on - so it's either through the SPN, or nowhere.
  - Some stuff still worked:
    - DNS is cached.
    - You may have exlcuded SSH from the SPN.
    - If there are still live connections through the SPN, these may be still be usable
- 
- Restart + SPN Off = No Internet
  - This would be a bug. Are you sure the SPN was off?
  - If the SPN goes to a failed state after restart, then it has to be turned on, as this code is only executed if the SPN is turned on.
  - SPN showing a failure means it is on and trying to connect.

On thing that is weird also, is that it took over a week for the Portmaster to check your account status.

**Comment by northys** [comment]
> If there are still live connections through the SPN, these may be still be usable

At the beginning the SPN was turned off. I havent used it for a while since it is slow when not going though my favorite node in Germany. I wanted to connect and vote multiple times on a comment on some website to get more upvotes from different IPs :D

> On thing that is weird also, is that it took over a week for the Portmaster to check your account status.

I noticed my subscription expired on 2022-01-01 IIRC. I've sent you some e-mail on 2022-01-03 though. This probably confirms that it took some time before portmaster checked the account status.

> If the SPN goes to a failed state after restart, then it has to be turned on, as this code is only executed if the SPN is turned on.

IIRC I clicked on the toggle multiple times and since it looks off (failed) on posted screenshot I would expect that toggling it would just turn it on again.

**Comment by northys** [comment]
I can probably create new account and test it without subscription but today is lazy day :D

**Comment by northys** [comment]
Here I've posted screenshot from 2022-01-14 where I'm connected to SPN but it is weird because its freshly installed VM im which I logged in that day. So probably my account was still subscribed on 2022-01-14? I think that when I activated the current subscription it showed that it expired on 2022-01-01 but I'm not 100% sure https://github.com/safing/spn/issues/37#issuecomment-1013183906
