### ISSUE TITLE
Detected Compatibility Issue bug

### ISSUE THREAD

**Issue by Kyoya-Yaku** [safing/portmaster#526]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**: 
I switched the Secure DNS to use NextDNS and after a couple of mins, i noticed I was being given this error for Detected Compatibility Issue i have no VPN or antivirus that could cause this besides nextdns application. thinking that was the problem and restarted my computer, the issue persisted after the restart. i switched the secure DNS to another default service that was an option and that too brought up the compatibility issue again. Reverted to system default and that fixed the issue but only for a few mins just like before. 
![image](https://user-images.githubusercontent.com/72183199/153502428-ed495e60-975e-48a1-b8e5-c0dc4b110389.png)

**What did you expect to happen?**:
No error and for the issue to be settled 

**How did you reproduce it?**:
successfully switched the DNS server to nextdns and then after a handful of mins the issue appeared. Nothing was done within this time, the issue just accrued after switching the DNS server.

**Debug Information**:

https://support.safing.io/privatebin/?5b2cd2299722c661#AWmSSriGPdt18wxJ2F313sVmpFWBZARLZ9QBVmh6rayr

EDITED by Safing:
Debug Info about to expire, most important info:

- Version 0.7.18
- Microsoft Windows 10 Home windows (Standalone Workstation) 10.0.19043 Build 19043
- self-check # 3: dns integration check failed: did not receive test response after 3s
- Everything else seems normal

**Comment by dhaavi** [comment]
Hey @Kyoya-Yaku, thanks for reporting this!

Do you have the NextDNS Application installed?
If so, have you tried stopping NextDNS to see if it was interfering?

Please note that it always takes a couple minutes until the Portmaster will show the error, as it wants to be absolutely sure there is really a persistent problem and so checks a couple times.

**Comment by Kyoya-Yaku** [comment]
no its uninstalled, but this still lingers around on my PC although it is disabled so im pretty sure its harmless 
![image](https://user-images.githubusercontent.com/72183199/153558701-ea18f6e5-8b38-4451-92ff-f631eae5c989.png)

**Comment by KCodin** [comment]
I have the same issue of Comparability issue and have no anti-virus or vpn.I thought it was simple wall,but checking the compatible apps it was supported of them.I uninstalled it and restarted the computer, but the error was still there.

But when i restart Portmaster with the error, it goes away and works well.I installed simple wall again and gave Portmaster full internet access and works well sometimes.

Love your software.Other than this there is no other issue.<3

**Comment by dhaavi** [comment]
Thanks for your input on this @KCodin.
It could, in fact, be that the order of loading other applications could be problem here.

@Kyoya-Yaku Can you try to restart Portmaster (not your system) and see if that solves it?

**Comment by Kyoya-Yaku** [comment]
yeah I've restarted it before the issue goes away for a couple of mins and then immediately goes back to giving me the compatibility warning

**Comment by Kyoya-Yaku** [comment]
tried it didn't do anything for the first few mins and then restarted portmaster was fine for a few mins longer but then reverted back to the compatibility issue.

**Comment by dhaavi** [comment]
Hm. This is really weird.

Can you try rebooting into safe mode and launch the Portmaster there (if possible)?
Maybe we can get Windows to load less stuff and see if that works.

**Comment by Kyoya-Yaku** [comment]
sorry to say portmaster did not want to work in safe mode. safe mode and safe mode with networking did launch the program but portmaster needed the core service and that would not launch and clicking boot services would just make it freeze after a couple of clicks. i did try looking to see if I could launch the core service manually since portmaster couldn't and all i got when trying to do so was this when doing so and quickly disappear after 
![image](https://user-images.githubusercontent.com/72183199/154146032-bc4cf425-497c-4177-99b8-07b6d0856bf1.png)
also just to be sure this is the core service it tries to launch right? 
![image](https://user-images.githubusercontent.com/72183199/154146356-0a3a9737-4cc5-4e64-8a68-4ebf02f954ac.png)
there was another one of the same name but with 18 instead of 21 in the name and resulted in the same error I posted earlier.

**Comment by dhaavi** [comment]
> portmaster did not want to work in safe mode

Ok, it could be that Windows stopped the Portmaster from loading its kernel driver.

> just to be sure this is the core service it tries to launch right?

Yes, this is it.

Ok, we'll have to dig deeper:
Please open a terminal with administrator rights and run this windows command - `netsh wfp show state` - and then upload the file it creates. It will contain all firewall like things registered in Windows that might interfere here.

@KCodin: What @Kyoya-Yaku is experiencing here is rather uncommon. Please open another issue with your own debug info so we can have a look. You can also do this from within the Portmaster from the Get Help page.

**Comment by Kyoya-Yaku** [comment]
[wfpstate.zip](https://github.com/safing/portmaster/files/8134826/wfpstate.zip)
Got it.

**Comment by Kyoya-Yaku** [comment]
nope not using it. haven't touched it in a year and everything for it has been disabled for a while now. ill uninstall it and check back if it fixes the issue

**Comment by Kyoya-Yaku** [comment]
issue still present ill put the wpfstate file again in case you need to see it again 
[wfpstate.zip](https://github.com/safing/portmaster/files/8143615/wfpstate.zip)

**Comment by dhaavi** [comment]
Perfect. One down, one to go:

I also found Private Internet Access registered in the Windows firewall:
```
Private Internet Access Firewall               Provider   Implements privacy filtering features of Private Internet Access.            {08de3850-a416-4c47-b3ad-657c5ef140fb}
Private Internet Access Firewall               SubLayer   Implements privacy filtering features of Private Internet Access.            {f31e288d-de5a-4522-9458-de14ebd0a3f8}
```

Let's see if removing that changes something.

**Comment by Kyoya-Yaku** [comment]
tried looking but didn't really see anything, not the greatest at looking for windows firewall but weirdly enough portmaster seems to be fine now 
![image](https://user-images.githubusercontent.com/72183199/156476645-1e534036-6b2c-44c3-9ada-dcad4469ed44.png)
don't know what happened but im not getting the notification anymore don't know when it started to maybe a couple days ago or the weekend?  ill send the wfp and debug logs so you can check 
[wfpstate.zip](https://github.com/safing/portmaster/files/8173996/wfpstate.zip)
https://support.safing.io/privatebin/?87bf4fcf2a89c5d8#C4fhuhzaCTS9KrEuvsUH7JJfqtTvhZjp7rKLHUn7W34T

**Comment by KCodin** [comment]
Mine seemed to have stopped giving the compatibility issue message too.Moreover,also started a few days ago.

**Comment by dhaavi** [comment]
Great to hear it now works for both of you. I'll check out the logs later.

**Comment by dhaavi** [comment]
wfpstate looks the same as before. Thanks again for taking the time to get to cause of this. The newest version has a cleaned up version of the wfpstate in the debug data so we can solve these problems a lot quicker in the future.
