### ISSUE TITLE
Remember Connection history filter selections

### ISSUE THREAD

**Issue by KCodin** [safing/portmaster#527]
Just a feature suggestion,having the remember filter option or default would be really nice on the connection history.If it is possible if not i will stop being lazy,thanks.Love your software.Keep up the good work.

Edit:i don't know how to put a suggestion tag,don't fault me.

**Comment by KCodin** [comment]
Sorry for the late response.You could maybe have a toggle for Show (persist permanently) and off(or default).

Sorry for bad English.  

> You'll need to use the provided templates instead of opening a plain issue. ;)

I don't know how to do that,but i read that a label can only be put if you have permission to.I don't need any permission its fine.

Thanks.

**Comment by dhaavi** [comment]
Ok, thanks for the idea. I will talk with the team about it.

No problem. ;)

**Comment by Aziks0** [comment]
Definitely something that should be added, it's really annoying having to manually change the filters every time.

> We've been thinking how to do this best.
>
> What do you think about:
> 
> - "Show" section: Persist permanently.
> - "Filter" section: Persist in session only, reset when UI is re-opened. (Already the case.)
> - "Settings" section: Persist in session only, reset when UI is re-opened. (Already the case.)

I would personally prefer having the "Settings" section to persist permanently. I'm always using the live mode to watch for connections as they occur. But it would be more convenient to have a settings section to choose the defaults values selected on UI re-open so that it suits everyone's preferences.

**Comment by dhaavi** [comment]
We are currently building the next version of the network overview. A lot of things will change.
I would like to continue this conversation when it is out - which I guess will take 1-3 months - but don't quote me on that.

**Comment by KCodin** [comment]
thanks for the consideration.Will look forward to it.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
