### ISSUE TITLE
Portmaster does not work properly with Malwarebytes

### ISSUE THREAD

**Issue by my7h1cal** [safing/portmaster#528]
### What worked?
Disabling Malwarebyte's Web Protection brings Portmaster to a "Trusted" rating.

### What did not work?
If you have Malwarebyte's Web Protection on, Portmaster will detect a compatibility issue, detect the network as "Insecure," and disable network traffic on the device.

### Additional information
Having the AV on would be beneficial, even if it'll just be a backup method.

**Debug-Info**: https://support.safing.io/privatebin/?5fa3d9f7e421e3be#CkgCWtNHQxrvAoDa1xyERqVhftxFCRokBAkyFBFGvtkv

**Comment by my7h1cal** [comment]
Correct, as long as Web Protection in Malwarebytes is disabled, both programs work as intended (albeit, Malwarebytes will occasionally warn you and display that you're not fully protected).

**Comment by dhaavi** [comment]
Great, thanks for the clarification!

Closing now. Please reopen if there is anything else.
