### ISSUE TITLE
Slow installer download speeds: Can't Download Portmaster (~300MB), From mainland China (with VPN)

### ISSUE THREAD

**Issue by product-think2049** [safing/portmaster#534]
**What happened**：
- Click portmaster-installer.exe，
- Keep downloading for several hours（really slow, 10KB/s）
- Direct download or using VPN download, not OK  （mainland China, Window 10）
![image](https://user-images.githubusercontent.com/13373715/154100949-4b9112b5-c6b1-4562-b854-82d14f19ac48.png)

Output folder: C:\ProgramData\Safing\Portmaster
Removing old Portmaster Files
Rename: C:\ProgramData\Safing\Portmaster\portmaster-start.exe->C:\ProgramData\Safing\Portmaster\portmaster-start.exe.bak
Delete file: C:\ProgramData\Safing\Portmaster\portmaster-start.exe.bak
Extract: portmaster-start.exe... 100%
Extract: portmaster.ico
Extract: portmaster-uninstaller.exe
Create folder: C:\Program Files\Safing
Create shortcut: C:\Program Files\Safing\Portmaster.lnk
Create folder: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Portmaster
Create shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Portmaster\Portmaster.lnk
Create shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Portmaster\Portmaster Notifier.lnk
Create shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\Portmaster Notifier.lnk
Add Toast-Properties to Shortcut
Successfully added Toast-Properties to Shortcut
Sucessfully added Shortcut-Attributes for Toast Messages. Return Code: 0 (0: S_OK)
Prepared the installation directory.
Downloading Portmaster (~300MB), depending on download speeds this may take a while ...

**Comment by SJTUboy** [comment]
Wondering how I can download whole .exe file, and install it?
(so can avoid downloading 300MB)

**Comment by dhaavi** [comment]
Hey @SJTUboy, thanks for raising this issue.

Unfortunately, you cannot "avoid" downloading the 300MB, because the Portmaster needs that data.
We don't provide a full .exe, as we are an early stage software and it would become out-of-date really fast.

I see you have the Portmaster installed. You can just reboot to start it - it will download any missing data it needs in the background.

I am not sure why the download only goes to 10KB/s - is this normal for when you access European servers?

**Comment by pommedefrance** [comment]
Hi,
i can't download the 300mb, i tried manually and i've got
" [control] 2022/03/16 11:11:01 WARNING: error loading indexes: failed to download index stable.json: failed to make request to "https://updates.safing.io/stable.json": Get "https://updates.safing.io/stable.json": x509: certificate signed by unknown authority
Error: failed to download index stable.json: failed to make request to "https://updates.safing.io/stable.json": Get "https://updates.safing.io/stable.json": x509: certificate signed by unknown authority"

can you help me ? :-)

**Comment by dhaavi** [comment]
Hey @pommedefrance, I've moved your comment to a new issue, as it is unrelated to the original problem here: https://github.com/safing/portmaster/issues/571

Marking this and the previous comment as off topic.

**Comment by jhongyu** [comment]
It goes faster when turn on TUN mode on [CFW](https://github.com/Fndroid/clash_for_windows_pkg) @SJTUboy

**Comment by itsnotsaved** [comment]
There's a old feature request https://github.com/safing/portmaster/issues/13

**Comment by dhaavi** [comment]
Thanks for the hint @itsnotsaved.
Yes, this is related to #13, but the underlying problem is a different one.

As I understand, this is mainly about speed. The offline installer is a workaround to that.

We have seen ourselves that traffic from the APAC region might be slower to the update server, which is hosted in Germany.

**Comment by product-think2049** [comment]
> 

This solution solved my problem! 
Thank you very much!

seems like the f*cking China's Great Firewall issue. Not software or EU server issue.

**Comment by product-think2049** [comment]
This Solution:

It goes faster when turn on TUN mode on [CFW](https://github.com/Fndroid/clash_for_windows_pkg) @SJTUboy

**Comment by Short-Arm-Ape** [comment]
> 嘿 @SJTUboy，感谢您提出此问题。
> 
> 不幸的是，您无法“避免”下载 300MB，因为 Portmaster 需要这些数据。我们不提供完整的.exe，因为我们是一个早期软件，它很快就会过时。
> 
> 我看到您已安装 Portmaster。您只需重新启动即可启动它 - 它会在后台下载所需的任何缺失数据。
> 
> 我不确定为什么下载速度只有 10KB/s - 当您访问欧洲服务器时，这正常吗？

I have encountered the same problem, can I solve it by copying files from other installed users?

**Comment by Short-Arm-Ape** [comment]
> Hey @SJTUboy, thanks for raising this issue.
> 
> Unfortunately, you cannot "avoid" downloading the 300MB, because the Portmaster needs that data. We don't provide a full .exe, as we are an early stage software and it would become out-of-date really fast.
> 
> I see you have the Portmaster installed. You can just reboot to start it - it will download any missing data it needs in the background.
> 
> I am not sure why the download only goes to 10KB/s - is this normal for when you access European servers?

![Image](https://github.com/user-attachments/assets/52a774a2-46f2-4214-8977-cc4b6ede8d28)

I am currently completely unable to use it.

**Comment by Short-Arm-Ape** [comment]
> Hey @SJTUboy, thanks for raising this issue.
> 
> Unfortunately, you cannot "avoid" downloading the 300MB, because the Portmaster needs that data. We don't provide a full .exe, as we are an early stage software and it would become out-of-date really fast.
> 
> I see you have the Portmaster installed. You can just reboot to start it - it will download any missing data it needs in the background.
> 
> I am not sure why the download only goes to 10KB/s - is this normal for when you access European servers?
