### ISSUE TITLE
Fedora: System DNS Client is trying to use secure DNS resolver

### ISSUE THREAD

**Issue by northys** [safing/portmaster#541]
**What worked?**

Everything works like a charm except for one annoying notification.

**What did not work?**

```
Portmaster detected that System DNS Client is trying to use a secure DNS resolver. While this is a good thing, the Portmaster already handles secure DNS for your whole device. Please disable the secure DNS resolver within the app.
```

There is `System DNS Process` which is `systemd-resolved` actually which apears time to time. I don't understand why this happens since I expect that portmaster should somehow stop this service on install. Shouldn't it?

I thought maybe it has something to do with flatpak apps bypassing portmaster since skype and microsoft domains appeared here and I have installed skype using flatpak. But I haven't noticed it before and now I have skype opened for multiple days so I'll turn it off so I can see whether it stops.

EDIT: firefox domains also appears in the list time to time but I have firefox installed natively using dnf. Firefox is configured to use default system DNS. I do not have DOH enabled in firefox.

![Screenshot from 2022-02-19 23-30-21](https://user-images.githubusercontent.com/2878126/154821257-17772e5d-15b1-4c4a-aeb6-5e1f8b96ad67.png)

**Debug Information FROM THE APP**:

https://support.safing.io/privatebin/?b825a1df4e71dd07#94RWiHkHsosCR5DMJuhg8x1wTfqQMUYg6Dm8prUZJXFE

**Comment by northys** [comment]
dropbox appears time to time as well. installed using dnf like firefox.

**Comment by northys** [comment]
related discussion on reddit https://www.reddit.com/r/safing/comments/rgfpj3/newbie_questions/

> And even if this is a false positive, it would help for us to understand where Portmaster may have detected something wrongly. Thanks for using the Portmaster and your report!

it probably isn't false positive. just system component is "blamed" instead of individual apps.

**Comment by northys** [comment]
> So you are getting the secure resolver notification for Dropbox too?

Yeah. It triggers the same "System DNS Client" warning and the dropbox itself is stuck connecting (which is another issue probably). I've copied the dropbox app debug info like 30 seconds after opening it just in case https://support.safing.io/privatebin/?b852ad67727f2845#Ccq6CqhB7SCgtVtXZhQyRJ9rRLn4CSyWMxgrXJKZbBpu

> On linux this works via the dbus.

So it uses different "API" to resolve domains? Does this mean that portmaster can't handle everything itself? I don't think this is the indeed bypass like when I set DOH in firefox for example.

**Comment by dhaavi** [comment]
We've improved this in v0.8.5 - the correct process should now be blamed.

I'm not sure about the dropbox thing. You can check the warning in the details tab of the app page. There, it says when it was last detected. If that does not change, maybe there was a hickup.

> Does this mean that some apps are more "modern" and use that dbus thing and portmaster has to handle those connections using it's documented magic where it tries to guess pairs of IPs app is connecting to and IPs which were resolved recently to get the actuall domain?

Yes. That's how it works on Windows 100% of the time. Works quite well.

> Does it mean that more and more apps are going to work like this on systemd linux distros?

Probably yes, but I don't have any details on that.

**Comment by northys** [comment]
@dhaavi works. iirc i haven't seen skypeforlinux at all.

![Screenshot from 2022-03-07 16-21-52](https://user-images.githubusercontent.com/2878126/157063110-7f70ed6e-0164-4843-865a-74288835400b.png)
