### ISSUE TITLE
Dns problem

### ISSUE THREAD

**Issue by boistordu** [safing/portmaster#543]
Sorry this is going to be an in-between question/clarification/bug report

Version 7.21
Os: Ubuntu 21.10

You are claiming in show help about the dns resolver that it's in the order they are specified in the list. 
Fine, very nice to have that system. But it doesn't work.

I have built a list of resolver based on your 2 privacy ones. I've added the nextdns resolver and one local rpi Pi-hole gateway. 
You are claiming also that if one fails the others take the relay. 
Apparently it doesn't work either.

Since I don't know if it has a link with the problem which I m encountering, I'm going to specify the chronology of events.

It's a linux tablet so I m moving with it a lot and I m disabling completely networking regularly. 
If I want to plug it in again to my rasp then it's fine it's getting its connectivity back.
If I want to rely on the general wifi then nothing.
The networking is definitely working since I can ping outside. But the dns resolving system of portmaster does not jump from one dns to another as it should do. 
If I do a dig -> timeout.
Restarting portmaster ->not much luck 

I've modified the order in the list even  + restarting portmaster -> still no luck....

Do you have a known bug that we should know about ?

EDIT: After some investigation:
if there is a single discrepancy in the dns line, so any malformed line in the dns server subsection like a dot://45.90.30.105?verify=portmaster.46a66.dns.nextdns.io in place of dot://45.90.30.105?verify=portmaster-46a66.nextdns.io or dns1 in place of dns.nextdns.io then portmaster is unable to go to the next server in line.  It also seems that then the whole software goes stucked because even if you rearrange the list to put official dns server builtin lines in front, and restart portmaster it does not take that into account and stay stucked. 
I will try to reproduce the behavior in the mean time and provide some logs 
for known format like nextdns, and if the system is at fault here to not be able tondeal with discrepancies, it would be good  to have some kind of tooltip indicating the user that the line is malformed.

**Comment by dhaavi** [comment]
Hey @boistordu, thanks for reporting this.

Having multiple resolvers that *should* fail and fall back to the next is not a use case we have thought of.

You can check which resolvers the Portmaster currently uses by going to http://127.0.0.1:817/api/v1/dns/resolvers - you might need to enable the developer mode for this.

If you can reproduce anything being stuck, please paste the debug info here about that!

> it would be good to have some kind of tooltip indicating the user that the line is malformed

I just found a TODO for that in our code, I now added better validation that will give an error immediately.

Thanks a ton for continuing to use the Portmaster and report bugs!

**Comment by dhaavi** [comment]
> What's the threshold of failing servers?

The Portmaster marks a resolver as failing when 20 queries fail. The resolver is then retried after 5 minutes by default.

The API endpoint http://127.0.0.1:817/api/v1/dns/resolvers will tell you which resolvers were parsed successfully and which are currently failing.

**Comment by boistordu** [comment]
Yeah but wait you were telling earlier that you didn't plan the case where multiple dns server are failing and now it seems that you are saying that it's all okey and the soft would just check the parsing of every dns server in the list transparently ... 

It's because you said earlier that you didn't plan this case that I've asked you what did you plan as a threshold on failing server in the list ? 1?2?5?

to know from which servers dns query did come from I already know that "dig" will mention that to me since portmaster is reporting this information to dig.

**Comment by dhaavi** [comment]
> Yeah but wait you were telling earlier that you didn't plan the case where multiple dns server are failing and now it seems that you are saying that it's all okey and the soft would just check the parsing of every dns server in the list transparently ...

I think we had a misunderstanding here. I don't see the failover system and the validation of configuration as related.

> It's because you said earlier that you didn't plan this case that I've asked you what did you plan as a threshold on failing server in the list ? 1?2?5?

The Portmaster only has what is in the list and the Portmaster will continue to the next resolver if a query fails on one. It will start ignoring a server if it failed 20 times within 5 minutes.

So your use case _might_ work, but the Portmaster will continually retry the unreachable resolver, leading to longer query times in some cases.

If things are still unclear, please ask.

**Comment by boistordu** [comment]
Okey then why has it stopped resolving address then? Simple question based on what I experienced or can reproduce even actually

**Comment by dhaavi** [comment]
There should be multiple warnings or errors in the logs about the resolver that will tell you why it marked a resolver as failed.
You can use the API endpoint at http://127.0.0.1:817/api/v1/dns/resolvers to check the current status of resolvers.

These two things will help to find out what is happening in your use case. Please share your findings!
