### ISSUE TITLE
ivpn compatibility report (good with some customizations)

### ISSUE THREAD

**Issue by boistordu** [safing/portmaster#544]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**
Ivpn wireguard works fine under debian-like distribution)

**What did not work?**
it is not working out of the box because since portmaster try to replace any other dns server, the ivpn client try to do the same thing. 
configure in ivpn gui, the custom dns to your local portmaster dns server which can be seen in /etc/resolv.conf
Also be aware that the anti-tracker feature from ivpn will override this parameter and the problem will come back, so be sure to have deactivate that in the wifi control system from ivpn  or anywhere else. 

Also the ipv6 availability in the ivpn tunnel does not seem to work correctly with portmaster (not only with dns but also a simple ping) but that needs more investigation. 

Do you still need the logs to confirm ?
**Debug Information**:

**Comment by boistordu** [comment]
If I may add a suggestion, everything is in the tooltip and of course the detection of this kind of executables running (which is in the end part of the project since your motto is "fight the surveillance), like that the user can exactly know what the problem is and how to disable it.

**Comment by dhaavi** [comment]
Hey @boistordu thanks a lot for the report and given workaround!

> If I may add a suggestion, everything is in the tooltip and of course the detection of this kind of executables running (which is in the end part of the project since your motto is "fight the surveillance), like that the user can exactly know what the problem is and how to disable it.

I'm not sure I followed correctly, can you elaborate?

**Comment by boistordu** [comment]
Well you wanted to add this feature of dns client detection tool, no?

So you could just go to the end of the reasoning and do the complete work about it which would be -> detect every processes on port 53 -> link the process id to the process name -> compare it to an exhaustive list of the clients out there (there are not that many that people might have set up) -> indicate in the tooltip you coded what is conflicting.

**Comment by dhaavi** [comment]
Ah, I understand.

Yes, this is something we are looking into. I haven't though about check what else runs on port 53, as I would have not expected a VPN client to create a DNS server. But this is indeed interesting.

Currently we are going in the direction of detecting other incompatible software by checking what software has registered in the WFP stack on Windows and check custom iptables chains on Linux.

Did the Portmaster send a compatibility notification when it didn't work at the beginning?

**Comment by boistordu** [comment]
> Ah, I understand.
> 
> 
> 
> Yes, this is something we are looking into. I haven't though about check what else runs on port 53, as I would have not expected a VPN client to create a DNS server. But this is indeed interesting.
> 
> 
> 
> Currently we are going in the direction of detecting other incompatible software by checking what software has registered in the WFP stack on Windows and check custom iptables chains on Linux.
> 
> 
> 
> Did the Portmaster send a compatibility notification when it didn't work at the beginning?

No it didn't.

Still having the same problem by the way. Complete loss of connectivity when using portmaster and Ivpn together
