### ISSUE TITLE
incompatibility with flathub version from jitsi-meet 

### ISSUE THREAD

**Issue by boistordu** [safing/portmaster#549]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**
I thought at first that it was jitsi-meet flathub version who was at fault but then I've run the flathub through CLI and have seen this 
```
node:3) electron: Failed to load URL: https://calls.disroot.org/breakit#jitsi_meet_external_api_id=0&config.disableAGC=false&config.prejoinPageEnabled=true&config.prejoinConfig=%7B%22enabled%22%3Atrue%7D&appData.localStorageContent=null with error: ERR_NAME_NOT_RESOLVED
(Use `jitsi-meet --trace-warnings ...` to show where the warning was created)
```

**What did not work?**

So I shutdowned portmaster service, change `/etc/resolv.conf` manually to bypass systemd with 9.9.9.9
did a dig -> good result
run the flathub version again, no more error not resolved, and all was fine I could finally join a room. 
So clearly something with the dns local server which is handle as you know by systemd which rely on portmaster once it is installed. 

So I guess your detection system doesn't recognize the call from flathub and then blocks it or just drops it because of unknown source? 

**Debug Information**:
https://support.safing.io/privatebin/?3969fcd4c4cccd3e#HyMPreqkJUbcr2SioD6PXQRVmAo1jnwf79P7g6smZcKV

**Comment by boistordu** [comment]
the deb version and AppImage seems to work but I'm not sure if it s not because of the cache dns still being active. But let's say for the sake of the argument that's it's only contained to flathub version for now.

**Comment by boistordu** [comment]
> 

SPN is not activated. This is the first thing I've looked. 
And yes  the packets were under the wrong section. This is why I think something is not quite well detected in the flathup version of jitsii but well with the original software.

**Comment by dhaavi** [comment]
Ok. I think I'll close this for now and refer to it when this comes up again. Thanks!
