### ISSUE TITLE
MATE compatibility issue

### ISSUE THREAD

**Issue by boistordu** [safing/portmaster#550]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

Everything besides things which are in my opinion not totally direclty linked to the DE. 
Most of my reports have been reproduceable under different DE on the same host and are contained to specific kind of ip packets and /or piece of software.

**What did not work?**

**Debug Information**:

**Comment by dhaavi** [comment]
Ok, I'll mark the issue as "waiting for input", should it be closed by the bot, just reopen it when you get to it.
