### ISSUE TITLE
Starting module interception failed

### ISSUE THREAD

**Issue by fakhamatia** [safing/portmaster#551]
**What happened**:

Starting module interception failed
Portmaster not start
![image](https://user-images.githubusercontent.com/20030910/155844034-8b6f0ee3-a5a3-499f-b247-148707a684e4.png)
```
Failed to start module: nfqueue(IPv4, out): netlink validate: mismatched sequence in netlink reply
```

**How did you reproduce it?**:

Portmaster was working fine.
I Change two things:
I install an adapter driver from [this link ](https://github.com/kelebek333/rtl8188fu)
And create a hotspot from adapter with[ this link ](https://askubuntu.com/a/609199/859739)
All things were working fine, and I reboot for testing, and Portmaster not work

**Debug Information**:
"Copy Debug Information" Not working :
![image](https://user-images.githubusercontent.com/20030910/155843948-a4bdd666-a7c8-4517-b776-71b3339dd07e.png)
```
Failed loading debug data
Http failure response for http://127.0.0.1:817/api/v1/debug/core?style=github: 503 Service Unavailable
```

Ubuntu 21.10
Portmaster Version:0.7.21 License:AGPLv3

**Comment by calinadamut** [comment]
same here:

Starting module interception failed
Failed to start module: could not initialize nfqueue: exec: "iptables": executable file not found in $PATH

any suggestion how to solve it?
