### ISSUE TITLE
Windows Notifications Do Not Allow "Accept" or "Block" Functionality. 

### ISSUE THREAD

**Issue by jumpa23** [safing/portmaster#552]
Not sure if this has been reported before, I'm on Windows 10 21H1 and when i get notifications via windows that an app or process is trying to connect, and get the choice of block or allow, no matter what I click on, it does not actually block or allow. I have to open up the Portmaster interface and choose block or allow from there. Would be great if this could be fixed, or if someone could tell me if I'm doing something wrong. 

Thanks

**Comment by dhaavi** [comment]
Hey @jumpa23, thanks for raising this with us.

We are aware of problems with notifications on Windows, but weren't able to find the cause yet.
I will update this issue when we know more.

**Comment by HeySteets** [comment]
Hello! New user here. Just wanted to chime in that I can reproduce this bug as well.

**Comment by youdontneedtoknow22** [comment]
> I don't even receive Windows notifications. I only see them in the Portmaster prompts box. I see #856 but not sure if this addresses the problem.

make sure to disable the "Focus Assist" or "Do Not Disturb", more than often that's the cause.

**Comment by c-prompt** [comment]
> > I don't even receive Windows notifications. I only see them in the Portmaster prompts box. I see #856 but not sure if this addresses the problem.
> 
> make sure to disable the "Focus Assist" or "Do Not Disturb", more than often that's the cause.

Verified long ago. Didn't make a difference.

**Comment by dhaavi** [comment]
This has been fixed a while ago.
