### ISSUE TITLE
SPN status in GNOME panel

### ISSUE THREAD

**Issue by northys** [safing/portmaster#556]
**What would you like to add or change?**:

I would love to see SPN icon over the portmaster icon when I'm connected. The same (blue) icon I can see in portmaster UI over the shield. Also I would love to see that icon to be red or something when SPN connection fails.

**Why do you and others need this?**:

It's a must :heart:

**Comment by dhaavi** [comment]
We're already on it.

> It's a must

I feel so too.

**Comment by dhaavi** [comment]
This has been released a while ago.
