### ISSUE TITLE
Windows Sandbox: no internet, no connection

### ISSUE THREAD

**Issue by PeopleInside** [safing/portmaster#559]
### What happened?
When Portmaster is active and open windows 10 or Windows 11 sandbox there is no internet connection on the sandbox

### What did you expect to happen?
Can have internet in Windows sandbox

### How did you reproduce it?
Install portmaster, restart the PC, open a windows sandbox and try to surfing using the Edge browser. results: no connection.

### Additional information

**Debug-Info**: https://support.safing.io/privatebin/?dd2cf42ebf50df3d#Cprq6WuqCpxdvPXvkr3Ky2erA7muErStHdFtkCrADAfd

**Comment by PeopleInside** [comment]
Need refresh browser sometime more than one time and seems I'm able to surf.
Is giving some little issue on Windows sandbox :)

**Comment by dhaavi** [comment]
Hey @PeopleInside, thanks for reporting this.

We do not yet support VMs (#166) and I'm not sure how Windows Sandbox handles its network traffic. It might just bypass the host network stack using a hyper-v switch.

I think related issues were resolved by setting a custom DNS resolver (eg. 1.1.1.1) in the VM/Sandbox.

**Comment by PeopleInside** [comment]
Thanks for the reply.
I'm searching a way to set something in portmaster to not have every time I use WindowsSandox to do something to have Internet connection.

**Comment by dhaavi** [comment]
If you are up for some experimental stuff, you can try out the [Network Service](https://docs.safing.io/portmaster/settings#core/networkService) mode. You will need to add something like `Allow LAN UDP/53` (or less, if you know the IPs of the sandbox) to the [Incoming Rules](https://docs.safing.io/portmaster/settings#filter/serviceEndpoints) of the "Portmaster Core Service" app to allow requests from the outside.

Only attempt if you are well versed with networking and understand the effects.

Other than that, I don't think we have a solution for this use case right now.

**Comment by PeopleInside** [comment]
I cannot try. decide you if keep this issue open or if for you is not an issue.,
I removed the program because I cannot use the Windows SandBox correctly.

**Comment by dhaavi** [comment]
Ok. I will then close the issue for now. We will have a look when we get to proper VM support.

**Comment by Marc05** [comment]
@dhaavi I realize that this is currently out of scope and general VM support will take some time. However, I think this should be re-opened and some effort put into allowing Windows Sandbox specifically to work. Windows Sandbox provides the flexibility of VMs in a simple and effective manner for any user. I'd imagine there's a fair overlap between Portmaster and Windows Sandbox users.

I've tried the Network Service mode suggestion, but it does not appear to help. I've managed to get limited connectivity working inside the sandbox by creating an allow incoming rule for "Windows Service: Shared Access". No other settings seem to help. I'm willing to test if needed.

```
PS C:\Users\WDAGUtilityAccount> nslookup google.com.
Server:  DESKTOP-0QG15HA.mshome.net
Address:  172.27.112.1

Non-authoritative answer:
Name:    google.com
Addresses:  2607:f8b0:4023:1009::8a
          2607:f8b0:4023:1009::66
          2607:f8b0:4023:1009::71
          2607:f8b0:4023:1009::8b
          142.251.33.46

PS C:\Users\WDAGUtilityAccount> ping google.com
Ping request could not find host google.com. Please check the name and try again.
```

**Comment by he3als** [comment]
I am having the same issue, I tried to do everything recommended here to try to get it to somewhat work, but nothing has worked. I also can not get an internet connection in Hyper-V VMs (I can in WSL though).
