### ISSUE TITLE
a little upgrade in docs and feature regarding the new feature of conficting dns client. 

### ISSUE THREAD

**Issue by changemenemo** [safing/portmaster#562]
**What would you like to add or change?**:

Hi,
You've introduced the feature of detecting other dns client and print it out a warning message in the UI about it  "Failed to resolve conflict between several dns clients" something like that. 
And your message is pointing to the incompatibility doc page which doesn't seem very fit to me. 
Apparently your software is reacting also to dns software layer like unbound and dnscrypt which don't contain any kernel driver to intercept dns request like your do (which is why I separate the software layer and kernel layer).
And that even if they are running on different loopback address. 
Maybe we should then upgrade the documentation to explain the layman why it is a problem ? I'm thinking about people who for example installed unbound which is described as giving more neutrality towards the respective ISP of the user.

Also in the docs it's unclear if you wish that systemd-resolve stay in place or if we should deactivate it and what are the benefits or the disadvantages of each solution (since your solution is working totally fine because of being at kernel stage without systemd-resolved.

And finally it could be beneficial for this feature to look for the different client running. if not, the user would not know where to look or what to disable and what is considered by the feature as a dns client and what is not (since systemd-resolved is tolerated).
**Why do you and others need this?**:

That would give a better idea to everybody why some things should stay in place and other should not. If not, people are just applying things without really knowing or understanding what they are doing.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
