### ISSUE TITLE
Mullvad newest multihop v2022.1 [Broken feature] [Windows]

### ISSUE THREAD

**Issue by TurkyDev** [safing/portmaster#568]
**What worked?**
OpenVPN and Wireguard connections with the workaround, just like normal.

**What did not work?**
The whole internet when enabling the newest wireguard multihop or "double vpn" feature in the adv wireguard settings.
As soon as you disable it, seems to all work fine again.
Or closing portmaster, the multihop + internet work fine too.

**Extra**
Seems to open a bunch of random connections in the unidentified processes and sys dns client
via LAN and internet incoming from the IP selected in the entry section. Plus a few others i can't make sense of. 
Would help a lot if someone more network savy tries this out.

**Comment by dhaavi** [comment]
Hey @TurkyDev, thanks for reporting this!

I won't have the time to try this out myself in the near future, but will mark it, so we can take a look ourselves as soon as resources allow it. Until then, we'll add a note to the docs.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
