### ISSUE TITLE
What is portmaster's source for information about AS?

### ISSUE THREAD

**Issue by northys** [safing/portmaster#573]
This looks like some kind of easter egg but it's not Easter yet :D How do you get AS details? Do you use some sort of public API or you use the same behaviour as `whois` command?

**What happened**:

![Screenshot from 2022-03-17 22-39-38](https://user-images.githubusercontent.com/2878126/158899390-761d4ead-3cc9-4f29-9c0e-e35314665c27.png)

I noticed a smile in `AS Org` field for twisto.cz. It is hosted by sh.cz which is somehow controversial datacenter so I wasn't surprised about the smile in the Org name. What surprised me is that I couldn't verify it by running `whois 95.168.205.33` in my console nor by googling exact match of `"SUPERNETWORK \\(^_^)/"`.

```
northys at northys-fedora in ~
» whois 95.168.205.33 | grep -i supernetwork
netname:        CZ-SUPERNETWORK-20090107
mnt-by:         SUPERNETWORK-MNT
mnt-lower:      SUPERNETWORK-MNT
mnt-routes:     SUPERNETWORK-MNT
mnt-domains:    SUPERNETWORK-MNT
mnt-ref:        SUPERNETWORK-MNT
mnt-ref:        SUPERNETWORK-MNT
mnt-by:         SUPERNETWORK-MNT
mnt-by:         supernetwork-mnt
mnt-by:         SUPERNETWORK-MNT
descr:          SuperNetwork s.r.o.
mnt-by:         SUPERNETWORK-MNT
northys at northys-fedora in ~
» whois 95.168.205.33 | grep -i 39392
% Information related to '95.168.192.0/20AS39392'
origin:         AS39392
```

**Comment by dhaavi** [comment]
Haha. This is funny.

We source from multiple places, but I think the AS data comes from https://iptoasn.com/.

We are currently evaluating how to source this data. Our main problem is that we need to redistribute the entire database, which means we cannot use MaxMind.
I will look into this when I continue with evaluation.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
