### ISSUE TITLE
Block/Allow temporarily

### ISSUE THREAD

**Issue by Flavelius** [safing/portmaster#574]
First of all, thanks for creating this software, it's strangely hard to find linux people who agree that application firewalls are necessary in today's software world where one cannot only rely on trusted (/outdated) sources.
So far it seems to work great and looks & feels very polished!

**What would you like to add or change?**:
Currently it seems confirming Block or Allow in the prompt automatically adds a permanent rule.
I'm used to temporarily allowing requests for applications on windows, using comodo firewall which has these prompt options.
It's quite convenient to select the block/allow action in the prompt there.
example:
https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.-s8G9UBk4e4nMy_g_M5dKgHaDw%26pid%3DApi&f=1
There block/allow is temporary by default and has to be made permanent by ticking a checkbox (which i like). It would be nice to have such an option too.

**Why do you and others need this?**:
It's not uncommon to only want to temporarily allow certain requests for example to activate a software but then block all its phoning home afterwards or to have peace of mind that some application that should only do web requests when actively commanded to can do so (selectively approving this connection).

P.S. using the .deb installer (on ubuntu) that opened the software center for installation was an unfortunate experience in that the installer seemed stuck at 22% for quite some time (not measured but felt like ~10min). After searching around it looks like it's the moment where it downloads some files from a remote location that are necessary for installation. This should be noted somewhere as the software center lacks user feedback in this regard.

**Comment by northys** [comment]
linking my similar issue https://github.com/safing/portmaster/issues/538

**Comment by dhaavi** [comment]
Hey @Flavelius, thanks for the suggestion.

This was already suggested in #538 - so I'm closing this to continue the discussion there.

(The note in the installers about downloading the assets is a bit if a pain in the ass, as there is no way to properly solve this. - But that's another issue.)
