### ISSUE TITLE
Connecting to Network Printers on Linux Mint

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [safing/portmaster#579]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility) 
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

Checked existing issues - no relevant issues appear to exist, open or closed.

**What worked?**

Portmaster is an incredibly effective tool to combat telemetry, tracking, and privacy invasive connections in general, and I've been recommending it to whomever I can.

**What did not work?**

It seems Portmaster prevents Linux Mint v20 from viewing available network printers. The affected device is a Canon wireless printer and the printer is not shown under [Network Printers] in Linux Mint's [Add Printer] dialog box while Portmaster is running. If Portmaster is shut down, the network printer appears. Even after the printer was added, printing is again prevented if Portmaster is started. I'm running the latest version of Portmaster.

**Debug Information**:
N/A - I can provide if needed.

**Comment by dhaavi** [comment]
Hey  @shrimprugbysnowowl, thanks for reporting this.

I will have to look into this.

**Comment by shrimprugbysnowowl** [comment]
For those following along, I discovered a workaround to this issue was to add global rules to allow ```LAN``` and ```Localhost```.
