### ISSUE TITLE
Clicking "Invalid Value" Notification in Outgoing Rules Clears All Outgoing Rules

### ISSUE THREAD

**Issue by shrimprugbysnowowl** [safing/portmaster#580]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

No similar existing issues are present.

**What happened**:

I attempted to set an Outgoing Rule in global settings to block "enterprise.activity.windows.com" and Portmaster notified me that the rule was invalid.  I clicked the red [Invalid Value] notification and Portmaster removed all the previously existing (and valid) outgoing rules.

![bug](https://user-images.githubusercontent.com/59341190/160166473-9986c388-9cf3-45c7-a89b-ec5a0443c372.png)

**What did you expect to happen?**:

I'm not sure, but not for all of them to disappear.

**How did you reproduce it?**:

Re-enter an outgoing rule that is considered invalid below other existing rules and click the red [Invalid Value] box which appears to the right of the [Outgoing Rules] heading.

**Debug Information**:

N/A, but I can provide if needed.

**Comment by dhaavi** [comment]
Hey @shrimprugbysnowowl, thanks for the report.

Yes, this is indeed not really nice. We will look into how to solve this.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.

**Comment by shrimprugbysnowowl** [comment]
Yes, this seems to be resolved.  Ok to keep closed.

> Please keep in mind, the free version of Portmaster only has limited support.

Is Portmaster now discouraging opening issues on Github?  I'm not trying to misinterpret the message here - just looking for clarification.

**Comment by Raphty** [comment]
You can open as many issues as you like. We are going to close issues, which are not reproducible on our end and no one from the community is working on more active in the future.

The goal is to keep the issues more relevant and active (100 open issues where nothing is happening doesn't help anyone). 
The limited support refers to support questions, configuration and so on. If something is a bug we want to solve it. But if a free user doesn't understand something or some other part of their software is interfering, then the community is the best place to ask. This can be here on GH, but with weeks of inactivity, the issue won't get solved.
