### ISSUE TITLE
Message: self-check #3: dns integration check failed: did not receive test response after 10s

### ISSUE THREAD

**Issue by Smart-Helper** [safing/portmaster#581]
**What happened**:

Portmaster throws me an error after 5-10 minutes of usage. After restarting the core it throws again after 5-10 minutes.
![image](https://user-images.githubusercontent.com/38812603/160166222-2c47210a-6c11-4202-9f33-05c6ab6c5d93.png)

I have an instance of AdGuard running on my local network. Portmaster worked fine for months with this configuration but suddenly started to give me these errors. Apparently everything continues to work properly but it still gives me the error.

I already tried to delete the DNS Server from cloudflare:
![image](https://user-images.githubusercontent.com/38812603/160166499-534f66df-9184-4aec-a236-bc72c1c0e174.png)
And i tried to insert the local IP adress of my AdGuard but it wont save it.

[2022-03-25-16-15-50.error.log](https://github.com/safing/portmaster/files/8352475/2022-03-25-16-15-50.error.log)

The LogFiles show the `Message: self-check #3: dns integration check failed: did not receive test response after 10s`

That's all i know. If someone can help me figure out what is going on here that would be great.

**Comment by Smart-Helper** [comment]
Hey @dhaavi 

sorry, i think my post was kinda missing the point. The secure DNS thing was just that i already tried to delete that option as a result of me having the initial Problem.

To clarify: I had my portmaster in default settings. Only thing i added were rules to some local IP adresses in my network.

Then, randomly at one day, it decided to give me the screenshoted error message. After that day, it was unfixable and happened every 5-10 minutes. I even tried to reinstall Portmaster but that didnt change anything.

I didn't change anything in my network settings, nor did i add any new DNS device or whatever in my network. The AdGuard DNS Server that runs in my network was running months prior to that issue and Portmaster never had a problem with that.

**Comment by dhaavi** [comment]
OK, thanks for the clarification.

When it first started to happen, did you do an update of your OS or the Portmaster before?
Do you remember which version of Portmaster you were running when the issue first appeared?

**Comment by Smart-Helper** [comment]
No i did not update my OS. But i switched my DE from KDE to Gnome41. I didnt have the issues in KDE. But i recently switched back to KDE which was still installed and i still have those Problems.

I am now quite sure that my network and my local DNS server is not the problem. I installed Portmaster now on my fedora laptop and my wifes ubuntu pc and both of them run perfectly fine in the same network as my pc.

Regarding the version i am not sure. I know i was on 0.7.X but im not sure if i had any updates inbetween.

**Comment by dhaavi** [comment]
I see. Can you try it with the current version and the default settings for "DNS Servers"?

Have you changed the "DNS Servers" setting on the other two devices?

**Comment by Smart-Helper** [comment]
I just uninstallled the old one, rebooted. Now i want to install it again
https://docs.safing.io/portmaster/install/linux#arch-linux
This is the correct approach for me with manjaro - right?

No i didnt change anything DNS related on any device. And i just changed those settings on the problematic device when it already acted up. So this setting can be ignored. As it didnt do anything. 

The problems occured before i changed anything

**Comment by Smart-Helper** [comment]
Still the same error right now

**Comment by Raphty** [comment]
@Knubbel Portmaster sends a query to check if it ends up back with Portmaster. If the query doesn't come back then Portmaster alerts you because something is interfering.
