### ISSUE TITLE
Portmaster/Windows 10

### ISSUE THREAD

**Issue by Ebmm** [safing/portmaster#582]
**What happened**:
After install, I had lost the ability to file share via the LAN with another Win10 machine. The machine with the install would fail to show on the network. I messed around with it all morning and I could find nothing. No settings had changed anywhere, NIC settings, services, firewall, nothing! No recent updates either. I then remembered I had installed Portmaster on the machine the evening before. I uninstalled Portmaster as well as my adapter. Booted back up, put my same static settings in the adapter and the problem was gone. To eliminate coincidence, I reinstalled Portmaster and the same problem again, after a reboot. Portmaster running or not. I then proceeded to do the same fix again and problem gone once again. Machine is a Dell T5500 using the onboard realtek NIC, Win 10 Pro. Machine does have a TAP and Hyper-V adapter but I had them disabled, plus they've always been installed anyway. Nothing goofy or exotic installed on the machine. It does have a "dual boot" with Linux but that's on a separate drive with it's own bootloader on it's own drive buts that's always been that way as well. The only proven variable was Portmaster. 

**What did you expect to happen?**:

**How did you reproduce it?**:
Duplicated it, as stated above.

**Debug Information**:

**Comment by dhaavi** [comment]
Hey @Ebmm, thanks for the elaborate report!

Did all other connections (ie. except for the file sharing) work fine?

The Portmaster blocks incoming connections by default, you'll need to allow them manually in the Portmaster. To do that, look for the affected application in the network monitor, then open the settings and add [Incoming Rules](https://docs.safing.io/portmaster/settings#filter/serviceEndpoints).


> Portmaster running or not.

How did you verify the Portmaster was not running? The Portmaster doesn't do any persistent changes to the network stack and everything should return to normal when the Portmaster is shut down via the tray notifier.

**Comment by Ebmm** [comment]
I remember Epic Games taking forever to load that morning. I didn’t do anything to reproduce Epic and portmaster though, like I did with the network discovery. I was focusing on this machine not showing on the network. It was as if network discovery was off or one of the 4 related services in Services were off. That’s exactly how it was acting. I didn’t think to check Epic again.

**Comment by Ebmm** [comment]
Just now seen your last question. As per my bug report, it did not matter if portmaster was on or off. Only a uninstall fixed the problem, I reinstalled and problem returned, I uninstalled again and problem was again resolved.

**Comment by ahmed-abdelrazek** [comment]
@Ebmm same

**Comment by dhaavi** [comment]
Thanks for the additional info on this!

How did you shut down the Portmaster?
(There sometimes is confusion about it being really off or not.)

**Comment by ahmed-abdelrazek** [comment]
i just reinstalled the app and it seems that issue has been solved i can access other devices on my local network and if i changed the settings for `Default Network Action` to `Prompt` it will even ask if i want to allow the connection to the other device ip (wasn't doing that before)

**Comment by rui4354** [comment]
I setup portmaster in a way to forbid all connection except the bare minimum for my os to function, like dns and application specific necessary connections. 

> Thanks for the additional info on this!
> 
> How did you shut down the Portmaster? (There sometimes is confusion about it being really off or not.)

Not a bug.


> **What happened**: After install, I had lost the ability to file share via the LAN with another Win10 machine. The machine with the install would fail to show on the network. I messed around with it all morning and I could find nothing. No settings had changed anywhere, NIC settings, services, firewall, nothing! No recent updates either. I then remembered I had installed Portmaster on the machine the evening before. I uninstalled Portmaster as well as my adapter. Booted back up, put my same static settings in the adapter and the problem was gone. To eliminate coincidence, I reinstalled Portmaster and the same problem again, after a reboot. Portmaster running or not. I then proceeded to do the same fix again and problem gone once again. Machine is a Dell T5500 using the onboard realtek NIC, Win 10 Pro. Machine does have a TAP and Hyper-V adapter but I had them disabled, plus they've always been installed anyway. Nothing goofy or exotic installed on the machine. It does have a "dual boot" with Linux but that's on a separate drive with it's own bootloader on it's own drive buts that's always been that way as well. The only proven variable was Portmaster.
> 
> **What did you expect to happen?**:
> 
> **How did you reproduce it?**: Duplicated it, as stated above.
> 
> **Debug Information**:

For lan share work , look for app "Operating system" set it to 'prompt', forbid internet access, allow lan access and in inbound/outbound allow only the ip you need and set to block everything.
