### ISSUE TITLE
MitM-proxy when installing Portmaster

### ISSUE THREAD

**Issue by ZzZombo** [safing/portmaster#583]
From #571: the installer will not trust certificates generated by such a proxy, and so the installation will never succeed. Either an option to ignore TLS errors/trust this particular certificate during installation, or to configure proxy settings (in case it is possible to bypass it like it was in my case, but I suppose on corporate networks it's unlikely) prior to this step would be necessary to complete the process, or to delegate downloading to a library/tool that uses the system trust store like curl with the `schannel` backend.

**Comment by dhaavi** [comment]
Hey @ZzZombo, thanks for creating a separate issue for this.

Golang (the language the Portmaster is written in) uses the certificate storage from the OS. So as long as the certificate that your MitM-peoxy is using is also imported into the OS itself, this should not be a problem.

Can you confirm that the MitM cert is imported in your OS?

**Comment by ZzZombo** [comment]
Hello. I don't think your *installer* is written in Go, is it? And if it is, somehow it doesn't trust that particular certificate; yes, its CA cert. is added to the trust store of the OS.

**Comment by northys** [comment]
> I don't think your _installer_ is written in Go

IIRC the installer is just some wrapper that runs portmaster-start (which is golang binary) that downloads everything needed from safing update servers. I'm not sure whether the portmaster-start isn't also downloaded by the installer wrapper. Maybe this could be a problem.

Do you have any screenshot / logs from the installer?

**Comment by dhaavi** [comment]
The installers have portmaster-start bundled, which then downloads the assets. The installers are also responsible for registering the Portmaster as a system service, auto-starting the notifier, adding start menu / desktop entries and other things.

**Comment by dhaavi** [comment]
The installer itself doesn't do anything on the network. That stuff is all done by portmaster-start, which is written in Go, and uses the system's CA store.
So, I would expect it to work when the CA is correctly added to the system store.
I will check if I can find a way to verify that.

**Comment by dhaavi** [comment]
The Go documentation is very clear on where the CAs come from:
```
// RootCAs defines the set of root certificate authorities
// that clients use when verifying server certificates.
// If RootCAs is nil, TLS uses the host's root CA set.
RootCAs *x509.CertPool
```
from https://pkg.go.dev/crypto/tls#Config

Here is the code that loads the root store:
Linux: https://go.dev/src/crypto/x509/root_linux.go
Windows: https://go.dev/src/crypto/x509/root_windows.go

Could it be that you loaded the CA into a different CA storage in Windows? There are a couple of them - but I do not know which one is the correct one.

**Comment by ZzZombo** [comment]
My root CA certificate is added into the Trusted root CA store of the current user, as seen in `certmgr.msc`. This is also how the majority of the applications over there work through the proxy w/o any other setup.

**Comment by dhaavi** [comment]
Can you try adding it the the root CA store for the "Computer account", not just your user?

**Comment by ZzZombo** [comment]
Sorry, I do not have a spare machine to test this w/o going through the hassle of uninstalling Portmaster first unless you have a better way to do it.

**Comment by dhaavi** [comment]
Ok. I'll just leave this here then. So whenever someone has this issue, please try the [mentioned idea](https://github.com/safing/portmaster/issues/583#issuecomment-1096335310) and see if it fixes this.
