### ISSUE TITLE
Simplewall issue

### ISSUE THREAD

**Issue by pommedefrance** [safing/portmaster#584]
then after many research, i don't find the problem
why when simplewall is turn on and i let this svchost allowed

i've got
```
dns-check.safing.io DNS Request 6:17:39 PM 6:17:39 PM 2700 C:\Windows\System32\svchost.exe query failed: all 1 query-compliant resolvers failed, last error: read udp 192.168.41.44:28296->80.67.188.188:53: i/o timeout
one.one.one.one     DNS Request 6:28:49 PM 6:28:49 PM 2700 C:\Windows\System32\svchost.exe query failed: all 1 query-compliant resolvers failed, last error: read udp 192.168.41.44:10131->80.67.188.188:53: i/o timeout
```
etc....

and why i don't have simplewall in portmaster ? (perhaps it's normal :-()
thks

EDITED by @dhaavi to update format for better readability

**Comment by dhaavi** [comment]
> ```
> dns-check.safing.io DNS Request 6:17:39 PM 6:17:39 PM 2700 C:\Windows\System32\svchost.exe query failed: all 1 query-compliant resolvers failed, last error: read udp 192.168.41.44:28296->80.67.188.188:53: i/o timeout
> one.one.one.one     DNS Request 6:28:49 PM 6:28:49 PM 2700 C:\Windows\System32\svchost.exe query failed: all 1 query-compliant resolvers failed, last error: read udp 192.168.41.44:10131->80.67.188.188:53: i/o timeout
> ```

What is your configured DNS resolver?
Does the Portmaster give any error?

> and why i don't have simplewall in portmaster ? (perhaps it's normal :-() thks

If simplewall itself does not do any network requests, then there are no connections for Portmaster to show.

Please provide the debug info from when you are experiencing the problem. You can copy it on the settings page.

**Comment by pommedefrance** [comment]
sorry, i'm not sure to understand dns resolver, the default in portmaster (i change nothing for the test, it's very complicated app for me ;-))..nothing else in my windows..
but when i go to a website dns leak, i've got 
195.181.165.165 	DataCamp Limited
is it normal ?
here the copy debug for dns pb.
[copy debug dns.txt](https://github.com/safing/portmaster/files/8379138/copy.debug.dns.txt)

.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
