### ISSUE TITLE
Add a redirect-to-proxy option 

### ISSUE THREAD

**Issue by yoshimo** [safing/portmaster#592]
**What would you like to add or change?**:
Instead of just selecting between allow and deny for a specific combination of port, application and target-host give the user the option to redirect this traffic to a certain proxy (host:port)

**Why do you and others need this?**:

Not every application follows the operating system settings or offers to enter proxy settings.
Such a feature would help with software analysis while reducing the complexity and possibilities when multiple applications are involved to make this work without support from PortMaster.

**Comment by dhaavi** [comment]
Hey @yoshimo, thanks for the suggestion!

I see the use case you have and see how this would be useful.
I'm not sure if this is something we will be doing, as there is quite some complexity involved in this. The next step in that direction would support for proxies in general, which was suggested here: https://github.com/safing/portmaster/issues/353

I'm adding this to the backlog, so we can have a fresh look at this suggestion later on.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.

**Comment by yoshimo** [comment]
I still can't find an option to toggle and configure this feature, so i guess it isn't done yet @Raphty

**Comment by Raphty** [comment]
As Daniel wrote over a year ago, this was not on the radmap, and still is not. Good ideas come back, so we might do something akin to this in the future. A super old open ticket will not help. I hope you understand.
