### ISSUE TITLE
incomplete list of private subnets

### ISSUE THREAD

**Issue by northys** [safing/portmaster#594]
**What happened**:

tailscale.com assings IPs from subnet `100.64.0.0/10` to connected clients and portmaster shows this connection as Internet P2P.

![Screenshot from 2022-04-07 10-29-30](https://user-images.githubusercontent.com/2878126/162155933-140985c9-c084-4e59-ae35-6daf11c8343e.png)

It's actually not LAN connection so P2P may seem to be legit here but for my wireguard `10.10.0.0/24` it shows LAN label so I expect that some list of private subnets in your code is incomplete.

**What did you expect to happen?**:

All private networks are shown as LAN. See https://en.wikipedia.org/wiki/Reserved_IP_addresses

**Comment by dhaavi** [comment]
Reserved != Private.

`100.64.0.0/10` is CGNAT, iirc. From a threats point of view, this is not your friendly neighborhood and should be treated with the same protection as the Internet, imho.

It would be interesting to put all these weird address spaces into their own `Weird` or `Special` category, so users can immediately see that these addresses are not normal, but very special in their use case.

**Comment by dhaavi** [comment]
Update: I've added `100.64.0.0/10` to the LAN range in v0.8.8 for now. (+ some other invalid ranges as well)

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
