### ISSUE TITLE
nordvpn + portmaster [Linux]

### ISSUE THREAD

**Issue by rafalohaki** [safing/portmaster#595]
### What happened?
When i enable portmaster with nordvpn. I got no internet connection. 
If i use nordvpn without portmaster, its working and if i use portmaster withou nordvpn its working.
Its not working if i have both enabled.

### What did you expect to happen?
No internet

### How did you reproduce it?
When i enable portmaster with nordvpn. I got no internet connection. 
If i use nordvpn without portmaster, its working and if i use portmaster withou nordvpn its working.
Its not working if i have both enabled.

### Additional information
Im using zorin linux

**Debug-Info**: https://support.safing.io/privatebin/?d3731e397b9ddfba#3AK6waQL5GYJcMuy9BaST2dkXToNLcKdJdCLd2gvSjoZ

**Comment by dhaavi** [comment]
Hey @rafalohaki, thanks for reporting this!

NordVPN was previously report compatible in https://github.com/safing/portmaster/issues/297. Can you check if that report helps you?

The debug info matches your description. Can you disable possible interfering features like the "DNS Leak Prevention" ? - The Portmaster already takes care of that.

**Comment by rafalohaki** [comment]
Well, I have installed windows now but if i will have problems again in future, I will make a ticket.
