### ISSUE TITLE
To add or properly categorize extra in-built filter lists

### ISSUE THREAD

**Issue by m77e4t** [safing/portmaster#598]
**What would you like to add or change?**:

Current filters lists are good, but not that much. They do not provide full protection like other content filters can do (NextDNS, Pihole etc)(Portmaster and Nextdn/pihole are quite different). Both of them have extensive filter lists like Adguard, U-block Orgin, Fanboyz, Easylist/Easyprivacy (also country specific ones like Easylist Lithuania) in their settings menu. These lists are quite extensive and cover the user 99% from ads, trackers, analytics etc.

So as an enhancement, it will be pretty good if above-mentioned extra lists are added in the in-built filter list section. Some of them can be Off or On by default, like the way it currently is for some lists.

This particular issue https://github.com/safing/portmaster/issues/326 asks to add custom filter list. While my issue asks to have some extra lists properly categorized in their section.

It seems Easylist/EasyPriavcy, some Adguard lists are already present via 'Adguard List by Ray' https://github.com/r-a-y/mobile-hosts, but it is hidden via a different name than what it is supposed to be. Ublock origin extension (and NextDNS) categories them properly, each one by one via their individual entry in the settings tab.

**Comment by dhaavi** [comment]
Hey @m77e4t, thanks for the suggestion!

Yes, sometimes we use aggregated lists because we could not find a better source.

Do you know of sources for Adguard, U-block Orgin, Fanboyz, Easylist/Easyprivacy lists that:
- Use hosts / domain only syntax (not adblock syntax)?
- Have an open license on the data so that we can safely use them?

Any pointers would be greatly appreciated. Thanks!

Also, if you want to help us out here, the list source configuration is public and on Github -> https://github.com/safing/intel-data

**Comment by m77e4t** [comment]
I found some on Blokada, a similar application made for android 

https://community.blokada.org/tag/blocklist, they have a duck duck go and a few others with open licences which Portmaster might be missing. Most of your and blokada list are same. 

https://github.com/openwrt/packages/blob/master/net/adblock/files/README.md (a similar aggregated lists).

Portmaster already has important lists like Adguard, Easylist by https://github.com/r-a-y/mobile-hosts. I think other content blockers directly integrate easylist, easyprivacy, adgaurd list into their filters as all of them have copy-left licences. 

I am not too well-versed in this topic, so I can exactly give you the input the way you might want. I have asked someone else, he might be able to give relevant information.

**Comment by m77e4t** [comment]
He gave me this data, https://filterlists.com/.

**Comment by dhaavi** [comment]
Thanks for the additional input.

We already know about filterlists.com - but found it hard to actually extract the high quality ones from the many they list.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.

**Comment by DraconicNEO** [comment]
I really hope this feature gets added in the future as there currently is still currently no way to add new/custom filterlists to the app which in my opinion is very much necessary as existing ones may not cover all basis and adding them as custom rules can get messy very fast.

**Comment by Raphty** [comment]
custom filter lists are possible https://docs.safing.io/portmaster/settings#filter/customListFile
