### ISSUE TITLE
App detail: allowed blocked numbers got crazy

### ISSUE THREAD

**Issue by northys** [safing/portmaster#600]
**What happened**:

![Screenshot from 2022-04-13 22-33-28](https://user-images.githubusercontent.com/2878126/163265880-7e24ec41-c230-40f6-b924-7c03e714dde2.png)

**What did you expect to happen?**:

Blocked % is not negative and allowed is not more than 100%

**How did you reproduce it?**:

I have no idea.

**Debug Information**:

https://support.safing.io/privatebin/?902c62702878957c#126ccthVKibJ2wYnPMDpVuFq5R7xjY18yRYmtoghCSTB

**Comment by dhaavi** [comment]
Yup. We've seen that a couple of times.

The new network monitor version which is currently in progress will fully replace the system that does these calculations, so we're not going to start fixing this now. ;)
