### ISSUE TITLE
Support for interfaces in Rules

### ISSUE THREAD

**Issue by northys** [safing/portmaster#604]
**What would you like to add or change?**:

It's not safe to allow some subnets (https://github.com/safing/portmaster/issues/594#issuecomment-1096350412) but it would be great if I could allow all traffic from `tailscale0`.

Also it's not good idea to allow traffic from 10.0.0.0/8 or part of it because it can conflict with train/office/hotel networks and it would be much better to allow wireguard / openvpn interfaces.

**Why do you and others need this?**:

Security ^_^

**Comment by dhaavi** [comment]
That's a great idea!

I'm not sure there is a good way to do that though. We don't get that information from the packets.
Might need a good chunk of work on the system integration.

Another way that is maybe easier (and more versatile?):
The successor of the network rating levels will most likely be based on layering settings on top of each other.
You could then have different setting layers for different environments, with the base layer being most restricted.
When you figured our your environment, you can then enable the layer for that environment to grant certain permissions.

**Comment by northys** [comment]
> I'm not sure there is a good way to do that though. We don't get that information from the packets.

You often talk about `packets` while I would expect that portmaster sits on higher level in theoretical ISO/OSI model than `iptables`, doesn't it? I would expect that either portmaster can do the same as `iptables` or it can't do many things that `iptables` is capable of. `iptables` is definitely capable of allowing traffic from interface so maybe portmaster could utilize that?

There are two problems I see in this solution
1) it's pretty nasty that portmaster modifies iptables to do something while it handles most of the things itself
2) portmaster won't know that something is blocked if it gets blocked by iptables rules portmaster added itself

---

Ad layers:
a) Do you mean layers like docker layers? That every layer above the base one inherits all settings all rules / configuration from all layers below it?
b) Do you mean layers like configuration parts which are tagged like "work", "home", "others and which are used when environment "work", "home" or "others" is used?

You said `layering settings on top of each other` which looks like a) but that feels like too much complexity for me and I would prefer b) one. It's always easy to get lost in layered / inherited settings. Now there are "2 layers" - global and app - and it can be already confusing for newbie users.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
