### ISSUE TITLE
Support for rules per SSID

### ISSUE THREAD

**Issue by northys** [safing/portmaster#605]
**What would you like to add or change?**:

Follow up to suggestion https://github.com/safing/portmaster/issues/604

I would love to allow incomming traffic only when I'm connected to home network.

I don't know if there is better identification than SSID. Also I don't know if it's possible to identify ethernet connection by some ID but it would be nice to allow 192.168.x.0/24 only for home network. This is widely used subnet by most of home networks and I don't want to be reachable when I'm connected to any network outside my own.

I'm aware that there is some kind of network rating feature but I didn't get used to it and I don't know if it changes automatically somehow when I change network or if it's just matter of wider configuration.

**Why do you and others need this?**:

Security ^_^

**Comment by dhaavi** [comment]
I think this is a nicer idea than #604 - as it also easier to understand.

Also, building on the setting layering system outlined in #604 - Some layers could auto-activate when the router has a matching IP and MAC address pair.

I kinda like this approach - what do you think?

**Comment by northys** [comment]
> I kinda like this approach - what do you think?

That's exactly what I imagined and did not describe well!

When I wrote the original post I though about simple dropdown select between Allow/Deny and input for rule (image below) in the UI with default of `All the time` where I could select `When connected to northys-home-ap`. I think we mean the same thing.

![Screenshot from 2022-04-27 13-43-32](https://user-images.githubusercontent.com/2878126/165511043-0453b802-ecd4-4a04-bc60-573baccf6d56.png)

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
