### ISSUE TITLE
REQUEST: Own blocked-list + Wildcards/Regexps

### ISSUE THREAD

**Issue by EstherMoellman** [safing/portmaster#606]
**What would you like to add or change?**:

Own customized blocked-list + Wildcards/RegExps working in the own customized blocked-list.

**Why do you and others need this?**:

The so called "filter lists" can block web garbage. However, even the best "filter list", unfortunately, normally has lot of wrong data, hurting device performance or breaking webpages. It was already proven that "filter lists" are not the most efficient approach to fight web garbage.

I'm a long time [DNSCrypt](https://dnscrypt.info/) user. This software is very lightweight, it doesn't hurt performance, and more important for me, it allows the use of own customized blocked-list with wildcards. In simple words, for example, you can use (asterisk ads) or (asterisk  ads asterisk ) or (ads asterisk ) etc in the blocked-list, and everything inside the domain containing "**ads**"... will be blocked. Yeah, it's not perfect, in this example a domain containing "**download**" will be blocked, but is up to the user. The point is that the own blocked-list + wildcard/regexps allows the user to build a more efficient customized blocked-list. My own list is incredible small, it includes several wildcards/regexps, and it blocks 70% of the webgarbage almost without breaking good stuff.

Of course, DNSCrypt is not a firewall. And that's the reason I'm requesting this feature for Portmaster.

I apologize in advance if my request already exists in Portmaster.
I'm a Portmaster newbie user, Portmaster has lot of settings (which I love), and takes time to learn all the Portmaster controls.

I take the opportunity to thank and to congrats you, because Portmaster is amazing.
I'm becoming a Portmaster fangirl... spreading the word : )

**Comment by dhaavi** [comment]
Hey @EstherMoellman, thanks a lot for the great suggestion and for spreading the word!

You can configure custom rules with the [Outgoing Rules](https://docs.safing.io/portmaster/settings#filter/endpoints).
They don't support regex (yet?), but there is support for wildcard at the start and end.

We have come to the conclusion that our current rule engine has reached its limits and we are in the process of designing a new engine. But it will take some time until we have the resources to implement it - as it will cover quite some complexity.

We are also working on a way to import your custom filter list - albeit without support for wildcards/regex.

Can you share some of your regex rules, so we get an idea how you are using them?

**Comment by EstherMoellman** [comment]
@dhaavi thanks a lot for your replay.

Yeah, I already know about the PortMaster rules alternative. But based on my ignorance, AFAIK, these PortMaster rules must be written one by one, which is not the end of the world, but that task adds lot of work (considering that PortMaster already needs several other configurations). A rule is great when you need to control an app or software or port or single element etc. But for a customized filter-list, rules written one by one... hummmmm : )

> We are also working on a way to import your custom filter list - albeit without support for wildcards/regex.

Bingo! : ) ... now we're talking .
My request/suggestion was more related to this kind of alternative, allowing users to import their own customized filter-list, which (quoting you)  in first-stage might work with wildcards, and in a second-stage with regexps.

> Can you share some of your regex rules, so we get an idea how you are using them?

Some of my wildcards: https://pastebin.com/uCEAhQGs

Some of my RegExps: https://pastebin.com/uVUj04EQ

Both working together can clean lot of webgarbage, without zero visible computer performance impact. In fact is quiet the opposite, both working together can improve computer performance (less CPU, faster browsing etc). Important to mention that you'll see some redundant expressions in both lists, but that is because sometimes I need to use them separately.
I have another wildcard/regexp lists which can block 99% of webgarbage... but at the cost of performance. So, this subject of wildcard/regexp lists depends a lot on each user. My priority definitely is performance, so I use very small wildcard/regexp lists.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
