### ISSUE TITLE
Request: An allow list of websites.

### ISSUE THREAD

**Issue by Z3r0ut** [safing/portmaster#607]
If an website is blocked that i know its save or i want to go on anyway, i want to exclude it from portmaster.

(If there is already such a feature, then sorry. In this case please say how i do it. cause i searched in the program and the docs but i didnt find a allow list or something)

**Comment by Z3r0ut** [comment]
Okey, i was just dump. I put in the whole address, including https and stuff, and cause that didnt work i thought this wasnt an allow list. I removed the https stuff from the domain and now it works. Thanks.

**Comment by northys** [comment]
there is usually a little i (stands for info) next to each configuration option. it usually gives you a hint when you are not sure about what to put in there or what should it do exactly.
