### ISSUE TITLE
"Ignore System/Network Servers" and "Enforce Secure DNS" needs to be disabled for internet to work.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#614]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
Hey @Rexadev, thanks for this issue.

In light of your other issues, I would assume that this might have to do with your setup.
We cannot reproduce and have no other errors on this.

The Portmaster works fine with both settings enabled.
Also, please include the debug info, as we don't know what is going on without it.
