### ISSUE TITLE
Add port blocking

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#615]
**What would you like to add or change?**:

Add port blocking

**Why do you and others need this?**:

Add port blocking

**Comment by northys** [comment]
you can block ports already using rules

https://docs.safing.io/portmaster/settings#filter/endpoints
https://docs.safing.io/portmaster/settings#filter/serviceEndpoints

**Comment by Rexadev** [comment]
@northys I meant on per app basis

**Comment by northys** [comment]
> @northys I meant on per app basis

You can do the same in app detail page. There is one global configuration and special configuration for each detected application.

I'm not at my laptop right now but I can send you some screenshots.

**Comment by northys** [comment]
Click on App -> Open App Page button -> Settings tab -> Rules

https://user-images.githubusercontent.com/2878126/164978799-a5ad1929-6f5f-4dd3-b3bd-c9274adb69ca.mp4

**Comment by dhaavi** [comment]
Hey @Rexadev thanks for the issue and thanks @northys for chiming in here.

Have you found what you were looking for @Rexadev?

**Comment by ppacher** [comment]
Hi @Rexadev, that's intended as the [default action](https://docs.safing.io/portmaster/settings#filter/defaultAction) is there to decide for connections that have not been blocked or allowed by some other setting.
Please checkout the docs for more information on available settings and what they do.

I'll close this issue as the original problem seems to be resolved. If you have any further issues feel free to open a new one.

**Comment by northys** [comment]
I havent tested it but maybe you can add block `*` to block list and `443/TCP` to allow list?
