### ISSUE TITLE
No internet connectivity without first restarting Portmaster with NordVPN

### ISSUE THREAD

**Issue by safinguser** [safing/portmaster#618]
**What happened**:
Portmaster is running from startup and I have internet connection.  I connect to NordVPN (Nordlynx, all features off except for DNS set to 127.0.0.1) and I immediately lose connectivity.  I shut down portmaster and start it up again, having to input my password to run the portmaster core service, I go to the settings tab and click the restart button.  All of this is done while still connected to NordVPN.  All of a sudden my connection is back and i can reach websites in firefox. 

**What did you expect to happen?**:
I expect my connection to not drop and require a full portmaster restart when connecting to NordVPN.

**How did you reproduce it?**:
Reproduced multiple times in this order:
Reboot PC
Portmaster runs automatically on startup
Connect to NordVPN
Shut down portmaster
Start portmaster
Click restart in portmaster settings page

**Debug Information**:
[Portmaster debug information before.txt](https://github.com/safing/portmaster/files/8546079/Portmaster.debug.information.before.txt)
[Portmaster debug information after.txt](https://github.com/safing/portmaster/files/8546080/Portmaster.debug.information.after.txt)

-->

**Comment by dhaavi** [comment]
Hey there, thanks for reporting this!

It seesms that some other process is listening locally on port 53 - blocking the Portmaster from starting correctly. This is in the "after" debug info, so not sure what happened here.

Are you running another software that handles DNS?

**Comment by safinguser** [comment]
> It seems that some other process is listening locally on port 53 - blocking the Portmaster from starting correctly. This is in the "after" debug info, so not sure what happened here.
> 
> Are you running another software that handles DNS?

No, i do not run any other software that should handle DNS.  I run a fresh popos install with only firefox, nordvpn, and portmaster so far.  I should also note that the issue/result is the exact same regardless if I enable or disable the built in NordVPN DNS feature.

**Comment by dhaavi** [comment]
Also see issue https://github.com/safing/portmaster/issues/643.
