### ISSUE TITLE
Failed to create issue: Suggesting Improvement via app.

### ISSUE THREAD

**Issue by Bilibox** [safing/portmaster#619]
**What happened**:

Failed to create issue
Invalid preset suggest-feature.md

**What did you expect to happen?**:
It should create the issue.

**How did you reproduce it?**:

Go to "suggest an improvement" for the "User Interface" and click "create on github", choose either option

**Comment by ppacher** [comment]
Hi, AFAIK this should already be resolved. I'll close this issue now. If it still happens feel free to re-open it

**Comment by starbock** [comment]
I was about to create a new issue and found this one.  It's still happening. 

![image](https://user-images.githubusercontent.com/16008913/194737045-a63aa540-8886-4f2a-8d56-74aba0b38f78.png)
