### ISSUE TITLE
tracker list

### ISSUE THREAD

**Issue by Frostedfox** [safing/portmaster#621]
Is it possible to add the auto updating [tracker list](https://github.com/duckduckgo/tracker-radar) from duckduckgo?

it contains the most common cross-site trackers and includes detailed information about their tracking behavior, including prevalence, ownership, fingerprinting behavior, cookie behavior, privacy policy, rules for specific resources (with exceptions for site breakage), and performance data <https://spreadprivacy.com/duckduckgo-tracker-radar/>

**Comment by dhaavi** [comment]
Hey @Frostedfox, thanks for the suggestion!

What would you want to do with it?
It explicitly states: `This is not a block list`.

**Comment by Frostedfox** [comment]
yeah, But they mentioned the exact opposite in their [blog post](https://spreadprivacy.com/duckduckgo-tracker-radar/)

![duck](https://user-images.githubusercontent.com/84601232/165372663-861ccd8f-a43b-4853-a6f8-54a3abb90d14.jpg)

this is the same tracker list used in [android app tracking protection](https://www.theverge.com/2021/11/20/22793068/duckduckgo-tool-prevent-apps-tracking-android-users) the alternative to apple's app tracking transparency

it would be awesome to apply this tracker block list system wide
