### ISSUE TITLE
Portmaster keeps trying connect using "one.one.one.one" (see in DNS logs) and doesn't use DNS DoT specified

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#623]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by itsnotsaved** [comment]
>Portmaster keeps trying connect using "one.one.one.one"

I saw that. I installed this software 5 days ago.
![image](https://user-images.githubusercontent.com/73447325/165029673-36884135-02ec-40d3-b0c2-bed1cc264ef5.png)
![image](https://user-images.githubusercontent.com/73447325/165029744-c5662ca9-48a0-4093-9106-f85780ea11a6.png)

**Comment by Rexadev** [comment]
@itsnotsaved What are those screenshots of?

**Comment by Rexadev** [comment]
@dhaavi why not just use the DoT dns specified by the user.

**Comment by itsnotsaved** [comment]
>What are those screenshots of?

DNS server logs. there're many softwares. CoreDNS, Pihole, ADH, PowerDNS, Technitium DNS, and more (or some facilities bundled softwares similar Keexybox, Quidsup notrack)

**Comment by itsnotsaved** [comment]
>The domains one.one.one.one. and dns-check.safing.io. are resolved using the system assigned resolver in order to check connectivity. No connection is initiated.

@dhaavi Does that need to check every few seconds? one time not enough?

**Comment by dhaavi** [comment]
We've released a fix for this in Portmaster v0.8.13 ([changelog](https://github.com/safing/portmaster/releases/tag/v0.8.13)), which is currently in the [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel).

Please update to this version and check if it resolves the issue.

**Comment by Rexadev** [comment]
Solved
