### ISSUE TITLE
[Feature Request] On 1st connection by program, Ask if it should be allowed/blocked/prompt.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#624]
### There can be 3 options - 

1. allow by default (or use default settings current UX) 
2. **ask every time**
3. Block

### There can be modes like - 

1. paranoid everything is asked,
2. normal non-whitlisted programs are asked,
3. monitoring mode everything is set to allow,
4. Block All

Similar feature but for zones - https://github.com/safing/portmaster/issues/626

@davegson might want to also see https://github.com/safing/portmaster/issues/741 and https://github.com/safing/portmaster/issues/626

**Comment by youdontneedtoknow22** [comment]
I'm not the dev but:
This is already what's being done when you set the default behavior to (Prompt) instead of (Allow). Do you want to make (Prompt) the default choice for Portmaster? I don't think that most common firewalls do that. (I can say for Comodo Firewall and Zonealarm that that's not the case and it's not the case for Linux's firewall. Once enabled, it blocks all incoming connections and allow outgoing connections, which is also the default for Portmaster)

**Comment by p2anav** [comment]
This is probably a good idea if you want to have more control over all your apps, but as I can imagine, most people won't like a UX in which you get multiple notifications from the Portmaster as soon as you install it. Moreover, this may break some important apps if you click *Don't Allow* for an app that you don't understand what it does (Like a system app). What do you think @davegson?

**Comment by Rexadev** [comment]
@p2anav UX, There can be 2 options allow by default (or use default settings current UX) and ask everytime

**Comment by p2anav** [comment]
I will let @dhaavi answer.

**Comment by davegson** [comment]
thanks for the suggestion - I do like the overall idea. Similarly to #538, we will look into this when we iterate the prompting system. Probably some time off until then - until then I hope prompt mode serves you well.

**Comment by Rexadev** [comment]
@davegson might want to also see https://github.com/safing/portmaster/issues/741

**Comment by Rexadev** [comment]
@dhaavi reconsider its priority please

**Comment by ppacher** [comment]
Hi @Rexadev, thanks for going over your issues again but we're a rather small team working on the portmaster and the SPN and posting a "please reconsider priority" to all your issue/feature/bug requests does not speed up things. Rather the opposite is the case as we need to go through the messages and check if there is anything important. If you want to help out please take some time and refine some of your issues so it's more clear whats up there, maybe add debug logs. This way other users might better find and upvote them. Thanks

**Comment by Raphty** [comment]
Prompting is one of the areas that we will tackle in the future, we usually work our way through feature sets, and this will be taken into consideration when we tackle prompting again in the future.

Thanks for the input!

**Comment by steelowheel** [comment]
Hello. I know this is closed, but I'd love to know if there's any update about this feature request, please. Thanks!

**Comment by Raphty** [comment]
letting us know that you would like something even on a closed issue, is super ok.
The amount of traction feature requests have is something we take into consideration when deciding what to work on.

But the news is not great in this case: We are currently working on reworking the UI backend and Kext and then we will most likely tackle some other things before we go down this rout.
