### ISSUE TITLE
Add a Connection Log for dignosis. Also a stats dash board.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#629]
Make it easier to diagnosis bad config.

**Comment by dhaavi** [comment]
Hey @Rexadev, can you elaborate on the stats dash board? What exactly do would want to see in such a thing? How would that help you diagnose problems?

The connection log (global view of all connections) will be part of the upcoming revamp of the Network Monitor page.

**Comment by Rexadev** [comment]
@dhaavi please reopen this
