### ISSUE TITLE
Can't get completions without a data dir

### ISSUE THREAD

**Issue by james-callahan** [safing/portmaster#630]
**What happened**:

Run `portmaster-start completion bash`
Get error:
```
Error: please set the data directory using --data=/path/to/data/dir
```

**What did you expect to happen?**:

Bash completions to be spat out

**Comment by james-callahan** [comment]
Working around this via a `portmaster-start --data dummy-path completion bash` the completion script seems to not work.

Inside of the completion script it runs `portmaster-start __complete` which seems to fail with the same 
```
Error: please set the data directory using --data=/path/to/data/dir
```

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
