### ISSUE TITLE
"Change Default" on the App Settings should take user to the default network action for the App

### ISSUE THREAD

**Issue by youdontneedtoknow22** [safing/portmaster#634]
**What would you like to add or change?**:

When clicking on "Change Default" for a specific app (Screenshot1) that got a prompt, Portmaster shows the "Connections" tab to this app (Screenshot2). It should actually show the "Settings" tab with highlighting the "default network action" for it. (Screenshot3) 

SS1: 
![grafik](https://user-images.githubusercontent.com/85135068/166125615-b7a5c38a-b7eb-4b57-ac81-0c3230366cfd.png)
SS2:
![grafik](https://user-images.githubusercontent.com/85135068/166125623-4837e207-4665-4e0b-ba01-a45b580ee0f9.png)
SS3 (it should be prompt tho, I already changed it to allowed):
![grafik](https://user-images.githubusercontent.com/85135068/166125631-a86095d4-0a5c-49c1-8f56-d4b3418912c4.png)

**Why do you and others need this?**:

It makes life easier when your default action is prompt and you need to allow specific apps that keep asking for permission to connect (like browsers). Also, this is what I understand with (Change default), that it would take me to the place where I can change the default behavior for this app.

**Comment by p2anav** [comment]
Yeah, that's counterintuitive. It also scrolls to "default network action" when you click on "change default" and then "settings". So, this might as well be a bug. Thanks for the input. I will pass it on to the team.
