### ISSUE TITLE
create a custom profile (next to allow, block and prompt)

### ISSUE THREAD

**Issue by youdontneedtoknow22** [safing/portmaster#635]
**What would you like to add or change?**:

So when using prompt, I tend to allow all connections from my browsers and some messaging apps like discord (for the sake of convenience). However, there are cases where I want to get back to a default prompt profile (where every application would ask for permissions before connecting). This would be hard to do without losing all the configurations I already did to my custom prompt profile.
It would be nice if we could create a custom profile (based on prompt but with configurations for specific apps from the user). With this, user can change between default prompt (which asks for permissions for all apps) and customized prompt (with the specific rules for apps done by the user)

**Why do you and others need this?**:

One of the reasons I'm using a firewall is in case I downloaded a trojan. Trojans inject themselves into known processes (for example svchost.exe or firefox.exe) and connect to the host (hacker in this case). My assumption would be that Portmaster won't be able to detect this, if I already allowed all outgoing connections for firefox. So when downloading a suspicious app, I would want to get back to prompt for all apps (because I don't know which specific process is being injected by the trojan) to check it. If it passed the test, I would want to go back to my custom profile where I allow all browsers and messaging apps.

**Comment by dhaavi** [comment]
Hey @youdontneedtoknow22, thanks for this suggestion and for explaining your use case! This is very helpful for us.

This is something we will be able tackle when we revamp our current threat modeling system.
I have tagged your idea there.

We are tracking this internally at CC#2338

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
