### ISSUE TITLE
Clicking on the notification should open Portmaster

### ISSUE THREAD

**Issue by youdontneedtoknow22** [safing/portmaster#638]
**What would you like to add or change?**:

When you get a notification, I tend to click on it to be able to open Portmaster (and check some details about the connection, or change default behavior for this app). However, clicking on the notification doesn't open portmaster and does pretty much nothing.
![grafik](https://user-images.githubusercontent.com/85135068/166149478-1b36bac2-9a88-4070-a31d-8f0558c419bc.png)

**Why do you and others need this?**:

It's faster than checking the tray icon, clicking on it and then clicking Open Portmaster.
This is how notifications also work for all apps (let's say you got a notification from Discord. When clicking on it, you go to discord).

**Comment by p2anav** [comment]
> This is how notifications also work for all apps

Thanks for the suggestion. Will pass this on to @dhaavi
