### ISSUE TITLE
Right clikcing on the tray icon should open Portmaster directly

### ISSUE THREAD

**Issue by youdontneedtoknow22** [safing/portmaster#639]
**What would you like to add or change?**:

On many apps (or all popular ones?), right clicking on the tray icon opens options or settings for this app. This is working for Portmaster.

However, left clicking should open Portmaster directly, without having this panel where you explicitly choose (Open App).
**Why do you and others need this?**:

It's a habit and it's way more faster for users who need to adjust their rules every couple of minutes (after downloading Portmaster where you still have a lot of apps that are asking for connection permission)

**Comment by dhaavi** [comment]
Hey @youdontneedtoknow22, thanks for the suggestion!

That sounds like a nice thing. Unfortunately, the library we use for the tray icon does not support custom click handlers on the icon itself.
This means that this is a bit more effort than anticipated.
I will however add it to the backlog, so we can look into it at a later.

**Comment by Marc05** [comment]
I think the opposite is better by default - open on left-click, settings on right-click. This follows the general navigation design, and personally I've seen that open-on-right-click is the exception to the rule rather than the norm.

**Comment by youdontneedtoknow22** [comment]
> I think the opposite is better by default - open on left-click, settings on right-click. This follows the general navigation design, and personally I've seen that open-on-right-click is the exception to the rule rather than the norm.

I actually think I messed up my whole feature-request.
That's exactly the expected behavior. I suppose that right-clicking doesn't open the menu right? That was my problem with Portmaster (I deleted it shot after this feature request)

**Comment by Marc05** [comment]
It opens a menu on both left/right-click. I've just started using it myself and have been mostly happy with it - at least I haven't found anything as polished as this that is open source (I'd be using simplewall otherwise).

**Comment by youdontneedtoknow22** [comment]
> It opens a menu on both left/right-click. I've just started using it myself and have been mostly happy with it - at least I haven't found anything as polished as this that is open source (I'd be using simplewall otherwise).

I just updated my feature request, thank you.
I actually think it's better to do what most apps do, which you explained in your comment. Right Clicking for options, left clicking to open directly.
