### ISSUE TITLE
Feature Request: Notes

### ISSUE THREAD

**Issue by bigolbooty** [safing/portmaster#640]
(Copied and pasted from reddit thread)

I love picking out domains safing shows accessed my computer, researching where they go, and then blocking the shit out of the ones I don't want.  

What I've noticed is a lot of domains that interact with my network have essentially gibberish names that I can't easily note or remember. I do my research (been using [https://otx.alienvault.com](https://otx.alienvault.com), would love anyone elses resources for researching domains), and sometimes I choose to leave it alone. But I don't have any method to easily recognize it again and will likely go and research the same domain name a week later, and waste that time.

I'd really love to be able to set manual flags for "I've approved this", change the color of line items for tags or something, or just have a plain text notes feature with a little icon on the domain showing me I've written a note about that one before.

Anything to mark off the concept that I've looked into this domain and I'm okay with it so I don't redo the work again. Or to even mark off that I did block this at one point and I broke some feature of another software.

**Comment by dhaavi** [comment]
Hey @bigolbooty, thanks for the nice suggestion!

I like this idea a lot. It fits perfectly into the concept of threat modeling.
I will bring this up with the team and see what they think.

However, just to be clear: This is something that will tie into a couple new systems and as such will take a while until we will be able to something like this. Just so set the expectations right here. ;)

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
