### ISSUE TITLE
Add Portmaster API authentication bypass/extensions settings

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster#65]
_Status: This is an idea and not currently planned. Please comment to tell us how and why you would use this feature so we know how much it is needed and how it would be applied._

**What would you like to be added**:

Add settings to the Portmaster Core that allow for bypassing/extending the API authentication.

For example, we could have a setting where you can add paths of executables that are also allowed to access the api. This could also support wildcards. 

**Why is this needed**:

In order to deploy 3rd party software that uses the Portmaster API, or if a user just wants to use the UI in their browser instead.

**Comment by ppacher** [comment]
I'd prefer some kind of **token based authentication** for the API endpoint. So one can create a new access token using the Portmaster UI (or an upcoming cli) and use that token to connect to the API from remote. That would allow a huge range features and tooling to be built around the Portmaster (like a central management UI for all your Portmaster-secured machines).

**Comment by dhaavi** [comment]
I like the idea for local authentication. The Portmaster API already issues tokens to authenticated processes in order to speed up authentication of whole batches of requests.

Instead of just using tokens, I'd rather add binary paths to an "allow list", so that we don't have to add protection against stolen tokens.

Regarding central management: This would probably best be handled by the identity system that will be introduced later with the SPN.

**Comment by dhaavi** [comment]
API Keys were added to the authentication system during the implementation of the API Endpoint Framework a while ago.
