### ISSUE TITLE
Can Portmaster use system DNS server and throttle its internet connectivity checks?

### ISSUE THREAD

**Issue by working-name** [safing/portmaster#650]
**What would you like to add or change?**:

I would like Portmaster to use what was set up in its settings to detect if there's internet connectivity. Right now, if I'm not mistaken, you're doing a DNS query to resolve Cloudflare's one.one.one.one and dns-check.safing.io which should return something like 0.65.67.75. 

I've added a local/fake DNS record in pihole for dns-check.safing.io but Portmaster does not seem to care, which makes me think it's not asking my configured DNS server, it's probably asking Cloudflare.

Is it necessary to hardcode one.one.one.one and dns-check.safing.io for connectivity checks? And if so, why not use the system's resolver? Furthermore, can we throttle the checks to maybe 1/5 seconds or so? I doubt it's that critical to figure out if connectivity is up every 250 - 333 milliseconds.

**Why do you and others need this?**:

So I can breathe, and tail my dns' logfile without feeling like I'm running a 100 computer internet cafe in eastern europe😆 

I was tailing the pihole log to figure out if it was blocking a specific site or it was really down, and could not follow it because Portmaster is slamming the DNS resolver with queries for one.one.one.one and dns-check.safing.io. I have 3 machines that currently use Portmaster, all windows machines, and the log goes by so fast I can't find what I need without grepping.

To put it into perspective: last month there were 488,530 requests to resolve one.one.one.one. Divided by 3, that 162,843 requests per station, 5,428 requests per day, 226 requests per hour, which is almost 4 requests per second. If I block one.one.one.one in pihole, Portmaster says it can't detect a connection. Roughly 15% of all household DNS queries are for one.one.one.one.

**Comment by dhaavi** [comment]
> I would like Portmaster to use what was set up in its settings to detect if there's internet connectivity. Right now, if I'm not mistaken, you're doing a DNS query to resolve Cloudflare's one.one.one.one and dns-check.safing.io which should return something like 0.65.67.75.

Yes, we currently use these two domains and queries them using the resolvers from the OS.

> I've added a local/fake DNS record in pihole for dns-check.safing.io but Portmaster does not seem to care, which makes me think it's not asking my configured DNS server, it's probably asking Cloudflare.

It should be querying them using the resolvers from the OS.

> Is it necessary to hardcode one.one.one.one and dns-check.safing.io for connectivity checks? And if so, why not use the system's resolver? Furthermore, can we throttle the checks to maybe 1/5 seconds or so? I doubt it's that critical to figure out if connectivity is up every 250 - 333 milliseconds.

Well, the thing is that the resolver is successfully querying other domains and hinting at the online status system to re-check. Your special handling of the two check domains fails, so it ends up in a loop.

I understand that this fills up the logs. I hoped that it would not, but did not think about someone blocking these domains.

Anyway, I made a couple improvements to the whole system, which will be in the next version (v0.8.13+).
With that version, we will only use `online-check.safing.io` and resolve it via the configured resolvers. If the Portmaster is connected to a DNS resolver already, it will not query any domain anymore. Also, it will be _way_ more lax when it comes to checking the result. I will accept almost anything now, except for an obvious error.

This should calm things down significantly.

Reference for future readers, also see issue #623.

**Comment by dhaavi** [comment]
We've released a fix for this in Portmaster v0.8.13 ([changelog](https://github.com/safing/portmaster/releases/tag/v0.8.13)), which is currently in the [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel).

Please update to this version and check if it resolves the issue.
