### ISSUE TITLE
query was blocked: no compliant resolvers for this query

### ISSUE THREAD

**Issue by wallart1** [safing/portmaster#652]
Have set up Samba on another (linux) computer in order to share some directories. On the (linux) computer where this occurs, I am unable to access the shared directory. In attempting to debug the issue, I see this in Portmaster. I see a blocked DNS query even though I have "Allowed Domain" for it

I'm wondering whether anything abnormal is going on here.   Thanks! 

![Screenshot from 2022-05-15 16-30-42](https://user-images.githubusercontent.com/84820338/168492669-a07bdbc2-785f-4129-bcdb-41080e01c1db.png)
![Screenshot from 2022-05-15 15-49-43](https://user-images.githubusercontent.com/84820338/168491307-633e7a7f-25a4-4ee2-8c98-1e1e7b52010f.png)
![Screenshot from 2022-05-15 15-53-06](https://user-images.githubusercontent.com/84820338/168491882-7cc5383d-cbac-4536-91ca-c24c7db78ac7.png)
[Debug information.zip](https://github.com/safing/portmaster/files/8695858/Debug.information.zip)
[System Information.zip](https://github.com/safing/portmaster/files/8695892/System.Information.zip)

**Comment by dhaavi** [comment]
Hey @wallart1, thanks for reporting this!

What domain/name are you using to access the share?
It seems Portmaster sees a query for `local`, which it then states it has no resolver for.

`.local` domains are resolved using a mDNS resolver. Have you disabled that via the [Ignore Multicast DNS](https://docs.safing.io/portmaster/settings#dns/noMulticastDNS) setting?

**Comment by dhaavi** [comment]
Hey @wallart1, thanks for reporting this!

What domain/name are you using to access the share?
It seems Portmaster sees a query for `local`, which it then states it has no resolver for.

`.local` domains are resolved using a mDNS resolver. Have you disabled that via the [Ignore Multicast DNS](https://docs.safing.io/portmaster/settings#dns/noMulticastDNS) setting?

**Comment by dhaavi** [comment]
Hey @wallart1, thanks for reporting this!

What domain/name are you using to access the share?
It seems Portmaster sees a query for `local`, which it then states it has no resolver for.

`.local` domains are resolved using a mDNS resolver. Have you disabled that via the [Ignore Multicast DNS](https://docs.safing.io/portmaster/settings#dns/noMulticastDNS) setting?

**Comment by wallart1** [comment]
Thanks for the reply, Daniel. Yes, I was attempting to use the .local domain not realizing that it has a connection to Multicast DNS. I had been blocking UDP port 5353 thinking that it might open a security hole from other systems on my network (IoT things that I don't really trust). I opened up this port on both systems and, after opening up a couple of other ports, it is working well now.
