### ISSUE TITLE
Company OpenVPN doesn't work when portmaster is running

### ISSUE THREAD

**Issue by northys** [safing/portmaster#654]
**What worked?**

OpenVPN which is use to access company's private subnet.

**What did not work?**

I couldn't connect to domains which resolves to private subnet. I enabled resolving of those domains by turning of enforce public/private split or whatever it is called... I still can't ping IPs on OpenVPN though...

EDIT: this one
![image](https://user-images.githubusercontent.com/2878126/168548920-d11e7f9c-e2fd-4013-9905-203c66873567.png)

**Debug Information**:

**I'M RUNNING UBUNTU AGAIN.**

https://support.safing.io/privatebin/?ee0ea3dd424b63c8#7LnDp9zYSG47iBYkRzTYnZZxujmuJsXyiKnLimPkpkBU

**Comment by dhaavi** [comment]
Hey @northys, what did the Portmaster say about these connections? Were you able to find them in the network monitor?

**Comment by northys** [comment]
I was able to see blocked requests before I've enabled resolving of private subnets from public DNS. IIRC I did not see the connections after I've managed the DNS to resolve it.

We use the L2 OpenVpn (I don't know if it's tun or tap, but I'm 100% sure it's the L2 one which doesn't work on Android).

I may install portmaster again to provide you more info when I get to mood of doing so but right now I can't afford to debug random network stuff in my new 9to5 job :(

**Comment by northys** [comment]
Sorry for not showing much but I'm too lazy to grayout company's domain. I can see it resolved to correct IP and it is green / allowed.

Firefox says: Unable to connect

Firefox can’t establish a connection to the server at grafana.xyz.com.

![image](https://user-images.githubusercontent.com/2878126/169757007-84513cfc-bb6c-4e54-84d2-caed9edb1973.png)

**Comment by northys** [comment]
Dafuq, it works after computer restart.

**Comment by northys** [comment]
I installed the portmaster again on monday around 10:00 ao so I did not install any updates if you didn't release anything that day.

**Comment by northys** [comment]
When I opened the issue the OpenBPN was managed by network manager gnome interface but about 4 days ago I switched to openvpn systemd service... But I dont think thats the case because that would work on monday after the install immediately.

**Comment by varunbpatil** [comment]
Hi @dhaavi , I have the same issue with my company openvpn. Private IP's are not resolved.
Looking at the network monitor, I see
```
Verdict: ReroutetoToNs
Reason: redirecting rogue dns query
```
How do I make this work on Linux?

**Comment by Raphty** [comment]
@varunbpatil can you send in the debug info for your issue if it still is an issue?
