### ISSUE TITLE
Limit Internet speed of specific programs

### ISSUE THREAD

**Issue by Z3r0ut** [safing/portmaster#663]
**What would you like to add or change?**:
Limit the speed of specific programs, for example limit a Webbrowser to max 1MB/s download

**Why do you and others need this?**:
I and others would need this for programs that use the Internet but do not have a speed limiter, for some reason.

**Comment by p2anav** [comment]
The Portmaster was not designed for this but we will surely think about it. Thanks for your suggestion I will pass to the team.

**Comment by itsnotsaved** [comment]
Duplicate of #382

**Comment by davegson** [comment]
closing as it's a duplicate - thanks @itsnotsaved
