### ISSUE TITLE
Make logs only available to root

### ISSUE THREAD

**Issue by arch-user-france1** [safing/portmaster#669]
**What would you like to add or change?**:
I suggest to only make the logs available to root or at least the sensitive information.

**Why do you and others need this?**:
**Because portmaster logs every connection made which is a security risk**

**Comment by dhaavi** [comment]
In the meantime you can also increase the [Log Level](https://docs.safing.io/portmaster/settings#core/log/level) to at least `warning`. Then connections won't be logged anymore.

**Comment by arch-user-france1** [comment]
> In the meantime you can also increase the [Log Level](https://docs.safing.io/portmaster/settings#core/log/level) to at least `warning`. Then connections won't be logged anymore.

I did that already. Thank you for looking into it.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
