### ISSUE TITLE
mullvad will not conneted 

### ISSUE THREAD

**Issue by kc8pdr205** [safing/portmaster#671]
I have portmaster installed on fedora 36 cinnamon And I using mullvad vpn after installing portmaster . I can not connect to any server . It keeps reconnect to any server . But after removing portmaster the vpn works just fine . I'm connected to my router hard wire . I have a i7 64 g ram 16tb drive

**Comment by p2anav** [comment]
Unfortunately Mullvad VPN is currently incompatible with the Portmaster on Linux. See https://docs.safing.io/portmaster/install/status/vpn-compatibility
