### ISSUE TITLE
Portmaster Core Service is not starting when I click on 'START CORE SERVICE'.

### ISSUE THREAD

**Issue by Zliced13** [safing/portmaster#673]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
Portmaster Core Service is not starting when I click on 'START CORE SERVICE'. 
![(portmaster-app_v0-2-3)I31537_06-01-2022](https://user-images.githubusercontent.com/101912712/171421768-474c8813-3f05-409c-b075-6a4cc5c64a98.gif)

**What did you expect to happen?**:
Portmaster should start normally when I click on 'START CORE SERVICE'. I have been using Portmaster for 5 months now, I had no issues with it until today.

**How did you reproduce it?**:
The video here shows how I reproduced it:
https://youtu.be/bYFnh870Q4E

**Debug Information**:

[logs.zip](https://github.com/safing/portmaster/files/8815770/logs.zip)

**Comment by KrisSchneider** [comment]
> When did this happen? Did you just boot or did you previously shut down Portmaster? Does a reboot start the core service correctly? Can you start the core service manually from the Windows service manager?
> 
> The logs you provided did not contain any logs from the core service.

>When did this happen? 

It happened today at 8:30 am (MST). 

>Did you just boot or did you previously shut down Portmaster?

I just booted Portmaster, after reinstalling it. I previously uninstalled Portmaster, restarted my computer. Then, I reinstalled it using the installer provided on your website (safing.io). 

>Does a reboot start the core service correctly?

**Comment by KrisSchneider** [comment]
I'm sorry if I'm not able to reply in a while. I'm currently in a business meeting which could take a lot of time. Furthermore, I might be able to reply after 1 hour and 30 mins from now.

**Comment by KrisSchneider** [comment]
I hope I don't have to run Portmaster like this in the future. I prefer the GUI more than this terminal.

**Comment by KrisSchneider** [comment]
Here is my portmaster folder, if you need more information. [Kris's Portmaster folder.zip](https://filen.io/d/60fbca3d-cadd-4806-9887-61b5097726cb#!V0B12CxU4SwxzXzaG4uYYNkiZ2ir01U0)

**Comment by KrisSchneider** [comment]
Hello, is this issue solved or I am still on wait?

**Comment by dhaavi** [comment]
> Here is my portmaster folder, if you need more information. [Kris's Portmaster folder.zip](https://filen.io/d/60fbca3d-cadd-4806-9887-61b5097726cb#!V0B12CxU4SwxzXzaG4uYYNkiZ2ir01U0)

Thanks! I tried to download, but it always stops at 68.94% for some reason.
Did you zip the *whole* folder? Please just share the logs dir - it's enough.
Also, please always delete the files after we got them, they can contain sensitive data.

Can you try to start the service from the Windows Service Manager and then send me log files from that one? Then I can look into why it won't start then run by Windows.

**Comment by MMZThumper** [comment]
I've been having this same issue but it was after installing it for the very first time. I contacted support via email and they suggested I give this post a read. I haven't tried running it from the Cmd line but I will give it a try probably tomorrow. I hope nobody minds me jumping into this thread!

**Comment by KrisSchneider** [comment]
I don't mind anyone jumping in this thread, just please keep it civil. Thats all.

**Comment by MMZThumper** [comment]
Most definitely! 👍🏻

**Comment by MMZThumper** [comment]
Alright. So, I was finally able to reinstall Portmaster and just like before, the app installed fine without any errors. I restarted and at first The Notifier was red but now it's turned green.  There was no desktop icon created during installation, so I had to search for it. I R-clicked on it and ran as admin. A few seconds later I received this Java error. After I closed it, the same screen popped up as before stating that Portmaster's Core Service wasn't running and when I click on "Start" nothing happens. I tried running the Cmd's that were suggested but that just resulted in some process starting and stopping repeatedly until I closed PowerShell. I'll attach screenshots of both errors if I can. I've tried all solutions posted in this thread and have no idea what I should do next. I don't want to create another problem report when the author of this post is experiencing the exact same issue I am. So, I thought it would be best that I join in here. Below is the info about Windows running on my laptop. If there is any other information you need, or if it is preferred that I create my own thread, please let me know. 

Edition	Windows 11 Home
Version	22H2
Installed on	‎5/‎17/‎2022
OS build	22621.1
Experience	Windows Feature Experience Pack 1000.22632.1000.0


![Screenshot 2022-06-13 203527](https://user-images.githubusercontent.com/98562828/173490395-6b8876bb-d862-490a-9c97-5fd61bc043cf.jpg)
![PwerShell Error](https://user-images.githubusercontent.com/98562828/173490813-bf336bd6-7c56-47a1-a324-2f6b7df273cb.jpg)

**Comment by KrisSchneider** [comment]
This issue is also happening on Windows 11? Wow. 
Also, sorry for not being able to reply for a few weeks. I have been focusing on college work for most of my time.

**Comment by dhaavi** [comment]
> @dhaavi were you able to successfully download the file?

Sadly, no. Were you able to upload it again?

> I restarted and at first The Notifier was red but now it's turned green.

If the notifier turns green, then everything should be in order.

> I R-clicked on it and ran as admin.

Running things as admin is not necessary for Portmaster (this was just the UI), and is also generally discouraged.
The only thing needing admin privileges is the system service, which gets them anyway.

> A few seconds later I received this Java[script] error.

This seems to an internal error of the UI. Interesting - also that it was gone on next start.

> After I closed it, the same screen popped up as before stating that Portmaster's Core Service wasn't running and when I click on "Start" nothing happens.

This hints at the Portmaster system service not having started correctly.

Looking at the output you posted I am not sure if this is the same problem - but it produces the same effect.
I'd leave both issues in here for now and let's see where we go from here.

Can you share the full log file from the core service? You can find the log files in `C:\ProgramData\Safing\Portmaster\logs\core`.
I'd recommend you upload it to a pastebin with a time or send us an email with it - if you do, please notify me here about it.

**Comment by KrisSchneider** [comment]
Hello, what's happening, any new updates to this issue?

**Comment by dhaavi** [comment]
Hey @KrisSchneider, I think you might have missed my comment posted just right before yours: https://github.com/safing/portmaster/issues/673#issuecomment-1161508921

**Comment by KrisSchneider** [comment]
Here you go @dhaavi, I uploaded the file to a different cloud storage this time. 
https://mega.nz/file/nGJTASqS#d73Um6YsuNPlbxYr2ezrs1aH0a4qOsrLSve9hhVIxR8

**Comment by KrisSchneider** [comment]
Sorry for the wait.

**Comment by KrisSchneider** [comment]
@dhaavi sorry I forgot that I was sharing something with you, here you 
https://mega.nz/file/nWJB0LKR#wOHm_beXsYCsrMLFMIZ9SzSFBeLuy6TfRTX3G-eSzes

**Comment by dhaavi** [comment]
Thanks for the tip from @aaronsvk in #498.

He found out that it was the disabled Windows Event Log system that was the problem for him.

I found the same in @KrisSchneider's logs (please delete them now):
```
failed to open eventlog: The RPC server is unavailable.
```

Can everyone here check if they have the Windows Event Log service enabled and running?

You can also test if this is the problem by executing:
```
C:\ProgramData\Safing\Portmaster\portmaster-start.exe core-service --data C:\ProgramData\Safing\Portmaster
```

This is the same as running Portmaster from the cmd, but it registers with the Windows Service Manager, and also logs to Windows Event Log - which seems to be the problem.

I will investigate if we can disable or ignore a missing Windows Event Log.

---

I also have a new idea about the issue with the javascript error about insufficient permissions:

It could be that an anti-virus system won't let you elevate privileges, leading the Portmaster UI to not even asking you about permissions, but failing directly.

**Comment by KrisSchneider** [comment]
Windows Event Log is running and enabled on my device:
![(mmc)y5N6n7_07-01-2022](https://user-images.githubusercontent.com/101912712/176979334-c23eb1a8-fb61-4408-9e2f-b29d2c5d2650.jpg)

**Comment by dhaavi** [comment]
@KrisSchneider: Interesting, can you try running:
`C:\ProgramData\Safing\Portmaster\portmaster-start.exe core-service --data C:\ProgramData\Safing\Portmaster`

**Comment by KrisSchneider** [comment]
@dhaavi, This is the output I got in my terminal:
![(WindowsTerminal)Z232W3_07-02-2022](https://user-images.githubusercontent.com/101912712/177022800-e93c57e3-6acf-450b-b574-29cb242328c5.jpg)
```powershell
[control] 2022/07/03 02:17:33 WARNING: portmaster-start is marked as a GUI application in order to get rid of the console window.
[control] 2022/07/03 02:17:33 WARNING: CTRL-C will immediately kill without clean shutdown.
[control] 2022/07/03 02:17:33 WARNING: running interactively, switching to debug execution (no real service).
PS C:\Users\krist> [control] 2022/07/03 02:17:33 disabling log output to stdout... bye!

```

**Comment by KrisSchneider** [comment]
The only antivirus I have on is windows defender.
![(explorer)-X6e9T1_07-07-2022](https://user-images.githubusercontent.com/101912712/177802469-39d8d4d7-55c6-489b-945b-1e4a334c3dc1.jpg)

**Comment by MMZThumper** [comment]
No. The only anti-virus I have installed is what came stock with Windows 11. I even went so far as to check just to be sure. Isn't there a log or something I can send you a copy of? Or how about this. We schedule a date and time and I give you remote access to my laptop. That way you can do whatever you need to figure out what the problem is instead of relying on me to give you information? Would that be a possibility?
________________________________

**Comment by MMZThumper** [comment]
Please excuse my inexperience but do I put this in the Run Dialog box? I ran the command by copy and pasting it and all it did was open a window with a flashing cursor. Then a Windows notification popped up. I’ve attached a screenshot of the window and the notification.

***@***.***



***@***.***

Shawn Edward-Roy Jannasch
1719 W. Glendale Ave
Apt# 2040
Phoenix, AZ 85021
(480)823-3563

**Comment by MMZThumper** [comment]
What exactly am I supposed to do with this folder? I’m sorry that I haven’t been replying to any of these emails. Almost all of them I had no idea I even had! I will try and keep an eye out and reply to them promptly!

Shawn Edward-Roy Jannasch
1719 W. Glendale Ave
Apt# 2040
Phoenix, AZ 85021
(480)823-3563

**Comment by Zliced13** [comment]
@dhaavi This issue is now solved. The latest version of portmaster solved this problem I had with it. It now works perfectly without anyproblems
