### ISSUE TITLE
Avast One

### ISSUE THREAD

**Issue by xlilxillx** [safing/portmaster#675]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

**What did not work?**
everything

**Debug Information**:

**Comment by p2anav** [comment]
Thanks for reporting this. We can work on a solution only with debug info. Can you submit that?
