### ISSUE TITLE
Filter Lists Appear to do Nothing

### ISSUE THREAD

**Issue by catwithbanana** [safing/portmaster#676]
**What happened**:
Filter lists don't appear to do anything. I check several lists, such as OISD, but domains that should be blocked are allowed and still show up in my DNS logs (via NextDNS, where they are blocked by OISD at that level).

**What did you expect to happen?**:
The filter lists should stop the specified domain requests from escaping the system.

**How did you reproduce it?**:
It happens 100% of the time. Disallowing internet access on a program-by-program basis works as expected, but filter lists do nothing.

I sent the debug files via the in-app bug reporter. I am using Portmaster in conjunction with Mullvad VPN.

**Comment by catwithbanana** [comment]
So even if the DNS requests are showing up in NextDNS' logs no data is actually being transmitted?

**Comment by dhaavi** [comment]
Yes, this is correct.

**Comment by catwithbanana** [comment]
Got it -- thanks
