### ISSUE TITLE
automatically reload connections

### ISSUE THREAD

**Issue by arch-user-france1** [safing/portmaster#679]
**What would you like to add or change?**:
It would be nice if there'd be an option to enable automatic reloading of all connections so we don't have to press the button all the time.
![image](https://user-images.githubusercontent.com/72965843/171921508-a9327b0e-2ae2-4504-b3c9-bf102d942c0c.png)

**Why do you and others need this?**:
It would be a qol (quality of life) improvement.

**Comment by p2anav** [comment]
Thanks for your suggestion.
