### ISSUE TITLE
Notifications not shown (Solus Budgie)

### ISSUE THREAD

**Issue by supernova874** [safing/portmaster#680]
delete previous version (after removing service etc.) and download a new and install it as the instructions say , i get this error :+1: 

tray: set to selected=AutoDetect active=AutoDetect icon=0 spn="" msg="Secure"
2022/06/06 17:13:51 systray error: failed to register our icon with the notifier watcher (maybe no tray is running?): The name org.kde.StatusNotifierWatcher was not provided by any .service files
220606 17:13:51.225 ifier/tray:276 ▶ INFO 007 [8x] tray: set to selected=AutoDetect active=Trusted icon=0 spn="disabled" msg="Secure"

the app starts by "portmaster-start app" command but notifier don't ...

**Comment by dhaavi** [comment]
Hey @supernova874, thanks for reporting this.

Can you tell you which Distro and DE you are using and their versions?

**Comment by supernova874** [comment]
I had some similar issues with Mailspring and i installed the snap version and now are gone , don't if that can help you...

**Comment by dhaavi** [comment]
This is really interesting that it would work without the snap version.

The `org.kde.StatusNotifierWatcher` is the namespace used for the app indicator icon. This has to be registered and provided by a system.
Do you know which component Budgie uses for this?

There is a FAQ entry regarding GNOME here: https://github.com/safing/portmaster-ui/issues/242
There is also a related issue here: https://github.com/safing/portmaster-ui/issues/240.

**Comment by supernova874** [comment]
After download and install anew i get this error when trying to run notifier:

/opt/safing/portmaster/portmaster-start notifier
Error: failed to exec lock: failed to evaluate path of existing process: lstat /app: no such file or directory

while portmaster-start app works
