### ISSUE TITLE
Blocked incoming connection -> Allow IP as incoming rule

### ISSUE THREAD

**Issue by NicolasGoeddel** [safing/portmaster#681]
**What would you like to add or change?**:
Most of the time Portmaster is blocking traffic to my system, e.g. rsyncd, apache, etc. When I click on the "Allow IP" button on the blocked connection it automatically adds the new rule to the outgoing rules section which makes no sense. Also the incoming rules are only visible in the advanced interface but I think this is still a very basic thing which everybody wants to see.

Here are two screenshots to help you better understand.
![grafik](https://user-images.githubusercontent.com/1520064/172216611-625553c2-2374-4b93-9bf0-8eb7d44d8529.png)

![grafik](https://user-images.githubusercontent.com/1520064/172216764-04a77ab7-e88f-49bf-b903-394c8c03700c.png)

It would also be cool if the port (873) would be also added to the rule.

**Why do you and others need this?**:
Because it makes a lot of things easier.

**Comment by p2anav** [comment]
Thanks for reporting. I will take a look.

**Comment by p2anav** [comment]
Yup, this a bug. @dhaavi please take a look.

**Comment by dhaavi** [comment]
Hey @NicolasGoeddel, thanks a lot for reporting!

We already have a fix in place, it will be released in the coming weeks.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
