### ISSUE TITLE
No incoming ssh connections

### ISSUE THREAD

**Issue by vvstubbs** [safing/portmaster#685]
### What happened?
I can no longer have incoming ssh connections. It is reply&#39;s connection refused. my normal firewall is set correct, and this behaviour only began after installing Portmaster.  This continues to happen even if I shut down Portmaster. This is a deal breaker for me, while I think what you are doing has merit I can not work without ssh in and out, while out is working i need in. So kindly how to uninstall  Portmaster 

### What did you expect to happen?
I expected the inbound ssh not to be refused

### How did you reproduce it?
Just try to connect 

### Additional information

**Debug-Info**: https://support.safing.io/privatebin/?ef2a99b7f050dbae#HjvkWDPdXRtgYSTG8P1TmpjKJ6gmD7c9dUHyRA4qCHMm

**Comment by dhaavi** [comment]
Hey @vvstubbs, thanks for reporting this!

For security reasons, Portmaster does not allow incoming connections by default.
After all, Portmaster is a firewall.

You can easily enable it for an application by opening it in the Portmaster UI and adding this to the [Incoming Rules](https://docs.safing.io/portmaster/settings#filter/serviceEndpoints): "Allow *"

If you'd rather uninstall, you can do so via your OS.
You can also find more help on our docs: https://docs.safing.io/
