### ISSUE TITLE
Show Network Noise Separately in Apps Dashboard

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#687]
![image](https://user-images.githubusercontent.com/62152714/172798383-610f2fa7-cc98-438f-8413-d07519893711.png)

and remove the block connection toggle and it's settings because it it not a app

**Comment by JS-E** [comment]
+1

**Comment by Rexadev** [comment]
@dhaavi Move this to UI

**Comment by ppacher** [comment]
What do you mean with "separately in Apps Dashboard"?

Also, Network Noise is still a profile that is applied to a certain set of connections and all profiles have the same settings.
