### ISSUE TITLE
My DNS logs show unencrypted DNS requests.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#691]
Maybe postmaster is not using DoT or postmaster is not being used for DNS, I have set DNS in Windows settings in adapter settings and Wi-Fi settings.

**Comment by p2anav** [comment]
> Maybe postmaster is not using DoT

Compare your settings with these - https://docs.safing.io/portmaster/guides/dns-configuration#dns-configuration-url-scheme

Where are you recording the logs?

**Comment by Rexadev** [comment]
My DNS format is right
What software to use DNS logs? I am using NextDNS
@p2anav

**Comment by p2anav** [comment]
Hmm, your queries shouldn't show 'unencrypted' if the DNS format is right. Are all DNS queries unencrypted or only some?

**Comment by Rexadev** [comment]
How to give you debug logs

**Comment by p2anav** [comment]
Below the settings icon - Click Help (?) - then Report a Bug - Scroll to the bottom and copy the debug logs

**Comment by Rexadev** [comment]
How to share log with postmaster team privately I don't want to put it on github for everyone to see it

**Comment by p2anav** [comment]
The same page also has an option to send the logs privately :)

**Comment by Rexadev** [comment]
Somehow it is working since around July 1st now, maybe it is because of v.8.13 (i dont know when 8.13 was released)

**Comment by dhaavi** [comment]
Thanks for reporting back!

We have changed some things regarding how we handle update checks. This likely has either fixed your situation or dramatically reduced it.

You can also read more about this in the "Leaks" section of the new FAQ: https://docs.safing.io/portmaster/faq#leaks
