### ISSUE TITLE
Network Noise is shown as allowed, but not responding to requests

### ISSUE THREAD

**Issue by JS-E** [safing/portmaster#693]
**What happened**:

Was testing a traceroute from my localserver (192.168.1.101) to my main pc (192.168.1.213 hostname:beast) and portmaster shows it as allowed but my server got no response from my pc. I also tried a ping and the same thing happened

**What did you expect to happen?**:

I expected portmaster to show it's allowed, and then show a traceroute return hop on my server.

**How did you reproduce it?**:

Sent a traceroute/ping from my server to my main pc

**Debug Information**:

![image](https://user-images.githubusercontent.com/33073990/173194373-27c24001-c69f-44fd-a8b4-553bc59002ff.png)

**Comment by dhaavi** [comment]
Hey @JS-E, thanks a lot for reporting this!

I've looked into it and found a bug where the direction of the connection was not registered correctly for "unsupported" protocols. This means that currently incoming ICMP connections would incorrectly show up in the "Unidentified App".

I've already fixed the bug and it will be in the next release.

**Comment by JS-E** [comment]
@dhaavi No problem at all, appreciate the response 😄 Great to hear it's in the next release, keep up the great work!

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
