### ISSUE TITLE
one.one.one.one => bypass prevention: blocked rogue connection to DNS resolver

### ISSUE THREAD

**Issue by northys** [safing/portmaster#695]
**What happened**:

I can't acces https://1.1.1.1 and https://one.one.one.one. Portmaster says `bypass prevention: blocked rogue connection to DNS resolver`

**What did you expect to happen?**:

It works

**How did you reproduce it?**:

Load mentioned urls.

**Debug Information**:

**Comment by p2anav** [comment]
I think they should be blocked as DNS can queries can also be resolved over https, thus bypassing DNS servers set in the PM. I will let @dhaavi take a look, just to be sure.

**Comment by dhaavi** [comment]
Yes, exactly.

But if you have manually disabled any secure DNS in the browser, then disabling Block Bypassing should be no problem.
