### ISSUE TITLE
Add Anti-Lockout Rules to Server Installs

### ISSUE THREAD

**Issue by OhMyMndy** [safing/portmaster#696]
Do not block all incoming connections by default, this makes sure that people who are remotely connected to the machine can still access it, instead of getting locked out.

This morning got locked out of two machines I remoted into (one through Citrix and one through TDP) after starting Portmaster.

At least having the option to start Portmaster with ports open to not lock yourself out would be great.

If this is a welcome change, I can maybe create a pull request for this feature later.

Also see, #685

**Comment by dhaavi** [comment]
Hey @OhMyMndy, thanks for the suggestion!

Currently, Portmaster is intended as a purely desktop focused application. We are exploring the server use cases, but without any priority. How we have done it until now is to configure initial settings on a local instance and then copy the `config.json` file to the server before installing.

I will talk with the team about how to improve this situation.
Tracking this internally at CC#2401.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
