### ISSUE TITLE
Option to choose automatic startup with OS boothing or not

### ISSUE THREAD

**Issue by Filbuntu** [safing/portmaster#710]
**What would you like to add or change?**:
With the command `sudo systemctl disable portmaster`, the core service does not start automatically upon startup but the app still starts up … Any way to stop it from automatically starting the app on booting the OS?

**Why do you and others need this?**:
I don't need to have portmaster run all the time. But I like to use it now and then to monitor network connections

Thanks for any help in this!

**Comment by dhaavi** [comment]
Hey @Filbuntu,

I think this is something you need to configure in your desktop environment. Can you check if it shows up in the "Startup Applications" app?

**Comment by Filbuntu** [comment]
Hey @dhaavi!
Thanks a lot for your response! 
Unfortunately there is no entry in the startup applications where I searched before. I checked again, no show.
I am on Ubuntu 20.04 LTS. Anywhere else to search for this configuration?

**Comment by dhaavi** [comment]
It might not show, because we have hidden the Notifier Desktop file, in order to reduce confusion about the multiple components. This seems to also affect the Startup Applications app.

However, you can just delete the symlink from `/etc/xdg/autostart/`.

**Comment by Filbuntu** [comment]
Deleting or moving the symlink /`portmaster_notifier.desktop` from `/etc/xdg/autostart/` did the trick! Thanks a lot!
