### ISSUE TITLE
DNS-over-QUIC support for DNS Server

### ISSUE THREAD

**Issue by AntoLiguori** [safing/portmaster#711]
**What would you like to add or change?:**
Support for DNS-over-QUIC. I've read about it in [this article](https://adguard.com/en/blog/dns-over-quic-official-standard.html) from the AdGuard Blog. I'm not an expert, but it seems something pretty nice to have, so I figured I'd suggest it.

**Why do you and others need this?:**
I'm quoting the article here:

> In short, here are the main advantages of DNS-over-QUIC:

> - It encrypts DNS traffic. Nobody except you can see what websites you visit.

> - QUIC is designed to solve the problem of "[head-of-line-blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking)", that is, it will work better in networks with a high packet loss rate (think mobile data in elevators or tunnels).

> - The QUIC standard supports the so-called "Connection Migration". When you're leaving home and your phone switches from Wi-Fi to mobile network, the QUIC connection, unlike other connections, doesn't drop. Unfortunately, it hasn't been implemented yet, but we hope the situation changes soon.

> - QUIC allows you to establish a network connection much faster. As with the "Connection Migration", it's especially useful when being on mobile. With DNS-over-QUIC implemented, the connection is established twice as fast as with DNS-over-TLS.

Also thank you guys for your work on The Portmaster, it's an amazing software and I look forward to keep using it and recommending it to other people.

**Comment by rdncNT** [comment]
I understand that it is not a priority, I was just curious about it. 

I appreciate your response, thanks again!

**Comment by bjwktcsnzh** [comment]
DoH and DoT is already BAN by GFW in China , but DoQ is not currently , 🥺👉👈

**Comment by thegreatGreenstar** [comment]
While DNS-over-QUIC (DoQ) isn't a major feature, it would still be useful for some reasons, eg making it easier to support DoQ with a firewall on Linux (Which would be useful especially for laptop users due to the improved "on-the-go" experience with Dns-Over-Quic). As such, I suggest considering future implementation however at a low priority. Per the previous sentence, I encourage removing the "completed" label. 
It might be a good idea to aim for a higher priority focus on this feature by around 2029 if not added by then. This timeline should allow ample time for migration and implementation. If it becomes obsolete by then, focus on it can be easily removed.

**Comment by thegreatGreenstar** [comment]
> While DNS-over-QUIC (DoQ) isn't a major feature, it would still be useful for some reasons, eg making it easier to support DoQ with a firewall on Linux (Which would be useful especially for laptop users due to the improved "on-the-go" experience with Dns-Over-Quic). As such, I suggest considering future implementation however at a low priority. Per the previous sentence, I encourage removing the "completed" label. It might be a good idea to aim for a higher priority focus on this feature by around 2029 if not added by then. This timeline should allow ample time for migration and implementation. If it becomes obsolete by then, focus on it can be easily removed.

From a *quic*k skim, DNS-Over-Quic appears to do a lot of what DNS-Over-TLS does, but possibly better, per "3.1.  Provide DNS Privacy" of https://datatracker.ietf.org/doc/rfc9250/ 
If I understand correctly it additionally seems that fallback to DNS-Over-TLS is allowed, so if/when implemented, there should be consideration for DoQ to become the recommended. (Especially if DoQ gains support for Encrypted ClientHello)
Something I also am curious about, though I don't know if it would be possible is how DoQ could be benefited by SPN.

If I am wrong on any of this, please correct me and I will attempt to revise any errors/excess.
