### ISSUE TITLE
Possible to run portmaster as network firewall ?

### ISSUE THREAD

**Issue by ddonindia** [safing/portmaster#713]
**What would you like to add or change?**:

I use Comodo firewall for my windows machine was looking for something similar for Linux and I found portmaster :).
It works really well and meets most of my expectations. 

**Why do you and others need this?**:
I am wondering if I can use portmaster as network firewall running on one machine or router on the network?

**Comment by p2anav** [comment]
It's possible but not recommended - See [Network Service](https://docs.safing.io/portmaster/settings#core/networkService)

**Comment by ddonindia** [comment]
There are not much details in that link. Is there any more detailed doc for the same?

**Comment by p2anav** [comment]
Unfortunately, no.

**Comment by dhaavi** [comment]
To shed a little more light into this:

While Portmaster can serve as a DNS server for the network, it cannot yet serve as a firewall - it does not yet handle any forwarded traffic.
There is some personal interest in this among the developers, so things for this will get done here or there, but don't expect anything fast or big.
