### ISSUE TITLE
Application routing / binding to interface

### ISSUE THREAD

**Issue by alexitx** [safing/portmaster#721]
Similar to #592, #353

**What would you like to add or change?**:
It would be great if Portmaster can route the traffic of individual applications, not just do monitoring and filtering. This is a huge pain to do on Windows and I'm not sure if it's even possible without third party tools.

OpenVPN and WireGuard can be set up to only route specific range of addresses through the tunnel and SOCKS proxies can only be used with applications that support it, but there is no higher level control of the traffic for arbitrary applications like most VPNs do with split tunneling.

Portmaster could offer multiple features such as socksifying an application to go through a specific SOCKS4/5 proxy or binding an application to a specific interface (OpenVPN TUN/TAP or WireGuard).

**Why do you and others need this?**:
Proxies and self hosted VPNs can be much more powerful that way as you have control over which applications are tunneled through a secure network and the applications that don't work well in those cases such as games are routed through the default network.

**Comment by dhaavi** [comment]
Hey @alexitx, thanks for this very interesting idea.

I really like the idea of being able to re-route applications to proxies.
As with #592, I am adding this to the backlog for later.

You haven't stated a specific use case, so what you are trying to do might be possible with the [SPN](https://safing.io/spn/), which allows to select a different set of countries per application - in the future possibly even per domain or IP.
You can also exclude connections from the SPN using any rule matching criteria: net, country, domain, IP, ...

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
