### ISSUE TITLE
Clicking on Invalid Rule Clears all Rules

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#723]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

Instead it should point what is invalid

**Comment by p2anav** [comment]
I checked and that is definitely a bug.

**Comment by davegson** [comment]
duplicate of #580
