### ISSUE TITLE
[@dhaavi Move to UI repo][Rule Engine] Show country name in bracket in Rules.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#724]
According to document it seems Postmaster accepts only https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2 but I tired random letters and numbers and it accepts it.
Portmaster show country name is bracket for easy management and to be sure the rule worked

Related https://github.com/safing/portmaster-ui/issues/304 @dhaavi

**Comment by dhaavi** [comment]
Hey @Rexadev, thanks, that is a good suggestion.

We will include this in the new rule engine, we will be building in the future.

**Comment by Rexadev** [comment]
Related https://github.com/safing/portmaster/issues/628 @dhaavi

**Comment by Rexadev** [comment]
@dhaavi Move this to UI repo Please

**Comment by Rexadev** [comment]
@dhaavi Move this to UI repo Please

**Comment by Rexadev** [comment]
@dhaavi Move this to UI repo Please

**Comment by dhaavi** [comment]
This will be part of the rule engine revamp - however we don't know yet when we will get to it.
