### ISSUE TITLE
Suggestion: Portmaster Android version

### ISSUE THREAD

**Issue by Z3r0ut** [safing/portmaster#725]
**What would you like to add or change?**:
I would like to use Portmaster on my Mobile device (android) too.
I dont care if it would need root or not. Im fine with either way.

**Why do you and others need this?**:
Well, to do everything this program on dekstop can on android.

**Comment by p2anav** [comment]
Hey, thanks for the suggestion. It's planned - https://docs.safing.io/portmaster/install/status/mobile#android. I am closing this issue, but feel free to reopen it if you have something to add :)

**Comment by Visual-Dawg** [comment]
I want to switch from Mullvad to safing once an Android app exists. Can the status be updated here? 
I subbed to the thread

**Comment by kreaninw** [comment]
Me too, I want to use this in place of my VPN, which will be expired soon.

**Comment by dhaavi** [comment]
Portmaster for Android is currently in Beta - starting with just the SPN feature, while other are still in development.

You can find the F-Droid repo here: https://updates.safing.io/fdroid/repo/index.html
We will likely be in the Google Play store some time in the future too.
