### ISSUE TITLE
Usage analytics

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#729]
Usage about
LAN and WAN data transfer on per app basis
show with sites, countries, protocols they connected to.

**Comment by dhaavi** [comment]
What do you mean with "data transfers"?

**Comment by davegson** [comment]
I do believe https://github.com/safing/portmaster/issues/683 covers this:

> Good news, we are actually already working on a feature for a full-device "Network Activity" overview, where you will see all connections of your device (from the last 10 minutes) with filtering included.

grouping by app, connection type, etc will also be possible. Should come to the "Beta" [Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel) in the next weeks

also see issues https://github.com/safing/portmaster/issues/698 and https://github.com/safing/portmaster/issues/151

ping me if you wanted something else

**Comment by Rexadev** [comment]
@davegson I tried the new UI. Here is my suggestion

1. Store all network activity instead of just 10 min
2. Add option to view specific time (like specific date, week, month)

**Comment by Rexadev** [comment]
@dhaavi Please reopen this
