### ISSUE TITLE
Add option to block by IP protocol

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#730]
Like 41 is IPv6

**Comment by dhaavi** [comment]
`Block * 41` - see [Outgoing Rules](https://docs.safing.io/portmaster/settings#filter/endpoints).
41 is IPv6 _Encapsulation_!

**Comment by Rexadev** [comment]
@dhaavi I can't find about IP protocol no. in the document

**Comment by Rexadev** [comment]
Not working

**Comment by dhaavi** [comment]
`Additionally, you may supply a protocol and port just behind that using numbers (6/80) or names (TCP/HTTP).`

So, you can use `Block * 41` to block IPv6 Encapsulation - which is NOT IPv6 itself.

What are you trying to achieve?

**Comment by wallart1** [comment]
Just want to add a vote for being able to block IPv6. I have IoT devices that are sending IPv6 traffic everywhere and would just like to block it, at least from my important devices running Portmaster.

**Comment by wallart1** [comment]
> Just want to add a vote for being able to block IPv6. I have IoT devices that are sending IPv6 traffic everywhere and would just like to block it, at least from my important devices running Portmaster.

I was just pointed to this issue item on Reddit. This is exactly what I'm looking for. Thank you so much
[https://github.com/safing/portmaster/issues/778]

**Comment by Rexadev** [comment]
@dhaavi 

Doesn't Block ::/0 Also block IPv6 loopback

**Comment by dhaavi** [comment]
> Doesn't blocking ::/0 Also block IPv6 loopback

Yes, it would.
I don't know of any app using IPv6 for localhost, as only IPv4 is guaranteed.

You can also just throw a `Allow Localhost` in front of it.

**Comment by Rexadev** [comment]
> > Doesn't blocking ::/0 Also block IPv6 loopback

Avid Products does. Professional audio video

**Comment by Rexadev** [comment]
> You can also just throw a Allow Localhost in front of it.

I don't understand? 
Also, ::1/128 will work for loopback CIDR?

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/190900614-2b64ae5c-6e44-41e5-aa10-c026bf0033e0.png)
