### ISSUE TITLE
Add option to ruleset which can then be applied to invidual apps

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#731]
Like if create a rule for browser

Allow 80 , 433 TCP and UDP
Deny all other

I should be able to apply it to other apps without having to config all again

@dhaavi That is more messy than my Idea. Because user can't name and store a ruleset and has to remember what rule is applied to which app.

**Comment by Rexadev** [comment]
@dhaavi That is more messy than my Idea. Because user can't name and store a ruleset and has to remember what rule is applied to which app.

**Comment by Rexadev** [comment]
@dhaavi That is more messy than my Idea. Because user can't name and store a ruleset and has to remember what rule is applied to which app.
Example - I create a ruleset named Only Port 443 that does what is says and I apply it to some of my apps. Then later I should be able to edit the ruleset and Make the rule Only Allow Port 443 and 80.

**Comment by ppacher** [comment]
Hi @Rexadev,

the possibility to have named rulesets that can be applied to apps is a nice thing to have. We already have a different concept in the backlog which will solve this use-case as well, but for the time being a simple import/export will be the first step as it's easier to do with limited resources and a pretty long backlog :)

**Comment by Rexadev** [comment]
@dhaavi reconsider its priority please
