### ISSUE TITLE
Add 'Ask' Rule

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#732]
Example

Allow port 433 TCP UDP
**Ask** All other IPv4         <--
Deny All other

**Comment by p2anav** [comment]
Hey @Rexadev thanks for this and all other suggestions. I am assigning all of them to me and @dhaavi.

**Comment by dhaavi** [comment]
This is also a nice idea, adding to the backlog.

**Comment by Rexadev** [comment]
Reopen

**Comment by dhaavi** [comment]
This will be part of the rule engine revamp - however we don't know yet when we will get to it.
