### ISSUE TITLE
UI and Features for Rule creation

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#736]
### The UI Box-
![image](https://user-images.githubusercontent.com/62152714/178218049-bb013272-bb90-4940-9d10-62f84d1be8a6.png)

Features-
### TCP/UDP and IP Option - IP option is non TCP/UDP. Can can select other IP protocols 
![image](https://user-images.githubusercontent.com/62152714/178218204-b15b0ffa-9ce2-4c7c-892a-5754bdd660b0.png)

### When IP mode is selected. IP Protocol Selection UI. Also can Choose custom and enter a IP protocol Number
![image](https://user-images.githubusercontent.com/62152714/178218252-9a2c81eb-55c2-4266-844a-40e534b5452d.png)

### Source/Destination Address Control
![image](https://user-images.githubusercontent.com/62152714/178218378-9c9ad5d0-138f-43bd-a25a-aa3c312c7ef2.png)

### Source/Destination Port Control
![image](https://user-images.githubusercontent.com/62152714/178220638-abb80bbd-7eb1-4e33-babf-98ab5c2d69e0.png)

### Also see
https://github.com/safing/portmaster/issues/732
https://github.com/safing/portmaster/issues/731

**Comment by Rexadev** [comment]
@dhaavi

**Comment by Rexadev** [comment]
@dhaavi 
I am suggesting features here
UI for easier rule creation
Currently all connections are logged and  I am suggesting to only log some rules as explained above.
more suggestion in top post

**Comment by Rexadev** [comment]
@dhaavi please reconsider it's priority

**Comment by Raphty** [comment]
Rules in general, the where and how is a topic we might be starting to look into in the near'ish future.

We will go into all the suggestions when starting. I close this issue for now.
