### ISSUE TITLE
[Rule Engine] Add option to make 'Port Sets' which can then be applied to indiviual Rules

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#737]
Also See - https://github.com/safing/portmaster/issues/736 - Source/Destination Port Control

Example - I can create a list of 
HTTP ports -80,443,8080
Vulnerable ports, etc
which will make creating rules easier

**Comment by dhaavi** [comment]
That a nice idea for the new rule engine. Adding to backlog.

**Comment by dhaavi** [comment]
Something like this _might_ be part of the new rule engine - no promises though.
