### ISSUE TITLE
[Rule Engine] Add option to create Custom Network Zones

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#738]
See - https://github.com/safing/portmaster/issues/736

Example -
Proton VPN needs 10.0.0.0/8 100.64.0.0/10 172.16.0.0/12 169.254.0.0/16 which is considered LAN by Postmaster but VPN uses it has loopback. Also It will be nice to control exact zones instead of just LAN and DeviceLocal aka loopback.

**Comment by dhaavi** [comment]
I don't think this makes sense globally, but as a rule engine option, this might be possible.

**Comment by Rexadev** [comment]
Reopen
