### ISSUE TITLE
In connection history add option filter by blocked reason.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#740]
Reason like - P2P, LAN, DeviceLinkLocal, Domain Blocklist, IP Blocklist, Rules, Rules Port, Rules IP, Rules IP Country.

**Comment by p2anav** [comment]
The developer interface already has options to filter by Local, LAN, etc, but it does not specifically filter blocked connections. If this is implemented I guess it would work similar to labels on Github.

**Comment by dhaavi** [comment]
The new network monitor page will be able to do this. Arriving in 1-2 weeks to Beta Release Channel.

**Comment by Rexadev** [comment]
@dhaavi I can't find this in new UI

**Comment by Rexadev** [comment]
@dhaavi Please reopen This

and add these filters

Blocked Reason-
- Domain Blocklist, 
- IP Blocklist,
- Rules,
- Rules Port,
- Rules IP,
- Rules IP Country.
