### ISSUE TITLE
Unable to connect to website after installing portmaster

### ISSUE THREAD

**Issue by FrostBlade5** [safing/portmaster#743]
https://pagexray.fouanalytics.com/

This is a very useful website where you can post any URL/Link and the website will then show you ALL outbound connections from the entered URL/Link. I miss this feature alot after installing portmaster i am unable to connect to this website, but it's only this one everything else works. Perhaps it is included to some blocklist? But why? It is legit. Anyways how can i stop portmaster from blocking access to this site? Is there a whitelist option or anything? I really want this scan feature back!

**Comment by FrostBlade5** [comment]
I have not seen #706 thank you that worked!

[https://i.postimg.cc/v8rGTLf2/portmaster-whitelist-pagexray.png](url)

**Comment by davegson** [comment]
great to hear it worked!
