### ISSUE TITLE
I have to reapply DNS for internet to work

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#745]
On WIndows Startup internet doesn't work beacuse of DNS
In PortMaster I edit a letter and type it again and save it. That I assume re-registers DoT in PortMaster .
That fixes the internet

Also have to enter DNS IP in WiFi settings (with DHCP gateway). 
Seems to me when postmaster tries to establish DoT is uses "Plain DNS" and does not use the DNS provided for that. Because I have only allowed my DNS IP for port 53 and 853

**Comment by dhaavi** [comment]
This should not be the case. When you edit the DNS server settings in Portmaster, this will refresh their status, but nothing is re-registered.
Do you have any other program that might block connections?
It seems that Portmaster has failed sending DNS requests - waiting a short amount of time should restore access itself.

**Comment by Rexadev** [comment]
Also have to enter DNS IP in WiFi settings (with DHCP gateway). 
Seems to me when postmaster tries to establish DoT is uses "Plain DNS" and does not use the DNS provided for that.

**Comment by ppacher** [comment]
Please re-open if this is still an issue
