### ISSUE TITLE
deepin linux (debian) portmaster service file removed after reboot

### ISSUE THREAD

**Issue by arch-user-france1** [safing/portmaster#764]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
After a reboot on Deepin there's no portmaster service anymore - I'd have to reinstall on every reboot.

**What did you expect to happen?**:
I think you know

**How did you reproduce it?**:
1. Install Deepin
2. Install Portmaster
3. Start portmaster.service by `sudo systemctl enable --now portmaster`
4. Restart the whole systemd system
5. You will notice that the Portmaster notifier will show a red dot, try getting the status of Portmaster by `systemctl status portmaster.service`
6. You'll notice that the command gets auto-completed (TAB, bash) but systemd can't find any `portmaster.service` service
7. Try restarting Portmaster by `sudo systemctl (re)start portmaster`
8. Try starting Portmaster using the GUI Portmaster client, won't work either.

**Debug Information**:

Cannot start Portmaster

**Additional Information**:
portmaster.service is in /opt/safing/portmaster

**Comment by arch-user-france1** [comment]
Looks like /etc/systemd/system/portmaster.service exists

**Comment by arch-user-france1** [comment]
Still happening

**Comment by dhaavi** [comment]
Hey @arch-user-france1, thanks for reporting this.

How did you install portmaster? Using the .deb or manual install?
Only the installer drops the file there, was happens then is up to the system.

I don't think the file should be copied. Rather, it should be symlinked.

Will assign to @ppacher to see if he has any ideas - my first impression is that this might be a system issue.

**Comment by arch-user-france1** [comment]
I noticed sometime that the unit file doesn't get deleted anymore or never was deleted, but instead I had to run daemon-reload every restart. 

I don't trust Deepin Linux and suspect it's messing up. If it works fine on debian (which I don't have and I wiped Deepin), then we should close this issue.
I don't have any other Debian based installation around anymore.

**Comment by ppacher** [comment]
Hi @arch-user-france1,

Since we also did a revamp of the installers lately (not yet released though) and it's working on Debian I'll close this issue for now.
If anyone else with Deepin Linux can confirm and maybe debug the issue please just re-open it.
