### ISSUE TITLE
When all apps are set to prompt by default, would be great when it prompts, I could set it to auto-block the entire app, instead just a domain

### ISSUE THREAD

**Issue by alexthekukats** [safing/portmaster#765]
When the "Network Default Action" is set to "Prompt", it would be great when it pops-up, that I could set the App to block or to allow connections, not just a single domain, so it stops bothering me.
This is the feature of simplewall, this is what I used before Portmaster, it pops up and asks if I want to allow this app to connect to the internet, when it tries to connect for the first time, and I could block it or allow it.

We need this so I don't have to go to the app settings->settings->default network action->select to block. pop-ups keep bothering, and I just wanna block apps without going through the hassle of blocking every app (and allowing a bunch others), one by one in the settings, when it could be just added to the pop-up that i want to allow or block the entire app.
This would be really nice, thanks

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
