### ISSUE TITLE
New network monitor does not work well on small screens

### ISSUE THREAD

**Issue by arch-user-france1** [safing/portmaster#766]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug) <-- nothing found

*What happened**:
I have joined the support channel on my desktop computer and the beta channel on my laptop.
On my laptop (beta channel) there is a new UI which looks ugly on smaller screens.
On my desktop computer (support channel) however there is still the old design, so I cannot test the ugly thing on larger screens.

Why is the support channel *behind*?
Why is there no portmaster version element in the settings on the beta branch anymore?

**Comment by arch-user-france1** [comment]
![image](https://user-images.githubusercontent.com/72965843/181880205-fce0c4f0-f2cb-49f6-9493-eab67e356c62.png)
Desktop

**Comment by dhaavi** [comment]
Hey @arch-user-france1, please DO NOT use the support channel.

We are working on improving the new network monitor on smaller screens.

**Comment by arch-user-france1** [comment]
Question...

Why shall I not use the support channel?
I should only not use the staging channel it says. There's nothing about not using the support channel.

Ps: I prefer the old interface. There's just too much information now, too many graphics...

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
