### ISSUE TITLE
Block port 53 and 853 (except DoT address specified and only Portmaster) system wide.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#767]
Using another firewall with PortMaster I can see "Windows Operating System" (I don't know what exactly) is trying to connect over port 53 and 853. I have blocked those and internet still works.

**Comment by dhaavi** [comment]
Why would you think that your Internet would stop working if you block these ports?
As Portmaster redirects port 53 to itself and resolves DNS, it is expected behavior that you Internet connection keeps working.

**Comment by Rexadev** [comment]
> Why would you think that your Internet would stop working if you block these ports?
You didn't understand. I am saying to block port 53 and 853 for all apps except Postmaster
