### ISSUE TITLE
Add mechanisms to clear the DNS cache to portmasterctl

### ISSUE THREAD

**Issue by dhaavi** [safing/portmaster#77]
**What would you like to be added**:

The DNS cache should be clearable, either in full or for specific records. This could be achieved using the following mechanisms, which should be understood as suggestions:
- If there are three consecutive requests (without any other in the middle) for the same domain, clear the cache for that domain and make a new request.
- If a query for `orf.at.clear.portmaster.` is made, the dns cache for `orf.at.` with the same query type is cleared.
- If a query for `clear.portmaster.` is made, the complete dns cache is cleared.
- If a query for `orf.at.fresh.portmaster` is made, the dns cache for `orf.at.` with the same query type is cleared, a fresh query is run and the results returned (unchanged?).

Before this is implemented, we should also think about potential attacks this could enable. For example, an attacker could circumvent being blocked by just resolving using `bad.example.com.fresh.portmaster.`. Also, it would be easy to determine if a user is running the Portmaster or not.

**Why is this needed**:

Developers and system administration often have to wait for updated DNS records to arrive at their machine. This would let them speed up the process.

**Comment by dhaavi** [comment]
Well, with all kinds of DNS related changes, admins usually monitor the change, especially when it is blocking their work. In the case you described, you were waiting until the DNS change finished, in order to run an ACME client. Running fresh queries would improve the accuracy of this approach. Especially with something as an ACME server, which is very unlikely to have a cached record of the domain in question, or even use a cache at all, all you want to know if the authoritative nameserver has been updated. Bypassing as many caches as possible is therefore desirable.

> Or is there any other DNS client that uses DNS query to purge cache?

No, not that I know of.

> What is the difference between `fresh.portmaster.` and `clear.portmaster.`. The `fresh.portmaster.` one returns fresh data returned by new query and `clear.portmaster.` returns what? Cached result being removed? Empty response?

A query for `clear.portmaster.` would probably return a TXT record with `Portmaster DNS cache cleared`.
 
> Regarding security issues - wouldn't it be better to take advantage of the same authorization process which is used by portmaster dashboard to authenticate to the portmaster core API? This could solve the security issues you have mentioned.

Authentication to the Portmaster Core API just checks if the process is part of the Portmaster. That would not work in this case, as the querying process would always be a process that isn't part of the Portmaster.
 
> Have you thought about mechanism to purge just one TLD (`*.at.clear.portmaster.`) or second level domain with all subdomains (`*.safing.at.clear.portmaster.`). Is asterisk allowed in DNS query? I'm not the DNS protocol master here but I would say it's not allowed.

That is a nice idea! `*` are not permitted, but `dig` for example doesn't care and sends anything you give it. So this could work.

> P.S. please correct me if u are used to different terminology (dashboard, core api...), I'll get used to it sooner or later.

Everything fine so far ;)

**Comment by northys** [comment]
> Authentication to the Portmaster Core API just checks if the process is part of the Portmaster. That would not work in this case, as the querying process would always be a process that isn't part of the Portmaster.

@dhaavi I thought about something completely different to purging DNS cache by DNS request. Llike `varnishadm` command used to manage varnish proxy - https://varnish-cache.org/docs/trunk/users-guide/purging.html#ban There could be command called e.g. `portmaster-dns` that would be much smarter (or at least could be) when compared to asterisk in dig which is actually breaking DNS standard.

When u have something like `portmaster-dns` you can rely on process detection to authenticate the DNS cache purge. This solves the potencial attack and portmater detection you have mentioned in original post.

**Comment by dhaavi** [comment]
Ah. I see now what you mean. This is also an interesting idea!
As this would take a lot more effort, I think I'd rather do something minimal near/mid-term.

An alternative to creating a whole new utility for that would be to add a utilities page in the app, where one could access such features.

**Comment by northys** [comment]
Is creating new binary with some default console calling portmaster API that time consuming? 

So there's a new idea - I think that sooner or later you will start creating utility similar to kubectl that will allow users manage portmaster using CLI. This won't be used only to purge DNS cache. This tool would use the same api endpoint as dashboard (where DNS cache purging will be sooner or later requested by users) will. This could be implemented as really tiny minimum viable product.

This idea covers both CLI for portmaster and also solves a lot of security issues that would be created by using your proposal. I don't say it's bad. I just think about it as an end user.

**Comment by dhaavi** [comment]
> Is creating new binary with some default console calling portmaster API that time consuming?

Well, no. But continuously maintaining stuff is. In that context I was still thinking about a distinct, almost single-purpose binary. See comments below.

> So there's a new idea - I think that sooner or later you will start creating utility similar to kubectl that will allow users manage portmaster using CLI. This won't be used only to purge DNS cache. This tool would use the same api endpoint as dashboard (where DNS cache purging will be sooner or later requested by users) will. This could be implemented as really tiny minimum viable product.

Yes, you are right. I've been looking forward to creating a cli interface for a while now, but somehow did not connect the dots here. I guess I need to go on a holiday more often - at least that is what my CEO tells me. 😋

Previously I have thought such a cli to be more like a TUI, recreating the App in a terminal, but having both that - to have a streamlined experience and be able to quickly get an overview over the current status - and having a cli with commands is a very nice combination. We would then probably even create the CLI part first, as this is much easier.

> ```shell
> portmasterctl dns cache purge '*.safing.at'
> ```

We already use `portmaster-control` as a service wrapper. I am not sure if it would be a good idea to merge these two use cases. It would definitely reduce confusion, but these two use cases would also add bloat to each other. What do you think?

Just to set expectations right, we probably won't be able to have a go at this until the end of the year.

> This idea covers both CLI for portmaster and also solves a lot of security issues that would be created by using your proposal. I don't say it's bad. I just think about it as an end user.

I like it very much, thank you for brainstorming! 😁

**Comment by ppacher** [comment]
I really like the idea of @northys regarding a `portmasterctl` tool. I also would like to have a headless verison of portmaster so I can run it on my servers as well. I also think that a `portmasterctl` should have higher priority than a TUI because folks working on headless systems typically want to script it anyway. And something like `portmasterctl watch alerts` or `portmasterctl allow /usr/bin/curl` could become very handy :). 

> We already use portmaster-control as a service wrapper. I am not sure if it would be a good idea to merge these two use cases. It would definitely reduce confusion, but these two use cases would also add bloat to each other. What do you think?

I'm not sure what's the best way to go here. At least, the name `portmaster-control` for a service wrapper can be irritating. IMHO we should keep concerns separated and let one be a cli and the other a service wrapper. 

@dhaavi if we add some more introspection to the portmaster API endpoint `portmasterctl` could start as a simple API call wrapper (by quering supported commands/settings and exposing them as "sub-commands"). A long the way we could move more and more features from a simple "API wrapper" to a built-in cli feature and thus provide better UX.

For example, we could just allow "database" or "event" access like:

```
portmastctl database query profiles:/usr/bin/curl
```
```
portmastctl api trigger-event force-update
```

For the portmaster settings we could already provide something like the following:
```
# Set a simple "one-of" settings
portmasterctl set --global experience-level developer

# Configure security levels
portmasterctl enable --global --security-levels=high,extreme block-service-inbound

# Get help about a setting (already available via the API).
portmasterctl describe block-service-inbound
```

Though, a API service wrapper will require us to keep the API stable so we don't break scripts. But we could reuse the "stable" feature flag here.

Just my bits ... :)

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
