### ISSUE TITLE
Portmaster with Simplewall?

### ISSUE THREAD

**Issue by FrostBlade5** [safing/portmaster#775]
Does it make any sense to use both together?
As you said, portmaster is for privacy, simplewall is against windows bloatware.

If i remove simplewall and use only portmaster will there be any "difference" / "downgrade"?
For example portmaster allows to block any exe like svchost to block it's network access.

**Comment by davegson** [comment]
closing as this is neither a suggestion nor a bug

**Comment by FrostBlade5** [comment]
I have already read the comparison, from what i can tell IF i must choose i will go with portmaster as it's simply more powerful, i can confirm that from my experience so far.

However indeed this is neither a suggestion nor a bug but it was a question.
Currently i use both together simplewall and portmaster, would you let me know if i should or should not do that and why?
Can portmaster do EVERYTHING that simplewall can do or will i be missing something?

For example.. in simplewall i can block networkaccess for individual exe applications like svchost.exe or firefox.exe
In portmaster can block networkaccess for applications by selecting a rule like allow, prompt, deny.
Is this the same function? I won't miss anything by only using portmaster without simplewall?

Then a final question, if i uninstall simplewall and keep only portmaster, what about the windows firewall? should it remain disabled as this is what simplewall suggested so i did it, or should i reenable it? and why?

**Comment by FrostBlade5** [comment]
If portmaster works a the systemlevel (kernel extension) why should i keep the windows firewall ON? What are potential reasons?

**Comment by davegson** [comment]
copied from [this thread](https://old.reddit.com/r/safing/comments/vqbvp2/canshould_i_disable_windows_firewall/iesod9g/):

> Speaking in general, Portmaster is a _Privacy_ Tool, focusing on privacy features like DNS encryption or blocking tracking requests.
> 
> Windows Defender Firewall on the other hand is a _Security_ Tool. As such, it focuses on security and includes features such as Malware detection which Portmaster simply does not have. It will also defend your device in areas which are currently [out of scope for Portmaster](https://github.com/safing/portmaster/issues/166).
> 
> That is why we **do not recommend** deactivating Windows Defender Firewall. Please both have a security and privacy setup. Without security your ~~perceived~~ privacy can quickly become non-existent.
