### ISSUE TITLE
Clicking "Allow IP" on an incoming connection places it in the "Outgoing Rules"

### ISSUE THREAD

**Issue by shadowblaster111** [safing/portmaster#780]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
I clicked on an "App" and then under "Connection History" I clicked on an incoming connection. Then I clicked on "Allow IP" and it placed it under "Outgoing Rules".
![img1](https://i.imgur.com/Nccb6hZ.png)
![img2](https://i.imgur.com/m3mUkWh.png)

**What did you expect to happen?**:
I expected an incoming connection to be placed under "Incoming Rules".

**How did you reproduce it?**:
Explained above.

**Debug Information**:
OS: Ubuntu 22.04
Portmaster version: 0.8.13

**Comment by fastzombies** [comment]
I see the same issue.

OS: Fedora 36
Portmaster version: 0.8.13

**Comment by dhaavi** [comment]
Thanks for chiming in here, @fastzombies.
This is already fixed in the current [Beta Release Channel](https://docs.safing.io/portmaster/settings#core/releaseChannel).
It will be available for everyone in about one week.

Also see https://github.com/safing/portmaster/issues/717.
