### ISSUE TITLE
Add folders to the Deny/Allow list

### ISSUE THREAD

**Issue by Z3r0ut** [safing/portmaster#781]
**What would you like to add or change?**:
I would like to add a whole folder to the deny/allow list, so all programs inside that folder cannot/can access the internet.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
