### ISSUE TITLE
Failed to save setting - Outgoing Rules (Localhost)

### ISSUE THREAD

**Issue by fugbixer** [safing/portmaster#782]
**What happened**:
`
failed to create config perspective: encountered 1 errors, first was: validation of filter/endpoints failed: encountered 1 errors, first was: unknown endpoint definition: "+ localhost:8118"`

can't access localhost services using the browser

**What did you expect to happen?**:

Being able to add rules for localhost as well

**How did you reproduce it?**:

where does the "+" come from in the error mesage ? 

 i tried adding 
```
localhost:8118
127.0.0.1:8118
```

Arch Linux

**Comment by fugbixer** [comment]
Wow also i clicked the red button invalid rules and i just deleted all my rules for the process... Seems quite extreme since it deleted  10+ valid rules for no reason without indicating nor questioning if i want to remove all ...

**Comment by dhaavi** [comment]
Hey @fugbixer, thanks for reporting this.

You can find the required format here: [Outgoing Rules](https://docs.safing.io/portmaster/settings#filter/endpoints)

> and it just deleted all my rules for the process... Seems quite extreme since it deleted 10+ valid rules for no reason without indicating nor questioning if i want to remove all ...

Sorry for the inconvenience. This behavior does not work well in this use case. Working on this.

> where does the "+" come from in the error mesage ?

This is the "Allow" from the dropdown. The message shows the text representation.

**Comment by fugbixer** [comment]
@dhaavi thanks for the reply.  i tried using just localhost before
but it still results in 

> The connection was reset
> 
> The connection to the server was reset while the page was loading.
> 
>     The site could be temporarily unavailable or too busy. Try again in a few moments.
>     If you are unable to load any pages, check your computer’s network connection.


https://i.ibb.co/3pkLSpR/output.png
https://i.ibb.co/Tk82Lrz/portmaster-config.png

I'm currently unable to use proxies nor access localhost web services.

**Comment by fugbixer** [comment]
@dhaavi still quite unfortunate that rules can't specify the port.

**Comment by dhaavi** [comment]
What do you mean?
As the help states: eg. "Localhost TCP/8080"

**Comment by fugbixer** [comment]
Oh sorry my bad, just quickly took a look.
