### ISSUE TITLE
Network issue on windows start

### ISSUE THREAD

**Issue by Stofa14** [safing/portmaster#790]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Stofa14** [comment]
I sent private ticket via email. I use Portmaster on virtualbox for testing and may this caused the issue.

**Comment by dhaavi** [comment]
Hey @Stofa14, we need a little more context here.

What exactly is the "network issue" here?

Also, does this issue still persist? If it does, please send an update debug info using the newest Portmaster version.
