### ISSUE TITLE
Portmaster does not display notifications after switching to another user.

### ISSUE THREAD

**Issue by Hell01World** [safing/portmaster#791]
**What happened**:
I have Linux Mint 21 installed on my laptop with 2 users: tux and user. After it booted and login as a "tux", the notifications are going to be available only for the tux. If I wanted to log out and switch to "user" I won't get any notification from Portmaster on it unless I will reboot and login as a "user" first but then notifications for tux won't be available. 

**What did you expect to happen?**:
Notifications to work for both users

**How did you reproduce it?**:
1. Turn on laptop
2. Login in as a tux, notifications works (screenrecording: https://pixeldrain.com/u/182N3WVU)
3. Log out and login as a "user"
4. Notifications from Portmaster doesn't work for "user" (screenrecording: https://pixeldrain.com/u/v4EWrLeE)

**Debug Information**:
https://pastebin.com/8Ua19V8f

**Comment by Hell01World** [comment]
Hi @p2anav, thank you for your reply.

The problem that I'm dealing with is that both of these users **can** run Portmaster Notifier, but **only one** can run it at the same time. Here is the output of `/opt/safing/portmaster/portmaster-start notifier` while another user is already running it: https://pastebin.com/MWXs3yg0
Here are the permission in the /opt/safing/portmaster directory: https://pastebin.com/s2H68jtM

A workaround for this would be running this command upon logging out `pkill portmaster ; cinnamon-session-quit `  and once I login to another user, the Portmaster Notifier starts automatically.

**Comment by dhaavi** [comment]
Huh. This is an interesting use case.
I guess we could make the check per-user somehow.

Not sure yet how though. Adding to the backlog.

**Comment by Raphty** [comment]
I am cleaning out old issues. If you feel this issue should not have been closed let me know.

Please keep in mind, the free version of Portmaster only has limited support.
For free users our active Discord community as well as the chat bot are the fastest and best way to get their help. https://discord.gg/safing
If you find our work brings value to you, please consider supporting it by purchasing Plus or Pro Packages https://safing.io/pricing/.
If you are already a subscriber, first Thank You! and also if you want priority support pleas send in an email and let me know your username so I can prioritize your request accordingly.
