### ISSUE TITLE
More than 1 custom blocklist

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#799]
Related https://github.com/safing/portmaster/issues/326

**Comment by dhaavi** [comment]
We kept the [Custom Filter List](https://docs.safing.io/portmaster/settings#filter/customListFile) feature simple on purpose. Managing multiple lists adds a lot of complexity.

Our thought was that when you need to build your script to update these lists anyway, then you can as well throw them into one file as well.
Maybe there is even a tool out there for this, possibly built for the hosts file, which pretty much is the same interface, except for the format.

**Comment by Rexadev** [comment]
> We kept the [Custom Filter List](https://docs.safing.io/portmaster/settings#filter/customListFile) feature simple on purpose. Managing multiple lists adds a lot of complexity.
> 
> Our thought was that when you need to build your script to update these lists anyway, then you can as well throw them into one file as well. Maybe there is even a tool out there for this, possibly built for the hosts file, which pretty much is the same interface, except for the format.

There are many blocklist on GitHub that overblock it would be nice to know which blocklist is causing problem

**Comment by ppacher** [comment]
Hm, if you already use a script or something similar to build that block list it should be pretty easy to check which list contains that certain domain or IP that you're searching for?

**Comment by Rexadev** [comment]
> Hm, if you already use a script or something similar to build that block list it should be pretty easy to check which list contains that certain domain or IP that you're searching for?

While using ```Nexy DSn``` and uBlockOrigin I found blocklists are trial-and-error i.e. I had to try them our to find if one overblocks and I should not use it or a few exceptions in allowlist would be fine.

**```Sexy DSn``` makes it easy. See their UI**
