### ISSUE TITLE
Insane amount of Linux journal logging

### ISSUE THREAD

**Issue by Bananaman** [safing/portmaster#803]
Portmaster spams the Linux journal.

I have had it installed for 10 hours and have been asleep, not using my computer.

Ran this command now to check:

```
journalctl -r | grep -i portmaster | wc -l
```

# The result is: 155 053 lines of logging in ten hours of inactivity.

A lot of it was Portmaster's connection rejections for DLNA home devices trying to reach my Plex Media Server and endlessly retrying.

I checked what is being logged. It is basically all useless garbage/noise:

"portmaster-start" is logging extremely detailed info about every connection, such as "connection:643 INFO 153 bla bla filter bla bla connrcyik allowed or blocked or dropped etc".

There is zero reason to log this in a non-debugging state. But I cannot find any way to turn off this logging even in Advanced Portmaster GUI mode.

Perhaps there is a bug. I briefly set my interface mode to Developer Mode to try it. Then I changed back to Simple mode. And went to bed. Maybe it got stuck in verbose debugging mode?

System: Fedora Workstation 36, with latest Portmaster RPM.

**Comment by Bananaman** [comment]
Ok I think I found a bug.

Switching to Developer Mode exposes a Log Level setting and sets it to INFO.

Changing back to Simple/Advanced mode seems to keep it stuck in INFO mode instead of reverting to sane, calm logging.

**Comment by Bananaman** [comment]
I hit the "Reset to system default" button below the UI mode setting, and reset my journalctl log to totally empty. Will see if the logging is sane now.

**Comment by Bananaman** [comment]
Rebooting doesn't work either.

The only way to fix it is to enable Developer Mode again. And setting Log Level to Warning. Now it finally shuts up.

The default INFO log level exposes private details for the user, by the way. It floods the logs with exact programs and domains that the user is connecting to.

**Comment by dhaavi** [comment]
The log level has been recently increased to warning with #783. Change is currently in beta release channel.
