### ISSUE TITLE
2 No and 1 Yes in Connection Allowed

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#804]
![image](https://user-images.githubusercontent.com/62152714/185684046-42629041-5c5f-4208-9537-f63427cf5412.png)
![image](https://user-images.githubusercontent.com/62152714/190208391-2b7e4c4c-2fdd-4ff2-9091-501964257552.png)

@dhaavi

**Comment by tukusejssirs** [comment]
I suggest to also rename `Yes` and `No` to `Allowed` and `Denied`, as when you select one of them, only `Yes` or `No` is output, thus less obvious what it does mean.

Also either allow up to one of them to be selected (like a toggle) or at least one of them. Currently no selected outputs `Allowed` and selection of both outputs `Allowed: 2 Selected`, neither seems to nice and user-friendly.

| Option 1: selected | Option 2: selected | Name            | Show                                |
|:-------------------|:-------------------|:----------------|:------------------------------------|
| none               | yes, no            | All connections | both allowed and denied connections |
| yes                | yes                | Allowed         | only allowed connections            |
| no                 | no                 | Denied          | only denied connections             |

`All connections` name might not be perfect though.

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/190208391-2b7e4c4c-2fdd-4ff2-9091-501964257552.png)

@dhaavi

**Comment by Rexadev** [comment]
> Sorry, I've overseen the "null" screen shot here. Re-opening

Sometime i also get false

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/192295468-2e7ecfa6-88ea-48d9-a111-fb63fc1f1a8a.png)
![image](https://user-images.githubusercontent.com/62152714/192295534-249995ac-7ae6-483d-8cbc-82b64478b88f.png)
![image](https://user-images.githubusercontent.com/62152714/192295553-3dd2fea6-e64f-4a46-b826-077a1ea4ce55.png)
![image](https://user-images.githubusercontent.com/62152714/192295579-c771eca7-b9e1-4834-9254-0c3e2d3bd946.png)

**Comment by dhaavi** [comment]
I can't follow what you mean. Please reopen with more details. The original issues seems resolved. One bug per issue. ;)
