### ISSUE TITLE
My opinion about what would be a great thing to add to Portmaster

### ISSUE THREAD

**Issue by Iceburgino** [safing/portmaster#808]
This post is based on this [Reddit](https://www.reddit.com/r/safing/comments/woezk9/my_personal_opinion_about_portmaster/), since  posting suggestions on GitHub is more convenient to the devs, I've decided to port it to here:

Portmaster's great! Finally, there is a decent network monitor and manager for Linux distros with an interface, that I can open from the tray with several clicks. As far as I see, the project is still in active development but looks very promising. Free, open-source, sleek-looking. I love that!

But there are still features that I personally miss from the software and I think would be beneficial to have, as adding all of these would make you stand out among all of the other network monitor and manager software. I'll try to list what would be such features to me:

- **Extend the monitor period to more than 10 minutes**
This is a really important one. The last 10 minutes are nice but do not tell you the full picture of what was happening when you, for instance, were off and the computer was sitting idle, or what was happening while you were working and didn't monitor Portmaster. The ability to log actions during the last minute/hour/day/week/month would have been reeeally helpful.

- **When default action is selected to prompt, add buttons for "allow all" and "block all"**
This would make that option the most absolute and unbeatable badass of them all. If you could just make the Portmaster remember settings for the app instead of asking every time, but at the same time prompt you every time something new happens, it would be just priceless.

- **Add a label of total internet usage for each app, general usage rate, and usage of the internet in total**
Connections are good, but it makes a difference if you see the usage. Some apps send texts. Some send images. Some send 5GB archives over the internet, and each could probably just use a single connection. But you wouldn't know what takes up your bandwidth if you just see the connections.

If those would ever make it to the app, nothing would come close to being what I consider a decent network monitoring and management software in comparison to Portmaster. Of course, those are just my personal wish, but I hope my feedback is useful to you. 

As [Davegson pointed out here](https://www.reddit.com/r/safing/comments/woezk9/comment/ikmjeve/?utm_source=share&utm_medium=web2x&context=3), some of those features already are underway, and some are in the plans for the near future. This is great! I just want to see how many people would want those too. Maybe a like/dislike vote would tell? Let me know in the comments!

**Comment by Rexadev** [comment]
> Extend the monitor period to more than 10 minutes

Already in Works

> When default action is selected to prompt, add buttons for "allow all" and "block all"

I reported a better version of that here

> Add a label of total internet usage for each app, general usage rate, and usage of the internet in total

This too
