### ISSUE TITLE
High CPU usage when Wi-Fi disconnected after wake up

### ISSUE THREAD

**Issue by northys** [safing/portmaster#81]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:

I have changed Wi-Fi SSDI of known network used by laptop where portmaster is running. After system wake up the laptop did not connect to the Wi-Fi and I have noticed that fans started running at full speed. In log there was only spam from resolver because it couldn't connect to cloudflare dns servers in loop while using 400% CPU.

![Screenshot from 2020-06-23 17-33-55](https://user-images.githubusercontent.com/2878126/85424497-4bc31300-b578-11ea-92b4-98ce2d63eb5a.png)

After connecting to the Wi-Fi network again the DNS requests from apps were resolved and the load caused by portmaster dropped immediately.

![Screenshot from 2020-06-23 17-34-40](https://user-images.githubusercontent.com/2878126/85424664-7d3bde80-b578-11ea-8953-58c919801273.png)

**What you expected to happen**:

Resolver should wait for network connection before querying configured DNS servers in loop. 

**How to reproduce it (as minimally and precisely as possible)**:

1) fresh ubuntu + portmaster
2) disconnect from network
3) open page in browser / run dig / be creative
4) portmaster resolver starts to spam could not connect to Cloudflare

**Anything else we need to know?**:

**Environment**:

Portmaster Version: 

```
Name: Portmaster
Version: 0.4.9
Commit: tags/v0.4.9-0-g1ea376fb03fb57a9c44a1bdbe45238f3b7d59f5c
Build Options: main.go
Build User: user
Build Host: docker
Build Date: 16.06.2020
Build Source: https://github.com/Safing/portmaster
```

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [ ] Windows 10
- [x] Linux

```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by dhaavi** [comment]
Thanks for reporting this. I think I know what is going on, but will only have to take a closer look and fix this in 2-3 weeks.

/remind me to investigate in 2 weeks

**Comment by dhaavi** [comment]
I was able to shift some tasks and was able to fix this in https://github.com/safing/portmaster/pull/83.

Please update and check if this also resolves the issue on your end.

**Comment by northys** [comment]
wasn't able to reproduce the issue using version

```
Name: Portmaster
Version: 0.4.10
Commit: tags/v0.4.10-0-g2afd9cd1438b6fe71b981938aad734ee3de81e07
Build Options: main.go
Build User: user
Build Host: docker
Build Date: 27.06.2020
Build Source: https://github.com/safing/portmaster
```

**Comment by dhaavi** [comment]
Did not know that the reminder reopens issues. Good to know.
