### ISSUE TITLE
My ISP seem block port 853 make app run fail.

### ISSUE THREAD

**Issue by issuex** [safing/portmaster#810]
**What happened**:
- after install, it seem like stuck at update and try to connect to 1.1.1.2 TCP 853. The ISP that i use may block 1.1.1.2 or block port 853. make app stuck loading.

**What did you expect to happen?**:
- installer should make app run correctly without internet, you should provide offline installer for more setup situation.

**How did you reproduce it?**:
- try to block traffic like ISP that i use.

**Debug Information**:
- can not do anything.

**Comment by Rexadev** [comment]
Reopen
