### ISSUE TITLE
Removal/Modification of "Blocked Bypass Attempt by Portmaster UI" Notification

### ISSUE THREAD

**Issue by AnorakArturo** [safing/portmaster#813]
Note: I wasn't sure whether to file this as a bug or a improvement. Since it seemed to be more of a suggestion, I went with the latter.
**What would you like to add or change?**
I'd like to get this notification to be changed/removed as it's a bit useless. (Blocked Bypass Attempt by Portmaster User Interface) 
![image](https://user-images.githubusercontent.com/97397709/186732202-30ac1a16-d8b7-41ca-b126-7ed4d92493ec.png)

Image in textual format:
**Blocked Bypass Attempt by Portmaster User Interface**
Portmaster User Interface is using its own Secure DNS resolver, which would bypass Portmaster's firewall protections. If Portmaster User Interface experiences problems, disable Secure DNS within Portmaster User Interface to restore functionality. Rest assured that Portmaster handles Secure DNS for your whole device, including Portmaster User Interface.

**Why do you and others need this?**
It is mostly a useless notification :)
Of course, we could just click the Ok button, but it'll likely pop up again like it does for browsers using their own internal DNS resolver.

**Comment by dhaavi** [comment]
Hey @AnorakArturo, thanks for the report.

Yes, this is useless, and as explained in #814, should not happen anyway and anymore.

**Comment by AnorakArturo** [comment]
> Hey @AnorakArturo, thanks for the report.
> 
> Yes, this is useless, and as explained in #814, should not happen anyway and anymore.

Just restarted
![image](https://user-images.githubusercontent.com/97397709/190417461-b69cfe50-ca71-48c2-b149-b3864c4e1530.png)

I'll check again in a while for updates
