### ISSUE TITLE
Portmaster self-reference

### ISSUE THREAD

**Issue by mikeazurek** [safing/portmaster#814]
Hi, I'm not sure if this is bug, but Portmaster just served me this notification:
![image](https://user-images.githubusercontent.com/58667581/186738644-5775e408-434a-4021-a05c-7b633ec70ddd.png)

**Comment by Stofa14** [comment]
This is happening to me too, and I don't understand what to do.

**Comment by AnorakArturo** [comment]
> This is happening to me too, and I don't understand what to do.

You needn't do anything. It is not a bug, more like a simple issue. 
https://github.com/safing/portmaster/issues/813#issue-1351243755

**Comment by dhaavi** [comment]
Yea, this is one of the ugly sides of using electron - it will try to do its own secure DNS.
We've already disabled it, so this should already be fixed - or in the near future.
