### ISSUE TITLE
Missed connection 

### ISSUE THREAD

**Issue by Stofa14** [safing/portmaster#815]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
missed connection 

**What did you expect to happen?**:
do not miss any connection made by other apps
![2](https://user-images.githubusercontent.com/51302004/186929906-85ec1d68-6dde-40da-9917-205b61a04f3b.PNG)

**How did you reproduce it?**:
I updated my kaspersky antivirus, but Portmaster did not monitor the connections to the update source 

**Debug Information**:

**Comment by Stofa14** [comment]
This connection catched by glasswire 
![Capture](https://user-images.githubusercontent.com/51302004/186936163-b61c9cec-b78b-4d2f-ae63-f600db5f54d0.PNG)

**Comment by dhaavi** [comment]
Hey @Stofa14, thanks for reporting this.

Are you sure Portmaster missed the connection? Can you try again and enter the IP address in the search box?

**Comment by Stofa14** [comment]
> Hey @Stofa14, thanks for reporting this.
> 
> Are you sure Portmaster missed the connection? Can you try again and enter the IP address in the search box?

Hello Dhaavi. I am happy you are fine.
I reproduced it by disabling kaspersky update connections through unidentified app and it wasn't missing. I was focusing on domains not remote peer ( I thought it would be as IP like in glasswire). You can close this issue.
