### ISSUE TITLE
WG 0.0.0.0/0 + Company WG for private subnet breaks portmaster

### ISSUE THREAD

**Issue by northys** [safing/portmaster#823]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**

I've been using portmaster half year ago with my WG vpn tunneling all my traffic through my server. The only problem I had was restarting portmaster after activating wg (could been done by systemd automatically but I ca'nt find the issue)

**What did not work?**

Now when I connect to wg0 (0000/0 tunnel for everything) and wg1 (company's wg tunneling private 10.74.74.0/24 subnet) I can't ping 8.8.8.8 at all.

**Debug Information**:

https://support.safing.io/privatebin/?2cc66ca9b0e11bfc#F7nPcygZgszGBeYSTiw6Q7U1VYwcHrCd7sDSJEED5Unv

**Comment by northys** [comment]
wg stands for wireguard btw

**Comment by northys** [comment]
```
```

**Comment by northys** [comment]
I don't think this is about bypassing or ignoring system name servers. I changed my WG config so there is no DNS configured. Did not help. Always starting wg and after that restarting portmaster to flush the iptables.

I also found out that I have netbird.io installed - disabled it and tried restarting my wg vps again together with portmaster - also did not help :(

**Comment by dhaavi** [comment]
Does it work without the 0/0 routing? I remember this being a source of problems - because of the packet marks used by wg-quick.

**Comment by northys** [comment]
Yup, when I turn off the main WG with 0.0.0.0/0 route it works. But I've been using it with no problems before and I can't find the old issues where we've solved it.
