### ISSUE TITLE
Portmaster UI at starup when closed needs to start with admin privilege

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#828]
Related 
https://github.com/safing/portmaster/issues/830
https://github.com/safing/portmaster/issues/829
https://github.com/safing/portmaster/issues/835

**Comment by AnorakArturo** [comment]
@Rexadev Is this [#829](https://github.com/safing/portmaster/issues/829#issue-1361484021) the same issue? I think this might've been an accident. If that's so, perhaps close this one?

Anyway, when you're closing Portmaster, do you get a dialogue box informing that only UI will be closed?

**Comment by Rexadev** [comment]
> @Rexadev Is this [#829](https://github.com/safing/portmaster/issues/829#issue-1361484021) the same issue? I think this might've been an accident. If that's so, perhaps close this one?
> 
> Anyway, when you're closing Portmaster, do you get a dialogue box informing that only UI will be closed?

No it is different. When I close UI, Portmaster keeps running in background and I expect it to minimize it to taskbar notification icon and UI should not require admin rights.

**Comment by AnorakArturo** [comment]
> . When I close UI, Portmaster keeps running in background and I expect it to minimize it to taskbar notification icon and UI should

Do you have Portmaster Notifier running? When you close the UI, the Tray notifier application icon is still shown in the taskbar. Since it can also be closed while Portmaster continues running in the background. 
![image](https://user-images.githubusercontent.com/97397709/188488609-50fe23cf-b725-4a03-95f2-9db659fb081f.png)

> UI should not require admin rights.
Indeed, the UI does not require admin rights, the core service does. To start the core service, you use the UI :)

**Comment by Rexadev** [comment]
> Do you have Portmaster Notifier running? When you close the UI, the Tray notifier application icon is still shown in the taskbar.

No.

> Since it can also be closed while Portmaster continues running in the background.

I know that is not the issue

> Indeed, the UI does not require admin rights, the core service does. To start the core service, you use the UI :)

OK

----------------------
After booting if Portmaster UI is closed it doesn't minimize to taskbar icon. But after starting with admin right again. UI can be open-and-closed but icon stays in the taskbar notification tray

**Comment by AnorakArturo** [comment]
Hmm, okay.

**Comment by dhaavi** [comment]
Maybe you opened to UI once with admin privs manually and broke the permissions of some files.
What is the error message when you open the UI?

**Comment by Rexadev** [comment]
> Maybe you opened to UI once with admin privs manually and broke the permissions of some files.

What?

What is the error message when you open the UI?

Starting Core services

**Comment by Rexadev** [comment]
@dhaavi Fixed on Windows 11 but not Windows 10
