### ISSUE TITLE
Portmaster should ask for admin privilege if needed

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#829]
Related : https://github.com/safing/portmaster/issues/830 https://github.com/safing/portmaster/issues/828

**Comment by AnorakArturo** [comment]
I don't see how this is a bug. Portmaster cannot function without admin privileges. Else how would it prevent connections, set filters and view network traffic?

**Comment by Rexadev** [comment]
> I don't see how this is a bug. Portmaster cannot function without admin privileges. Else how would it prevent connections, set filters and view network traffic?

Portmaster **UI**

**Comment by Rexadev** [comment]
> I don't see how this is a bug. Portmaster cannot function without admin privileges. Else how would it prevent connections, set filters and view network traffic?

It doesn't ask for it. I have to assume it needs it

**Comment by AnorakArturo** [comment]
> > I don't see how this is a bug. Portmaster cannot function without admin privileges. Else how would it prevent connections, set filters and view network traffic?
> 
> It doesn't ask for it. I have to assume it needs it

So what you're saying is that Portmaster doesn't ask for admin privileges? It'd be helpful to the Dev's if you could provide more information other than saying it doesn't work. Best information you could give would be the debug info [How to share Debug info](https://github.com/safing/portmaster/issues/705#issue-1280282264)

**Comment by Rexadev** [comment]
Portmaster when started without Admin right, if it requires should ask for admin rights. So user doesn't have to assume it needs admin rights.

**Comment by AnorakArturo** [comment]
> Portmaster when started without Admin right, if it requires should ask for admin rights. So user doesn't have to assume it needs admin rights. @AnorakArturo

But Portmaster does ask for Admin rights. I've to authorize it every time I start the Core service.
It would be useful if you **upload debug information**...I don't even know what OS you're running it on :,)

**Comment by Rexadev** [comment]
I am suggesting a improvement, Portmaster will not start without admin right so if user starts without admin rights Portmaster should ask for it.
I am running windows 10

**Comment by AnorakArturo** [comment]
> I am suggesting a improvement, Portmaster will not start without admin right so if user starts without admin rights Portmaster should ask for it.
> I am running windows 10

Ah, then you should've marked it as a suggestion :)
Portmaster will ask for the admin rights when you start the service. At bootup, I think it already has authorisation and thus doesn't need to ask.

**Comment by dhaavi** [comment]
The Portmaster UI should open just fine without administrative rights, as it should run in user-space. The Portmaster Core Service is a system service that runs with system privileges. You cannot even start that yourself. The Portmaster UI prompts you for the password and then with the privileges it instructs Windows to start the service.

If you need admin rights to start the UI, this is either a bug - or, more likely - a misconfiguration on your device.

Did you start the UI with admin rights previously?

**Comment by Rexadev** [comment]
> The Portmaster UI should open just fine without administrative rights, as it should run in user-space. 

It doesn't for my 2 windows 10 and 11 devices

> The Portmaster Core Service is a system service that runs with system privileges. You cannot even start that yourself. The Portmaster UI prompts you for the password and then with the privileges it instructs Windows to start the service.

That is the point it doesn't ask me for password

> If you need admin rights to start the UI, this is either a bug - or, more likely - a misconfiguration on your device.

I tested on my Windows 10 and a fresh windows 11 installed device

> Did you start the UI with admin rights previously?

YES!

**Comment by ppacher** [comment]
>> Did you start the UI with admin rights previously?

> YES!

This might be the issue! Please check the permissions of the executables in the Portmaster Installation directory or consider to uninstall and re-install the Portmaster.

Please report back if the issue persists - the UI was never intended to be started with admin privileges

**Comment by Rexadev** [comment]
>  Please check the permissions of the executables in the Portmaster Installation directory

How?

>  consider to uninstall and re-install the Portmaster.

Did it
