### ISSUE TITLE
Add option to "Pause" Portmaster and DNS don't resolve when Portmaster is shutdown

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#830]
Instead of shutting down user can pause reducing the number of problems currently with DNS resolving.
The problem that after shutting down Portmaster DNS doesn't resolve.

Related:
https://github.com/safing/portmaster/issues/828
https://github.com/safing/portmaster/issues/829
https://github.com/safing/portmaster/issues/830
https://github.com/safing/portmaster/issues/835

**Comment by dhaavi** [comment]
Why leave it running and make it blind? You can as well just shut it down.

> The problem that after shutting down Portmaster DNS doesn't resolve.

If your DNS does not work without Portmaster, your network setup is broken. Portmaster does not make any network configuration changes.

**Comment by Rexadev** [comment]
> Why leave it running and make it blind? You can as well just shut it down.

In Pause Mode Disable all filters and rule only resolve DNS

> If your DNS does not work without Portmaster, your network setup is broken. Portmaster does not make any network configuration changes.

Is it related to theses Portmaster options - 

Ignore System/Network Servers
Block Bypassing
Use Secure Protocols Only

**Comment by ppacher** [comment]
> In Pause Mode Disable all filters and rule only resolve DNS

Go the the global settings and disable the [Privacy Filter Module](https://docs.safing.io/portmaster/settings#filter/enable)

> Windows 11 Fresh Install with vey minimal apps installed still has this bug.

What exactly is the bug? As @dhaavi  mentioned the Portmaster does not change any system configuration so if you shut it down your system should function as if you have never started it. Also the settings you mentioned does nothing if the Portmaster isn't even running.

**Comment by Rexadev** [comment]
> Go the the global settings and disable the [Privacy Filter Module](https://docs.safing.io/portmaster/settings#filter/enable)

Could move it a move accessible place

> What exactly is the bug? As @dhaavi mentioned the Portmaster does not change any system configuration so if you shut it down your system should function as if you have never started it. Also the settings you mentioned does nothing if the Portmaster isn't even running.

I tested it on WIndows 10 and a fresh Windows 11 that if Portmaster is shutdown DNS not resolve. Sometimes it don't start.

**Comment by ppacher** [comment]
> Could move it a move accessible place

I don't think that is a good idea. We're here to provide privacy by default for people without deep technical understanding. An option to easily pause all protection is not something I would like to provide new users with. It's just a matter of a few clicks if you really want that so the current position for that is fine!

> I tested it on WIndows 10 and a fresh Windows 11 that if Portmaster is shutdown DNS not resolve. Sometimes it don't start.

Please provide debug information before you shutdown Portmaster. Also please tell what you System DNS settings are and what `ping 1.1.1.1` and `ping safing.io` output

**Comment by ppacher** [comment]
WARNING: do not disable the Privacy Filter module as there's a bug currently that will prevent the Portmaster form starting correctly when restarted with the module disabled. This will actually kill all connections from your system and also prevents accessing the Portmaster UI. If you happened to do that, edit the `config.json` file in the Portmaster installation directory manually and set `filter/enable` to true again.
