### ISSUE TITLE
Add option to require admin password to Shutdown portmaster

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#831]
**What would you like to add or change?**:

**Why do you and others need this?**:

Security.

**Comment by Stofa14** [comment]
A very important point. It is like self defense feature by Antivirus.

**Comment by dhaavi** [comment]
Interesting idea - This is something we can take a look at when we reach stable.

**Comment by twoex** [comment]
This idea definitely makes a lot of sense. Perhaps to touch a little further, expand this further and have the option to disable modifying global settings or app specific settings...  etc...

**Comment by dhaavi** [comment]
I still think this is a great idea, but we won't be able to tackle this in the near future. Closing for now for better focus.

**Comment by ZMensRain** [comment]
I would love to see this feature added, it would allow parents who have children that use Linux or parents that don't want to use big tech solutions protect their children from harmful content.

**Comment by For1YeshuaLightsMyPath2Victory** [comment]
Please add this Admin Global Settings Password Protection feature. It will ensure prevention of unauthorized access or changes to all Portmaster settings once configured.. This would/should ALSO make it more difficult for ransomeware or malware on a system that may contain or become infested from being able to override PortMaster settings -- preventing further system infiltration -- OR perhaps infiltration at all!  -- Thank you Portmaster Team for looking into this.
