### ISSUE TITLE
Tray Icon doesn't show on boot but service runs on Windows 11 User Account.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#835]
~At Windows startup Portmaster UI opens up.~ I want it to only show in taskbar tray area.

Update- 
Since I report, UI doesn't start at boot but I still don't get icon in notification tray
![image](https://user-images.githubusercontent.com/62152714/190123436-4079aaeb-285d-4672-8177-726e34c594e7.png)

Tested Again. After Reinstalling Postmaster. On windows 11 problem still but works on Windows 10.

Related
https://github.com/safing/portmaster/issues/828
https://github.com/safing/portmaster/issues/829
https://github.com/safing/portmaster/issues/830
https://github.com/safing/portmaster/issues/835

another person https://github.com/safing/portmaster/issues/854

**Comment by dhaavi** [comment]
The UI should not automatically start at boot. Did you maybe enable that yourself?

**Comment by Rexadev** [comment]
> The UI should not automatically start at boot. Did you maybe enable that yourself?

Since I report, UI doesn't start at boot but I still don't get icon in notification tray

![image](https://user-images.githubusercontent.com/62152714/190123436-4079aaeb-285d-4672-8177-726e34c594e7.png)

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/190480453-d2b90ba6-7513-480c-a709-6f17a0feac86.png)
@dhaavi

**Comment by Rexadev** [comment]
Tested Again. After Reinstalling Postmaster. On windows 11 problem still but works on Windows 10.
@dhaavi

**Comment by dhaavi** [comment]
Are you using multiple user accounts at the same time as in #854?

**Comment by Rexadev** [comment]
> Are you using multiple user accounts at the same time as in #854?

Yes on Problem on my Windows 11 with User Account

**Comment by klisza1993** [comment]
I had problem that occur "Core service isnt ruunig" where service itself was actually sturted. So i have added a lots exceptions in Windows defender and Firewall.
mailny from here"C:\ProgramData\Safing\Portmaster\updates\windows_amd64" -> for each .exe
and now its working but Internet connection is veeery laggy ;) and portmaster notification says "failed to check for updates"

**Comment by ArkhamCookie** [comment]
I can confirm this happens on Windows 10 as well.

**Comment by walterm128** [comment]
My solution for windows 11

icacls "C:\ProgramData\Safing" /q /c /t /grant Usuarios:F  
or
icacls "C:\ProgramData\Safing" /q /c /t /grant Users:F

Registry:
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Run]
"PortmasterRUN"="\"C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\Portmaster\\Portmaster Notifier.lnk\""
