### ISSUE TITLE
Automatically update path for updated UWP apps

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#836]
![image](https://user-images.githubusercontent.com/62152714/188709951-d274ed66-a1a7-404f-aea1-1cf785801d25.png)

**What would you like to add or change?**:

**Why do you and others need this?**:

**Comment by ppacher** [comment]
This also seems to be a duplicate of https://github.com/safing/portmaster/issues/485

**Comment by Rexadev** [comment]
@dhaavi Related? https://github.com/safing/portmaster/commit/c22fb3316b33d5a2d00ce054d88651102c75c46c
