### ISSUE TITLE
Add option to navigate the UI via keyboard shortcuts

### ISSUE THREAD

**Issue by tukusejssirs** [safing/portmaster#838]
Related and partially fixed by safing/portmaster-ui#220.

---

I prefer keyboard-based navigation whenever possible. Currently, Portmaster does not seem to use any keyboard shortcuts, although I have found out that <kbd>F5</kbd> restarts the app.

Below are some suggestions. I don’t the defaults to be set to these shortcuts, however, it would be nice they all would be user-configurable. The list below is not finite.

| Shortcut                       | Action                                  |
|:-------------------------------|:----------------------------------------|
| <kbd>Ctrl</kbd>+<kbd>,</kbd>   | Open global settings                    |
| <kbd>Ctrl</kbd>+<kbd>F</kbd>   | Global search                           |
| <kbd>Ctrl</kbd>+<kbd>N</kbd>   | Open notifications                      |
| <kbd>Ctrl</kbd>+<kbd>P</kbd>   | Open prompts                            |
| <kbd>F2</kbd>                  | Toggle interface mode (simple/advanced) |
| <kbd>Up</kbd>, <kbd>Down</kbd> | Move up/down in a list                  |
| <kbd>Tab</kbd>                 | Move from one area to another\*         |

\* Sort of works, but it is not usable really.

---

An example keyboard navigation could work when managing incomming/outcomming rules manually:

- allow using <kbd>Tab</kbd> to move between `Allow/Block` rolling box and rule text box;
- allow using <kbd>Up</kbd> and <kbd>Down</kbd> when `Allow/Block` rolling box is selected to change its value;
- allow using <kbd>Up</kbd> and <kbd>Down</kbd> when rule box is selected to change the selected rule (including saved rules);
- allow using <kbd>Shift</kbd>+<kbd>Up</kbd> and <kbd>Shift</kbd>+<kbd>Down</kbd> when rule box is selected to move the selected rule (including rules that are being edited) up or down respectively;
- allow using <kbd>Space</kbd> to toggle selection (select/unselect) the selected rule:
   - this could be used to bulk move rules up or down, but also to bulk move them between app and global settings;
- allow using <kbd>E</kbd> to edit the selected rule;
- allow using <kbd>M</kbd> to (bulk) move the selected rule(s):
   - Portmaster should show a modal dialogue to let the user choose when to move the selected rule(s), i.e. either global settings (if they are not already in global settings) or a specific app;
- allow using <kbd>Esc</kbd> to hide the text box to add a new rule;
- allow using <kbd>Enter</kbd> to add the rule:
   - pressing <kbd>Enter</kbd> should after adding the rule open a new text box to enter a new rule.

**Comment by c-prompt** [comment]
Let me know if I should open this as a new issues: I see "Pro Tip: Inside the search box, use CTRL + SPACE to force loading suggestions." However, some of us on Windows use CTRL + SPACE for something else system-wide and this overrides our typical usage. You either need to make this shortcut configurable or get rid of it.

**Comment by eugenesvk** [comment]
What input was missing for this issue to be closed? Keyboard navigation is currently rather bad
