### ISSUE TITLE
Disable update check notifications when they were successful

### ISSUE THREAD

**Issue by tukusejssirs** [safing/portmaster#840]
**What would you like to add or change?**:

Disable update check notifications when they were successful. I think they just create a noise within the app.

It might be under some configuration option one can simply toggle.

**Why do you and others need this?**:

Remove unnecessary notifications.

**Comment by dhaavi** [comment]
Hey @tukusejssirs, thanks for your feedback.

The thing is, we currently do not know what triggered an update check. If it was you from within the UI, you'd defintiely want a notification that the update check has completed successfully.
The notification only stays for a minute and then disappears anyway. It should not appear on the desktop. I think this is an acceptable level.
I think it also good from a UX perspective - it assures the user that the software is up to date.

How often do you encounter the notification?

**Comment by tukusejssirs** [comment]
> The thing is, we currently do not know what triggered an update check.

Would it be acceptable by you to disable the notification for update results when there is currently no new Portmaster version available? I actually would like to be notified of new versions with a link to a changelog.

> The notification only stays for a minute and then disappears anyway.

That is not an issue, it disapears after a minute.

> It should not appear on the desktop.

If by `desktop` you mean desktop notifications, then yes, there are no desktop notifications about Postmaster updates.

> How often do you encounter the notification?

I have no idea, maybe once an hour.
