### ISSUE TITLE
Prompt should not disappear by themselves

### ISSUE THREAD

**Issue by tukusejssirs** [safing/portmaster#843]
**What would you like to add or change?**:

I have no idea what is the reason for prompts being closed by themselves, maybe it relates to the prompt timeout or connection timeout, however, sometimes I am too slow to allow/deny a connection, esp when there are multiple connections requests.

I suggest to add an option to disable the prompt timeout. When an app stops waiting for a connection, the prompt should not disappear, but the prompt should (for example) change its colour to reflect that the apps is no longer wating for the connection to be allowed.

**Why do you and others need this?**:

I want to deal with all connection requests/prompts.

**Comment by tukusejssirs** [comment]
> Also, on GNOME, If I miss the prompt I cannot see the allow/deny options in the notifications panel.

Just to provide additional information: I use Arch Linux + Sway + `swaync` (notifications centre) and when I don’t interact with the notification for pre-configured amount of time, it is moved to `swaync` (as expected), however, when the prompt disappears from `Notifications` widget of Portmaster, the notifications disappearrs from `swaync` too (as I would expect).

However, I’d like to make it _stop_ disappearing.

**Comment by ppacher** [comment]
Hi @tukusejssirs,

you can try to increase the prompt timeout setting: [Prompt Timeout](https://docs.safing.io/portmaster/settings#filter/askTimeout).
It defaults to 60 seconds, maybe try a higher value that will likely not cause a timeout.

**Comment by tukusejssirs** [comment]
Thanks, @ppacher! I have no idea why did I miss that setting. It indeed fixes my issue.
