### ISSUE TITLE
HTML code in Tip modals is output when searching the settings

### ISSUE THREAD

**Issue by tukusejssirs** [safing/portmaster#851]
**What happened**:

When I search global or app settings, it outputs HTML code in `Tip`/`Info` modal dialogues. For example, when searching for `prompt`, clicking on `Tip` besides `Prompt Timeout` in the global settings, shows the following text in the modal dialogue:

```html
Tip
<em class="search-result">Prompt</em> Timeout
How long the Portmaster will wait for a reply to a prompt notification. Please note that Desktop Notifications might not respect this or have their own limits.
```

**What did you expect to happen?**:

The HTML code should be parsed even when we search the settings.

**How did you reproduce it?**:

1. Open global or app settings.
2. Search for a setting using the search box.
3. Click on any `Tip`/`Info` button.

**Additional Information**:

OS: Arch Linux

**Debug Information**:

When needed, I’ll provide any addiotional information, incl debug information.

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/190899673-23f9aeb8-9d63-49d8-ac59-acf473477b2e.png)

**Comment by Rexadev** [comment]
@Raphty move this issue to UI repo

**Comment by Raphty** [comment]
confirmed this is still an issue

**Comment by dhaavi** [comment]
Thanks! Fixed in latest release.
