### ISSUE TITLE
Move Portmaster status icon to sidebar as an icon only

### ISSUE THREAD

**Issue by tukusejssirs** [safing/portmaster#852]
**What would you like to add or change?**:

Currently, the Portmaster status icon (the shield icon) is a widget and takes quite much of screen estate.

I suggest to move it to sidebar (where there are icons used to navigate between screen like Network Activity, All Apps, or Global Settings).

If you think you want to keep the widget as default, you could add a setting to change it to a smaller icon in the sidebar.

**Why do you and others need this?**:

Portmaster could better use the widget space / screen estate.

**Comment by ppacher** [comment]
Hi @tukusejssirs,
have you already seen the new side-dash which already entered the Beta release channel? Can you check if it's better now? The shield is still there in the side dash but the whole thing can be collapsed. If that's the case, the shield replaces the Safing logo on the top right

**Comment by tukusejssirs** [comment]
@ppacher, it is much better, however, I still think the status icon (without text description like `Secure`) could be moved to the side panel (I didn’t place it exactly in the centre). 

In the screenshot below, I would place it at one of the red dots (the top one might be preferable). In the lower part, I placed the shield icon as an example how it could look like.

![portmaster](https://user-images.githubusercontent.com/5111894/190637982-418f0b59-7f07-43e4-aa05-c3f8546a8372.png)
