### ISSUE TITLE
Widget height should be user-configurable

### ISSUE THREAD

**Issue by tukusejssirs** [safing/portmaster#853]
**What would you like to add or change?**:

Widgets use pre-defined, fixed height. This is contrary to the [screenshot](https://camo.githubusercontent.com/f1ec8daf052b6a3ed4a82b16807f969bb028324938300480c049e15054d3b9f7/68747470733a2f2f6173736574732e736166696e672e696f2f706f72746d61737465722f66756c6c2d696e746572666163652e706e673f) in `README.md` (which seems to be taken from an older, web app version of Portmaster).

For example, `Network Activity` widget shows only five apps (14 in total when counted the hidden apps accessible by scrolling).

I see two possible options to fix this, but I think both should be implemented:

1. a widget should always use all available space in widget space;
2. user can change the height of each individual widget using a mouse on the widget top/bottom border.

**Why do you and others need this?**:

Improve usage of widget space. Improve UX.

**Comment by ppacher** [comment]
Hi @tukusejssirs,

if I remember correctly you already had a look at the new Side-Dash in the BETA release channel? If so, is this still an issue?

**Comment by tukusejssirs** [comment]
@ppacher, yeah, I’ve been using the beta channel for ten days already.

Well, the reason why I raised this issue is because in the current stable channel, it seemed that there will be more widgets in the future. In the stable channel, there are currently three widget only:
- the shield,
- list of apps,
- and a widget where a user could output a parsed Markdown (static) string.

In the beta channel, you upgraded both the shield (a bit, you mostly added the SPN-related stuff to it) and the apps list. You seem to have removed the static widget (which was IMHO useless anyway). I’d still expect that Portmaster would have move widgets, as well as _dynamic_ widgets that the users could create or configure.

In the end, if there is no plan to create other widgets, then this issue is irrelevant and should be closed.
