### ISSUE TITLE
No postmaster notifier under windows 11 with other user then the admin

### ISSUE THREAD

**Issue by changemenemo** [safing/portmaster#854]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
No notification icon if I log in with a simple user and not the admin account.

Should we not create a specific user for portmaster which would not depend from the admin or any other user account be like that we would avoid the problem completely ? 

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Rexadev** [comment]
Duplicate- https://github.com/safing/portmaster/issues/835

**Comment by dhaavi** [comment]
We currently only support one user at the moment. We are looking into this.

The Portmaster Core Service runs a system service, which always uses the user SYSTEM.

The tray icon is a separate program, executed by the user that logs in.
Right now, this creates a PID file globally, which prevents other users from starting it at the same time.
