### ISSUE TITLE
[Discussion] Some Apps communicate to DNS servers over non DNS ports

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#860]
![image](https://user-images.githubusercontent.com/62152714/190864891-7d75178a-2ad9-4b30-b7a4-9f82b5a15a71.png)

Not only Windows apps, other apps too. Generally apps uses NextDNS IP (not my NextDNS IP).

Why? What they are doing?

Related: Make PortMaster block DNS servers domains and IPs so Apps don't bypass local domain blocklist.

**Comment by Rexadev** [comment]
> I'm not sure what you're showing us here and since you removed the parts of the IP address I also cannot confirm that those are talking to some DNS server. 

That is my NextDNS IP

>Also port 80 is HTTP so I'm pretty sure they don't do DNS ;)

That is what I trying to tell

> Please elaborate. Also I'm not sure what you mean with **"Generally apps uses NextDNS IP"**

I use NextDNS. Apps that try to connect DNS servers over non-standard ports either use my NextDNS IP (NextDNS gives everyone thier own IP),or IP that belongs to NextDNS, or 9.9.9.9.

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/191826285-905efee4-f4de-49b2-8f49-a49244aded9e.png)
![image](https://user-images.githubusercontent.com/62152714/191826434-9ac64855-bc15-4b57-b09c-1d33bd9ed690.png)

**Comment by Rexadev** [comment]
![Screenshot 2022-09-20 222930](https://user-images.githubusercontent.com/62152714/191829503-3f58c1ad-2c14-4eb6-a14f-c49ff4148d8b.png)
![Screenshot 2022-09-20 222923](https://user-images.githubusercontent.com/62152714/191829505-88d34fa8-3018-45a8-8d87-9af1a91326e2.png)

**Comment by Rexadev** [comment]
![DNS 80](https://user-images.githubusercontent.com/62152714/192097080-a4117fd9-00a9-4ddb-afcd-203f409fd0cc.png)

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/192100284-20509e13-28f7-4dff-b6de-a6d070c7dff4.png)

**Comment by ppacher** [comment]
I'm not sure what the issue that you're reporting here is. I guess you have NextDNS configured as your system wide DNS resolver or otherwise use NextDNS. I don't know why software would try to access anything using port 80 (http) instead of encrypted HTTPS (443). However, that's nothing the portmaster can do about it. If you feel that these apps should not connect to those servers then block them. If you fear they are using some kind of hand-rolled name-resolution (i.e. not using standart ports) than "Force Block P2P". 

I'm closing this here since it only takes a lot of time resources on our side which we just don't have. We're a rather small team building the Portmaster and the SPN. If you want to know why those applications communicate with the servers you mentions, please ask them!

**Comment by ppacher** [comment]
Also, if you insist on not providing debug information we will likely not be able to even debug your issues and it will require a lot more effort on our side than if you would just start posting debug information.

If you don't like posting that public on Github you can always report bugs privately at hello@safing.io.

Not providing debug information really causes a lot of overhead that would better be spent in improving and working on our software.

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/193411432-cb6797e9-87f0-47fe-8176-a2978eec95b8.png)

@ppacher Portmaster it self does it

![image](https://user-images.githubusercontent.com/62152714/193411455-e42f73f5-9960-4231-8789-ac7dac71d5c8.png)

**Comment by ppacher** [comment]
Still not sure what you're showing us here. the first screenshot is Portmaster communicating with a DNS server over DNS port 53.
The section one isn't even related to portmaster and shows some other app talking to a different IP on https.

Also, where's the debug info?

**Comment by ppacher** [comment]
While you're right that the IP seen there belongs to nextdns, you didn't even answer my previous comment/question if you have somehow configured NextDNS so I'm not sure what you want us to do here

**Comment by Rexadev** [comment]
> the first screenshot is Portmaster communicating with a DNS server over DNS port 53.
>>I don't know why software would try to access anything using port 80 (http) instead of encrypted HTTPS (443). However, that's nothing the portmaster can do about it. If you feel that these apps should not connect to those servers then block them. If you fear they are using some kind of hand-rolled name-resolution (i.e. not using standart ports) than "Force Block P2P".

Even Portmaster does the same thing itself

> The section one isn't even related to portmaster and shows some other app talking to a different IP on https.
 
As Issues title says "Some Apps communicate to DNS servers over non DNS ports"

>> I guess you have NextDNS configured as your system wide DNS resolver or otherwise use NextDNS.
> you didn't even answer my previous comment/question if you have somehow configured NextDNS

I have created a NextDNS account and use the provided DNS in Portmaster
