### ISSUE TITLE
Update Documentation for DoH syntax

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#861]
https://docs.safing.io/portmaster/guides/dns-configuration says protocol://ip:port?parameter=value&parameter=value is to be use but DoH on PortMaster uses https:// format

**Comment by ppacher** [comment]
DoH stands for DNS-over-HTTPS so the protocol for that is HTTPS. Though, we should mention that there

**Comment by Rexadev** [comment]
Reopen
