### ISSUE TITLE
[Question] How to block by IP protocol.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#862]
Documentation (https://docs.safing.io/portmaster/settings#filter/endpoints) says I can use ICPM.
Does it support all protocols? Can I use number? Is there a way to block all protocols except TPC/UDP with something like protocol=*

**Comment by ppacher** [comment]
As the docs say you can use numbers. Names are supported for the following: [see here](https://github.com/safing/portmaster/blob/develop/network/reference/protocols.go)

To block all protocols except TCP/UDP you would use:
```
Allow * TCP
Allow * UDP
Block *
```
