### ISSUE TITLE
Add VPN and TOR to Network scope to have some apps be able to connect only on it.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#869]
**What would you like to add or change?**:

**Why do you and others need this?**:
Some apps run in background or user may accidently run it. and the user may not want expose themselves.

**Comment by ppacher** [comment]
There's just no way to support all possible VPN implementations so this is in no way feasible to do. Also, TOR only works if you have TOR installed and configured locally. Please provide more information on the actual use case and how you would image that to work

**Comment by Rexadev** [comment]
For VPN on Windows 
You can use Windows 10's inbuilt VPN client. 
or integrate OpenVPN/Wireguard into Postmaster as modules

For TOR -
Portmaster would have to integrate TOR in it.
