### ISSUE TITLE
I see soo many DNS53 requests

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#871]
Should block port 53
![image](https://user-images.githubusercontent.com/62152714/190924230-67b538eb-ac56-472c-9594-04c2485ed418.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by ppacher** [comment]
Same question as in https://github.com/safing/portmaster/issues/873:

You see those connections because the System DNS Client tried to connect to those name-servers to resolve DNS queries. The portmaster intercepted those requests and answered them on it's own using the configured DNS servers (so likely DoT or DoH). If you open up the details of those connections you will see that `reason` is set to "redirecting rogue dns query" and the verdict is set to `RerouteToNs`. That means that this connection never left your system but has been handled by the portmaster.

Blocking the system DNS client would kill network for almost all your applications that's why the whole System DNS client get some special treatment by the Portmaster and all it's connections are marked as "internal" and only shown in developer mode.

**Comment by shtirlic** [comment]
@ppacher Is there any way to bypass any DNS security measures for selected application? I am on Windows and running VirtualBox  Linux VM, so having DNS bypass option will be greatly anticipated.

**Comment by Rexadev** [comment]
> @ppacher Is there any way to bypass any DNS security measures for selected application? I am on Windows and running VirtualBox Linux VM, so having DNS bypass option will be greatly anticipated.

You mean some apps will use different DNS?

**Comment by ppacher** [comment]
Hi @shtirlic, thanks for asking.

Unfortunately that is not possible as the redirection of the DNS queries happens in the kernel before the Portmaster actually handles the connection and searches for the origin application. So excluding some applications and let them bypass DNS is not possible.

Do I understand correctly that you want your linux VM to use a different DNS server? What are the exact symptoms/issues you're facing? Maybe we can find another work-around for your case.

**Comment by shtirlic** [comment]
@Rexadev yes, 

@ppacher  here is my setup:

Lan (WIFI) Router with DNS server forward and cache:  10.0.110.1

Windows 11 laptop on Wifi

> Linux VirtualBox guest : 
- > Internal VB nat interface (10.0.2.15/24) enp0s3
- > Internal VB host interface (192.168.56.109/24) enp0s8

Result from /etc/resolv.conf resolvectl output on linux guest (systemd-resolved stub mode):

``` 

cat /etc/resolv.conf

nameserver 127.0.0.53
options edns0 trust-ad
search .


resolvectl 

Global
           Protocols: +LLMNR +mDNS -DNSOverTLS DNSSEC=no/unsupported
    resolv.conf mode: stub
Fallback DNS Servers: 1.1.1.1#cloudflare-dns.com 9.9.9.9#dns.quad9.net 8.8.8.8#dns.google
                      2606:4700:4700::1111#cloudflare-dns.com 2620:fe::9#dns.quad9.net 2001:4860:4860::8888#dns.google

Link 2 (enp0s3)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.0.110.1
       DNS Servers: 10.0.110.1

```
Sample outputs from nslookup
```
[root@arazu-arch ~]# nslookup google.com
;; communications error to 127.0.0.53#53: timed out
Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   google.com
Address: 142.250.179.206
;; communications error to 127.0.0.53#53: timed out
Name:   google.com
Address: 2a00:1450:400e:811::200e

[root@arazu-arch ~]# nslookup google.com 10.0.110.1
;; communications error to 10.0.110.1#53: timed out
;; communications error to 10.0.110.1#53: timed out
;; communications error to 10.0.110.1#53: timed out
;; no servers could be reached

```
