### ISSUE TITLE
[Help] Is my System DNS Client resolving DNS for chrome

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#873]
![image](https://user-images.githubusercontent.com/62152714/191018589-6ebaa128-aabc-49dd-af60-c34f45a9c42a.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by ppacher** [comment]
Hi, the short answer is yes. The system DNS client is used by all applications that do not implement DNS resolution on their own (which is about 98% of commonly installed software). Thats why the system dns client is automatically granted to even resolve DNS queries that would be blocked by the origin app profile. Note that only the DNS request is allowed and a subsequent connection attempt by an application will be blocked as expected.

**Comment by Rexadev** [comment]
> Hi, the short answer is yes. The system DNS client is used by all applications that do not implement DNS resolution on their own (which is about 98% of commonly installed software). Thats why the system dns client is automatically granted to even resolve DNS queries that would be blocked by the origin app profile. Note that only the DNS request is allowed and a subsequent connection attempt by an application will be blocked as expected.

Those are redirected to portmaster? Why they show is it as DNS53. I want to use DoT only

**Comment by ppacher** [comment]
See answer here: https://github.com/safing/portmaster/issues/871
