### ISSUE TITLE
Add option to remove MAC Address from IPv6

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#877]
**What would you like to add or change?**:

**Why do you and others need this?**:

Privacy

**Comment by ppacher** [comment]
The Portmaster is not a network configuration tool so configuring IPv6 addresses is not in the scope of what we want the Portmaster to do.

**Comment by Rexadev** [comment]
> The Portmaster is not a network configuration tool so configuring IPv6 addresses is not in the scope of what we want the Portmaster to do.

Randomizing EUI for Privacy.
