### ISSUE TITLE
Warn user about needing restart. On Windows 10 updating needs reboot. Windows 11 doesn't. 

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#884]
I switched from Release Stable to Beta and Internet stopped working and Portmaster could be started I had to restart the OS.
Also happen when pdating from 9.5 to 9.6

To reiterate - Internet stopped working and Portmaster could be started I had to restart the OS.
----------------------------------

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
Nothing changes when you switch release channel. It just downloads some new resources. They are only applied when you restart.

If you can reproduce, please provide debug info.

**Comment by Rexadev** [comment]
> Nothing changes when you switch release channel. It just downloads some new resources. They are only applied when you restart.
> 
> If you can reproduce, please provide debug info.

I know. To reiterate -  Internet stopped working and Portmaster could be started I had to restart the OS.

**Comment by ppacher** [comment]
There's still no debug information and it's still unclear what the issue is. Just changing the release-channel setting will not change anything unless you actually reboot your system.

Please provide debug information and further elaborate on your issue.
