### ISSUE TITLE
UI not working correctly on nvidia & wayland

### ISSUE THREAD

**Issue by FlyinPancake** [safing/portmaster#888]
**What happened**:

Opened portmaster UI from app menu with the bg service running in the background

![image](https://user-images.githubusercontent.com/36113055/191985839-d313814d-7ed0-4879-bc4d-79ac6b4f0289.png)

**What did you expect to happen?**:

The app to open normally

**How did you reproduce it?**:

Have a Fedora 37 pc with nvidia gpu on wayland, launch portmaster

Running with 
```sh
/opt/safing/portmaster/portmaster-start app --data=/opt/safing/portmaster -- --enable-features=UseOzonePlatform --ozone-platform=wayland
```
works but I don't get a titlebar then.

**Debug Information**:

[2022-09-23-14-36-20.log](https://github.com/safing/portmaster/files/9634621/2022-09-23-14-36-20.log)
[2022-09-23-14-36-20.error.log](https://github.com/safing/portmaster/files/9634622/2022-09-23-14-36-20.error.log):

**Comment by ppacher** [comment]
Hi @FlyinPancake,

thanks for the report. We already have a fix for that in the develop branch but it has not yet been released to the STABLE release channel yet.

Can you please try if using `--enable-features=UseOzonePlatform,WaylandWindowDecorations  --ozone-platform=wayland` works for you?`
