### ISSUE TITLE
[Feature] Add option to disable DNS servers.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#889]
### Example
I have entered many DNS servers in my postmaster. In many situation I would like disable or enable some or totally use somethings else.

### UI

Make it drag-able to a disable section

Or add toggles

1. If 9.9.9.9 is over blocking user switchs to 1.1.1.1 or 8.8.8.8
2. If user finds too latency he switches from NextDNS to 8.8.8.8
3. User using public Network and doesn't want to look different he switched from NextDNS or 9.9.9.9 to 8.8.8.8

**Comment by ppacher** [comment]
I'm not sure what the real use case is here and what other users would benefit from (please use the ISSUE TEMPLATE).

The portmaster will use the DNS servers from top-to-bottom. Why would you like to disable some of your configured DNS servers in one situation but enable others? Please explain your use case!

**Comment by Rexadev** [comment]
1. If 9.9.9.9 is over blocking user switchs to 1.1.1.1 or 8.8.8.8
2. If user finds too latency he switches from NextDNS to 8.8.8.8
3. User using public Network and doesn't want to look different he switched from NextDNS or 9.9.9.9 to 8.8.8.8

@ppacher

**Comment by itsnotsaved** [comment]
@Rexadev check a nearby region / low latency and high performance public dns server and use it. i think we don't change them often except rarely. or use your ISP dns servers or buy a server/vps and set-up your own (pihole, coredns, adguardhome)
