### ISSUE TITLE
Ping.exe shows as Unidentified App and is blocked

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#890]
![image](https://user-images.githubusercontent.com/62152714/192084166-b3092bf7-aeb1-40f6-a815-2d44af098073.png)

![image](https://user-images.githubusercontent.com/62152714/192084126-ae5c0887-f48d-46cd-b9ba-ab0373897946.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by ppacher** [comment]
Ping on windows uses kernel internals to send a ICMP echo request. That's just how it works on windows.

**Comment by Rexadev** [comment]
> Ping on windows uses kernel internals to send a ICMP echo request. That's just how it works on windows.

But how do I ping ?

**Comment by dhaavi** [comment]
All "pings" are handled by the Kernel. The kernel does not tell us which process a "ping" comes from.
This is why all of them go into "Unidentified App".

Note: We don't monitor replies to closed issues. They might get missed.

**Comment by Rexadev** [comment]
> Note: We don't monitor replies to closed issues. They might get missed.

There are a few issues I would like you to re open. I marked them [@dhaavi or @ppacher reopen]

**Comment by Rexadev** [comment]
> All "pings" are handled by the Kernel. The kernel does not tell us which process a "ping" comes from. This is why all of them go into "Unidentified App".

Simplewall (FOSS) maybe you can borrow their technique

**Comment by Flashwalker** [comment]
Same on linux. ping is recognized as Other connections
