### ISSUE TITLE
Country and IP/Domain blocklists should have separate whitelist from User blocklist. Make it easier to manage rules.

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#891]
### Add option to add domain to Country Block exception

Example - 

I have blocked country A and some sites others host there. I would like to add website domains to an allow list ex- domain.com but that will also allow all it's sub domains in the domain blocklist.  I would like to block sub domains from blocklist ex- sub.domain.com and IP blocklists but to reiterate exempt it from country blocklist.

Any kind of ordering of allow-block-domain-IP will not work. This will need a separate feature

Related:https://github.com/safing/portmaster/issues/741

---

Make a list for Blocklist whitelist too

---

### Also

Make it Easier to organize Allow domain list.
Like using text file.
The UI is too big.

Add option to sort Domains from a site site together

There are 3 reasons to add a domain to allow list - Over-blocking domain list, Over-blocking IP list, or adding exception to blocked Countries. The other 2 are unlikely as compared to country.
I change the wording of the original post please try again.

![image](https://github.com/safing/portmaster/assets/62152714/83947e1e-eb18-492f-b66c-4f49a29f7019)

**Comment by ppacher** [comment]
I'm sorry but I don't understand your use case here. Please elaborate with some better explained examples.

**Comment by Rexadev** [comment]
> I'm sorry but I don't understand your use case here. Please elaborate with some better explained examples.

There are 3 reasons to add a domain to allow list - Over-blocking domain list, Over-blocking IP list, or adding exception to blocked Countries. The other 2 are unlikely as compared to country. 
I change the wording of the original post please try again.

**Comment by Rexadev** [comment]
![image](https://user-images.githubusercontent.com/62152714/192159447-5e4e410f-4857-4d74-a464-8e3bdc6ef3ef.png)

@ppacher

**Comment by Raphty** [comment]
stale for over a year
