### ISSUE TITLE
Q: Does Portmaster block all Windows network traffic?

### ISSUE THREAD

**Issue by FrostBlade5** [safing/portmaster#894]
Portmaster is a kernel extensions right? When i shutdown windows and reboot it, is there a chance microsoft sends data to their servers before portmaster is loaded?

Does portmaster monitor ALL network traffic? Windows is a bad choice regarding privacy but some programs only work on windows and not linux, that's why i use windows. That said, i configured windows for the best possible privacy with some scripts and tools, anyways i just want to know if when i use protmaster is windows still sending some data to microsoft? Is there parts of windows which is a closed source system, that portmaster cannot monitor and has no access to and so it cannot monitor all network traffic?
For example:
![Capture](https://user-images.githubusercontent.com/91756004/192136742-77c1ca38-e1f9-4a37-9057-e873b3f54936.PNG)
There is no option to fully disable data reports to microsoft, but with portmaster i imagine i can block connection to microsoft servers and so they wont get any info about my device or what im doing on it, is that correct? does portmaster monitor all network traffic or can windows still phone home?

**Comment by ppacher** [comment]
While @dhaavi is better suited in answering this, I feel like https://github.com/safing/portmaster/issues/701 might contain the information you are seeking for.

**Comment by FrostBlade5** [comment]
> While @dhaavi is better suited in answering this, I feel like #701 might contain the information you are seeking for.

Thanks for the reply, i read #701 and from what i understand untill a future version protects my pc from connecting to ms server i will have to pull my ethernetcable and plug it once the pc is fully loaded which means untill portmaster is fully loaded to prevent ms from establishing any connecting with my personal device.

Anyways this was only one question i had, but what about the second question i asked above?

**Comment by FrostBlade5** [comment]
Can microsoft still phone home and send diagnostics and feeback data when i use portmaster?

**Comment by dhaavi** [comment]
> Does portmaster monitor ALL network traffic?

Yes.

> Windows is a bad choice regarding privacy but some programs only work on windows and not linux, that's why i use windows.

We understand. We don't judge. We are here for you. ;)

> That said, i configured windows for the best possible privacy with some scripts and tools, anyways i just want to know if when i use protmaster is windows still sending some data to microsoft?

I don't know if we block everything you'd want by default, but you can definitely configure Portmaster to do so.

> Is there parts of windows which is a closed source system, that portmaster cannot monitor and has no access to and so it cannot monitor all network traffic?

Portmaster is becomes part of the network stack and sees all traffic. While Microsoft _could_ build something to circumvent that (*cough cough* like Apple did), we have no indication that this is the case.
Portmaster sees and can block any traffic, even from Windows itself. (Most of the stuff does not run in the Kernel anyway.)

> Thanks for the reply, i read https://github.com/safing/portmaster/issues/701 and from what i understand untill a future version protects my pc from connecting to ms server i will have to pull my ethernetcable and plug it once the pc is fully loaded which means untill portmaster is fully loaded to prevent ms from establishing any connecting with my personal device.

Yes, this is currently the safest way to go about this.

**Comment by FrostBlade5** [comment]
Thank you for the reply this is very helpful and interesting!
You basically just told me i can configure portmaster to block every connection that could be a risk to my privacy, you are heros, seriously we need more people like you, i can't thank you enough for providing portmaster!!

I hope no matter what the future brings you will never sell out no matter how much they offer you, to many companys made this mistake already, but at the end the people pay the price.

Without people like you guys working on portmaster i fear every person on our planet could face a dictatorship and mass surveillance future like china, and looking at what is happening inside of china i would never want to exist in a place like that.
Freedom in china is dead and so are the people inside.

Your work is of the highest importance, no money will ever have value like that.

Getting back to the topic, i'm on windows 10 for now but should i ever install a new version of windows and microsoft decides to build something where portmaster has no access and cannot monitor network traffic (like Apple did), where can i learn about this situation, where would i be informed that version xyz of windows is not secure to use with portmaster? Or is this the reason why macOS is listed as not supported on your website and will windows also lose support if microsoft builds that crap? Apple is pure spyware anyways..

In portmaster i found an entry named System DNS Client, do you have a documentation that explains what that is or can i find that information elsewhere?
Anyways, in System DNS Client i found svchost.exe located at C:\Windows\System32 was trying to establish a connection with services.gfe.nvidia.com and ctldl.windowsupdate.com, both connections are blocked, without portmaster i wouldn't be able to block this, need to thank you once again.

Network Noise is another entry i found in portmaster, same question is there a documentation on what it is or can i find that information elsewhere?

Thanks for taking the time to reply to my questions, hope you are having a great day!

**Comment by FrostBlade5** [comment]
Oh and, as good as portmaster is im afraid i can do absolutly nothing against physical spyware that is integrated into the computer hardware, for example in the cpu, intel management engine or amt vpro? I Heared all modern computers after 2008 have that backdoor built-in... what a nightmare.
