### ISSUE TITLE
[Help] IP Blocklist not working

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#899]
**Pre-Submit Checklist**:
- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
https://raw.githubusercontent.com/dibdot/DoH-IP-blocklists/master/doh-ipv4.txt list is not working
It is in the format -
```
1.0.0.1             # 1dot1dot1dot1.cloudflare-dns.com
1.0.0.2             # security.cloudflare-dns.com
1.0.0.3             # family.cloudflare-dns.com
1.1.1.1             # 1dot1dot1dot1.cloudflare-dns.com
1.1.1.2             # security.cloudflare-dns.com
1.1.1.3             # family.cloudflare-dns.com
3.216.94.195        # dns.api.staging.globuscs.info
```

@dhaavi Another one https://www.spamhaus.org/drop/edrop.txt

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
Please fill out the template.

**Comment by Rexadev** [comment]
@dhaavi 
![image](https://user-images.githubusercontent.com/62152714/192548895-1569e72e-c770-45a4-9d0d-80958a0fc763.png)

**Comment by Raphty** [comment]
This is an old and stale issue, if you encounter this issue, pleas open a new issue
