### ISSUE TITLE
Autodetect Network Rating detect Trusted on Enterprise Networks

### ISSUE THREAD

**Issue by h4ckerle** [safing/portmaster#903]
**What happened**:

I enabled auto-detect Network Rating in the Dev Interface on a WPA2 EAP Network, which I before had set to untrusted manually. When setting to auto detect it auto changed to trusted.

**What did you expect to happen?**:

Either keep the manually set rating and "learn" it or see Enterprise Wifis as untrusted by default (as it is an enviroment which is public)

**How did you reproduce it?**:

Issue is reproducible. You have to have Dev Interface enabled to change manual <-> autodetect and have to have the network rating system enabled.

**Debug Information**:

<details>
<summary>Version 0.9.6</summary>

```
Portmaster
version 0.9.6

commit tags/v0.9.6-0-g084a1a26545de7ec373fcefa31f8a2bdb96b92a8
built with go1.19 (gc) linux/amd64
  using options main.go
  by user@docker
  on 23.09.2022

Licensed under the AGPLv3 license.
The source code is available here: https://github.com/safing/portmaster
```

</details>

<details>
<summary>Platform: arch "rolling"</summary>

```
System: arch linux (arch) "rolling"
Kernel: 5.19.11-zen1-1-zen x86_64

```

</details>

<details>
<summary>Status: Untrusted</summary>

```
ActiveSecurityLevel:   Untrusted
SelectedSecurityLevel: Untrusted
ThreatMitigationLevel: Trusted
CaptivePortal:         
OnlineStatus:          Online
```

</details>

<details>
<summary>Config: 11</summary>

```
core/enableNetworkRating: true
core/expertiseLevel: developer
dns/dontResolveSpecialDomains: 6
dns/nameservers: [redacted]
dns/noInsecureProtocols: 7
filter/blockInbound: 6
filter/blockLAN: 6
filter/blockLocal: 6
filter/blockP2P: 6
filter/lists: [TRAC MAL DECEP BAD CB-MW UNBREAK]
filter/preventBypassing: 6
```

</details>

<details>
<summary>Resolvers: 4/4</summary>

```
private-private.dns.nextdns.io (dot://xxxx-xxxx.dns.nextdns.io:853#config)
  dot://xxx-xxxx.dns.nextdns.io:853#config
  Failing: false

Quad9 (dot://dns.quad9.net:853#config)
  dot://dns.quad9.net:853#config
  Failing: false

00.00.0.2 (dns://00.00.0.2:53#system)
  dns://00.00.0.2:53#system
  Search Domains: .no.no.
  Failing: false

192.168.1.2 (dns://192.168.1.2:53#system)
  dns://192.168.1.2:53#system
  Search Domains: .no.no.
  Failing: false
```

</details>

<details>
<summary>SPN: disabled (module disabled)</summary>

```
HomeHubID:    
HomeHubName:  
HomeHubIP:    
Transport:    
---
Client:       true
PublicHub:    false
HubHasIPv4:   false
HubHasIPv6:   false
```

</details>

<details>
<summary>Compatibility: IPTables Chains (36)</summary>

```
v4
  filter
    INPUT
    FORWARD
    OUTPUT
    PORTMASTER-FILTER
  nat
    PREROUTING
    INPUT
    OUTPUT
    POSTROUTING
    PORTMASTER-REDIRECT
  mangle
    PREROUTING
    INPUT
    FORWARD
    OUTPUT
    POSTROUTING
    PORTMASTER-INGEST-INPUT
    PORTMASTER-INGEST-OUTPUT
  raw
    PREROUTING
    OUTPUT
v6
  filter
    INPUT
    FORWARD
    OUTPUT
    PORTMASTER-FILTER
  nat
    PREROUTING
    INPUT
    OUTPUT
    POSTROUTING
    PORTMASTER-REDIRECT
  mangle
    PREROUTING
    INPUT
    FORWARD
    OUTPUT
    POSTROUTING
    PORTMASTER-INGEST-INPUT
    PORTMASTER-INGEST-OUTPUT
  raw
    PREROUTING
    OUTPUT
```

</details>

**Comment by h4ckerle** [comment]
Hey @Raphty what input is needed? If there's anything you need, i'd be happy to provide it.

**Comment by Raphty** [comment]
@h4ckerle thanks for offering help! super valuable.

But there are a couple things here:
- the network rating is a deprecated feature, I hope we are communicating this clear enough on all the places
- we want to get into this, but we changed ideas on how to tackle this, and it technically different so not compatible with the network rating
- the issue was open for over halve a year and not picked up, so to keep the issues current and focused I wanted to clear stale ones out

I hope you understand 😅 

if you have ideas on how to fix the issue, pleas let me know, this might be helpful for the automatic profile switching we are thinking about. A more powerful option of the network rating, where you can change more settings with more freedom.
