### ISSUE TITLE
[Bug] Old version files are not auto deleted

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#906]
![image](https://user-images.githubusercontent.com/62152714/193232910-2746563d-f347-4bc0-9665-8f9d9d05ef55.png)
![image](https://user-images.githubusercontent.com/62152714/193233497-70c488d1-3c0b-4ad4-b0cb-d245c8ed8423.png)
![image](https://user-images.githubusercontent.com/62152714/193233627-4360aba2-4392-4fb9-b544-d2081a687ac9.png)

### Using HIPS I can see some are still being used/running - 
C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-5\portmaster-app_v0-2-5.exe
C:\ProgramData\Safing\Portmaster\updates\windows_amd64\notifier\portmaster-notifier_v0-3-2.exe

### Exe being used have names of old versions
![image](https://user-images.githubusercontent.com/62152714/193287959-1ef62938-efc7-4090-9b0d-920af870a227.png)

**Comment by dhaavi** [comment]
Yes, you may delete old resources. However, it should automatically delete resources more than 2 versions back.
Leaving this open for investigation.

**Comment by Rexadev** [comment]
> Yes, you may delete old resources. However, it should automatically delete resources more than 2 versions back. Leaving this open for investigation.

Using HIPS I can see some are still being used/running - 
C:\ProgramData\Safing\Portmaster\updates\windows_amd64\app\portmaster-app_v0-2-5\portmaster-app_v0-2-5.exe
C:\ProgramData\Safing\Portmaster\updates\windows_amd64\notifier\portmaster-notifier_v0-3-2.exe

**Comment by Rexadev** [comment]
@dhaavi problem still in lastest release

**Comment by Raphty** [comment]
Hey @Rexadev so you say it does keep versions older then 2 releases back? because as Daniel was saying 2 versions is expected behavior
