### ISSUE TITLE
Include these Blocklists

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#909]
https://www.spamhaus.org/drop/edrop.txt
https://github.com/pallebone/StrictBlockPAllebone
https://github.com/tg12/badrep_report
https://github.com/T145/black-mirror
https://github.com/LittleJake/ip-blacklist
https://github.com/Rezanans-wow/BZ-antiddos

**What would you like to add or change?**:

**Why do you and others need this?**:

**Comment by dhaavi** [comment]
Please elaborate on them and tell us why you think they are needed in addition to our current ones and also check if their quality is good enough.
