### ISSUE TITLE
No icons for apt programs on Debian

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#910]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

I am on Debian Testing . Portmaster doesn't show icons for any programs.

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
Expected behavior.
