### ISSUE TITLE
Autoruns PortmasterKext is disabled. Should I enable it?

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#913]
![image](https://user-images.githubusercontent.com/62152714/193421488-444abce0-8844-466e-bcfd-73329b6080e8.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
No.
