### ISSUE TITLE
[Help] Is it normal for Portmaster to connect to 10.0.0.0/8 :53 when using ProtonVPN

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#914]
![53 10 0 0 0](https://user-images.githubusercontent.com/62152714/193444538-7c1c549e-2979-4aac-a342-42ef4558d029.PNG)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by dhaavi** [comment]
Depends.
