### ISSUE TITLE
No internet connection after uninstall on Windows 11

### ISSUE THREAD

**Issue by a-rekkusu** [safing/portmaster#916]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [x] [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [x] [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
- I downloaded the installer from the website and installed it with the default settings
- I tried it out a bit, but changed nothing in the configuration
- I uninstalled it with the checkbox set for Data (I was in the same session though, without reboot)
- I saw I had no network connection and figured it might be because of Portmaster
- I rebooted, and still had no internet
- I could connect to my WiFi Network but have no communication there. I can't access devices on the local network either
- I tried to connect to a mobile Hotspot from my Smartphone, but no internet there either
- I tried to reinstall Portmaster from the exe to see if it would work again, but it failed because it fetches the release via the internet (I still have some rudimentary directory of this reinstall attempt in the ProgramData now)
- I reset the network options from the windows settings back to the default
- I executed the two commands described in the [Portmaster FAQ](https://docs.safing.io/portmaster/install/windows#known-issues) in an administrative cmd
- I faced a permission issue on the first command, where it said "failed", "access denied" at the "cleanup neighbours" step
- I troubleshooted this and fixed the registry entry as described in [this](https://appuals.com/how-to-fix-the-netsh-int-ip-reset-failed-problem-on-windows/) article 
- I rebooted, executed the commands again (now successfully)
- I rebooted again, but still have no internet connection
- At this point I'm out of guesses and need your guys' help to restore my internet connection, please

**What did you expect to happen?**:
- Internet connection should work normally as before

**How did you reproduce it?**:
-

**Debug Information**:

I can try to find if there is some logs from the reinstall attempt in the directory, but I'm not sure. I will update with the logs if I have some, but need to reboot to the Windows partition to do so.

Edit: Unfortunately I have no logs to share here.

<!--
Paste debug information below:
- General issue: Click on "Copy Debug Information" on the Settings page.
- App related issue: Click on "Copy Debug Information" in the dropdown menu of an app in the Monitor view.

**Comment by a-rekkusu** [comment]
I have actually fixed it already. Here's what did it for me now:
I triggered a problem solving process for the WiFi adapter. At the end it suggested me to reset all network options, which I did. Then it said the system would reboot in 5 minutes. I waited those 5 minutes for it to do this automatically. After the reboot, it was fixed.
When I first reset the network configuration in Windows, I wanted to reboot immediately, so I didn't wait those 5 minutes and shut it down manually. I didn't think it would make a difference, and I'm still not entirely sure this is where the problem was. 
Maybe it helps somebody else down the road.

**Comment by dhaavi** [comment]
Hey @a-rekkusu, thanks for reporting this problem and outlining a solution!

We actually have a section on this on the Windows install docs, I guess we have to surface it better:
https://docs.safing.io/portmaster/install/windows#network-issues-after-stopping-or-uninstalling-portmaster
