### ISSUE TITLE
PortMaster doesn't work well with HIPS

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#922]
[HIPS](https://en.wikipedia.org/wiki/Intrusion_detection_system#:~:text=intrusion%20prevention%20system%20(-,HIPS,-)%3A%20an%20installed)

When PortMaster is shutdown or UI is closed needs HIPS to be disabled to start.
When updating PortMaster is required HIPS to be disabled or a Windows reboot.

### Related-
https://github.com/safing/portmaster/issues/622 (Probably same cause)
https://github.com/safing/portmaster/issues/884 (Probably same cause)
https://github.com/safing/portmaster/issues/828 (Probably same cause)
https://github.com/safing/portmaster/issues/829 (Maybe)

-----------------------------

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

https://github.com/safing/portmaster/issues/622

**Comment by dhaavi** [comment]
Please configure your HIPS to allow everything from the Portmaster data directory. Check the install guide for your OS for details.

**Comment by Rexadev** [comment]
> Please configure your HIPS to allow everything from the Portmaster data directory. Check the install guide for your OS for details.

https://github.com/safing/portmaster/issues/622
