### ISSUE TITLE
"Incoming Rules" are ignored when "Force Block Incoming Connections" is enabled

### ISSUE THREAD

**Issue by NicolasGoeddel** [safing/portmaster#926]
When "Force Block Incoming Connections" is enabled globally also the "Incoming Rules" are ignored even when ICMP is allowed.
Because ICMP is no specific app I can not disable "Force Block Incoming Connections" on app level to allow ICMP packets.
Instead I disabled that switch globally and and added these incoming rules:
![image](https://user-images.githubusercontent.com/1520064/194933229-856e9b50-f0e9-40b4-a6fc-757eeaa19eed.png)

**What would you like to add or change?**:
The global "Incoming Rules" should be able to override the "Force Block Incoming Connections" switch instead of being ignored if the switch is enabled.

**Why do you and others need this?**:
I want to be able to allow certain things which are not related to any app.

**Comment by rwjack** [comment]
Yeah I'm trying to ping my desktop as well with the same config you made, doesn't work.
Though upon stopping and starting portmaster, I can ping my device now.

Will see if it works on reboot.

**Comment by rwjack** [comment]
Yeah didn't even reboot, ICMP stopped working: 

`remote machine -x-> machine with portmaster`

Portmaster settings:
- force block incoming connections is enabled
- Global incoming rules: allow (remote machine ip)

**Comment by Broeckelmann** [comment]
Same here, I want to keep Force Block Incoming Connections but still allow handwritten incoming rules. 

It doesn't really makes sense to show the incoming rules section when they are ignored anyway...

**Comment by rwjack** [comment]
@Broeckelmann As it turns out, I managed to get this working on Linux, the only thing needed was to Stop/Start Portmaster.

The only allow rule I have: `10.1.2.3 ICMP` and it seems to work.

Different story on Windows, since by default Defender blocks ICMP. Even when enabling incoming ICMP in the advanced firewall settings (+ the portmaster rule) I couldn't get it to work...

**Comment by Broeckelmann** [comment]
@rwjack 
I am using Windows in my case I have to disable Force Block Incoming Connections to get it to work :(, it just ignores my ALLOW incoming rules that I wrote. Does not works even after restarting.

**Comment by 3941** [comment]
The checkbox says that the setting trumps the rules, so it's expected behavior.
I don't mind switching it off and handling the default blocking with rules, but what I do mind is the frequent reminder that this is very dangerous.

**Comment by Raphty** [comment]
We know we need to improve the UI here, but since the "issues" regarding this are super low in volume and occurrence we are prioritizing other features higher.
