### ISSUE TITLE
(UX) Tray Notifier name in Windows 11 "Taskbar Corner Overflow"

### ISSUE THREAD

**Issue by TheAresjej** [safing/portmaster#928]
**What happened**:
Notifier displays wrong application name (containing versions and file extension).
![image](https://user-images.githubusercontent.com/19390797/195085670-9b5784ee-0cba-4a40-964b-65ff81e372f1.png)

![image](https://user-images.githubusercontent.com/19390797/195086477-caf518d2-4d97-4a98-b81c-fefca00adff9.png)

**What did you expect to happen?**:
Notifier should display the name Portmaster.

**How did you reproduce it?**:
Settings > Personalisation > Taskbar > Taskbar Corner Overlfow

**Comment by vlabo** [comment]
Thank you for the report.

This is a good suggestion. I have to do some research where is the setting for this.
