### ISSUE TITLE
Don't use DHCP provided DNS for resolving DoH

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#931]
**What would you like to add or change?**:
Use one of the IPs (DoT/TCP/DNS) from DNS Rules or Use 9.9.9.9/1.1.1.1

**Why do you and others need this?**:
1. Privacy
2. Prevent DHCP related connection problems. Windows DHCP is bad.
3. If that fails sent to router
4. Then use DHCP DNS

**Comment by Rexadev** [comment]
@Raphty

**Comment by Raphty** [comment]
this is one of the reasons we don't like doh... an why the default is dot

you can add a dot bellow the doh and it would use that to resolve the domain in your doh entry.

you can also disable fallback to network/device dns completely.

The default and quick settings Private, and we trust that users who are making changes know what they are doing.
