### ISSUE TITLE
what is this ? ah?

### ISSUE THREAD

**Issue by haniissa** [safing/portmaster#933]
![portMaster-1](https://user-images.gi
![portMaster-3](https://user-images.githubusercontent.com/40047556/195247184-92cb861f-20a1-44ec-bbab-9039cef73c86.jpg)
![portMaster-4](https://user-images.githubusercontent.com/40047556/195247187-b86ae66e-3d2f-4431-8d1f-0293c950b538.jpg)
thubusercontent.com/40047556/195247176-7258dabc-a1f6-4e32-b89c-0cf3f01f4ea2.jpg)
![portMaster-2](https://user-images.githubusercontent.com/40047556/195247180-94ed41aa-8df8-43c7-9cfe-3849a594c1e0.jpg)
![portMaster-5](https://user-images.githubusercontent.com/40047556/195247573-788bc229-43b8-4b27-8f85-a495df6408d7.jpg)

**Comment by dhaavi** [comment]
Just two shitty antivirus engines? I'm surprised.
(Seriously: This means nothing.)

If you really want actually verify our binaries, you can check the checksums or signatures.

**Comment by haniissa** [comment]
what do you mean ? nothing?
I was install your program to protect me from malware, but I found the malware in your program.


![portMaster-5](https://user-images.githubusercontent.com/40047556/195318880-2887cd4d-2d2e-4f04-acf6-215d00a3f3e4.jpg)

**Comment by zaee-k** [comment]
MaxSecure isn't most reputable AV.
