### ISSUE TITLE
My LAN IP to my DNS shows as incoming

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#935]
![image](https://user-images.githubusercontent.com/62152714/195291806-b594a283-4a6f-4786-80b0-383bf9219713.png)

**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Rexadev** [comment]
@Raphty

**Comment by Raphty** [comment]
@Rexadev this issue had its last activity over halve a year ago, there is no debug info or anything. Portmaster had several gig updates in the mean time. If you have a new bug pleas open a new issue.
