### ISSUE TITLE
Cannot Login to Twitch via SE.Live (OBS Plugin)

### ISSUE THREAD

**Issue by iamflorencejay** [safing/portmaster#937]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:
If static.cloudflareinsights.com is blocked, it can't logged in to SE.Live (part of the OBS browser page.exe)

**What did you expect to happen?**:
Can login to the app

**How did you reproduce it?**:
Download Portmaster with default stuff
Download SE.Live and OBS
Cannot Login

**Debug Information**:

**Comment by iamflorencejay** [comment]
This domain needs to be unblocked in order to function properly 
- static.cloudflareinsights.com

**Comment by iamflorencejay** [comment]
Yep. It is fixed, but it can be whitelisted on portmaster by default or not?

**Comment by dhaavi** [comment]
This domain hosts a tracking script at `https://static.cloudflareinsights.com/beacon.min.js` and should be a personal decision to allow.
It is sad to see that services and websites are coded so poorly that they fail when the domain is not accessible - or simply down.
