### ISSUE TITLE
Use ICE for Frontend on Linux

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#946]
ICE - https://github.com/peppermintos/ice

**What would you like to add or change?**:

**Why do you and others need this?**:

No need for GUI.
Light on RAM and Disk.

**Comment by dhaavi** [comment]
Looks like an interesting project, but we currently have no resources to maintain per-distro UI components.

**Comment by Rexadev** [comment]
> per-distro UI components

Linux Mint uses it's fork and Works on all Debian distros.
@dhaavi
