### ISSUE TITLE
TeamSpeak 3 connection issue 

### ISSUE THREAD

**Issue by LukeSeers** [safing/portmaster#95]
**Checklist**:

- [x] I'm using the official portmaster release (i.e no custom builds)
- [x] I searched for similar/existing issues first.
- [x] My issue is not mentioned in the Known Issues section of my [OS](https://github.com/safing/portmaster/wiki)

**What happened**:
When connecting to a TeamSpeak 3 server given a domain like `ts.example.com`(points to IP address) it don't connect.

**What you expected to happen**:
For the client to connect to the TeamSpeak 3 server.

**How to reproduce it (as minimally and precisely as possible)**:
Find a TeamSpeak 3 server that uses a domain name, try and connect to it while Portmaster is enabled.

**Anything else we need to know?**:
I have not tried it with a plain IP address only a domain that points to their relative IP address.

**I found a fix for this issue kinda...** 
Copy the domain name into the url of the browser and hit enter.

From what I understand when I try and connect the domain through the TeamSpeak 3 first it don't query the domain? until I goto the browser and do what I said above, But now I have found that sometimes it works and other times it don't.

**Environment**:

Portmaster Version: 

<details>
  <summary>Versions from the `About` page in Portmaster's UI</summary>
  I will update this when I'm able to, but I'm pretty sure I'm running the latest build.
</details>

Operating System:
- [ ] Windows 7
- [ ] Windows 8/8.1
- [x] Windows 10
- [ ] Linux

**Comment by dhaavi** [comment]
Hey @LukeSeers, thanks for poppin' by!

While we've had issues with TeamSpeak in the past, it has been working well lately as far as I know. I would have gone straight for the "It's DNS." conclusion, but what I find weird, is that letting the browser query that domain sometimes fixes it. There shouldn't be any difference who resolves the domain.

What could be happening is that the DNS query takes longer for some reason and that is why waiting, or just triggering the query again works. You should be able to see in the Monitor what is going on exactly. I am very sure that it queries the domain. I connected to a TeamSpeak server using a domain last night and it worked flawlessly on the first attempt.

I would ask you to just retry a couple times if it does not connect the first time. Using the IP address would be a valid workaround, if you find that it does not work at all.

Depending on the service used for the TeamSpeak server, there also could be an issue with them rotating IPs. While DNS is built for this, there are often problems here. We already have a better cache invalidation mechanism that we will release soon that might help with this issue.

**Comment by LukeSeers** [comment]
I just tried **v0.4.13** with the new _DNS cache clearing_ feature and that seems to fix my issue.

**Reproduce:**
I don't know how fast it takes to clear the DNS, so I hit the clear DNS 2 times.

`Connect (ts.exsample.com) -> failed -> cleared DNS -> Connect (ts.exsample.com) -> failed-> cleared DNS -> Connect (ts.exsample.com) -> works!`

**Comment by dhaavi** [comment]
Great to hear that it works! With this update it should fail a lot less often.
Also, you do not necessarily need use the "Clear DNS Cache" button when it fails: When the same query for a domain comes in 3 times in a row (with other queries in between), it resets the cache for that query.

So go and smash that connect button! I think that fits your style, eh?
