### ISSUE TITLE
[Documentation] What is the new Fingerprint/Profile Feature?

### ISSUE THREAD

**Issue by Rexadev** [safing/portmaster#950]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Windows Known Issues](https://docs.safing.io/portmaster/install/windows#known-issues)
  - [Linux Known Issues](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Abug)

**What happened**:

**What did you expect to happen?**:

**How did you reproduce it?**:

**Debug Information**:

**Comment by Rubber-Duckie** [comment]
not working, or non-intuitive. See: #1552
