### ISSUE TITLE
Portmaster Windows Kernel Extension Driver not loading

### ISSUE THREAD

**Issue by vigneshk01** [safing/portmaster#961]
Installed Portmaster 1.0.0 on my machine (Windows 11 Home 22H2)

The Portmaster kernel is not loading during boot, getting disabled automatically.
there seems to be some conflict, can this be due to Kaspersky AV?. 

Below is my Autoruns screenshot:
![image](https://user-images.githubusercontent.com/33518968/198628668-8ac58de1-ff4b-466f-8946-626244272b38.png)

**Comment by zaee-k** [comment]
I wonder if this is somehow related with signing not being verified (authenticode problem?). 
Try to disable KasperskyAV and reinstall Portmaster?
