### ISSUE TITLE
1 security vendor and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by MAG10d** [safing/portmaster#970]
**What happened**:
https://www.virustotal.com/ report virus risk
https://www.virustotal.com/gui/file/61cb59f25c4fcb130df0e925f6a1df21569379280c501dab1754080a24260856/detection

**How did you reproduce it?**:
Download windows version installer from https://safing.io/
and upload to https://www.virustotal.com/

**Debug Information**:
N/A

**Comment by davegson** [comment]
comments from a [related reddit thread](https://old.reddit.com/r/safing/comments/sn46eb/possible_malware_detected_in_v0721/hwcyf2y/)

> But why is it flagging this as a trojan? There's this [great article giving some insight](https://www.csoonline.com/article/3216765/heres-why-the-scanners-on-virustotal-flagged-hello-world-as-harmful.html), explaining why many of today's anti-viruses sometimes even flag a basic "Hello World" as malware. You can even read the reasonings behind it given by the vendors. In short, as I read it it's about machine learning and some approaching things with "rather false positive than false negatives".
>
> And yes, Portmaster does more advanced thing than your average calculator, meaning it is closer to the system and this might trigger some AV. We know Portmaster goes deep into the system, which is why we are firm believers of open source. Both generally speaking, but even stronger within this context.
