### ISSUE TITLE
blockt app still get some conactons allowt

### ISSUE THREAD

**Issue by sander732** [safing/portmaster#973]
![2022-11-04 18_29_24-Portmaster](https://user-images.githubusercontent.com/24863809/200039187-bae04bb7-adf2-42bd-bfc1-62bcd72a0b46.png)

**Comment by davegson** [comment]
Portmaster shows what has happened in the **last 10 minutes** - could this connection have happened before you activated "Block Connections"?

**Comment by sander732** [comment]
no there was a day between blocking and this screen shot

**Comment by davegson** [comment]
Can you reproduce this? If so, could you show the allowed connections?

**Comment by sander732** [comment]
I think its just te procent thats wrong because don't find allowed connections

**Comment by davegson** [comment]
good to hear! I will mark this as closed as a result. If the numbers in the UI are wrong again and you want to help improve it, it would help us if you could [gather logs after it happens again](https://github.com/safing/portmaster/issues/705)
