### ISSUE TITLE
Block or allow executable/apps in notifications instead of individual app ip:port combinations

### ISSUE THREAD

**Issue by nidhoggr-nil** [safing/portmaster#974]
**What would you like to add or change?**:
A way to block or allow an app to make all the ip:port connections allowable in an notification dialog, without having to allow each individual connection which maps to a different port for the same app.

**Why do you and others need this?**:

I think it's neat that portmaster allows to dissect individual requests on a port level, but for an ease of use viewpoint, just having a clickable notification to whitelist an entire app would be easier and remove all future notifications and reduce the cognitive overhead of specifically managing the rules for an app as it is in the current state.

It could go like this, if you want to keep the current port differentation.
    1. A new app gets an incoming request, like firefox
    2. Portmaster sends out notification asking the user what to do with two options
    3. Current implementation: Allow/deny individal connection request which maps the rule to a specific port
    4. Whitelist the whole app, since I trust the app/firefox, I'll allow it to make as many connections as it wants, and I do not wish to consider it again

You could allow a toggle setting to display the permanent whitelisting of an executable in the notification area, so that it is not shown by default. Since showing this by default could be a problem, so that the user does not click it by accident or gets confused.

I tried the "prompt me" option for the requests option, but I get overwhelmed by connections I have to allow/block. I think this is bad by design unless you really know what you are doing, since the normal response to this is to become more complacent, as there are too many rules and too much cognitive overhead to make a well thought out consideration of each connection/app combo. It quickly becomes a habit to just press yes if something looks just remotely legitimate, which is bad.

It's decision fatique.

I know that you can set the default network action per app basis, but it is tedious to access the setting, you have to

1. open portmaster
2. go the app
3. settings
4. change the default network action to allow

Those are 4 steps for what could just be a notification with some options.

One issue with allowing the whitelisting of apps, is how they will respect the global setting in portmaster, which is to block incoming connections. My initial thought, is to leave it be, but I was considering if making an "allow incoming connections" option in the notification area to default to no, but allow it to be toggleable to yes. This option should be hidden by default, and only allowed to be seen in the notifications if toggled on in settings, as it is dangerous to expose without knowing what it means globally. But it would be very nice for power users/developers, and make this a really good alternative to a traditional firewall which usually works on app/executable basis by default. Just having these quality of life settings would be awesome.

**Comment by pcgamehunter** [comment]
This is the main reason I can't use portmaster. 
The granularity is nice as an option, but most of the time I simply want to prevent access for an app until I actively approve it. The per address prompts makes the most impractical to use. And using the menu to do it manually is too much work.

**Comment by dhaavi** [comment]
Hey @Osigmae and @pcgamehunter - we already have an improvement planned to make this easier. But it will take a little until we get there.

**Comment by vvirtues** [comment]
is this still being actively developed, and if so, is there an ETA I can expect?

**Comment by Kyzoku** [comment]
+1

**Comment by ill5-com** [comment]
+1

**Comment by Baton34** [comment]
+1
I need "Allow all" and "Block all" buttons in notification, so it change "Default Network Action" for app to "allow" or "block".

**Comment by Osigmae** [comment]
@dhaavi Hello, what is the status of this? :-) it looks like it keeps being added and removed to the backlog?

**Comment by dhaavi** [comment]
We've just cleaned up the labels.

Current status is: we'd like to do this (or similar) soon-ish, but it is not yet in the pipeline.

**Comment by Alex9001** [comment]
+1

**Comment by CCS86** [comment]
2 years later, are we any closer to this fairly basic feature?

The best implementation IMO would be when a new app tries to make a network connection for the first time, the user is prompted to either "allow all", "allow LAN only", or "block all".

**Comment by Raphty** [comment]
Thanks for the feedback. if you or someone else wants to start with this implementation, feel free to reach out with a draft outline of a specification.
we are working on other things, but are happy to help FOSS developers/contributors to implement this 😃

**Comment by CCS86** [comment]
@Raphty, so this is no longer the case?

> Hey @Osigmae and @pcgamehunter - we already have an improvement planned to make this easier. But it will take a little until we get there.

**Comment by Raphty** [comment]
It is still not in the pipeline, and I can't say when this will get priority from us. Again, we would like to help anyone who wants to contribute this as a feature, our priorities are evaluated and weighted based on multiple factors.

**Comment by JGKle** [comment]
Bit weird that this was randomly closed when clearly many people were waiting for it...
