### ISSUE TITLE
On the tray menu provide an option to disable Postmaster without shutting it down

### ISSUE THREAD

**Issue by biergit** [safing/portmaster#978]
**What would you like to add or change?**:
A quick way to disable / reenable Postmaster via tray menu

**Why do you and others need this?**:
It's the quickest way to rule out Postmaster in case of issues.

**Comment by biergit** [comment]
What more input would you need?

**Comment by Raphty** [comment]
Hey @biergit thanks for the suggestion. I was/am cleaning out stale issues with not activity, in this case it was over halve a year with 0 activity.

To comment on your suggestion, I don't see the difference in what not shutting it down but not doing anything would make to shutting it down. 

if it is an issue you cant find in the network monitor by looking for all blocked connections. If it is a compatibility issue, which to trouble shoot would involve shutting down at leas the kernel modules anyway, which will take time, so it is not faster then shutting Portmaster down as a whole. i don't understand the benefit.

If you have a use case I can't see pleas let me know.

rest assured that I see the comment for the closed issues as well 😄
