### ISSUE TITLE
Cannot set DNS Server to 127.0.0.1

### ISSUE THREAD

**Issue by SynapseScribe** [safing/portmaster#985]
I already run a secured dns server through acrylicDNS on 127.0.0.1. I want to use it but i get error "Invalid Value: validation of dns/nameservers failed: entry #1 did not match validation regex"

**Comment by vlabo** [comment]
Are you just adding the ip address in the configuration?
If so this is not going to work, there is a special syntax for plain dns.

It should be something like this 
```dns://127.0.0.1```

https://docs.safing.io/portmaster/guides/dns-configuration#dns-configuration-url-scheme
