### ISSUE TITLE
World Map view for network traffic

### ISSUE THREAD

**Issue by kidimbwi** [safing/portmaster#987]
**What would you like to add or change?**:

Little Snitch on MacOS has a great feature where network connections to and from your computer are projected onto a map of the globe. this feature is visible in this screenshot from their site

![monitor-screenshot](https://user-images.githubusercontent.com/65897337/200881655-b86f018a-6dd2-49c2-b3b0-5a5eaeaf6be5.png)

it would be really great to have such a feature in Portmaster.

**Why do you and others need this?**:

being able to see traffic flows on a map of the world would give users enhanced visibility into where exactly network requests are coming from and where they are going. such a graphical view of network traffic would enable users make even better informed decisions on whether to allow or block a connection they've received.

**Comment by 197788** [comment]
It would be nice to zoom into the map a bit more because some nodes are stacked 3 deep on top of each other, and it is impossible (almost, but takes skill) to pick the one I'd like to see

**Comment by JS-E** [comment]
I totally agree, just a thought about this so i did wonder if other people had a similar idea. Would be an awesome addition 👍
