### ISSUE TITLE
Possible incompatibility with wine app(?)

### ISSUE THREAD

**Issue by changemenemo** [safing/portmaster#992]
**Pre-Submit Checklist**:

- Check applicable sources for existing issues:
  - [Linux Compatibility](https://docs.safing.io/portmaster/install/linux#compatibility)
  - [VPN Compatibility](https://docs.safing.io/portmaster/install/status/vpn-compatibility)
  - [Github Issues](https://github.com/safing/portmaster/issues?q=is%3Aissue+label%3Ain%2Fcompatibility)

**What worked?**
Portmaster is responsive and classify correctly the app as far as I can see
I'm trying to use eveonline game through the proton api of steam. 

**What did not work?**
After a few minutes each time, portmaster goes haywire and caps out the cpu. 
I will put some logs in 

**Debug Information**:
Is :Ubuntu 22.04.1

**Comment by boistordu** [comment]
Seems the portmaster loop be triggered by steam downloads too.
